extension Translations {
    static let chinese: [String: String] = [
        "step.runs": "运行 %@",
        "step.runsCommand": "运行命令",
        "step.reads": "读取 %@",
        "step.aFile": "文件",
        "step.edits": "编辑 %@",
        "step.editsFiles": "编辑文件",
        "step.searches": "搜索“%@”",
        "step.searchesCode": "搜索代码",
        "step.searchesWeb": "搜索网页",
        "step.opens": "打开 %@",
        "step.startsHelper": "启动辅助代理",
        "step.updatesPlan": "更新计划",
        "step.uses": "使用 %@",
        "step.working": "工作中…",
        "step.thinking": "思考中…",
        "step.waitingForYou": "等你处理",
        "step.done": "完成",

        "title.idle": "一切安好",
        "title.working": "代理正在工作",
        "title.needsYou": "需要你",
        "title.limitUsedUp": "%@ 额度已用完",
        "title.limitAlmost": "%@ 额度快用完了",
        "subtitle.noSessions": "启动 Claude Code 或 Codex — 我会帮你盯着。",
        "subtitle.noHooks": "在菜单栏中连接 Claude Code 和 Codex。",
        "subtitle.serverDown": "无法开始监听代理。",
        "limit.detailResets": "%1$@，%2$@ 后重置",

        "approval.allow": "允许",
        "approval.deny": "拒绝",
        "approval.askThere": "在那边确认",
        "approval.wantsTo": "想要",
        "approval.more": "还有 %ld 个在等待",

        "stats.spending": "花费",
        "stats.apiValue": "按 API 价格",
        "stats.now": "现在",
        "stats.workingNow": "工作中",
        "stats.limitsLater": "下一次回复后会显示额度",
        "stats.updated": "更新于 %@",
        "stats.tokens": "%@ 个 token",
        "stats.tokensWord": "个 token",
        "stats.fromCache": "%ld%% 来自缓存",
        "stats.todayTotal": "今天 %@",
        "stats.noPrice": "Codex 模型没有公开价格",
        "period.today": "今天",
        "period.week": "7 天",
        "period.month": "30 天",
        "window.session": "会话",
        "window.week": "本周",
        "window.limit": "额度",
        "stats.activity": "活跃度",
        "stats.streak": "连续 %ld 天",
        "stats.activeDays": "活跃天数",
        "stats.busiestDay": "最忙的一天",

        "time.daysHours": "%1$ld 天 %2$ld 小时",
        "time.hoursMinutes": "%1$ld 小时 %2$ld 分",
        "time.minutes": "%ld 分钟",
        "time.hours": "%ld 小时",
        "time.days": "%ld 天",
        "time.months": "%ld 个月",
        "time.justNow": "刚刚",
        "time.ago": "%@前",

        "resets.line": "重置次数：%ld",
        "resets.expiresIn": "最近一次 %@ 后过期",
        "resets.use": "使用重置",
        "resets.resetting": "正在重置…",
        "resets.confirmTitle": "现在重置 Codex 额度？",
        "resets.confirmBody": "将使用一次储备的重置：会话和每周额度会立即刷新。剩余次数：%ld。",
        "resets.outcome.reset": "Codex 额度已重置",
        "resets.outcome.nothing": "暂时没有需要重置的额度",
        "resets.outcome.noCredit": "没有可用的重置次数",
        "resets.outcome.already": "这次重置已经用过了",
        "resets.outcome.failed": "重置失败 — 这台 Mac 上的 Codex 登录了吗？",

        "drop.here": "松开 — 我会为代理复制路径",
        "drop.copiedOne": "已复制 %@ 的路径 — 粘贴给你的代理 (⌘V)",
        "drop.copiedMany": "已复制 %ld 个路径 — 粘贴给你的代理 (⌘V)",
        "drop.remoteCantSee": "%@ 上的代理看不到这台 Mac 上的文件。",
        "drop.willSendOne": "已复制服务器路径 — 文件会随你的下一条消息发送到 %@ (⌘V)",
        "drop.willSendMany": "已复制服务器路径 — %1$ld 个文件会随你的下一条消息发送到 %2$@ (⌘V)",
        "drop.delivered": "已送达 %1$@：%2$ld",
        "drop.skippedFolders": "暂不支持发送文件夹。",
        "drop.tooBig": "每次最多 20 MB。",
        "drop.shelfInFullDenny": "文件暂存架和音乐控制 — 在完整版 Denny 中 →",
        "fullDenny": "任务、笔记和离线 AI — 完整版 Denny →",

        "alerts.menu": "通知",
        "alerts.finish": "任务完成",
        "alerts.limit": "套餐额度",
        "alerts.budget": "每日预算（API 价格）",
        "alerts.off": "关闭",
        "alerts.anyLength": "任意时长",
        "alerts.longerThan": "超过 %ld 分钟",
        "alerts.atPercent": "达到 %ld%%",
        "alerts.finishedTitle": "%@ 完成了",
        "alerts.finishedBody": "%1$@ · 工作了 %2$@",
        "alerts.limitTitle": "%1$@ 额度已达 %2$ld%%",
        "alerts.budgetTitle": "已达每日预算：%@",
        "alerts.budgetBody": "按 API 标价计算，包括这台 Mac 和你的服务器。",

        "menu.claude": "关注 Claude Code",
        "menu.codex": "关注 Codex",
        "menu.remote": "远程服务器 (SSH)…",
        "menu.fullDenny": "获取完整版 Denny…",
        "menu.quit": "退出 Denny for Agents",
        "remote.title": "关注 SSH 服务器上的代理",
        "remote.body": "1. 连接期间转发端口：在 Termius 中添加 Remote 端口转发规则（服务器 127.0.0.1:{port} → 这台 Mac 127.0.0.1:{port}），或用 ssh -R {port}:127.0.0.1:{port} user@server 连接\n2. 把仓库里的 remote/denny-hook.py 放到服务器的 ~/.denny-for-agents/。\n3. 在服务器上运行复制的命令，然后运行：python3 ~/.denny-for-agents/denny-hook.py --ping",
        "remote.copy": "复制安装命令",
        "remote.unavailable": "远程模式无法启动：端口被占用。",
        "common.close": "关闭",
        "common.cancel": "取消",
        "connect.title": "把 Denny 连接到你的代理？",
        "connect.body": "Denny 会在 ~/.claude/settings.json 和 ~/.codex/hooks.json 中添加 hook（并在旁边保存备份）。如果 Denny 没有运行，这些 hook 什么也不做，绝不会阻塞你的代理。",
        "connect.connect": "连接",
        "connect.later": "稍后",
        "connect.failed": "无法修改设置文件",

        "value.title": "套餐价值",
        "value.line": "30 天按 API 价格为 %@",
        "value.planMonthly": "%1$@ · %2$@/月",
        "stats.trend": "趋势",
        "stats.models": "模型",
        "stats.projects": "项目",
        "stats.peak": "峰值 %@",
        "card.limits": "额度",
        "alerts.renewedTitle": "%@ 额度已恢复",
        "menu.cards": "卡片",
        "menu.readout": "摄像头旁",
        "readout.timer": "任务计时",
        "readout.limit": "最紧张的额度",
        "page.overview": "概览",
        "page.stats": "统计",
        "stats.noFresh": "暂无最新数据",

        "settings.title": "设置",
        "settings.menu": "设置…",
        "settings.section.agents": "代理",
        "settings.section.servers": "服务器",
        "settings.section.notch": "刘海",
        "settings.section.cards": "卡片",
        "settings.section.alerts": "通知",
        "settings.section.language": "语言",
        "settings.section.privacy": "隐私",
        "settings.section.about": "关于",
        "settings.connected": "已连接",
        "settings.notConnected": "未连接",
        "settings.disconnect": "断开",
        "settings.agentsFooter": "Denny 会把 hook 添加到每个代理的设置文件中，并在旁边保存备份。如果 Denny 没有运行，这些 hook 什么也不做。",
        "settings.keepAwake": "代理工作时保持 Mac 唤醒",
        "settings.keepAwakeFooter": "仅在这台 Mac 上有代理工作时生效。屏幕仍可关闭。",
        "settings.serversConnected": "已连接的服务器",
        "settings.noServers": "还没有服务器。请在下方设置。",
        "settings.lastSeen": "上次在线 %@",
        "settings.peeks": "弹出提示",
        "settings.peekOnStart": "发送任务时",
        "settings.peekOnWriting": "代理开始写代码时",
        "settings.peekOnFinish": "代理完成时",
        "settings.display": "显示器",
        "settings.displayAuto": "带刘海的那台",
        "settings.fullScreen": "在全屏应用上方显示",
        "settings.cardsFooter": "关闭的卡片会从刘海中消失。概览包含额度、花费和现在；统计包含其余卡片。",
        "settings.languageSystem": "跟随系统",
        "settings.languageRestart": "新语言将在重启后生效。",
        "settings.restart": "立即重启",
        "settings.privacyReads": "Denny 读取什么",
        "settings.privacyReadsBody": "Claude Code 和 Codex 日志中的 token 数、模型名称、时间和项目文件夹名称；来自 ~/.claude.json、Claude 应用和 Codex 的套餐额度；你的代理发送给 hook 的事件。",
        "settings.privacyNever": "Denny 从不读取或发送什么",
        "settings.privacyNeverBody": "你的提示、回答和文件内容。除了每天下载公开价格表，没有任何数据离开你的机器。拖到刘海上的文件只会发送到你自己的服务器。",
        "settings.removeAll": "断开代理并清除 Denny 的数据",
        "settings.removeAllFooter": "从 Claude Code 和 Codex 中移除 hook，删除包含历史和设置的 ~/.denny-for-agents，然后退出。",
        "settings.removeAllConfirm": "清除 Denny for Agents 保存的所有内容？",
        "settings.version": "版本 %@",
        "settings.about": "住在刘海里的小机器人，帮你盯着 Claude Code 和 Codex。Denny 的免费开源部分。",
        "settings.section.nightShift": "夜班",
        "night.newJob": "稍后执行的新任务",
        "night.agent": "智能体",
        "night.noFolder": "未选择文件夹",
        "night.chooseFolder": "选择…",
        "night.when": "开始",
        "night.whenRenews": "当额度恢复时",
        "night.whenAt": "在指定时间",
        "night.queue": "加入队列",
        "night.queueTitle": "队列",
        "night.waitsUntil": "等待至 %@",
        "night.waitsForLimit": "等待额度恢复",
        "night.running": "进行中 %@",
        "night.doneAt": "完成于 %@",
        "night.failedShort": "失败：%@",
        "night.footer": "只要这台 Mac 开着就会运行（Denny 会让它保持唤醒）。夜里没人批准，所以 Denny 很谨慎：文件修改和安全命令会照常进行，守卫认为危险的操作一律拒绝。安全网照常保存快照；早上会有一张小票等着你，完成时 Telegram 会通知你。",
        "night.interrupted": "因重启而中断",
        "night.started": "%1$@ 已在 %2$@ 开始夜间任务",
        "night.done": "%1$@ 已在 %2$@ 完成夜间任务——小票在刘海里等你",
        "night.failed": "%1$@ 未能在 %2$@ 完成夜间任务：%3$@",
        "settings.section.phone": "手机",
        "phone.title": "在手机上批准",
        "phone.steps": "1. 在 Telegram 中打开 @BotFather 并发送 /newbot。\n2. 起个名字——BotFather 会发给你一个令牌。\n3. 把令牌粘贴到这里。",
        "phone.tokenPlaceholder": "机器人令牌",
        "phone.check": "检查",
        "phone.badToken": "这个令牌无效——请从 @BotFather 重新复制。",
        "phone.sendCode": "把这个代码发送给 @%@：",
        "phone.openBot": "打开机器人",
        "phone.topicHint": "想在某个话题或群组里接收请求？就把代码发到那里——Denny 只会在这个话题里发消息，也只有你能按按钮。",
        "phone.waiting": "正在等待代码…",
        "phone.connected": "已通过 @%2$@ 连接到 %1$@",
        "phone.whenAway": "当我不在 Mac 前时",
        "phone.always": "始终",
        "phone.finished": "任务完成时也通知我",
        "phone.test": "发送测试",
        "phone.testText": "我是 Denny 👋 你的智能体的请求会发到这个聊天。",
        "phone.disconnect": "断开连接",
        "phone.footer": "请求会经过 Telegram 的服务器，包括命令文本。机器人只听从发送代码的聊天。不在 = 2 分钟没有鼠标和键盘操作。",
        "phone.paired": "Denny 已连接 🎉 当智能体请求权限而你不在 Mac 前时，请求会发到这里。",
        "phone.request": "%1$@ · %2$@ 想要：",
        "phone.allow": "✅ 允许",
        "phone.deny": "❌ 拒绝",
        "phone.allowed": "✅ 已允许",
        "phone.denied": "❌ 已拒绝",
        "phone.expired": "⌛ 这里没有回应——智能体在自己的终端里询问。",
        "review.button": "让 %@ 检查",
        "review.running": "%1$@ 正在检查… %2$@",
        "review.clean": "✅ %@ 没有发现问题",
        "review.findings": "%1$@ 发现问题：%2$ld",
        "review.send": "发送给 %@",
        "review.copied": "已复制——粘贴给 %@（⌘V）",
        "review.failed": "%1$@ 无法检查：%2$@",
        "review.noChanges": "没有需要检查的改动",
        "review.notFound": "在此 Mac 上未找到",
        "review.agentMessage": "%1$@ 检查了你的改动，发现：\n\n%2$@\n\n请核对这些问题并修复合理的部分。",
        "tests.run": "运行测试",
        "tests.running": "测试运行中… %@",
        "tests.passed": "✅ 测试通过 · %@",
        "tests.failed": "❌ 测试失败 · %@",
        "tests.sendToAgent": "发送给智能体",
        "tests.copied": "已复制——粘贴给智能体（⌘V）",
        "tests.agentMessage": "你的修改之后测试失败了（`%1$@`）。以下是输出的结尾——请修复：\n\n%2$@",
        "tests.autoSetting": "每个任务完成后运行项目测试",
        "tests.autoFooter": "仅限此 Mac 上的项目。Denny 会自己找到命令（swift test、npm test、cargo test、pytest…）；也可以在项目根目录的 .denny-test 文件中写入你自己的命令。",
        "tests.timedOut": "10 分钟后已停止。",
        "receipt.title": "任务小票",
        "receipt.files": "文件：%ld",
        "receipt.lines": "+%1$ld −%2$ld",
        "receipt.commands": "命令：%ld",
        "receipt.tokens": "Token：%@",
        "receipt.cost": "按 API 价格 %@",
        "receipt.copy": "复制",
        "receipt.copied": "小票已复制",
        "receipt.hide": "隐藏",
        "receipt.signature": "来自 Denny for Agents",
        "settings.section.safetyNet": "安全网",
        "safety.peekTitle": "已在危险命令前保存文件",
        "safety.cardTitle": "安全网",
        "safety.cardBody": "在这条命令执行前已保存文件。撤销可将它们恢复原样。",
        "safety.onServer": "已保存在 %@ 上——需在那里执行恢复",
        "safety.undo": "撤销…",
        "safety.copyCommand": "复制服务器命令",
        "safety.hide": "隐藏",
        "safety.confirmTitle": "将文件恢复到“%@”之前的状态？",
        "safety.confirmBody": "将恢复 %ld 个文件。快照之后对它们的修改会丢失；新文件保留。",
        "safety.confirmRestore": "恢复",
        "safety.nothing": "无需恢复——文件与快照一致。",
        "safety.restored": "文件已恢复",
        "safety.failed": "无法恢复文件",
        "safety.commandCopied": "命令已复制——请在服务器上运行",
        "safety.empty": "还没有快照。在智能体运行 rm、git reset --hard 等命令之前，Denny 会把你的文件保存在这里。",
        "safety.footer": "最多 50 个快照。在 git 项目中保存在隐藏的引用里，绝不触碰你的分支、索引或 stash。",
        "safety.storage": "存储",
        "safety.keepFor": "快照保留",
        "safety.keep.1": "1 天",
        "safety.keep.7": "7 天",
        "safety.keep.30": "30 天",
        "safety.limit": "副本空间",
        "safety.gb": "%ld GB",
        "safety.used": "此 Mac 上的副本：%@",
        "safety.clear": "删除所有快照…",
        "safety.clearConfirm": "删除此 Mac 上的所有快照？",
        "safety.clearBody": "之后将无法再恢复其中的文件。",
        "safety.delete": "删除",
        "safety.limitFooter": "只计算 git 之外文件的副本——git 快照保存在项目内，几乎不占空间。空间不足时，最早的快照会先被删除。服务器会在你给智能体发送下一条消息时获取这些设置。",
        "update.check": "检查更新",
        "update.checking": "正在检查…",
        "update.upToDate": "已是最新版本",
        "update.available": "%@ 版本可用",
        "update.install": "更新",
        "update.installing": "正在下载更新… Denny 将重新启动",
        "update.failed": "更新失败：%@",
        "update.reason.offline": "无法连接 GitHub",
        "update.reason.checksum": "文件与校验和不匹配",
        "update.reason.folder": "没有权限替换应用——请将其放在“应用程序”中",
        "update.reason.download": "下载失败",
        "update.homebrew": "通过 Homebrew 安装——请运行：brew upgrade denny-for-agents",
        "update.notifyBody": "打开 Denny 设置 → 关于 以进行更新。",

        "quiet.on": "静音一小时",
        "quiet.active": "静音至 %@ — 点按结束",
        "quick.refresh": "立即刷新",
        "awake.manual": "手动保持唤醒",
        "awake.duration": "时长",
        "awake.until": "直到",
        "awake.indefinite": "直到我关闭",
        "awake.start": "开始",
        "awake.stop": "停止",
        "awake.activeUntil": "Mac 将保持唤醒至 %@",
        "awake.untilOff": "Mac 将保持唤醒，直到你停止",
        "awake.lid": "合盖后继续工作",
        "awake.lidWarning": "仅在连接充电器时生效。只需输入一次管理员密码，用于允许唯一一条命令（pmset disablesleep），工作结束后会自动关闭。不要把合盖运行中的 Mac 放进包里。",
        "awake.lidNeedsPower": "当前使用电池 — 接上充电器后会自动开启。",

        "risk.safe": "看起来安全",
        "risk.caution": "值得看一眼",
        "risk.danger": "危险",
        "risk.critical": "非常危险",
        "risk.reason.pipeToShell": "从网上下载代码并立即运行。",
        "risk.reason.wipeRoot": "删除 /、主目录或当前文件夹中的所有内容。",
        "risk.reason.rawDisk": "直接写入磁盘 — 可能把它清空。",
        "risk.reason.format": "格式化或抹掉磁盘。",
        "risk.reason.forkBomb": "Fork 炸弹：Mac 会卡死。",
        "risk.reason.dropData": "删除数据库表或数据。",
        "risk.reason.deleteRecursive": "删除文件夹 %@ 及其全部内容，不经过废纸篓。",
        "risk.reason.forcePush": "覆盖服务器上的分支历史。",
        "risk.reason.resetHard": "丢弃所有未提交的更改。",
        "risk.reason.cleanUntracked": "删除 git 未跟踪的文件。",
        "risk.reason.sudo": "以管理员身份运行（sudo）。",
        "risk.reason.permissions": "把文件开放给所有人或更改其所有者。",
        "risk.reason.killProcess": "强制结束正在运行的程序。",
        "risk.reason.reboot": "关机或重启电脑。",
        "risk.reason.dockerPrune": "删除 Docker 容器、卷或数据。",
        "risk.reason.publish": "向所有人发布软件包或版本。",
        "risk.reason.secrets": "涉及密钥、密码或 .env 机密。",
        "risk.reason.push": "把提交推送到服务器。",
        "risk.reason.deleteFile": "删除 %@。",
        "risk.reason.install": "从网上安装软件包。",
        "risk.reason.network": "访问网络。",
        "risk.reason.gitHistory": "改写 git 历史或丢弃文件更改。",
        "risk.reason.sensitiveFile": "修改敏感文件：%@。",
        "risk.reason.externalTool": "使用外部工具（MCP 服务器）。",

        "load.thisMac": "这台 Mac",
        "load.cpu": "CPU",
        "load.cpuLoad": "负载（%ld 核）",
        "load.memory": "内存",
        "load.pressureNormal": "内存压力：正常",
        "load.pressureWarning": "内存压力：偏高",
        "load.pressureCritical": "内存压力：严重",
        "load.swap": "交换 %@",
        "load.uptime": "已运行 %@",
        "load.memoryLow": "内存快满了 — 大型构建可能会被终止。",
        "load.noServer": "服务器负载将随已连接服务器的下一份报告到达。",
        "settings.section.load": "负载",

        "relay.title": "%@ 已达额度上限",
        "relay.titleUntil": "%1$@ 已达额度上限，%2$@ 恢复",
        "relay.body": "把任务交给 %@？我会写一份交接说明：要做什么、已经做了什么。",
        "relay.copy": "复制给 %@ 的交接说明",
        "relay.later": "暂不",
        "relay.copied": "交接说明已复制 — 粘贴到 %@ (⌘V)",
        "relay.handoff": "把任务交给 %@",
        "relay.note.intro": "继续 %1$@ 开始的任务（%2$@）。",
        "relay.note.reasonLimit": "它达到了套餐额度上限",
        "relay.note.reasonManual": "我把它交给你",
        "relay.note.folder": "文件夹：%@",
        "relay.note.server": "服务器：%@",
        "relay.note.task": "任务：",
        "relay.note.done": "已完成：",
        "relay.note.edited": "修改过：%@",
        "relay.note.ran": "运行过：%@",
        "relay.note.last": "%@ 的最后一条消息：",
        "relay.note.next": "先查看当前改动（git status、git diff），再从中断的地方继续。",

        "stuck.title": "%@ 好像在原地打转",
        "stuck.repeatCommand": "第 %1$ld 次运行“%2$@”",
        "stuck.repeatEdit": "第 %1$ld 次修改 %2$@",
        "stuck.noProgress": "工作了 %ld 分钟却没有任何改动",
        "stuck.setting": "代理原地打转时提醒我"
    ]
}
