extension Translations {
    static let chinese: [String: String] = [
        "step.runs": "运行 %@",
        "step.runsCommand": "运行命令",
        "step.reads": "读取 %@",
        "step.aFile": "文件",
        "step.edits": "编辑 %@",
        "step.editsFiles": "编辑文件",
        "step.searches": "搜索“%@”",
        "step.searchesCode": "搜索代码",
        "step.searchesWeb": "搜索网页",
        "step.opens": "打开 %@",
        "step.startsHelper": "启动辅助代理",
        "step.updatesPlan": "更新计划",
        "step.uses": "使用 %@",
        "step.working": "工作中…",
        "step.thinking": "思考中…",
        "step.waitingForYou": "等你处理",
        "step.done": "完成",

        "title.idle": "一切安好",
        "title.working": "代理正在工作",
        "title.needsYou": "需要你",
        "title.limitUsedUp": "%@ 额度已用完",
        "title.limitAlmost": "%@ 额度快用完了",
        "subtitle.noSessions": "启动 Claude Code 或 Codex — 我会帮你盯着。",
        "subtitle.noHooks": "在菜单栏中连接 Claude Code 和 Codex。",
        "subtitle.serverDown": "无法开始监听代理。",
        "limit.detailResets": "%1$@，%2$@ 后重置",

        "approval.allow": "允许",
        "approval.deny": "拒绝",
        "approval.askThere": "在那边确认",
        "approval.wantsTo": "想要",
        "approval.more": "还有 %ld 个在等待",

        "stats.spending": "花费",
        "stats.apiValue": "按 API 价格",
        "stats.now": "现在",
        "stats.workingNow": "工作中",
        "stats.limitsLater": "下一次回复后会显示额度",
        "stats.updated": "更新于 %@",
        "stats.tokens": "%@ 个 token",
        "stats.tokensWord": "个 token",
        "stats.fromCache": "%ld%% 来自缓存",
        "stats.todayTotal": "今天 %@",
        "stats.noPrice": "Codex 模型没有公开价格",
        "period.today": "今天",
        "period.week": "7 天",
        "period.month": "30 天",
        "window.session": "会话",
        "window.week": "本周",
        "window.limit": "额度",
        "stats.activity": "活跃度",
        "stats.streak": "连续 %ld 天",
        "stats.activeDays": "活跃天数",
        "stats.busiestDay": "最忙的一天",

        "time.daysHours": "%1$ld 天 %2$ld 小时",
        "time.hoursMinutes": "%1$ld 小时 %2$ld 分",
        "time.minutes": "%ld 分钟",
        "time.hours": "%ld 小时",
        "time.days": "%ld 天",
        "time.months": "%ld 个月",
        "time.justNow": "刚刚",
        "time.ago": "%@前",

        "resets.line": "重置次数：%ld",
        "resets.expiresIn": "最近一次 %@ 后过期",
        "resets.use": "使用重置",
        "resets.resetting": "正在重置…",
        "resets.confirmTitle": "现在重置 Codex 额度？",
        "resets.confirmBody": "将使用一次储备的重置：会话和每周额度会立即刷新。剩余次数：%ld。",
        "resets.outcome.reset": "Codex 额度已重置",
        "resets.outcome.nothing": "暂时没有需要重置的额度",
        "resets.outcome.noCredit": "没有可用的重置次数",
        "resets.outcome.already": "这次重置已经用过了",
        "resets.outcome.failed": "重置失败 — 这台 Mac 上的 Codex 登录了吗？",

        "drop.here": "松开 — 我会为代理复制路径",
        "drop.copiedOne": "已复制 %@ 的路径 — 粘贴给你的代理 (⌘V)",
        "drop.copiedMany": "已复制 %ld 个路径 — 粘贴给你的代理 (⌘V)",
        "drop.remoteCantSee": "%@ 上的代理看不到这台 Mac 上的文件。",
        "drop.willSendOne": "已复制服务器路径 — 文件会随你的下一条消息发送到 %@ (⌘V)",
        "drop.willSendMany": "已复制服务器路径 — %1$ld 个文件会随你的下一条消息发送到 %2$@ (⌘V)",
        "drop.delivered": "已送达 %1$@：%2$ld",
        "drop.skippedFolders": "暂不支持发送文件夹。",
        "drop.tooBig": "每次最多 20 MB。",
        "drop.shelfInFullDenny": "文件暂存架和音乐控制 — 在完整版 Denny 中 →",
        "fullDenny": "任务、笔记和离线 AI — 完整版 Denny →",

        "alerts.menu": "通知",
        "alerts.finish": "任务完成",
        "alerts.limit": "套餐额度",
        "alerts.budget": "每日预算（API 价格）",
        "alerts.off": "关闭",
        "alerts.anyLength": "任意时长",
        "alerts.longerThan": "超过 %ld 分钟",
        "alerts.atPercent": "达到 %ld%%",
        "alerts.finishedTitle": "%@ 完成了",
        "alerts.finishedBody": "%1$@ · 工作了 %2$@",
        "alerts.limitTitle": "%1$@ 额度已达 %2$ld%%",
        "alerts.budgetTitle": "已达每日预算：%@",
        "alerts.budgetBody": "按 API 标价计算，包括这台 Mac 和你的服务器。",

        "menu.claude": "关注 Claude Code",
        "menu.codex": "关注 Codex",
        "menu.remote": "远程服务器 (SSH)…",
        "menu.fullDenny": "获取完整版 Denny…",
        "menu.quit": "退出 Denny for Agents",
        "remote.title": "关注 SSH 服务器上的代理",
        "remote.body": "1. 连接期间转发端口：在 Termius 中添加 Remote 端口转发规则（服务器 127.0.0.1:{port} → 这台 Mac 127.0.0.1:{port}），或用 ssh -R {port}:127.0.0.1:{port} user@server 连接\n2. 把仓库里的 remote/denny-hook.py 放到服务器的 ~/.denny-for-agents/。\n3. 在服务器上运行复制的命令，然后运行：python3 ~/.denny-for-agents/denny-hook.py --ping",
        "remote.copy": "复制安装命令",
        "remote.unavailable": "远程模式无法启动：端口被占用。",
        "common.close": "关闭",
        "common.cancel": "取消",
        "connect.title": "把 Denny 连接到你的代理？",
        "connect.body": "Denny 会在 ~/.claude/settings.json 和 ~/.codex/hooks.json 中添加 hook（并在旁边保存备份）。如果 Denny 没有运行，这些 hook 什么也不做，绝不会阻塞你的代理。",
        "connect.connect": "连接",
        "connect.later": "稍后",
        "connect.failed": "无法修改设置文件"
    ]
}
