extension Translations {
    static let english: [String: String] = [
        // Agent steps
        "step.runs": "Runs %@",
        "step.runsCommand": "Runs a command",
        "step.reads": "Reads %@",
        "step.aFile": "a file",
        "step.edits": "Edits %@",
        "step.editsFiles": "Edits files",
        "step.searches": "Searches “%@”",
        "step.searchesCode": "Searches the code",
        "step.searchesWeb": "Searches the web",
        "step.opens": "Opens %@",
        "step.startsHelper": "Starts a helper agent",
        "step.updatesPlan": "Updates the plan",
        "step.uses": "Uses %@",
        "step.working": "Working…",
        "step.thinking": "Thinking…",
        "step.waitingForYou": "Waiting for you",
        "step.done": "Done",

        // Header
        "title.idle": "All quiet",
        "title.working": "Agents at work",
        "title.needsYou": "Needs you",
        "title.limitUsedUp": "%@ limit used up",
        "title.limitAlmost": "%@ limit almost used",
        "subtitle.noSessions": "Start Claude Code or Codex — I'll keep an eye on it.",
        "subtitle.noHooks": "Connect Claude Code and Codex in the menu bar.",
        "subtitle.serverDown": "Couldn't start listening for agents.",
        "limit.detailResets": "%1$@, resets in %2$@",

        // Approvals
        "approval.allow": "Allow",
        "approval.deny": "Deny",
        "approval.askThere": "Ask there",
        "approval.wantsTo": "wants to",
        "approval.more": "+%ld more waiting",

        // Stats
        "stats.spending": "Spending",
        "stats.apiValue": "API value",
        "stats.now": "Now",
        "stats.workingNow": "working",
        "stats.limitsLater": "Limits show up after the next reply",
        "stats.updated": "Updated %@",
        "stats.tokens": "%@ tokens",
        "stats.tokensWord": "tokens",
        "stats.fromCache": "%ld%% from cache",
        "stats.todayTotal": "Today %@",
        "stats.noPrice": "No public price for Codex models",
        "period.today": "Today",
        "period.week": "7 days",
        "period.month": "30 days",
        "window.session": "Session",
        "window.week": "Week",
        "window.limit": "Limit",
        "stats.activity": "Activity",
        "stats.streak": "%ld-day streak",
        "stats.activeDays": "Active days",
        "stats.busiestDay": "Busiest day",

        // Time
        "time.daysHours": "%1$ldd %2$ldh",
        "time.hoursMinutes": "%1$ldh %2$ldm",
        "time.minutes": "%ldm",
        "time.hours": "%ldh",
        "time.days": "%ldd",
        "time.months": "%ldmo",
        "time.justNow": "just now",
        "time.ago": "%@ ago",

        // Codex resets
        "resets.line": "Resets: %ld",
        "resets.expiresIn": "next expires in %@",
        "resets.use": "Use a reset",
        "resets.resetting": "Resetting…",
        "resets.confirmTitle": "Reset Codex limits now?",
        "resets.confirmBody": "Uses one banked reset: the session and weekly limits renew right away. Resets left: %ld.",
        "resets.outcome.reset": "Codex limits were reset",
        "resets.outcome.nothing": "Nothing to reset yet",
        "resets.outcome.noCredit": "No resets left",
        "resets.outcome.already": "That reset was already used",
        "resets.outcome.failed": "Couldn't use a reset — is Codex signed in on this Mac?",

        // Files
        "drop.here": "Drop — I'll copy the path for your agent",
        "drop.copiedOne": "Copied the path to %@ — paste it to your agent (⌘V)",
        "drop.copiedMany": "Copied %ld paths — paste them to your agent (⌘V)",
        "drop.remoteCantSee": "The agent on %@ can't see files on this Mac.",
        "drop.willSendOne": "Copied the server path — the file goes to %@ with your next message (⌘V)",
        "drop.willSendMany": "Copied the server paths — %1$ld files go to %2$@ with your next message (⌘V)",
        "drop.delivered": "Delivered to %1$@: %2$ld",
        "drop.skippedFolders": "Folders aren't sent yet.",
        "drop.tooBig": "Up to 20 MB per drop.",
        "drop.shelfInFullDenny": "Keep files on a shelf and control music — in full Denny →",
        "fullDenny": "Tasks, notes & offline AI — full Denny →",

        // Notifications
        "alerts.menu": "Notifications",
        "alerts.finish": "Task finished",
        "alerts.limit": "Plan limit",
        "alerts.budget": "Daily API budget",
        "alerts.off": "Off",
        "alerts.anyLength": "Any length",
        "alerts.longerThan": "Longer than %ld min",
        "alerts.atPercent": "At %ld%%",
        "alerts.finishedTitle": "%@ is done",
        "alerts.finishedBody": "%1$@ · worked %2$@",
        "alerts.limitTitle": "%1$@ limit at %2$ld%%",
        "alerts.budgetTitle": "Daily budget reached: %@",
        "alerts.budgetBody": "At API list prices, across this Mac and your servers.",

        // Menu and setup
        "menu.claude": "Watch Claude Code",
        "menu.codex": "Watch Codex",
        "menu.remote": "Remote server (SSH)…",
        "menu.fullDenny": "Get full Denny…",
        "menu.quit": "Quit Denny for Agents",
        "remote.title": "Watch agents on an SSH server",
        "remote.body": "1. Forward the port while connected: in Termius add a Remote port forwarding rule (server 127.0.0.1:{port} → this Mac 127.0.0.1:{port}), or connect with ssh -R {port}:127.0.0.1:{port} user@server\n2. Put remote/denny-hook.py from the repo into ~/.denny-for-agents/ on the server.\n3. On the server run the copied command, then: python3 ~/.denny-for-agents/denny-hook.py --ping",
        "remote.copy": "Copy install command",
        "remote.unavailable": "Remote mode couldn't start: port is busy.",
        "common.close": "Close",
        "common.cancel": "Cancel",
        "connect.title": "Connect Denny to your agents?",
        "connect.body": "Denny will add hooks to ~/.claude/settings.json and ~/.codex/hooks.json (a backup is saved next to each file). If Denny isn't running, the hooks do nothing and never block your agents.",
        "connect.connect": "Connect",
        "connect.later": "Later",
        "connect.failed": "Couldn't update the settings file"
    ]
}
