extension Translations {
    static let english: [String: String] = [
        // Agent steps
        "step.runs": "Runs %@",
        "step.runsCommand": "Runs a command",
        "step.reads": "Reads %@",
        "step.aFile": "a file",
        "step.edits": "Edits %@",
        "step.editsFiles": "Edits files",
        "step.searches": "Searches “%@”",
        "step.searchesCode": "Searches the code",
        "step.searchesWeb": "Searches the web",
        "step.opens": "Opens %@",
        "step.startsHelper": "Starts a helper agent",
        "step.updatesPlan": "Updates the plan",
        "step.uses": "Uses %@",
        "step.working": "Working…",
        "step.thinking": "Thinking…",
        "step.waitingForYou": "Waiting for you",
        "step.done": "Done",

        // Header
        "title.idle": "All quiet",
        "title.working": "Agents at work",
        "title.needsYou": "Needs you",
        "title.limitUsedUp": "%@ limit used up",
        "title.limitAlmost": "%@ limit almost used",
        "subtitle.noSessions": "Start Claude Code or Codex — I'll keep an eye on it.",
        "subtitle.noHooks": "Connect Claude Code and Codex in the menu bar.",
        "subtitle.serverDown": "Couldn't start listening for agents.",
        "limit.detailResets": "%1$@, resets in %2$@",

        // Approvals
        "approval.allow": "Allow",
        "approval.deny": "Deny",
        "approval.askThere": "Ask there",
        "approval.wantsTo": "wants to",
        "approval.more": "+%ld more waiting",

        // Stats
        "stats.spending": "Spending",
        "stats.apiValue": "API value",
        "stats.now": "Now",
        "stats.workingNow": "working",
        "stats.limitsLater": "Limits show up after the next reply",
        "stats.updated": "Updated %@",
        "stats.tokens": "%@ tokens",
        "stats.tokensWord": "tokens",
        "stats.fromCache": "%ld%% from cache",
        "stats.todayTotal": "Today %@",
        "stats.noPrice": "No public price for Codex models",
        "period.today": "Today",
        "period.week": "7 days",
        "period.month": "30 days",
        "window.session": "Session",
        "window.week": "Week",
        "window.limit": "Limit",
        "stats.activity": "Activity",
        "stats.streak": "%ld-day streak",
        "stats.activeDays": "Active days",
        "stats.busiestDay": "Busiest day",

        // Time
        "time.daysHours": "%1$ldd %2$ldh",
        "time.hoursMinutes": "%1$ldh %2$ldm",
        "time.minutes": "%ldm",
        "time.hours": "%ldh",
        "time.days": "%ldd",
        "time.months": "%ldmo",
        "time.justNow": "just now",
        "time.ago": "%@ ago",

        // Codex resets
        "resets.line": "Resets: %ld",
        "resets.expiresIn": "next expires in %@",
        "resets.use": "Use a reset",
        "resets.resetting": "Resetting…",
        "resets.confirmTitle": "Reset Codex limits now?",
        "resets.confirmBody": "Uses one banked reset: the session and weekly limits renew right away. Resets left: %ld.",
        "resets.outcome.reset": "Codex limits were reset",
        "resets.outcome.nothing": "Nothing to reset yet",
        "resets.outcome.noCredit": "No resets left",
        "resets.outcome.already": "That reset was already used",
        "resets.outcome.failed": "Couldn't use a reset — is Codex signed in on this Mac?",

        // Files
        "drop.here": "Drop — I'll copy the path for your agent",
        "drop.copiedOne": "Copied the path to %@ — paste it to your agent (⌘V)",
        "drop.copiedMany": "Copied %ld paths — paste them to your agent (⌘V)",
        "drop.remoteCantSee": "The agent on %@ can't see files on this Mac.",
        "drop.willSendOne": "Copied the server path — the file goes to %@ with your next message (⌘V)",
        "drop.willSendMany": "Copied the server paths — %1$ld files go to %2$@ with your next message (⌘V)",
        "drop.delivered": "Delivered to %1$@: %2$ld",
        "drop.skippedFolders": "Folders aren't sent yet.",
        "drop.tooBig": "Up to 20 MB per drop.",
        "drop.shelfInFullDenny": "Keep files on a shelf and control music — in full Denny →",
        "fullDenny": "Tasks, notes & offline AI — full Denny →",

        // Notifications
        "alerts.menu": "Notifications",
        "alerts.finish": "Task finished",
        "alerts.limit": "Plan limit",
        "alerts.budget": "Daily API budget",
        "alerts.off": "Off",
        "alerts.anyLength": "Any length",
        "alerts.longerThan": "Longer than %ld min",
        "alerts.atPercent": "At %ld%%",
        "alerts.finishedTitle": "%@ is done",
        "alerts.finishedBody": "%1$@ · worked %2$@",
        "alerts.limitTitle": "%1$@ limit at %2$ld%%",
        "alerts.budgetTitle": "Daily budget reached: %@",
        "alerts.budgetBody": "At API list prices, across this Mac and your servers.",

        // Menu and setup
        "menu.claude": "Watch Claude Code",
        "menu.codex": "Watch Codex",
        "menu.remote": "Remote server (SSH)…",
        "menu.fullDenny": "Get full Denny…",
        "menu.quit": "Quit Denny for Agents",
        "remote.title": "Watch agents on an SSH server",
        "remote.body": "1. Forward the port while connected: in Termius add a Remote port forwarding rule (server 127.0.0.1:{port} → this Mac 127.0.0.1:{port}), or connect with ssh -R {port}:127.0.0.1:{port} user@server\n2. Put remote/denny-hook.py from the repo into ~/.denny-for-agents/ on the server.\n3. On the server run the copied command, then: python3 ~/.denny-for-agents/denny-hook.py --ping",
        "remote.copy": "Copy install command",
        "remote.unavailable": "Remote mode couldn't start: port is busy.",
        "common.close": "Close",
        "common.cancel": "Cancel",
        "connect.title": "Connect Denny to your agents?",
        "connect.body": "Denny will add hooks to ~/.claude/settings.json and ~/.codex/hooks.json (a backup is saved next to each file). If Denny isn't running, the hooks do nothing and never block your agents.",
        "connect.connect": "Connect",
        "connect.later": "Later",
        "connect.failed": "Couldn't update the settings file",

        "value.title": "Plan value",
        "value.line": "%@ at API prices in 30 days",
        "value.planMonthly": "%1$@ · %2$@/mo",
        "stats.trend": "Trend",
        "stats.models": "Models",
        "stats.projects": "Projects",
        "stats.peak": "peak %@",
        "card.limits": "Limits",
        "alerts.renewedTitle": "%@ limit renewed",
        "menu.cards": "Cards",
        "menu.readout": "By the camera",
        "readout.timer": "Task timer",
        "readout.limit": "Tightest limit",
        "page.overview": "Overview",
        "page.stats": "Stats",
        "stats.noFresh": "No fresh data",

        "settings.title": "Settings",
        "settings.menu": "Settings…",
        "settings.section.agents": "Agents",
        "settings.section.servers": "Servers",
        "settings.section.notch": "Notch",
        "settings.section.cards": "Cards",
        "settings.section.alerts": "Notifications",
        "settings.section.language": "Language",
        "settings.section.privacy": "Privacy",
        "settings.section.about": "About",
        "settings.connected": "Connected",
        "settings.notConnected": "Not connected",
        "settings.disconnect": "Disconnect",
        "settings.agentsFooter": "Denny adds its hooks to each agent's settings file and saves a backup next to it. If Denny isn't running, the hooks do nothing.",
        "settings.keepAwake": "Keep the Mac awake while agents work",
        "settings.keepAwakeFooter": "Only while an agent on this Mac is working. The display can still turn off.",
        "settings.serversConnected": "Connected servers",
        "settings.noServers": "No servers yet. Set one up below.",
        "settings.lastSeen": "last seen %@",
        "settings.peeks": "Peeks",
        "settings.peekOnStart": "When you send a task",
        "settings.peekOnWriting": "When the agent starts writing code",
        "settings.peekOnFinish": "When the agent finishes",
        "settings.display": "Display",
        "settings.displayAuto": "The one with the notch",
        "settings.fullScreen": "Show over full-screen apps",
        "settings.cardsFooter": "Cards you turn off disappear from the notch. Overview holds limits, spending and Now; Stats holds the rest.",
        "settings.languageSystem": "Same as the system",
        "settings.languageRestart": "The new language applies after a restart.",
        "settings.restart": "Restart now",
        "settings.privacyReads": "What Denny reads",
        "settings.privacyReadsBody": "Token counts, model names, times and project folder names from Claude Code and Codex logs; plan limits from ~/.claude.json, the Claude app and Codex; the events your agents send to the hooks.",
        "settings.privacyNever": "What Denny never reads or sends",
        "settings.privacyNeverBody": "Your prompts, answers and file contents. Nothing leaves your machines except a daily download of the public price list. Files you drop on the notch go only to your own server.",
        "settings.removeAll": "Disconnect agents and erase Denny's data",
        "settings.removeAllFooter": "Removes the hooks from Claude Code and Codex, deletes ~/.denny-for-agents with its history and settings, then quits.",
        "settings.removeAllConfirm": "Erase everything Denny for Agents saved?",
        "settings.version": "Version %@",
        "settings.about": "A small robot in your notch that keeps an eye on Claude Code and Codex. The free, open part of Denny.",

        "quiet.on": "Quiet for an hour",
        "quiet.active": "Quiet until %@ — tap to end",
        "quick.refresh": "Refresh now",
        "awake.manual": "Stay awake manually",
        "awake.duration": "For",
        "awake.until": "Until",
        "awake.indefinite": "Until I turn it off",
        "awake.start": "Start",
        "awake.stop": "Stop",
        "awake.activeUntil": "The Mac stays awake until %@",
        "awake.untilOff": "The Mac stays awake until you stop it",
        "awake.lid": "Keep working with the lid closed",
        "awake.lidWarning": "Works only on the charger. Asks for your admin password once to allow exactly one command (pmset disablesleep) and turns itself off when the work is done. Don't put a running closed Mac in a bag.",
        "awake.lidNeedsPower": "On battery now — it will turn on when you plug in the charger.",

        "risk.safe": "Looks safe",
        "risk.caution": "Worth a glance",
        "risk.danger": "Dangerous",
        "risk.critical": "Very dangerous",
        "risk.reason.pipeToShell": "Downloads code from the internet and runs it right away.",
        "risk.reason.wipeRoot": "Deletes everything in /, your home folder or the current folder.",
        "risk.reason.rawDisk": "Writes straight to a disk — can wipe it.",
        "risk.reason.format": "Formats or erases a disk.",
        "risk.reason.forkBomb": "A fork bomb: it would freeze the Mac.",
        "risk.reason.dropData": "Deletes database tables or data.",
        "risk.reason.deleteRecursive": "Deletes the folder %@ with everything inside, no Trash.",
        "risk.reason.forcePush": "Overwrites the branch history on the server.",
        "risk.reason.resetHard": "Throws away all uncommitted changes.",
        "risk.reason.cleanUntracked": "Deletes files git doesn't track.",
        "risk.reason.sudo": "Runs as administrator (sudo).",
        "risk.reason.permissions": "Opens files up to everyone or changes their owner.",
        "risk.reason.killProcess": "Force-stops running programs.",
        "risk.reason.reboot": "Shuts down or restarts the computer.",
        "risk.reason.dockerPrune": "Deletes Docker containers, volumes or data.",
        "risk.reason.publish": "Publishes a package or release for everyone.",
        "risk.reason.secrets": "Touches keys, passwords or .env secrets.",
        "risk.reason.push": "Sends commits to the server.",
        "risk.reason.deleteFile": "Deletes %@.",
        "risk.reason.install": "Installs packages from the internet.",
        "risk.reason.network": "Talks to the network.",
        "risk.reason.gitHistory": "Rewrites git history or discards file changes.",
        "risk.reason.sensitiveFile": "Changes a sensitive file: %@.",
        "risk.reason.externalTool": "Uses an external tool (MCP server).",

        "load.thisMac": "This Mac",
        "load.cpu": "CPU",
        "load.cpuLoad": "Load (%ld cores)",
        "load.memory": "Memory",
        "load.pressureNormal": "Memory pressure: normal",
        "load.pressureWarning": "Memory pressure: high",
        "load.pressureCritical": "Memory pressure: critical",
        "load.swap": "Swap %@",
        "load.uptime": "Up for %@",
        "load.memoryLow": "Memory is almost full — a heavy build could get killed.",
        "load.noServer": "Server load arrives with the next report from a connected server.",
        "settings.section.load": "Load",

        "relay.title": "%@ hit its limit",
        "relay.titleUntil": "%1$@ hit its limit until %2$@",
        "relay.body": "Hand the task to %@? I'll write a note with what was asked and what's done.",
        "relay.copy": "Copy note for %@",
        "relay.later": "Not now",
        "relay.copied": "Note copied — paste it into %@ (⌘V)",
        "relay.handoff": "Hand the task to %@",
        "relay.note.intro": "Continue a task that %1$@ started (%2$@).",
        "relay.note.reasonLimit": "it hit its plan limit",
        "relay.note.reasonManual": "I'm handing it over to you",
        "relay.note.folder": "Folder: %@",
        "relay.note.server": "Server: %@",
        "relay.note.task": "The task:",
        "relay.note.done": "Already done:",
        "relay.note.edited": "edited: %@",
        "relay.note.ran": "ran: %@",
        "relay.note.last": "Last message from %@:",
        "relay.note.next": "First look at the current changes (git status, git diff), then carry on from where it stopped."
    ]
}
