extension Translations {
    static let french: [String: String] = [
        "step.runs": "Exécute %@",
        "step.runsCommand": "Exécute une commande",
        "step.reads": "Lit %@",
        "step.aFile": "un fichier",
        "step.edits": "Modifie %@",
        "step.editsFiles": "Modifie des fichiers",
        "step.searches": "Cherche « %@ »",
        "step.searchesCode": "Cherche dans le code",
        "step.searchesWeb": "Cherche sur le web",
        "step.opens": "Ouvre %@",
        "step.startsHelper": "Lance un agent assistant",
        "step.updatesPlan": "Met à jour le plan",
        "step.uses": "Utilise %@",
        "step.working": "Au travail…",
        "step.thinking": "Réfléchit…",
        "step.waitingForYou": "T'attend",
        "step.done": "Terminé",

        "title.idle": "Tout est calme",
        "title.working": "Les agents travaillent",
        "title.needsYou": "On a besoin de toi",
        "title.limitUsedUp": "Limite %@ épuisée",
        "title.limitAlmost": "Limite %@ presque épuisée",
        "subtitle.noSessions": "Lance Claude Code ou Codex — je garde un œil dessus.",
        "subtitle.noHooks": "Connecte Claude Code et Codex dans la barre des menus.",
        "subtitle.serverDown": "Impossible d'écouter les agents.",
        "limit.detailResets": "%1$@, réinitialisation dans %2$@",

        "approval.allow": "Autoriser",
        "approval.deny": "Refuser",
        "approval.askThere": "Demander là-bas",
        "approval.wantsTo": "veut",
        "approval.more": "+%ld autres en attente",

        "stats.spending": "Dépenses",
        "stats.apiValue": "valeur API",
        "stats.now": "Maintenant",
        "stats.workingNow": "au travail",
        "stats.limitsLater": "Les limites apparaîtront après la prochaine réponse",
        "stats.updated": "Mis à jour %@",
        "stats.tokens": "%@ jetons",
        "stats.tokensWord": "jetons",
        "stats.fromCache": "%ld%% depuis le cache",
        "stats.todayTotal": "Aujourd'hui %@",
        "stats.noPrice": "Pas de prix public pour les modèles Codex",
        "period.today": "Aujourd'hui",
        "period.week": "7 jours",
        "period.month": "30 jours",
        "window.session": "Session",
        "window.week": "Semaine",
        "window.limit": "Limite",
        "stats.activity": "Activité",
        "stats.streak": "%ld jours d'affilée",
        "stats.activeDays": "Jours actifs",
        "stats.busiestDay": "Jour le plus actif",

        "time.daysHours": "%1$ld j %2$ld h",
        "time.hoursMinutes": "%1$ld h %2$ld min",
        "time.minutes": "%ld min",
        "time.hours": "%ld h",
        "time.days": "%ld j",
        "time.months": "%ld mois",
        "time.justNow": "à l'instant",
        "time.ago": "il y a %@",

        "resets.line": "Réinitialisations : %ld",
        "resets.expiresIn": "la prochaine expire dans %@",
        "resets.use": "Utiliser une réinitialisation",
        "resets.resetting": "Réinitialisation…",
        "resets.confirmTitle": "Réinitialiser les limites Codex maintenant ?",
        "resets.confirmBody": "Utilise une réinitialisation en réserve : les limites de session et de semaine repartent à zéro. Restantes : %ld.",
        "resets.outcome.reset": "Limites Codex réinitialisées",
        "resets.outcome.nothing": "Rien à réinitialiser pour l'instant",
        "resets.outcome.noCredit": "Plus de réinitialisations disponibles",
        "resets.outcome.already": "Cette réinitialisation a déjà été utilisée",
        "resets.outcome.failed": "Échec — Codex est-il connecté sur ce Mac ?",

        "drop.here": "Lâche — je copie le chemin pour ton agent",
        "drop.copiedOne": "Chemin de %@ copié — colle-le à ton agent (⌘V)",
        "drop.copiedMany": "%ld chemins copiés — colle-les à ton agent (⌘V)",
        "drop.remoteCantSee": "L'agent sur %@ ne voit pas les fichiers de ce Mac.",
        "drop.willSendOne": "Chemin serveur copié — le fichier part vers %@ avec ton prochain message (⌘V)",
        "drop.willSendMany": "Chemins serveur copiés — %1$ld fichiers partent vers %2$@ avec ton prochain message (⌘V)",
        "drop.delivered": "Livré sur %1$@ : %2$ld",
        "drop.skippedFolders": "Les dossiers ne sont pas encore envoyés.",
        "drop.tooBig": "Jusqu'à 20 Mo par dépôt.",
        "drop.shelfInFullDenny": "Étagère à fichiers et contrôle de la musique — dans Denny complet →",
        "fullDenny": "Tâches, notes et IA hors ligne — Denny complet →",

        "alerts.menu": "Notifications",
        "alerts.finish": "Tâche terminée",
        "alerts.limit": "Limite du forfait",
        "alerts.budget": "Budget quotidien (prix API)",
        "alerts.off": "Désactivé",
        "alerts.anyLength": "Toute durée",
        "alerts.longerThan": "Plus de %ld min",
        "alerts.atPercent": "À %ld%%",
        "alerts.finishedTitle": "%@ a terminé",
        "alerts.finishedBody": "%1$@ · a travaillé %2$@",
        "alerts.limitTitle": "Limite %1$@ à %2$ld%%",
        "alerts.budgetTitle": "Budget quotidien atteint : %@",
        "alerts.budgetBody": "Aux prix catalogue de l'API, sur ce Mac et tes serveurs.",

        "menu.claude": "Surveiller Claude Code",
        "menu.codex": "Surveiller Codex",
        "menu.remote": "Serveur distant (SSH)…",
        "menu.fullDenny": "Obtenir Denny complet…",
        "menu.quit": "Quitter Denny for Agents",
        "remote.title": "Surveiller les agents sur un serveur SSH",
        "remote.body": "1. Redirige le port pendant la connexion : dans Termius, ajoute une règle de redirection Remote (serveur 127.0.0.1:{port} → ce Mac 127.0.0.1:{port}), ou connecte-toi avec ssh -R {port}:127.0.0.1:{port} user@server\n2. Place remote/denny-hook.py du dépôt dans ~/.denny-for-agents/ sur le serveur.\n3. Sur le serveur, lance la commande copiée, puis : python3 ~/.denny-for-agents/denny-hook.py --ping",
        "remote.copy": "Copier la commande d'installation",
        "remote.unavailable": "Le mode distant n'a pas pu démarrer : port occupé.",
        "common.close": "Fermer",
        "common.cancel": "Annuler",
        "connect.title": "Connecter Denny à tes agents ?",
        "connect.body": "Denny ajoutera des hooks à ~/.claude/settings.json et ~/.codex/hooks.json (une sauvegarde est créée à côté). Si Denny ne tourne pas, les hooks ne font rien et ne bloquent jamais tes agents.",
        "connect.connect": "Connecter",
        "connect.later": "Plus tard",
        "connect.failed": "Impossible de modifier le fichier de réglages",

        "value.title": "Valeur du forfait",
        "value.line": "%@ aux prix API sur 30 jours",
        "value.planMonthly": "%1$@ · %2$@/mois",
        "stats.trend": "Tendance",
        "stats.models": "Modèles",
        "stats.projects": "Projets",
        "stats.peak": "pic %@",
        "card.limits": "Limites",
        "alerts.renewedTitle": "Limite %@ renouvelée",
        "menu.cards": "Cartes",
        "menu.readout": "Près de la caméra",
        "readout.timer": "Minuteur de tâche",
        "readout.limit": "Limite la plus proche",
        "page.overview": "Aperçu",
        "page.stats": "Statistiques",
        "stats.noFresh": "Pas de données récentes",

        "settings.title": "Réglages",
        "settings.menu": "Réglages…",
        "settings.section.agents": "Agents",
        "settings.section.servers": "Serveurs",
        "settings.section.notch": "Encoche",
        "settings.section.cards": "Cartes",
        "settings.section.alerts": "Notifications",
        "settings.section.language": "Langue",
        "settings.section.privacy": "Confidentialité",
        "settings.section.about": "À propos",
        "settings.connected": "Connecté",
        "settings.notConnected": "Non connecté",
        "settings.disconnect": "Déconnecter",
        "settings.agentsFooter": "Denny ajoute ses hooks au fichier de réglages de chaque agent et garde une sauvegarde à côté. Si Denny ne tourne pas, les hooks ne font rien.",
        "settings.keepAwake": "Empêcher la veille du Mac pendant que les agents travaillent",
        "settings.keepAwakeFooter": "Seulement pendant qu'un agent travaille sur ce Mac. L'écran peut tout de même s'éteindre.",
        "settings.serversConnected": "Serveurs connectés",
        "settings.noServers": "Aucun serveur pour l'instant. Configure-en un ci-dessous.",
        "settings.lastSeen": "vu %@",
        "settings.peeks": "Apparitions",
        "settings.peekOnStart": "Quand tu envoies une tâche",
        "settings.peekOnWriting": "Quand l'agent commence à écrire du code",
        "settings.peekOnFinish": "Quand l'agent a terminé",
        "settings.display": "Écran",
        "settings.displayAuto": "Celui avec l'encoche",
        "settings.fullScreen": "Afficher par-dessus les apps en plein écran",
        "settings.cardsFooter": "Les cartes désactivées disparaissent de l'encoche. Aperçu contient limites, dépenses et Maintenant ; Statistiques le reste.",
        "settings.languageSystem": "Comme le système",
        "settings.languageRestart": "La nouvelle langue s'applique après un redémarrage.",
        "settings.restart": "Redémarrer",
        "settings.privacyReads": "Ce que Denny lit",
        "settings.privacyReadsBody": "Nombre de jetons, noms de modèles, heures et noms de dossiers de projet depuis les journaux de Claude Code et Codex ; limites du forfait depuis ~/.claude.json, l'app Claude et Codex ; les événements que tes agents envoient aux hooks.",
        "settings.privacyNever": "Ce que Denny ne lit ni n'envoie jamais",
        "settings.privacyNeverBody": "Tes prompts, réponses et contenus de fichiers. Rien ne quitte tes machines, sauf le téléchargement quotidien de la liste de prix publique. Les fichiers déposés sur l'encoche vont uniquement sur ton serveur.",
        "settings.removeAll": "Déconnecter les agents et effacer les données de Denny",
        "settings.removeAllFooter": "Retire les hooks de Claude Code et Codex, supprime ~/.denny-for-agents avec l'historique et les réglages, puis quitte.",
        "settings.removeAllConfirm": "Effacer tout ce que Denny for Agents a enregistré ?",
        "settings.version": "Version %@",
        "settings.about": "Un petit robot dans ton encoche qui garde un œil sur Claude Code et Codex. La partie libre et gratuite de Denny.",

        "quiet.on": "Silence pendant une heure",
        "quiet.active": "Silence jusqu'à %@ — touche pour arrêter",
        "quick.refresh": "Actualiser",
        "awake.manual": "Rester éveillé manuellement",
        "awake.duration": "Pendant",
        "awake.until": "Jusqu'à",
        "awake.indefinite": "Jusqu'à ce que je l'arrête",
        "awake.start": "Démarrer",
        "awake.stop": "Arrêter",
        "awake.activeUntil": "Le Mac reste éveillé jusqu'à %@",
        "awake.untilOff": "Le Mac reste éveillé jusqu'à ce que tu l'arrêtes",
        "awake.lid": "Continuer écran rabattu",
        "awake.lidWarning": "Uniquement sur secteur. Demande une fois le mot de passe administrateur pour autoriser une seule commande (pmset disablesleep) et se désactive quand le travail est fini. Ne range pas un Mac fermé en marche dans un sac.",
        "awake.lidNeedsPower": "Sur batterie — s'activera quand tu brancheras le chargeur.",

        "risk.safe": "Semble sûr",
        "risk.caution": "À vérifier",
        "risk.danger": "Dangereux",
        "risk.critical": "Très dangereux",
        "risk.reason.pipeToShell": "Télécharge du code depuis Internet et l'exécute aussitôt.",
        "risk.reason.wipeRoot": "Supprime tout dans /, ton dossier personnel ou le dossier courant.",
        "risk.reason.rawDisk": "Écrit directement sur un disque — peut l'effacer.",
        "risk.reason.format": "Formate ou efface un disque.",
        "risk.reason.forkBomb": "Une fork bomb : le Mac va se figer.",
        "risk.reason.dropData": "Supprime des tables ou des données de base.",
        "risk.reason.deleteRecursive": "Supprime le dossier %@ et tout son contenu, sans corbeille.",
        "risk.reason.forcePush": "Réécrit l'historique de la branche sur le serveur.",
        "risk.reason.resetHard": "Jette toutes les modifications non commitées.",
        "risk.reason.cleanUntracked": "Supprime les fichiers que git ne suit pas.",
        "risk.reason.sudo": "S'exécute en administrateur (sudo).",
        "risk.reason.permissions": "Ouvre des fichiers à tout le monde ou change leur propriétaire.",
        "risk.reason.killProcess": "Arrête de force des programmes.",
        "risk.reason.reboot": "Éteint ou redémarre l'ordinateur.",
        "risk.reason.dockerPrune": "Supprime des conteneurs, volumes ou données Docker.",
        "risk.reason.publish": "Publie un paquet ou une version pour tout le monde.",
        "risk.reason.secrets": "Touche à des clés, mots de passe ou secrets .env.",
        "risk.reason.push": "Envoie des commits au serveur.",
        "risk.reason.deleteFile": "Supprime %@.",
        "risk.reason.install": "Installe des paquets depuis Internet.",
        "risk.reason.network": "Accède au réseau.",
        "risk.reason.gitHistory": "Réécrit l'historique git ou annule des modifications.",
        "risk.reason.sensitiveFile": "Modifie un fichier sensible : %@.",
        "risk.reason.externalTool": "Utilise un outil externe (serveur MCP).",

        "load.thisMac": "Ce Mac",
        "load.cpu": "Processeur",
        "load.cpuLoad": "Charge (%ld cœurs)",
        "load.memory": "Mémoire",
        "load.pressureNormal": "Pression mémoire : normale",
        "load.pressureWarning": "Pression mémoire : élevée",
        "load.pressureCritical": "Pression mémoire : critique",
        "load.swap": "Swap %@",
        "load.uptime": "Allumé depuis %@",
        "load.memoryLow": "Mémoire presque pleine — un gros build pourrait être tué.",
        "load.noServer": "La charge du serveur arrivera avec le prochain rapport d'un serveur connecté.",
        "settings.section.load": "Charge",

        "relay.title": "%@ a atteint sa limite",
        "relay.titleUntil": "%1$@ a atteint sa limite jusqu'à %2$@",
        "relay.body": "Passer la tâche à %@ ? J'écris une note avec la demande et ce qui est fait.",
        "relay.copy": "Copier la note pour %@",
        "relay.later": "Pas maintenant",
        "relay.copied": "Note copiée — colle-la dans %@ (⌘V)",
        "relay.handoff": "Passer la tâche à %@",
        "relay.note.intro": "Reprends une tâche commencée par %1$@ (%2$@).",
        "relay.note.reasonLimit": "il a atteint la limite de son forfait",
        "relay.note.reasonManual": "je te la confie",
        "relay.note.folder": "Dossier : %@",
        "relay.note.server": "Serveur : %@",
        "relay.note.task": "La tâche :",
        "relay.note.done": "Déjà fait :",
        "relay.note.edited": "modifié : %@",
        "relay.note.ran": "exécuté : %@",
        "relay.note.last": "Dernier message de %@ :",
        "relay.note.next": "Regarde d'abord les changements en cours (git status, git diff), puis reprends là où ça s'est arrêté."
    ]
}
