extension Translations {
    static let french: [String: String] = [
        "step.runs": "Exécute %@",
        "step.runsCommand": "Exécute une commande",
        "step.reads": "Lit %@",
        "step.aFile": "un fichier",
        "step.edits": "Modifie %@",
        "step.editsFiles": "Modifie des fichiers",
        "step.searches": "Cherche « %@ »",
        "step.searchesCode": "Cherche dans le code",
        "step.searchesWeb": "Cherche sur le web",
        "step.opens": "Ouvre %@",
        "step.startsHelper": "Lance un agent assistant",
        "step.updatesPlan": "Met à jour le plan",
        "step.uses": "Utilise %@",
        "step.working": "Au travail…",
        "step.thinking": "Réfléchit…",
        "step.waitingForYou": "T'attend",
        "step.done": "Terminé",

        "title.idle": "Tout est calme",
        "title.working": "Les agents travaillent",
        "title.needsYou": "On a besoin de toi",
        "title.limitUsedUp": "Limite %@ épuisée",
        "title.limitAlmost": "Limite %@ presque épuisée",
        "subtitle.noSessions": "Lance Claude Code ou Codex — je garde un œil dessus.",
        "subtitle.noHooks": "Connecte Claude Code et Codex dans la barre des menus.",
        "subtitle.serverDown": "Impossible d'écouter les agents.",
        "limit.detailResets": "%1$@, réinitialisation dans %2$@",

        "approval.allow": "Autoriser",
        "approval.deny": "Refuser",
        "approval.askThere": "Demander là-bas",
        "approval.wantsTo": "veut",
        "approval.more": "+%ld autres en attente",

        "stats.spending": "Dépenses",
        "stats.apiValue": "valeur API",
        "stats.now": "Maintenant",
        "stats.workingNow": "au travail",
        "stats.limitsLater": "Les limites apparaîtront après la prochaine réponse",
        "stats.updated": "Mis à jour %@",
        "stats.tokens": "%@ jetons",
        "stats.tokensWord": "jetons",
        "stats.fromCache": "%ld%% depuis le cache",
        "stats.todayTotal": "Aujourd'hui %@",
        "stats.noPrice": "Pas de prix public pour les modèles Codex",
        "period.today": "Aujourd'hui",
        "period.week": "7 jours",
        "period.month": "30 jours",
        "window.session": "Session",
        "window.week": "Semaine",
        "window.limit": "Limite",
        "stats.activity": "Activité",
        "stats.streak": "%ld jours d'affilée",
        "stats.activeDays": "Jours actifs",
        "stats.busiestDay": "Jour le plus actif",

        "time.daysHours": "%1$ld j %2$ld h",
        "time.hoursMinutes": "%1$ld h %2$ld min",
        "time.minutes": "%ld min",
        "time.hours": "%ld h",
        "time.days": "%ld j",
        "time.months": "%ld mois",
        "time.justNow": "à l'instant",
        "time.ago": "il y a %@",

        "resets.line": "Réinitialisations : %ld",
        "resets.expiresIn": "la prochaine expire dans %@",
        "resets.use": "Utiliser une réinitialisation",
        "resets.resetting": "Réinitialisation…",
        "resets.confirmTitle": "Réinitialiser les limites Codex maintenant ?",
        "resets.confirmBody": "Utilise une réinitialisation en réserve : les limites de session et de semaine repartent à zéro. Restantes : %ld.",
        "resets.outcome.reset": "Limites Codex réinitialisées",
        "resets.outcome.nothing": "Rien à réinitialiser pour l'instant",
        "resets.outcome.noCredit": "Plus de réinitialisations disponibles",
        "resets.outcome.already": "Cette réinitialisation a déjà été utilisée",
        "resets.outcome.failed": "Échec — Codex est-il connecté sur ce Mac ?",

        "drop.here": "Lâche — je copie le chemin pour ton agent",
        "drop.copiedOne": "Chemin de %@ copié — colle-le à ton agent (⌘V)",
        "drop.copiedMany": "%ld chemins copiés — colle-les à ton agent (⌘V)",
        "drop.remoteCantSee": "L'agent sur %@ ne voit pas les fichiers de ce Mac.",
        "drop.willSendOne": "Chemin serveur copié — le fichier part vers %@ avec ton prochain message (⌘V)",
        "drop.willSendMany": "Chemins serveur copiés — %1$ld fichiers partent vers %2$@ avec ton prochain message (⌘V)",
        "drop.delivered": "Livré sur %1$@ : %2$ld",
        "drop.skippedFolders": "Les dossiers ne sont pas encore envoyés.",
        "drop.tooBig": "Jusqu'à 20 Mo par dépôt.",
        "drop.shelfInFullDenny": "Étagère à fichiers et contrôle de la musique — dans Denny complet →",
        "fullDenny": "Tâches, notes et IA hors ligne — Denny complet →",

        "alerts.menu": "Notifications",
        "alerts.finish": "Tâche terminée",
        "alerts.limit": "Limite du forfait",
        "alerts.budget": "Budget quotidien (prix API)",
        "alerts.off": "Désactivé",
        "alerts.anyLength": "Toute durée",
        "alerts.longerThan": "Plus de %ld min",
        "alerts.atPercent": "À %ld%%",
        "alerts.finishedTitle": "%@ a terminé",
        "alerts.finishedBody": "%1$@ · a travaillé %2$@",
        "alerts.limitTitle": "Limite %1$@ à %2$ld%%",
        "alerts.budgetTitle": "Budget quotidien atteint : %@",
        "alerts.budgetBody": "Aux prix catalogue de l'API, sur ce Mac et tes serveurs.",

        "menu.claude": "Surveiller Claude Code",
        "menu.codex": "Surveiller Codex",
        "menu.remote": "Serveur distant (SSH)…",
        "menu.fullDenny": "Obtenir Denny complet…",
        "menu.quit": "Quitter Denny for Agents",
        "remote.title": "Surveiller les agents sur un serveur SSH",
        "remote.body": "1. Redirige le port pendant la connexion : dans Termius, ajoute une règle de redirection Remote (serveur 127.0.0.1:{port} → ce Mac 127.0.0.1:{port}), ou connecte-toi avec ssh -R {port}:127.0.0.1:{port} user@server\n2. Place remote/denny-hook.py du dépôt dans ~/.denny-for-agents/ sur le serveur.\n3. Sur le serveur, lance la commande copiée, puis : python3 ~/.denny-for-agents/denny-hook.py --ping",
        "remote.copy": "Copier la commande d'installation",
        "remote.unavailable": "Le mode distant n'a pas pu démarrer : port occupé.",
        "common.close": "Fermer",
        "common.cancel": "Annuler",
        "connect.title": "Connecter Denny à tes agents ?",
        "connect.body": "Denny ajoutera des hooks à ~/.claude/settings.json et ~/.codex/hooks.json (une sauvegarde est créée à côté). Si Denny ne tourne pas, les hooks ne font rien et ne bloquent jamais tes agents.",
        "connect.connect": "Connecter",
        "connect.later": "Plus tard",
        "connect.failed": "Impossible de modifier le fichier de réglages",

        "value.title": "Valeur du forfait",
        "value.line": "%@ aux prix API sur 30 jours",
        "value.planMonthly": "%1$@ · %2$@/mois",
        "stats.trend": "Tendance",
        "stats.models": "Modèles",
        "stats.projects": "Projets",
        "stats.peak": "pic %@",
        "card.limits": "Limites",
        "alerts.renewedTitle": "Limite %@ renouvelée",
        "menu.cards": "Cartes",
        "menu.readout": "Près de la caméra",
        "readout.timer": "Minuteur de tâche",
        "readout.limit": "Limite la plus proche",
        "page.overview": "Aperçu",
        "page.stats": "Statistiques",
        "stats.noFresh": "Pas de données récentes",

        "settings.title": "Réglages",
        "settings.menu": "Réglages…",
        "settings.section.agents": "Agents",
        "settings.section.servers": "Serveurs",
        "settings.section.notch": "Encoche",
        "settings.section.cards": "Cartes",
        "settings.section.alerts": "Notifications",
        "settings.section.language": "Langue",
        "settings.section.privacy": "Confidentialité",
        "settings.section.about": "À propos",
        "settings.connected": "Connecté",
        "settings.notConnected": "Non connecté",
        "settings.disconnect": "Déconnecter",
        "settings.agentsFooter": "Denny ajoute ses hooks au fichier de réglages de chaque agent et garde une sauvegarde à côté. Si Denny ne tourne pas, les hooks ne font rien.",
        "settings.keepAwake": "Empêcher la veille du Mac pendant que les agents travaillent",
        "settings.keepAwakeFooter": "Seulement pendant qu'un agent travaille sur ce Mac. L'écran peut tout de même s'éteindre.",
        "settings.serversConnected": "Serveurs connectés",
        "settings.noServers": "Aucun serveur pour l'instant. Configure-en un ci-dessous.",
        "settings.lastSeen": "vu %@",
        "settings.noContact": "sans contact %@",
        "ssh.title": "Connexions de Denny",
        "ssh.body": "Denny se connecte lui-même en SSH et garde le lien : après une veille, un changement de réseau ou une reconnexion VPN, il se reconnecte tout seul. Utilise les clés SSH et ~/.ssh/config de ce Mac — pas besoin de Termius.",
        "ssh.placeholder": "root@serveur ou un nom de ~/.ssh/config",
        "ssh.add": "Ajouter",
        "ssh.invalid": "Indique user@hôte ou un nom de ~/.ssh/config (pour un autre port, ajoute-le dans ~/.ssh/config).",
        "ssh.connecting": "Connexion…",
        "ssh.connected": "connecté %@",
        "ssh.retry": "nouvel essai dans %@",
        "ssh.connectAgents": "Connecter les agents",
        "ssh.connectAgentsHelp": "Installer le hook de Denny sur le serveur et y connecter Claude Code et Codex",
        "ssh.installing": "Connexion…",
        "ssh.agentsConnected": "Agents connectés. Redémarre Claude Code / Codex sur le serveur.",
        "ssh.installFailed": "Impossible de connecter les agents : %@",
        "ssh.needsKey": "Pas de clé SSH pour ce serveur",
        "ssh.keyHint": "Ce Mac a besoin d'une clé SSH acceptée par le serveur. Exécute dans le Terminal du Mac (la seconde commande demande une fois le mot de passe du serveur) :",
        "ssh.copyCommands": "Copier les commandes",
        "ssh.hostKeyChanged": "La clé du serveur a changé — vérifie-la et corrige ~/.ssh/known_hosts",
        "ssh.unreachable": "Serveur injoignable",
        "ssh.portBusy": "Port encore occupé sur le serveur, essai du suivant",
        "ssh.noPython": "python3 n'est pas installé sur le serveur",
        "ssh.dropped": "Connexion interrompue",
        "ssh.remove": "Retirer",
        "ssh.removeAndUnhook": "Retirer et déconnecter les agents sur le serveur",
        "ssh.removeQuestion": "Retirer ce serveur ?",
        "settings.peeks": "Apparitions",
        "settings.peekOnStart": "Quand tu envoies une tâche",
        "settings.peekOnWriting": "Quand l'agent commence à écrire du code",
        "settings.peekOnFinish": "Quand l'agent a terminé",
        "settings.display": "Écran",
        "settings.displayAuto": "Celui avec l'encoche",
        "settings.fullScreen": "Afficher par-dessus les apps en plein écran",
        "settings.cardsFooter": "Les cartes désactivées disparaissent de l'encoche. Aperçu contient limites, dépenses et Maintenant ; Statistiques le reste.",
        "settings.languageSystem": "Comme le système",
        "settings.languageRestart": "La nouvelle langue s'applique après un redémarrage.",
        "settings.restart": "Redémarrer",
        "settings.privacyReads": "Ce que Denny lit",
        "settings.privacyReadsBody": "Nombre de jetons, noms de modèles, heures et noms de dossiers de projet depuis les journaux de Claude Code et Codex ; limites du forfait depuis ~/.claude.json, l'app Claude et Codex ; les événements que tes agents envoient aux hooks.",
        "settings.privacyNever": "Ce que Denny ne lit ni n'envoie jamais",
        "settings.privacyNeverBody": "Tes prompts, réponses et contenus de fichiers. Rien ne quitte tes machines, sauf le téléchargement quotidien de la liste de prix publique. Les fichiers déposés sur l'encoche vont uniquement sur ton serveur.",
        "settings.removeAll": "Déconnecter les agents et effacer les données de Denny",
        "settings.removeAllFooter": "Retire les hooks de Claude Code et Codex, supprime ~/.denny-for-agents avec l'historique et les réglages, puis quitte.",
        "settings.removeAllConfirm": "Effacer tout ce que Denny for Agents a enregistré ?",
        "settings.version": "Version %@",
        "settings.about": "Un petit robot dans ton encoche qui garde un œil sur Claude Code et Codex. La partie libre et gratuite de Denny.",
        "tests.onServer": "Se lance sur %@",
        "tests.noneOnServer": "Aucun test trouvé sur le serveur",
        "server.jobWaits": "%@ : la tâche attend le serveur — elle démarre dès qu'un agent y fait quelque chose (ou en quelques secondes s'il tourne)",
        "night.where": "Où",
        "night.thisMac": "Ce Mac",
        "night.serverFolder": "Dossier sur le serveur, ex. ~/projects/shop",
        "settings.section.office": "Bureau",
        "settings.section.nightShift": "Équipe de nuit",
        "night.newJob": "Nouvelle tâche pour plus tard",
        "night.agent": "Agent",
        "night.noFolder": "Aucun dossier choisi",
        "night.chooseFolder": "Choisir…",
        "night.when": "Démarrer",
        "night.whenRenews": "Quand la limite se renouvelle",
        "night.whenAt": "À une heure précise",
        "night.queue": "Mettre en file",
        "night.queueTitle": "File d'attente",
        "night.waitsUntil": "attend jusqu'à %@",
        "night.waitsForLimit": "attend la limite",
        "night.running": "en cours %@",
        "night.doneAt": "fini à %@",
        "night.failedShort": "échec : %@",
        "night.footer": "Sur ce Mac (Denny l'empêche de dormir) ou sur un serveur (la tâche continue même si la session SSH tombe ; le résultat arrive à ta reconnexion). La nuit, personne n'autorise rien, alors Denny reste prudent : les modifications de fichiers et les commandes sûres passent, tout ce que le gardien juge dangereux est refusé. Le filet de sécurité sauvegarde toujours, et Telegram te prévient quand c'est fini. Pour une tâche sur un serveur, le message Telegram arrive dès que le Mac est de nouveau connecté à ce serveur.",
        "night.interrupted": "interrompu par un redémarrage",
        "night.started": "%1$@ a lancé la tâche de nuit dans %2$@",
        "night.done": "%1$@ a fini la tâche de nuit dans %2$@ — le reçu attend dans l'encoche",
        "night.failed": "%1$@ n'a pas pu finir la tâche de nuit dans %2$@ : %3$@",
        "settings.section.phone": "Téléphone",
        "phone.title": "Autorisations sur le téléphone",
        "phone.steps": "1. Dans Telegram, ouvre @BotFather et envoie /newbot.\n2. Choisis un nom — BotFather t'envoie un jeton.\n3. Colle le jeton ici.",
        "phone.tokenPlaceholder": "Jeton du bot",
        "phone.check": "Vérifier",
        "phone.badToken": "Ce jeton ne marche pas — recopie-le depuis @BotFather.",
        "phone.sendCode": "Envoie ce code à @%@ :",
        "phone.openBot": "Ouvrir le bot",
        "phone.topicHint": "Tu veux les demandes dans un sujet ou un groupe précis ? Envoie le code là-bas — Denny écrira seulement dans ce sujet, et toi seul pourras appuyer sur les boutons.",
        "phone.waiting": "En attente du code…",
        "phone.connected": "Connecté à %1$@ via @%2$@",
        "phone.whenAway": "Quand je ne suis pas au Mac",
        "phone.always": "Toujours",
        "phone.finished": "Me prévenir aussi quand une tâche est finie",
        "phone.test": "Envoyer un test",
        "phone.testText": "Ici Denny 👋 Les demandes de tes agents arriveront dans ce chat.",
        "phone.disconnect": "Déconnecter",
        "phone.footer": "Les demandes passent par les serveurs de Telegram, texte de la commande compris. Le bot n'obéit qu'au chat qui a envoyé le code. Absent = 2 minutes sans souris ni clavier.",
        "phone.paired": "Denny est connecté 🎉 Quand un agent demandera une autorisation et que tu ne seras pas au Mac, la demande arrivera ici.",
        "phone.request": "%1$@ · %2$@ veut :",
        "phone.allow": "✅ Autoriser",
        "phone.deny": "❌ Refuser",
        "phone.allowed": "✅ Autorisé",
        "phone.denied": "❌ Refusé",
        "phone.expired": "⌛ Pas de réponse ici — l'agent demande dans son terminal.",
        "phone.replyHint": "↩️ Réponds à ce message pour dire à l'agent quoi faire ensuite.",
        "phone.replyUnknown": "Réponds à un message ✅ terminé pour dire à cet agent quoi faire ensuite.",
        "phone.replyLive": "%@ a reçu ta réponse et continue dans son terminal.",
        "phone.replyBackground": "%1$@ continue en arrière-plan dans %2$@ (mode prudent : rien de dangereux sans toi). Telegram préviendra quand ce sera fini.",
        "phone.replyFailed": "Impossible de continuer cette tâche : dossier ou session inconnus.",
        "office.interrupted": "Interrompu : l'app a redémarré",
        "office.stopped": "Arrêté",
        "office.newTask": "Nouvelle tâche",
        "office.give": "Confier la tâche",
        "office.column.inbox": "À faire",
        "office.column.working": "En cours",
        "office.column.review": "À vérifier",
        "office.column.done": "Terminé",
        "office.remove": "Retirer",
        "office.stop": "Arrêter",
        "office.accept": "Accepter",
        "office.discard": "Jeter",
        "office.waiting": "en attente",
        "office.readyAt": "prête à %@",
        "office.accepted": "acceptée",
        "office.discarded": "jetée",
        "office.acceptFailed": "Fusion impossible : %@",
        "office.noGit": "Le dossier n'est pas dans git : l'agent a travaillé directement dedans, rien à fusionner.",
        "office.empty": "Aucune tâche pour l'instant.",
        "office.footer": "Chaque tâche tourne dans sa propre branche git et sa propre copie : ton projet reste intact jusqu'à ce que tu appuies sur Accepter (la branche est fusionnée dans l'actuelle) ; Jeter supprime la branche. Personne n'approuve pendant le travail, donc la règle prudente du travail de nuit s'applique : modifications et commandes sûres passent, le dangereux est refusé. Une tâche par dossier, deux à la fois.",
        "office.auto": "Denny décide",
        "office.repeat": "Répéter régulièrement",
        "office.everyDay": "Tous les jours",
        "office.atHour": "à %ld h",
        "office.addRecurring": "Ajouter la tâche récurrente",
        "office.recurringTitle": "Tâches récurrentes",
        "office.rework": "Retoucher",
        "office.sendRework": "Envoyer",
        "office.cancel": "Annuler",
        "office.howTitle": "Fonctionnement du bureau",
        "office.reviewToggle": "L'autre agent relit chaque tâche",
        "office.claudeBudget": "Budget Claude par tâche, $",
        "office.codexBudget": "Budget Codex par tâche, milliers de tokens",
        "office.standupToggle": "Point du matin dans Telegram",
        "office.howFooter": "Budget vide — pas de limite. Claude s'arrête de lui-même à sa limite de dépense ; Codex n'a pas de prix publics, donc Denny l'arrête aux tokens. Le point du matin : ce qui est fait, ce qui t'attend, ce que ça a coûté.",
        "office.overBudget": "Arrêté : budget dépassé",
        "office.reviewClean": "%@ a relu : aucune remarque",
        "office.reviewFindings": "%1$@ a relu : %2$ld remarques",
        "office.changes": "fichiers : %1$ld · +%2$ld −%3$ld",
        "office.testsPassed": "tests ✅",
        "office.testsFailed": "tests ❌",
        "office.tg.expired": "Ce n'est plus d'actualité : la tâche a avancé.",
        "office.tg.accepted": "✅ Fusionné dans %@",
        "office.tg.discarded": "🗑 Jeté",
        "office.tg.given": "📥 Confié à %1$@ dans %2$@. Le rapport arrivera ici.",
        "office.tg.reworking": "🔁 %@ s'en occupe.",
        "office.tg.how": "Écris ainsi : /task quoi faire. Réponds à un rapport pour le retoucher, /board montre le bureau.",
        "office.tg.noFolders": "Pas encore de projets : confie la première tâche sur le Mac (Réglages → Bureau).",
        "office.tg.pick": "Qui et où ?",
        "office.tg.boardEmpty": "Le bureau est vide : aucune tâche ouverte.",
        "office.tg.replyHint": "↩️ Réponds à ce message pour demander des modifications.",
        "office.tg.taskCommand": "Confier une tâche à Claude ou Codex",
        "office.tg.boardCommand": "Le tableau du bureau",
        "office.standup.title": "☀️ Point du bureau",
        "office.standup.done": "Terminées : %ld",
        "office.standup.waiting": "T'attendent : %ld",
        "office.standup.working": "En cours : %ld",
        "office.standup.queued": "En attente : %ld",
        "office.standup.spent": "Dépensé : %@",
        "review.button": "Faire vérifier par %@",
        "review.running": "%1$@ vérifie… %2$@",
        "review.clean": "✅ %@ n'a trouvé aucun problème",
        "review.findings": "%1$@ a trouvé des problèmes : %2$ld",
        "review.send": "Envoyer à %@",
        "review.copied": "Copié — colle-le à %@ (⌘V)",
        "review.failed": "%1$@ n'a pas pu vérifier : %2$@",
        "review.noChanges": "aucune modification à vérifier",
        "review.notFound": "introuvable sur ce Mac",
        "review.agentMessage": "%1$@ a relu tes modifications et a trouvé :\n\n%2$@\n\nVérifie ces points et corrige ce qui est juste.",
        "tests.run": "Lancer les tests",
        "tests.running": "Tests en cours… %@",
        "tests.passed": "✅ Tests réussis · %@",
        "tests.failed": "❌ Tests en échec · %@",
        "tests.sendToAgent": "Envoyer à l'agent",
        "tests.copied": "Copié — colle-le à l'agent (⌘V)",
        "tests.agentMessage": "Les tests échouent après tes modifications (`%1$@`). Voici la fin de la sortie — corrige, s'il te plaît :\n\n%2$@",
        "tests.autoSetting": "Lancer les tests du projet après chaque tâche",
        "tests.autoFooter": "Sur ce Mac et sur les serveurs. Denny trouve la commande tout seul (swift test, npm test, cargo test, pytest…) ; mets la tienne dans un fichier .denny-test à la racine du projet.",
        "tests.timedOut": "Arrêté après 10 minutes.",
        "receipt.title": "Reçu de la tâche",
        "receipt.files": "Fichiers : %ld",
        "receipt.lines": "+%1$ld −%2$ld",
        "receipt.commands": "Commandes : %ld",
        "receipt.tokens": "Tokens : %@",
        "receipt.cost": "%@ aux prix de l'API",
        "receipt.copy": "Copier",
        "receipt.copied": "Reçu copié",
        "receipt.hide": "Masquer",
        "receipt.signature": "via Denny for Agents",
        "settings.section.safetyNet": "Filet de sécurité",
        "safety.peekTitle": "Fichiers sauvegardés avant une commande risquée",
        "safety.cardTitle": "Filet de sécurité",
        "safety.cardBody": "Les fichiers ont été sauvegardés juste avant cette commande. Annuler les remet en place.",
        "safety.onServer": "Sauvegardé sur %@ — l'annulation se lance là-bas",
        "safety.undo": "Annuler…",
        "safety.copyCommand": "Copier la commande pour le serveur",
        "safety.hide": "Masquer",
        "safety.confirmTitle": "Remettre les fichiers comme avant « %@ » ?",
        "safety.confirmBody": "%ld fichier(s) reviendront. Les modifications faites après la sauvegarde seront perdues ; les nouveaux fichiers restent.",
        "safety.confirmRestore": "Remettre",
        "safety.nothing": "Rien à remettre — les fichiers sont identiques à la sauvegarde.",
        "safety.restored": "Les fichiers sont revenus",
        "safety.failed": "Impossible de remettre les fichiers",
        "safety.commandCopied": "Commande copiée — lance-la sur le serveur",
        "safety.empty": "Aucune sauvegarde pour l'instant. Juste avant qu'un agent lance rm, git reset --hard ou autre, Denny sauvegarde tes fichiers ici.",
        "safety.footer": "Jusqu'à 50 sauvegardes. Dans un projet git, elles vivent dans une ref cachée et ne touchent jamais ta branche, ton index ni ton stash.",
        "safety.storage": "Stockage",
        "safety.keepFor": "Garder les sauvegardes",
        "safety.keep.1": "1 jour",
        "safety.keep.7": "7 jours",
        "safety.keep.30": "30 jours",
        "safety.limit": "Espace pour les copies",
        "safety.gb": "%ld Go",
        "safety.used": "Copies sur ce Mac : %@",
        "safety.clear": "Supprimer toutes les sauvegardes…",
        "safety.clearConfirm": "Supprimer toutes les sauvegardes de ce Mac ?",
        "safety.clearBody": "Leurs fichiers ne pourront plus être remis ensuite.",
        "safety.delete": "Supprimer",
        "safety.limitFooter": "Seules les copies de fichiers hors git comptent — les sauvegardes git vivent dans le projet et ne prennent presque pas de place. Quand l'espace manque, les plus anciennes partent d'abord. Les serveurs reçoivent ces réglages avec ton prochain message à l'agent.",
        "update.check": "Rechercher des mises à jour",
        "update.checking": "Recherche…",
        "update.upToDate": "Tu as la dernière version",
        "update.available": "La version %@ est disponible",
        "update.install": "Mettre à jour",
        "update.installing": "Téléchargement de la mise à jour… Denny va redémarrer",
        "update.failed": "Échec de la mise à jour : %@",
        "update.reason.offline": "GitHub est injoignable",
        "update.reason.checksum": "le fichier ne correspond pas à sa somme de contrôle",
        "update.reason.folder": "pas le droit de remplacer l'app — garde-la dans Applications",
        "update.reason.download": "le téléchargement a échoué",
        "update.homebrew": "Installé avec Homebrew — lance : brew upgrade denny-for-agents",
        "update.notifyBody": "Ouvre les réglages de Denny → À propos pour mettre à jour.",

        "quiet.on": "Silence pendant une heure",
        "quiet.active": "Silence jusqu'à %@ — touche pour arrêter",
        "quick.refresh": "Actualiser",
        "awake.manual": "Rester éveillé manuellement",
        "awake.duration": "Pendant",
        "awake.until": "Jusqu'à",
        "awake.indefinite": "Jusqu'à ce que je l'arrête",
        "awake.start": "Démarrer",
        "awake.stop": "Arrêter",
        "awake.activeUntil": "Le Mac reste éveillé jusqu'à %@",
        "awake.untilOff": "Le Mac reste éveillé jusqu'à ce que tu l'arrêtes",
        "awake.lid": "Continuer écran rabattu",
        "awake.lidWarning": "Uniquement sur secteur. Demande une fois le mot de passe administrateur pour autoriser une seule commande (pmset disablesleep) et se désactive quand le travail est fini. Ne range pas un Mac fermé en marche dans un sac.",
        "awake.lidNeedsPower": "Sur batterie — s'activera quand tu brancheras le chargeur.",

        "risk.safe": "Semble sûr",
        "risk.caution": "À vérifier",
        "risk.danger": "Dangereux",
        "risk.critical": "Très dangereux",
        "risk.reason.pipeToShell": "Télécharge du code depuis Internet et l'exécute aussitôt.",
        "risk.reason.wipeRoot": "Supprime tout dans /, ton dossier personnel ou le dossier courant.",
        "risk.reason.rawDisk": "Écrit directement sur un disque — peut l'effacer.",
        "risk.reason.format": "Formate ou efface un disque.",
        "risk.reason.forkBomb": "Une fork bomb : le Mac va se figer.",
        "risk.reason.dropData": "Supprime des tables ou des données de base.",
        "risk.reason.deleteRecursive": "Supprime le dossier %@ et tout son contenu, sans corbeille.",
        "risk.reason.forcePush": "Réécrit l'historique de la branche sur le serveur.",
        "risk.reason.resetHard": "Jette toutes les modifications non commitées.",
        "risk.reason.cleanUntracked": "Supprime les fichiers que git ne suit pas.",
        "risk.reason.sudo": "S'exécute en administrateur (sudo).",
        "risk.reason.permissions": "Ouvre des fichiers à tout le monde ou change leur propriétaire.",
        "risk.reason.killProcess": "Arrête de force des programmes.",
        "risk.reason.reboot": "Éteint ou redémarre l'ordinateur.",
        "risk.reason.dockerPrune": "Supprime des conteneurs, volumes ou données Docker.",
        "risk.reason.publish": "Publie un paquet ou une version pour tout le monde.",
        "risk.reason.secrets": "Touche à des clés, mots de passe ou secrets .env.",
        "risk.reason.push": "Envoie des commits au serveur.",
        "risk.reason.deleteFile": "Supprime %@.",
        "risk.reason.install": "Installe des paquets depuis Internet.",
        "risk.reason.network": "Accède au réseau.",
        "risk.reason.gitHistory": "Réécrit l'historique git ou annule des modifications.",
        "risk.reason.sensitiveFile": "Modifie un fichier sensible : %@.",
        "risk.reason.externalTool": "Utilise un outil externe (serveur MCP).",

        "load.thisMac": "Ce Mac",
        "load.cpu": "Processeur",
        "load.cpuLoad": "Charge (%ld cœurs)",
        "load.memory": "Mémoire",
        "load.pressureNormal": "Pression mémoire : normale",
        "load.pressureWarning": "Pression mémoire : élevée",
        "load.pressureCritical": "Pression mémoire : critique",
        "load.swap": "Swap %@",
        "load.uptime": "Allumé depuis %@",
        "load.memoryLow": "Mémoire presque pleine — un gros build pourrait être tué.",
        "load.noServer": "La charge du serveur arrivera avec le prochain rapport d'un serveur connecté.",
        "settings.section.load": "Charge",

        "relay.title": "%@ a atteint sa limite",
        "relay.titleUntil": "%1$@ a atteint sa limite jusqu'à %2$@",
        "relay.body": "Passer la tâche à %@ ? J'écris une note avec la demande et ce qui est fait.",
        "relay.copy": "Copier la note pour %@",
        "relay.later": "Pas maintenant",
        "relay.copied": "Note copiée — colle-la dans %@ (⌘V)",
        "relay.handoff": "Passer la tâche à %@",
        "relay.note.intro": "Reprends une tâche commencée par %1$@ (%2$@).",
        "relay.note.reasonLimit": "il a atteint la limite de son forfait",
        "relay.note.reasonManual": "je te la confie",
        "relay.note.folder": "Dossier : %@",
        "relay.note.server": "Serveur : %@",
        "relay.note.task": "La tâche :",
        "relay.note.done": "Déjà fait :",
        "relay.note.edited": "modifié : %@",
        "relay.note.ran": "exécuté : %@",
        "relay.note.last": "Dernier message de %@ :",
        "relay.note.next": "Regarde d'abord les changements en cours (git status, git diff), puis reprends là où ça s'est arrêté.",

        "stuck.title": "%@ semble tourner en rond",
        "stuck.repeatCommand": "Lance « %2$@ » pour la %1$ldᵉ fois",
        "stuck.repeatEdit": "Modifie %2$@ pour la %1$ldᵉ fois",
        "stuck.noProgress": "%ld min de travail sans le moindre changement",
        "stuck.setting": "Prévenir quand un agent tourne en rond"
    ]
}
