extension Translations {
    static let french: [String: String] = [
        "step.runs": "Exécute %@",
        "step.runsCommand": "Exécute une commande",
        "step.reads": "Lit %@",
        "step.aFile": "un fichier",
        "step.edits": "Modifie %@",
        "step.editsFiles": "Modifie des fichiers",
        "step.searches": "Cherche « %@ »",
        "step.searchesCode": "Cherche dans le code",
        "step.searchesWeb": "Cherche sur le web",
        "step.opens": "Ouvre %@",
        "step.startsHelper": "Lance un agent assistant",
        "step.updatesPlan": "Met à jour le plan",
        "step.uses": "Utilise %@",
        "step.working": "Au travail…",
        "step.thinking": "Réfléchit…",
        "step.waitingForYou": "T'attend",
        "step.done": "Terminé",

        "title.idle": "Tout est calme",
        "title.working": "Les agents travaillent",
        "title.needsYou": "On a besoin de toi",
        "title.limitUsedUp": "Limite %@ épuisée",
        "title.limitAlmost": "Limite %@ presque épuisée",
        "subtitle.noSessions": "Lance Claude Code ou Codex — je garde un œil dessus.",
        "subtitle.noHooks": "Connecte Claude Code et Codex dans la barre des menus.",
        "subtitle.serverDown": "Impossible d'écouter les agents.",
        "limit.detailResets": "%1$@, réinitialisation dans %2$@",

        "approval.allow": "Autoriser",
        "approval.deny": "Refuser",
        "approval.askThere": "Demander là-bas",
        "approval.wantsTo": "veut",
        "approval.more": "+%ld autres en attente",

        "stats.spending": "Dépenses",
        "stats.apiValue": "valeur API",
        "stats.now": "Maintenant",
        "stats.workingNow": "au travail",
        "stats.limitsLater": "Les limites apparaîtront après la prochaine réponse",
        "stats.updated": "Mis à jour %@",
        "stats.tokens": "%@ jetons",
        "stats.tokensWord": "jetons",
        "stats.fromCache": "%ld%% depuis le cache",
        "stats.todayTotal": "Aujourd'hui %@",
        "stats.noPrice": "Pas de prix public pour les modèles Codex",
        "period.today": "Aujourd'hui",
        "period.week": "7 jours",
        "period.month": "30 jours",
        "window.session": "Session",
        "window.week": "Semaine",
        "window.limit": "Limite",
        "stats.activity": "Activité",
        "stats.streak": "%ld jours d'affilée",
        "stats.activeDays": "Jours actifs",
        "stats.busiestDay": "Jour le plus actif",

        "time.daysHours": "%1$ld j %2$ld h",
        "time.hoursMinutes": "%1$ld h %2$ld min",
        "time.minutes": "%ld min",
        "time.hours": "%ld h",
        "time.days": "%ld j",
        "time.months": "%ld mois",
        "time.justNow": "à l'instant",
        "time.ago": "il y a %@",

        "resets.line": "Réinitialisations : %ld",
        "resets.expiresIn": "la prochaine expire dans %@",
        "resets.use": "Utiliser une réinitialisation",
        "resets.resetting": "Réinitialisation…",
        "resets.confirmTitle": "Réinitialiser les limites Codex maintenant ?",
        "resets.confirmBody": "Utilise une réinitialisation en réserve : les limites de session et de semaine repartent à zéro. Restantes : %ld.",
        "resets.outcome.reset": "Limites Codex réinitialisées",
        "resets.outcome.nothing": "Rien à réinitialiser pour l'instant",
        "resets.outcome.noCredit": "Plus de réinitialisations disponibles",
        "resets.outcome.already": "Cette réinitialisation a déjà été utilisée",
        "resets.outcome.failed": "Échec — Codex est-il connecté sur ce Mac ?",

        "drop.here": "Lâche — je copie le chemin pour ton agent",
        "drop.copiedOne": "Chemin de %@ copié — colle-le à ton agent (⌘V)",
        "drop.copiedMany": "%ld chemins copiés — colle-les à ton agent (⌘V)",
        "drop.remoteCantSee": "L'agent sur %@ ne voit pas les fichiers de ce Mac.",
        "drop.willSendOne": "Chemin serveur copié — le fichier part vers %@ avec ton prochain message (⌘V)",
        "drop.willSendMany": "Chemins serveur copiés — %1$ld fichiers partent vers %2$@ avec ton prochain message (⌘V)",
        "drop.delivered": "Livré sur %1$@ : %2$ld",
        "drop.skippedFolders": "Les dossiers ne sont pas encore envoyés.",
        "drop.tooBig": "Jusqu'à 20 Mo par dépôt.",
        "drop.shelfInFullDenny": "Étagère à fichiers et contrôle de la musique — dans Denny complet →",
        "fullDenny": "Tâches, notes et IA hors ligne — Denny complet →",

        "alerts.menu": "Notifications",
        "alerts.finish": "Tâche terminée",
        "alerts.limit": "Limite du forfait",
        "alerts.budget": "Budget quotidien (prix API)",
        "alerts.off": "Désactivé",
        "alerts.anyLength": "Toute durée",
        "alerts.longerThan": "Plus de %ld min",
        "alerts.atPercent": "À %ld%%",
        "alerts.finishedTitle": "%@ a terminé",
        "alerts.finishedBody": "%1$@ · a travaillé %2$@",
        "alerts.limitTitle": "Limite %1$@ à %2$ld%%",
        "alerts.budgetTitle": "Budget quotidien atteint : %@",
        "alerts.budgetBody": "Aux prix catalogue de l'API, sur ce Mac et tes serveurs.",

        "menu.claude": "Surveiller Claude Code",
        "menu.codex": "Surveiller Codex",
        "menu.remote": "Serveur distant (SSH)…",
        "menu.fullDenny": "Obtenir Denny complet…",
        "menu.quit": "Quitter Denny for Agents",
        "remote.title": "Surveiller les agents sur un serveur SSH",
        "remote.body": "1. Redirige le port pendant la connexion : dans Termius, ajoute une règle de redirection Remote (serveur 127.0.0.1:{port} → ce Mac 127.0.0.1:{port}), ou connecte-toi avec ssh -R {port}:127.0.0.1:{port} user@server\n2. Place remote/denny-hook.py du dépôt dans ~/.denny-for-agents/ sur le serveur.\n3. Sur le serveur, lance la commande copiée, puis : python3 ~/.denny-for-agents/denny-hook.py --ping",
        "remote.copy": "Copier la commande d'installation",
        "remote.unavailable": "Le mode distant n'a pas pu démarrer : port occupé.",
        "common.close": "Fermer",
        "common.cancel": "Annuler",
        "connect.title": "Connecter Denny à tes agents ?",
        "connect.body": "Denny ajoutera des hooks à ~/.claude/settings.json et ~/.codex/hooks.json (une sauvegarde est créée à côté). Si Denny ne tourne pas, les hooks ne font rien et ne bloquent jamais tes agents.",
        "connect.connect": "Connecter",
        "connect.later": "Plus tard",
        "connect.failed": "Impossible de modifier le fichier de réglages"
    ]
}
