extension Translations {
    static let german: [String: String] = [
        "step.runs": "Führt %@ aus",
        "step.runsCommand": "Führt einen Befehl aus",
        "step.reads": "Liest %@",
        "step.aFile": "eine Datei",
        "step.edits": "Bearbeitet %@",
        "step.editsFiles": "Bearbeitet Dateien",
        "step.searches": "Sucht „%@“",
        "step.searchesCode": "Durchsucht den Code",
        "step.searchesWeb": "Sucht im Web",
        "step.opens": "Öffnet %@",
        "step.startsHelper": "Startet einen Hilfsagenten",
        "step.updatesPlan": "Aktualisiert den Plan",
        "step.uses": "Nutzt %@",
        "step.working": "Arbeitet…",
        "step.thinking": "Denkt nach…",
        "step.waitingForYou": "Wartet auf dich",
        "step.done": "Fertig",

        "title.idle": "Alles ruhig",
        "title.working": "Agenten arbeiten",
        "title.needsYou": "Braucht dich",
        "title.limitUsedUp": "%@-Limit aufgebraucht",
        "title.limitAlmost": "%@-Limit fast aufgebraucht",
        "subtitle.noSessions": "Starte Claude Code oder Codex – ich behalte es im Blick.",
        "subtitle.noHooks": "Verbinde Claude Code und Codex in der Menüleiste.",
        "subtitle.serverDown": "Konnte nicht auf Agenten lauschen.",
        "limit.detailResets": "%1$@, Reset in %2$@",

        "approval.allow": "Erlauben",
        "approval.deny": "Ablehnen",
        "approval.askThere": "Dort fragen",
        "approval.wantsTo": "möchte",
        "approval.more": "+%ld weitere warten",

        "stats.spending": "Kosten",
        "stats.apiValue": "API-Wert",
        "stats.now": "Jetzt",
        "stats.workingNow": "arbeitet",
        "stats.limitsLater": "Limits erscheinen nach der nächsten Antwort",
        "stats.updated": "Aktualisiert %@",
        "stats.tokens": "%@ Tokens",
        "stats.tokensWord": "Tokens",
        "stats.fromCache": "%ld%% aus dem Cache",
        "stats.todayTotal": "Heute %@",
        "stats.noPrice": "Kein öffentlicher Preis für Codex-Modelle",
        "period.today": "Heute",
        "period.week": "7 Tage",
        "period.month": "30 Tage",
        "window.session": "Sitzung",
        "window.week": "Woche",
        "window.limit": "Limit",
        "stats.activity": "Aktivität",
        "stats.streak": "%ld Tage in Folge",
        "stats.activeDays": "Aktive Tage",
        "stats.busiestDay": "Aktivster Tag",

        "time.daysHours": "%1$ld T %2$ld Std",
        "time.hoursMinutes": "%1$ld Std %2$ld Min",
        "time.minutes": "%ld Min",
        "time.hours": "%ld Std",
        "time.days": "%ld T",
        "time.months": "%ld Mon.",
        "time.justNow": "gerade eben",
        "time.ago": "vor %@",

        "resets.line": "Resets: %ld",
        "resets.expiresIn": "nächster verfällt in %@",
        "resets.use": "Reset nutzen",
        "resets.resetting": "Setze zurück…",
        "resets.confirmTitle": "Codex-Limits jetzt zurücksetzen?",
        "resets.confirmBody": "Verbraucht einen gesparten Reset: Sitzungs- und Wochenlimit erneuern sich sofort. Verbleibende Resets: %ld.",
        "resets.outcome.reset": "Codex-Limits wurden zurückgesetzt",
        "resets.outcome.nothing": "Noch nichts zurückzusetzen",
        "resets.outcome.noCredit": "Keine Resets mehr übrig",
        "resets.outcome.already": "Dieser Reset wurde bereits genutzt",
        "resets.outcome.failed": "Reset fehlgeschlagen – ist Codex auf diesem Mac angemeldet?",

        "drop.here": "Loslassen – ich kopiere den Pfad für deinen Agenten",
        "drop.copiedOne": "Pfad zu %@ kopiert – füge ihn bei deinem Agenten ein (⌘V)",
        "drop.copiedMany": "%ld Pfade kopiert – füge sie bei deinem Agenten ein (⌘V)",
        "drop.remoteCantSee": "Der Agent auf %@ sieht keine Dateien auf diesem Mac.",
        "drop.willSendOne": "Serverpfad kopiert – die Datei geht mit deiner nächsten Nachricht an %@ (⌘V)",
        "drop.willSendMany": "Serverpfade kopiert – %1$ld Dateien gehen mit deiner nächsten Nachricht an %2$@ (⌘V)",
        "drop.delivered": "An %1$@ geliefert: %2$ld",
        "drop.skippedFolders": "Ordner werden noch nicht gesendet.",
        "drop.tooBig": "Bis zu 20 MB pro Ablage.",
        "drop.shelfInFullDenny": "Dateiablage und Musiksteuerung – im vollen Denny →",
        "fullDenny": "Aufgaben, Notizen & Offline-KI – der volle Denny →",

        "alerts.menu": "Mitteilungen",
        "alerts.finish": "Aufgabe fertig",
        "alerts.limit": "Tariflimit",
        "alerts.budget": "Tagesbudget (API-Preise)",
        "alerts.off": "Aus",
        "alerts.anyLength": "Jede Dauer",
        "alerts.longerThan": "Länger als %ld Min",
        "alerts.atPercent": "Bei %ld%%",
        "alerts.finishedTitle": "%@ ist fertig",
        "alerts.finishedBody": "%1$@ · hat %2$@ gearbeitet",
        "alerts.limitTitle": "%1$@-Limit bei %2$ld%%",
        "alerts.budgetTitle": "Tagesbudget erreicht: %@",
        "alerts.budgetBody": "Zu API-Listenpreisen, über diesen Mac und deine Server.",

        "menu.claude": "Claude Code beobachten",
        "menu.codex": "Codex beobachten",
        "menu.remote": "Entfernter Server (SSH)…",
        "menu.fullDenny": "Den vollen Denny holen…",
        "menu.quit": "Denny for Agents beenden",
        "remote.title": "Agenten auf einem SSH-Server beobachten",
        "remote.body": "1. Leite den Port während der Verbindung weiter: in Termius eine Remote-Port-Weiterleitung anlegen (Server 127.0.0.1:{port} → dieser Mac 127.0.0.1:{port}) oder so verbinden: ssh -R {port}:127.0.0.1:{port} user@server\n2. Lege remote/denny-hook.py aus dem Repo auf dem Server in ~/.denny-for-agents/ ab.\n3. Führe auf dem Server den kopierten Befehl aus, dann: python3 ~/.denny-for-agents/denny-hook.py --ping",
        "remote.copy": "Installationsbefehl kopieren",
        "remote.unavailable": "Remote-Modus konnte nicht starten: Port belegt.",
        "common.close": "Schließen",
        "common.cancel": "Abbrechen",
        "connect.title": "Denny mit deinen Agenten verbinden?",
        "connect.body": "Denny fügt Hooks zu ~/.claude/settings.json und ~/.codex/hooks.json hinzu (daneben wird eine Sicherung abgelegt). Läuft Denny nicht, tun die Hooks nichts und blockieren deine Agenten nie.",
        "connect.connect": "Verbinden",
        "connect.later": "Später",
        "connect.failed": "Einstellungsdatei konnte nicht geändert werden",

        "value.title": "Tarifwert",
        "value.line": "%@ zu API-Preisen in 30 Tagen",
        "value.planMonthly": "%1$@ · %2$@/Monat",
        "stats.trend": "Verlauf",
        "stats.models": "Modelle",
        "stats.projects": "Projekte",
        "stats.peak": "Spitze %@",
        "card.limits": "Limits",
        "alerts.renewedTitle": "%@-Limit erneuert",
        "menu.cards": "Karten",
        "menu.readout": "Neben der Kamera",
        "readout.timer": "Aufgaben-Timer",
        "readout.limit": "Knappstes Limit",
        "page.overview": "Übersicht",
        "page.stats": "Statistik",
        "stats.noFresh": "Keine aktuellen Daten",

        "settings.title": "Einstellungen",
        "settings.menu": "Einstellungen…",
        "settings.section.agents": "Agenten",
        "settings.section.servers": "Server",
        "settings.section.notch": "Notch",
        "settings.section.cards": "Karten",
        "settings.section.alerts": "Mitteilungen",
        "settings.section.language": "Sprache",
        "settings.section.privacy": "Datenschutz",
        "settings.section.about": "Über",
        "settings.connected": "Verbunden",
        "settings.notConnected": "Nicht verbunden",
        "settings.disconnect": "Trennen",
        "settings.agentsFooter": "Denny fügt seine Hooks zur Einstellungsdatei jedes Agenten hinzu und legt daneben eine Sicherung ab. Läuft Denny nicht, tun die Hooks nichts.",
        "settings.keepAwake": "Mac wach halten, solange Agenten arbeiten",
        "settings.keepAwakeFooter": "Nur solange ein Agent auf diesem Mac arbeitet. Der Bildschirm darf trotzdem ausgehen.",
        "settings.serversConnected": "Verbundene Server",
        "settings.noServers": "Noch keine Server. Richte unten einen ein.",
        "settings.lastSeen": "zuletzt %@",
        "settings.peeks": "Einblendungen",
        "settings.peekOnStart": "Wenn du eine Aufgabe sendest",
        "settings.peekOnWriting": "Wenn der Agent Code schreibt",
        "settings.peekOnFinish": "Wenn der Agent fertig ist",
        "settings.display": "Bildschirm",
        "settings.displayAuto": "Der mit der Notch",
        "settings.fullScreen": "Über Vollbild-Apps anzeigen",
        "settings.cardsFooter": "Ausgeschaltete Karten verschwinden aus der Notch. Übersicht zeigt Limits, Kosten und Jetzt; Statistik den Rest.",
        "settings.languageSystem": "Wie das System",
        "settings.languageRestart": "Die neue Sprache gilt nach einem Neustart.",
        "settings.restart": "Jetzt neu starten",
        "settings.privacyReads": "Was Denny liest",
        "settings.privacyReadsBody": "Token-Zahlen, Modellnamen, Zeiten und Projektordnernamen aus den Logs von Claude Code und Codex; Tariflimits aus ~/.claude.json, der Claude-App und Codex; die Ereignisse, die deine Agenten an die Hooks senden.",
        "settings.privacyNever": "Was Denny nie liest oder sendet",
        "settings.privacyNeverBody": "Deine Prompts, Antworten und Dateiinhalte. Nichts verlässt deine Rechner außer dem täglichen Download der öffentlichen Preisliste. Auf die Notch gezogene Dateien gehen nur an deinen eigenen Server.",
        "settings.removeAll": "Agenten trennen und Dennys Daten löschen",
        "settings.removeAllFooter": "Entfernt die Hooks aus Claude Code und Codex, löscht ~/.denny-for-agents mit Verlauf und Einstellungen und beendet die App.",
        "settings.removeAllConfirm": "Alles löschen, was Denny for Agents gespeichert hat?",
        "settings.version": "Version %@",
        "settings.about": "Ein kleiner Roboter in deiner Notch, der Claude Code und Codex im Blick behält. Der kostenlose, offene Teil von Denny.",
        "update.check": "Nach Updates suchen",
        "update.checking": "Suche…",
        "update.upToDate": "Du hast die neueste Version",
        "update.available": "Version %@ ist verfügbar",
        "update.install": "Aktualisieren",
        "update.installing": "Lade das Update… Denny startet neu",
        "update.failed": "Update fehlgeschlagen: %@",
        "update.reason.offline": "GitHub ist nicht erreichbar",
        "update.reason.checksum": "die Datei passt nicht zur Prüfsumme",
        "update.reason.folder": "keine Berechtigung, die App zu ersetzen — lass sie im Ordner „Programme“",
        "update.reason.download": "der Download ist fehlgeschlagen",
        "update.homebrew": "Mit Homebrew installiert — führe aus: brew upgrade denny-for-agents",
        "update.notifyBody": "Öffne Dennys Einstellungen → Über, um zu aktualisieren.",

        "quiet.on": "Eine Stunde Ruhe",
        "quiet.active": "Ruhe bis %@ – tippen zum Beenden",
        "quick.refresh": "Jetzt aktualisieren",
        "awake.manual": "Manuell wach halten",
        "awake.duration": "Dauer",
        "awake.until": "Bis",
        "awake.indefinite": "Bis ich es ausschalte",
        "awake.start": "Starten",
        "awake.stop": "Stoppen",
        "awake.activeUntil": "Der Mac bleibt bis %@ wach",
        "awake.untilOff": "Der Mac bleibt wach, bis du stoppst",
        "awake.lid": "Bei geschlossenem Deckel weiterarbeiten",
        "awake.lidWarning": "Nur am Ladegerät. Fragt einmal nach dem Admin-Passwort, um genau einen Befehl (pmset disablesleep) zu erlauben, und schaltet sich ab, wenn die Arbeit fertig ist. Einen laufenden, zugeklappten Mac nicht in die Tasche stecken.",
        "awake.lidNeedsPower": "Gerade im Akkubetrieb – schaltet sich ein, sobald das Ladegerät angeschlossen ist.",

        "risk.safe": "Sieht sicher aus",
        "risk.caution": "Kurz prüfen",
        "risk.danger": "Gefährlich",
        "risk.critical": "Sehr gefährlich",
        "risk.reason.pipeToShell": "Lädt Code aus dem Internet und führt ihn sofort aus.",
        "risk.reason.wipeRoot": "Löscht alles in /, im Benutzerordner oder im aktuellen Ordner.",
        "risk.reason.rawDisk": "Schreibt direkt auf eine Festplatte – kann sie löschen.",
        "risk.reason.format": "Formatiert oder löscht eine Festplatte.",
        "risk.reason.forkBomb": "Eine Fork-Bombe: der Mac friert ein.",
        "risk.reason.dropData": "Löscht Datenbanktabellen oder Daten.",
        "risk.reason.deleteRecursive": "Löscht den Ordner %@ samt Inhalt, ohne Papierkorb.",
        "risk.reason.forcePush": "Überschreibt die Branch-Historie auf dem Server.",
        "risk.reason.resetHard": "Verwirft alle nicht committeten Änderungen.",
        "risk.reason.cleanUntracked": "Löscht Dateien, die git nicht verfolgt.",
        "risk.reason.sudo": "Läuft als Administrator (sudo).",
        "risk.reason.permissions": "Gibt Dateien für alle frei oder ändert den Besitzer.",
        "risk.reason.killProcess": "Beendet laufende Programme zwangsweise.",
        "risk.reason.reboot": "Fährt den Computer herunter oder startet ihn neu.",
        "risk.reason.dockerPrune": "Löscht Docker-Container, Volumes oder Daten.",
        "risk.reason.publish": "Veröffentlicht ein Paket oder Release für alle.",
        "risk.reason.secrets": "Berührt Schlüssel, Passwörter oder .env-Geheimnisse.",
        "risk.reason.push": "Schickt Commits an den Server.",
        "risk.reason.deleteFile": "Löscht %@.",
        "risk.reason.install": "Installiert Pakete aus dem Internet.",
        "risk.reason.network": "Greift aufs Netzwerk zu.",
        "risk.reason.gitHistory": "Schreibt die git-Historie um oder verwirft Dateiänderungen.",
        "risk.reason.sensitiveFile": "Ändert eine heikle Datei: %@.",
        "risk.reason.externalTool": "Nutzt ein externes Werkzeug (MCP-Server).",

        "load.thisMac": "Dieser Mac",
        "load.cpu": "CPU",
        "load.cpuLoad": "Last (%ld Kerne)",
        "load.memory": "Speicher",
        "load.pressureNormal": "Speicherdruck: normal",
        "load.pressureWarning": "Speicherdruck: hoch",
        "load.pressureCritical": "Speicherdruck: kritisch",
        "load.swap": "Swap %@",
        "load.uptime": "Läuft seit %@",
        "load.memoryLow": "Speicher fast voll – ein schwerer Build könnte abgebrochen werden.",
        "load.noServer": "Die Serverlast kommt mit dem nächsten Bericht eines verbundenen Servers.",
        "settings.section.load": "Last",

        "relay.title": "%@ hat sein Limit erreicht",
        "relay.titleUntil": "%1$@ hat sein Limit bis %2$@ erreicht",
        "relay.body": "Die Aufgabe an %@ übergeben? Ich schreibe eine Notiz mit Auftrag und Stand.",
        "relay.copy": "Notiz für %@ kopieren",
        "relay.later": "Nicht jetzt",
        "relay.copied": "Notiz kopiert – füge sie in %@ ein (⌘V)",
        "relay.handoff": "Aufgabe an %@ übergeben",
        "relay.note.intro": "Setze eine Aufgabe fort, die %1$@ begonnen hat (%2$@).",
        "relay.note.reasonLimit": "es hat sein Tariflimit erreicht",
        "relay.note.reasonManual": "ich übergebe sie dir",
        "relay.note.folder": "Ordner: %@",
        "relay.note.server": "Server: %@",
        "relay.note.task": "Die Aufgabe:",
        "relay.note.done": "Bereits erledigt:",
        "relay.note.edited": "bearbeitet: %@",
        "relay.note.ran": "ausgeführt: %@",
        "relay.note.last": "Letzte Nachricht von %@:",
        "relay.note.next": "Sieh dir zuerst die aktuellen Änderungen an (git status, git diff) und mach dann dort weiter, wo aufgehört wurde.",

        "stuck.title": "%@ dreht sich offenbar im Kreis",
        "stuck.repeatCommand": "Führt „%2$@“ zum %1$ld. Mal aus",
        "stuck.repeatEdit": "Bearbeitet %2$@ zum %1$ld. Mal",
        "stuck.noProgress": "%ld Min. Arbeit ohne eine einzige Änderung",
        "stuck.setting": "Warnen, wenn ein Agent sich im Kreis dreht"
    ]
}
