extension Translations {
    static let german: [String: String] = [
        "step.runs": "Führt %@ aus",
        "step.runsCommand": "Führt einen Befehl aus",
        "step.reads": "Liest %@",
        "step.aFile": "eine Datei",
        "step.edits": "Bearbeitet %@",
        "step.editsFiles": "Bearbeitet Dateien",
        "step.searches": "Sucht „%@“",
        "step.searchesCode": "Durchsucht den Code",
        "step.searchesWeb": "Sucht im Web",
        "step.opens": "Öffnet %@",
        "step.startsHelper": "Startet einen Hilfsagenten",
        "step.updatesPlan": "Aktualisiert den Plan",
        "step.uses": "Nutzt %@",
        "step.working": "Arbeitet…",
        "step.thinking": "Denkt nach…",
        "step.waitingForYou": "Wartet auf dich",
        "step.done": "Fertig",

        "title.idle": "Alles ruhig",
        "title.working": "Agenten arbeiten",
        "title.needsYou": "Braucht dich",
        "title.limitUsedUp": "%@-Limit aufgebraucht",
        "title.limitAlmost": "%@-Limit fast aufgebraucht",
        "subtitle.noSessions": "Starte Claude Code oder Codex – ich behalte es im Blick.",
        "subtitle.noHooks": "Verbinde Claude Code und Codex in der Menüleiste.",
        "subtitle.serverDown": "Konnte nicht auf Agenten lauschen.",
        "limit.detailResets": "%1$@, Reset in %2$@",

        "approval.allow": "Erlauben",
        "approval.deny": "Ablehnen",
        "approval.askThere": "Dort fragen",
        "approval.wantsTo": "möchte",
        "approval.more": "+%ld weitere warten",

        "stats.spending": "Kosten",
        "stats.apiValue": "API-Wert",
        "stats.now": "Jetzt",
        "stats.workingNow": "arbeitet",
        "stats.limitsLater": "Limits erscheinen nach der nächsten Antwort",
        "stats.updated": "Aktualisiert %@",
        "stats.tokens": "%@ Tokens",
        "stats.tokensWord": "Tokens",
        "stats.fromCache": "%ld%% aus dem Cache",
        "stats.todayTotal": "Heute %@",
        "stats.noPrice": "Kein öffentlicher Preis für Codex-Modelle",
        "period.today": "Heute",
        "period.week": "7 Tage",
        "period.month": "30 Tage",
        "window.session": "Sitzung",
        "window.week": "Woche",
        "window.limit": "Limit",
        "stats.activity": "Aktivität",
        "stats.streak": "%ld Tage in Folge",
        "stats.activeDays": "Aktive Tage",
        "stats.busiestDay": "Aktivster Tag",

        "time.daysHours": "%1$ld T %2$ld Std",
        "time.hoursMinutes": "%1$ld Std %2$ld Min",
        "time.minutes": "%ld Min",
        "time.hours": "%ld Std",
        "time.days": "%ld T",
        "time.months": "%ld Mon.",
        "time.justNow": "gerade eben",
        "time.ago": "vor %@",

        "resets.line": "Resets: %ld",
        "resets.expiresIn": "nächster verfällt in %@",
        "resets.use": "Reset nutzen",
        "resets.resetting": "Setze zurück…",
        "resets.confirmTitle": "Codex-Limits jetzt zurücksetzen?",
        "resets.confirmBody": "Verbraucht einen gesparten Reset: Sitzungs- und Wochenlimit erneuern sich sofort. Verbleibende Resets: %ld.",
        "resets.outcome.reset": "Codex-Limits wurden zurückgesetzt",
        "resets.outcome.nothing": "Noch nichts zurückzusetzen",
        "resets.outcome.noCredit": "Keine Resets mehr übrig",
        "resets.outcome.already": "Dieser Reset wurde bereits genutzt",
        "resets.outcome.failed": "Reset fehlgeschlagen – ist Codex auf diesem Mac angemeldet?",

        "drop.here": "Loslassen – ich kopiere den Pfad für deinen Agenten",
        "drop.copiedOne": "Pfad zu %@ kopiert – füge ihn bei deinem Agenten ein (⌘V)",
        "drop.copiedMany": "%ld Pfade kopiert – füge sie bei deinem Agenten ein (⌘V)",
        "drop.remoteCantSee": "Der Agent auf %@ sieht keine Dateien auf diesem Mac.",
        "drop.willSendOne": "Serverpfad kopiert – die Datei geht mit deiner nächsten Nachricht an %@ (⌘V)",
        "drop.willSendMany": "Serverpfade kopiert – %1$ld Dateien gehen mit deiner nächsten Nachricht an %2$@ (⌘V)",
        "drop.delivered": "An %1$@ geliefert: %2$ld",
        "drop.skippedFolders": "Ordner werden noch nicht gesendet.",
        "drop.tooBig": "Bis zu 20 MB pro Ablage.",
        "drop.shelfInFullDenny": "Dateiablage und Musiksteuerung – im vollen Denny →",
        "fullDenny": "Aufgaben, Notizen & Offline-KI – der volle Denny →",

        "alerts.menu": "Mitteilungen",
        "alerts.finish": "Aufgabe fertig",
        "alerts.limit": "Tariflimit",
        "alerts.budget": "Tagesbudget (API-Preise)",
        "alerts.off": "Aus",
        "alerts.anyLength": "Jede Dauer",
        "alerts.longerThan": "Länger als %ld Min",
        "alerts.atPercent": "Bei %ld%%",
        "alerts.finishedTitle": "%@ ist fertig",
        "alerts.finishedBody": "%1$@ · hat %2$@ gearbeitet",
        "alerts.limitTitle": "%1$@-Limit bei %2$ld%%",
        "alerts.budgetTitle": "Tagesbudget erreicht: %@",
        "alerts.budgetBody": "Zu API-Listenpreisen, über diesen Mac und deine Server.",

        "menu.claude": "Claude Code beobachten",
        "menu.codex": "Codex beobachten",
        "menu.remote": "Entfernter Server (SSH)…",
        "menu.fullDenny": "Den vollen Denny holen…",
        "menu.quit": "Denny for Agents beenden",
        "remote.title": "Agenten auf einem SSH-Server beobachten",
        "remote.body": "1. Leite den Port während der Verbindung weiter: in Termius eine Remote-Port-Weiterleitung anlegen (Server 127.0.0.1:{port} → dieser Mac 127.0.0.1:{port}) oder so verbinden: ssh -R {port}:127.0.0.1:{port} user@server\n2. Lege remote/denny-hook.py aus dem Repo auf dem Server in ~/.denny-for-agents/ ab.\n3. Führe auf dem Server den kopierten Befehl aus, dann: python3 ~/.denny-for-agents/denny-hook.py --ping",
        "remote.copy": "Installationsbefehl kopieren",
        "remote.unavailable": "Remote-Modus konnte nicht starten: Port belegt.",
        "common.close": "Schließen",
        "common.cancel": "Abbrechen",
        "connect.title": "Denny mit deinen Agenten verbinden?",
        "connect.body": "Denny fügt Hooks zu ~/.claude/settings.json und ~/.codex/hooks.json hinzu (daneben wird eine Sicherung abgelegt). Läuft Denny nicht, tun die Hooks nichts und blockieren deine Agenten nie.",
        "connect.connect": "Verbinden",
        "connect.later": "Später",
        "connect.failed": "Einstellungsdatei konnte nicht geändert werden",

        "value.title": "Tarifwert",
        "value.line": "%@ zu API-Preisen in 30 Tagen",
        "value.planMonthly": "%1$@ · %2$@/Monat",
        "stats.trend": "Verlauf",
        "stats.models": "Modelle",
        "stats.projects": "Projekte",
        "stats.peak": "Spitze %@",
        "card.limits": "Limits",
        "alerts.renewedTitle": "%@-Limit erneuert",
        "menu.cards": "Karten",
        "menu.readout": "Neben der Kamera",
        "readout.timer": "Aufgaben-Timer",
        "readout.limit": "Knappstes Limit",
        "page.overview": "Übersicht",
        "page.stats": "Statistik",
        "stats.noFresh": "Keine aktuellen Daten",

        "settings.title": "Einstellungen",
        "settings.menu": "Einstellungen…",
        "settings.section.agents": "Agenten",
        "settings.section.servers": "Server",
        "settings.section.notch": "Notch",
        "settings.section.cards": "Karten",
        "settings.section.alerts": "Mitteilungen",
        "settings.section.language": "Sprache",
        "settings.section.privacy": "Datenschutz",
        "settings.section.about": "Über",
        "settings.connected": "Verbunden",
        "settings.notConnected": "Nicht verbunden",
        "settings.disconnect": "Trennen",
        "settings.agentsFooter": "Denny fügt seine Hooks zur Einstellungsdatei jedes Agenten hinzu und legt daneben eine Sicherung ab. Läuft Denny nicht, tun die Hooks nichts.",
        "settings.keepAwake": "Mac wach halten, solange Agenten arbeiten",
        "settings.keepAwakeFooter": "Nur solange ein Agent auf diesem Mac arbeitet. Der Bildschirm darf trotzdem ausgehen.",
        "settings.serversConnected": "Verbundene Server",
        "settings.noServers": "Noch keine Server. Richte unten einen ein.",
        "settings.lastSeen": "zuletzt %@",
        "settings.noContact": "kein Kontakt %@",
        "ssh.title": "Dennys eigene Verbindungen",
        "ssh.body": "Denny verbindet sich selbst per SSH und hält die Verbindung: nach dem Ruhezustand, einem Netzwechsel oder einer VPN-Neuverbindung verbindet er sich von selbst neu. Nutzt die SSH-Schlüssel und ~/.ssh/config dieses Mac — kein Termius nötig.",
        "ssh.placeholder": "root@server oder ein Name aus ~/.ssh/config",
        "ssh.add": "Hinzufügen",
        "ssh.invalid": "Gib user@host oder einen Namen aus ~/.ssh/config an (einen anderen Port in ~/.ssh/config eintragen).",
        "ssh.connecting": "Verbinde…",
        "ssh.connected": "verbunden %@",
        "ssh.retry": "neuer Versuch in %@",
        "ssh.connectAgents": "Agenten verbinden",
        "ssh.connectAgentsHelp": "Dennys Hook auf den Server legen und dort Claude Code und Codex verbinden",
        "ssh.installing": "Verbinde…",
        "ssh.agentsConnected": "Agenten verbunden. Starte Claude Code / Codex auf dem Server neu.",
        "ssh.installFailed": "Agenten konnten nicht verbunden werden: %@",
        "ssh.needsKey": "Kein SSH-Schlüssel für diesen Server",
        "ssh.keyHint": "Dieser Mac braucht einen SSH-Schlüssel, den der Server akzeptiert. Im Terminal auf dem Mac ausführen (der zweite Befehl fragt einmal nach dem Server-Passwort):",
        "ssh.copyCommands": "Befehle kopieren",
        "ssh.hostKeyChanged": "Der Schlüssel des Servers hat sich geändert — prüfe ihn und korrigiere ~/.ssh/known_hosts",
        "ssh.unreachable": "Server nicht erreichbar",
        "ssh.portBusy": "Port auf dem Server noch belegt, versuche den nächsten",
        "ssh.noPython": "python3 ist auf dem Server nicht installiert",
        "ssh.dropped": "Verbindung abgebrochen",
        "ssh.remove": "Entfernen",
        "ssh.removeAndUnhook": "Entfernen und Agenten auf dem Server trennen",
        "ssh.removeQuestion": "Diesen Server entfernen?",
        "settings.peeks": "Einblendungen",
        "settings.peekOnStart": "Wenn du eine Aufgabe sendest",
        "settings.peekOnWriting": "Wenn der Agent Code schreibt",
        "settings.peekOnFinish": "Wenn der Agent fertig ist",
        "settings.display": "Bildschirm",
        "settings.displayAuto": "Der mit der Notch",
        "settings.fullScreen": "Über Vollbild-Apps anzeigen",
        "settings.cardsFooter": "Ausgeschaltete Karten verschwinden aus der Notch. Übersicht zeigt Limits, Kosten und Jetzt; Statistik den Rest.",
        "settings.languageSystem": "Wie das System",
        "settings.languageRestart": "Die neue Sprache gilt nach einem Neustart.",
        "settings.restart": "Jetzt neu starten",
        "settings.privacyReads": "Was Denny liest",
        "settings.privacyReadsBody": "Token-Zahlen, Modellnamen, Zeiten und Projektordnernamen aus den Logs von Claude Code und Codex; Tariflimits aus ~/.claude.json, der Claude-App und Codex; die Ereignisse, die deine Agenten an die Hooks senden.",
        "settings.privacyNever": "Was Denny nie liest oder sendet",
        "settings.privacyNeverBody": "Deine Prompts, Antworten und Dateiinhalte. Nichts verlässt deine Rechner außer dem täglichen Download der öffentlichen Preisliste. Auf die Notch gezogene Dateien gehen nur an deinen eigenen Server.",
        "settings.removeAll": "Agenten trennen und Dennys Daten löschen",
        "settings.removeAllFooter": "Entfernt die Hooks aus Claude Code und Codex, löscht ~/.denny-for-agents mit Verlauf und Einstellungen und beendet die App.",
        "settings.removeAllConfirm": "Alles löschen, was Denny for Agents gespeichert hat?",
        "settings.version": "Version %@",
        "settings.about": "Ein kleiner Roboter in deiner Notch, der Claude Code und Codex im Blick behält. Der kostenlose, offene Teil von Denny.",
        "tests.onServer": "Läuft auf %@",
        "tests.noneOnServer": "Auf dem Server keine Tests gefunden",
        "server.jobWaits": "%@: Der Auftrag wartet auf den Server — er startet, sobald ein Agent dort etwas tut (oder in Sekunden, wenn einer läuft)",
        "night.where": "Wo",
        "night.thisMac": "Dieser Mac",
        "night.serverFolder": "Ordner auf dem Server, z. B. ~/projects/shop",
        "settings.section.office": "Büro",
        "settings.section.nightShift": "Nachtschicht",
        "night.newJob": "Neue Aufgabe für später",
        "night.agent": "Agent",
        "night.noFolder": "Kein Ordner gewählt",
        "night.chooseFolder": "Wählen…",
        "night.when": "Start",
        "night.whenRenews": "Wenn das Limit erneuert wird",
        "night.whenAt": "Zu einer festen Zeit",
        "night.queue": "Einreihen",
        "night.queueTitle": "Warteschlange",
        "night.waitsUntil": "wartet bis %@",
        "night.waitsForLimit": "wartet auf das Limit",
        "night.running": "läuft %@",
        "night.doneAt": "fertig um %@",
        "night.failedShort": "fehlgeschlagen: %@",
        "night.footer": "Auf diesem Mac (Denny hält ihn wach) oder auf einem Server (dort läuft es weiter, auch wenn die SSH-Sitzung abbricht; das Ergebnis kommt, wenn du dich wieder verbindest). Nachts gibt niemand Freigaben, also bleibt Denny vorsichtig: Dateiänderungen und sichere Befehle laufen, alles, was der Wächter gefährlich findet, wird abgelehnt. Das Sicherheitsnetz macht weiter Snapshots, und Telegram meldet, wenn es fertig ist. Bei einer Server-Aufgabe kommt die Telegram-Nachricht, sobald der Mac wieder mit dem Server verbunden ist.",
        "night.interrupted": "durch einen Neustart unterbrochen",
        "night.started": "%1$@ hat die Nachtaufgabe in %2$@ gestartet",
        "night.done": "%1$@ hat die Nachtaufgabe in %2$@ erledigt — der Beleg wartet in der Notch",
        "night.failed": "%1$@ konnte die Nachtaufgabe in %2$@ nicht beenden: %3$@",
        "settings.section.phone": "Telefon",
        "phone.title": "Freigaben auf dem Handy",
        "phone.steps": "1. Öffne in Telegram @BotFather und sende /newbot.\n2. Wähle einen Namen — BotFather schickt dir ein Token.\n3. Füge das Token hier ein.",
        "phone.tokenPlaceholder": "Bot-Token",
        "phone.check": "Prüfen",
        "phone.badToken": "Dieses Token funktioniert nicht — kopiere es erneut von @BotFather.",
        "phone.sendCode": "Sende diesen Code an @%@:",
        "phone.openBot": "Bot öffnen",
        "phone.topicHint": "Anfragen in einem bestimmten Thema oder einer Gruppe? Schick den Code genau dorthin — Denny schreibt nur in dieses Thema, und nur du kannst die Knöpfe drücken.",
        "phone.waiting": "Warte auf den Code…",
        "phone.connected": "Verbunden mit %1$@ über @%2$@",
        "phone.whenAway": "Wenn ich nicht am Mac bin",
        "phone.always": "Immer",
        "phone.finished": "Auch melden, wenn eine Aufgabe fertig ist",
        "phone.test": "Test senden",
        "phone.testText": "Hier ist Denny 👋 Anfragen deiner Agenten kommen in diesen Chat.",
        "phone.disconnect": "Trennen",
        "phone.footer": "Anfragen laufen über die Server von Telegram, samt Befehlstext. Der Bot gehorcht nur dem Chat, der den Code geschickt hat. Abwesend = 2 Minuten ohne Maus und Tastatur.",
        "phone.paired": "Denny ist verbunden 🎉 Wenn ein Agent um Erlaubnis bittet und du nicht am Mac bist, kommt die Anfrage hierher.",
        "phone.request": "%1$@ · %2$@ möchte:",
        "phone.allow": "✅ Erlauben",
        "phone.deny": "❌ Ablehnen",
        "phone.allowed": "✅ Erlaubt",
        "phone.denied": "❌ Abgelehnt",
        "phone.expired": "⌛ Hier nicht beantwortet — der Agent fragt in seinem Terminal.",
        "phone.replyHint": "↩️ Antworte auf diese Nachricht, um dem Agenten zu sagen, wie es weitergeht.",
        "phone.replyUnknown": "Antworte auf eine ✅-Fertig-Nachricht, um diesem Agenten zu sagen, wie es weitergeht.",
        "phone.replyLive": "%@ hat deine Antwort und macht in seinem Terminal weiter.",
        "phone.replyBackground": "%1$@ macht im Hintergrund in %2$@ weiter (vorsichtiger Modus: nichts Gefährliches ohne dich). Telegram meldet, wenn es fertig ist.",
        "phone.replyFailed": "Diese Aufgabe kann nicht fortgesetzt werden: Ordner oder Sitzung unbekannt.",
        "office.interrupted": "Unterbrochen: die App wurde neu gestartet",
        "office.stopped": "Gestoppt",
        "office.newTask": "Neue Aufgabe",
        "office.give": "Aufgabe geben",
        "office.column.inbox": "Eingang",
        "office.column.working": "In Arbeit",
        "office.column.review": "Zur Prüfung",
        "office.column.done": "Erledigt",
        "office.remove": "Entfernen",
        "office.stop": "Stoppen",
        "office.accept": "Übernehmen",
        "office.discard": "Verwerfen",
        "office.waiting": "wartet",
        "office.readyAt": "fertig um %@",
        "office.accepted": "übernommen",
        "office.discarded": "verworfen",
        "office.acceptFailed": "Zusammenführen fehlgeschlagen: %@",
        "office.noGit": "Der Ordner ist nicht in git: der Agent hat direkt darin gearbeitet, nichts zusammenzuführen.",
        "office.empty": "Noch keine Aufgaben.",
        "office.footer": "Jede Aufgabe läuft in einem eigenen git-Branch und einer eigenen Arbeitskopie: dein Projekt bleibt unberührt, bis du Übernehmen drückst (der Branch wird in den aktuellen gemergt); Verwerfen löscht den Branch. Während der Arbeit kann niemand zustimmen, daher gilt die vorsichtige Nachtschicht-Regel: Änderungen und sichere Befehle laufen, Gefährliches wird abgelehnt. Eine Aufgabe pro Ordner, zwei gleichzeitig.",
        "office.auto": "Denny entscheidet",
        "office.repeat": "Regelmäßig wiederholen",
        "office.everyDay": "Jeden Tag",
        "office.atHour": "um %ld:00",
        "office.addRecurring": "Regelaufgabe hinzufügen",
        "office.recurringTitle": "Regelaufgaben",
        "office.rework": "Nachbessern",
        "office.sendRework": "Senden",
        "office.cancel": "Abbrechen",
        "office.howTitle": "So arbeitet das Büro",
        "office.reviewToggle": "Der andere Agent prüft jede Aufgabe",
        "office.claudeBudget": "Claude-Budget pro Aufgabe, $",
        "office.codexBudget": "Codex-Budget pro Aufgabe, Tsd. Tokens",
        "office.standupToggle": "Morgen-Stand-up in Telegram",
        "office.howFooter": "Leeres Budget — keine Grenze. Claude stoppt selbst an seinem Ausgabenlimit; Codex hat keine öffentlichen Preise, daher stoppt Denny ihn nach Tokens. Das Stand-up zeigt, was erledigt ist, was auf dich wartet und was es gekostet hat.",
        "office.overBudget": "Gestoppt: Budget überschritten",
        "office.reviewClean": "%@ hat geprüft: keine Anmerkungen",
        "office.reviewFindings": "%1$@ hat geprüft: %2$ld Anmerkungen",
        "office.changes": "Dateien: %1$ld · +%2$ld −%3$ld",
        "office.testsPassed": "Tests ✅",
        "office.testsFailed": "Tests ❌",
        "office.tg.expired": "Das ist veraltet: die Aufgabe ist schon weiter.",
        "office.tg.accepted": "✅ In %@ übernommen",
        "office.tg.discarded": "🗑 Verworfen",
        "office.tg.given": "📥 An %1$@ in %2$@ übergeben. Der Bericht kommt hierher.",
        "office.tg.reworking": "🔁 %@ bessert nach.",
        "office.tg.how": "Schreib so: /task was zu tun ist. Antworte auf einen Bericht zum Nachbessern, /board zeigt das Büro.",
        "office.tg.noFolders": "Noch keine Projekte: gib die erste Aufgabe am Mac (Einstellungen → Büro).",
        "office.tg.pick": "Wer und wo?",
        "office.tg.boardEmpty": "Das Büro ist leer: keine offenen Aufgaben.",
        "office.tg.replyHint": "↩️ Antworte auf diese Nachricht, um Änderungen zu verlangen.",
        "office.tg.taskCommand": "Claude oder Codex eine Aufgabe geben",
        "office.tg.boardCommand": "Das Büro-Board",
        "office.standup.title": "☀️ Büro-Stand-up",
        "office.standup.done": "Erledigt: %ld",
        "office.standup.waiting": "Warten auf dich: %ld",
        "office.standup.working": "In Arbeit: %ld",
        "office.standup.queued": "In der Warteschlange: %ld",
        "office.standup.spent": "Ausgegeben: %@",
        "review.button": "Von %@ prüfen lassen",
        "review.running": "%1$@ prüft… %2$@",
        "review.clean": "✅ %@ hat keine Probleme gefunden",
        "review.findings": "%1$@ hat Probleme gefunden: %2$ld",
        "review.send": "An %@ senden",
        "review.copied": "Kopiert — bei %@ einfügen (⌘V)",
        "review.failed": "%1$@ konnte nicht prüfen: %2$@",
        "review.noChanges": "keine Änderungen zum Prüfen",
        "review.notFound": "auf diesem Mac nicht gefunden",
        "review.agentMessage": "%1$@ hat deine Änderungen geprüft und gefunden:\n\n%2$@\n\nBitte prüfe das und behebe, was zutrifft.",
        "tests.run": "Tests ausführen",
        "tests.running": "Tests laufen… %@",
        "tests.passed": "✅ Tests bestanden · %@",
        "tests.failed": "❌ Tests fehlgeschlagen · %@",
        "tests.sendToAgent": "An den Agenten senden",
        "tests.copied": "Kopiert — beim Agenten einfügen (⌘V)",
        "tests.agentMessage": "Nach deinen Änderungen schlagen die Tests fehl (`%1$@`). Hier das Ende der Ausgabe — bitte beheben:\n\n%2$@",
        "tests.autoSetting": "Nach jeder Aufgabe die Tests des Projekts ausführen",
        "tests.autoFooter": "Auf diesem Mac und auf Servern. Denny findet den Befehl selbst (swift test, npm test, cargo test, pytest…); einen eigenen in eine Datei .denny-test im Projektordner schreiben.",
        "tests.timedOut": "Nach 10 Minuten abgebrochen.",
        "receipt.title": "Aufgabenbeleg",
        "receipt.files": "Dateien: %ld",
        "receipt.lines": "+%1$ld −%2$ld",
        "receipt.commands": "Befehle: %ld",
        "receipt.tokens": "Tokens: %@",
        "receipt.cost": "%@ zu API-Preisen",
        "receipt.copy": "Kopieren",
        "receipt.copied": "Beleg kopiert",
        "receipt.hide": "Ausblenden",
        "receipt.signature": "via Denny for Agents",
        "settings.section.safetyNet": "Sicherheitsnetz",
        "safety.peekTitle": "Dateien vor einem riskanten Befehl gesichert",
        "safety.cardTitle": "Sicherheitsnetz",
        "safety.cardBody": "Direkt vor diesem Befehl wurden die Dateien gesichert. Rückgängig holt sie zurück.",
        "safety.onServer": "Gesichert auf %@ — die Wiederherstellung läuft dort",
        "safety.undo": "Rückgängig…",
        "safety.copyCommand": "Befehl für den Server kopieren",
        "safety.hide": "Ausblenden",
        "safety.confirmTitle": "Dateien auf den Stand vor „%@“ zurücksetzen?",
        "safety.confirmBody": "%ld Datei(en) kommen zurück. Spätere Änderungen daran gehen verloren; neue Dateien bleiben.",
        "safety.confirmRestore": "Zurückholen",
        "safety.nothing": "Nichts zurückzuholen — die Dateien entsprechen dem Snapshot.",
        "safety.restored": "Dateien sind zurück",
        "safety.failed": "Dateien konnten nicht zurückgeholt werden",
        "safety.commandCopied": "Befehl kopiert — führe ihn auf dem Server aus",
        "safety.empty": "Noch keine Snapshots. Direkt bevor ein Agent rm, git reset --hard o. Ä. ausführt, sichert Denny hier deine Dateien.",
        "safety.footer": "Bis zu 50 Snapshots. In einem Git-Projekt liegen sie in einer versteckten Ref und berühren nie Branch, Index oder Stash.",
        "safety.storage": "Speicher",
        "safety.keepFor": "Snapshots behalten",
        "safety.keep.1": "1 Tag",
        "safety.keep.7": "7 Tage",
        "safety.keep.30": "30 Tage",
        "safety.limit": "Platz für Kopien",
        "safety.gb": "%ld GB",
        "safety.used": "Kopien auf diesem Mac: %@",
        "safety.clear": "Alle Snapshots löschen…",
        "safety.clearConfirm": "Alle Snapshots auf diesem Mac löschen?",
        "safety.clearBody": "Ihre Dateien lassen sich danach nicht mehr zurückholen.",
        "safety.delete": "Löschen",
        "safety.limitFooter": "Nur Kopien von Dateien außerhalb von Git zählen — Git-Snapshots liegen im Projekt und brauchen kaum Platz. Wird der Platz knapp, fallen zuerst die ältesten Snapshots weg. Server übernehmen diese Einstellungen mit deiner nächsten Nachricht an den Agenten.",
        "update.check": "Nach Updates suchen",
        "update.checking": "Suche…",
        "update.upToDate": "Du hast die neueste Version",
        "update.available": "Version %@ ist verfügbar",
        "update.install": "Aktualisieren",
        "update.installing": "Lade das Update… Denny startet neu",
        "update.failed": "Update fehlgeschlagen: %@",
        "update.reason.offline": "GitHub ist nicht erreichbar",
        "update.reason.checksum": "die Datei passt nicht zur Prüfsumme",
        "update.reason.folder": "keine Berechtigung, die App zu ersetzen — lass sie im Ordner „Programme“",
        "update.reason.download": "der Download ist fehlgeschlagen",
        "update.homebrew": "Mit Homebrew installiert — führe aus: brew upgrade denny-for-agents",
        "update.notifyBody": "Öffne Dennys Einstellungen → Über, um zu aktualisieren.",

        "quiet.on": "Eine Stunde Ruhe",
        "quiet.active": "Ruhe bis %@ – tippen zum Beenden",
        "quick.refresh": "Jetzt aktualisieren",
        "awake.manual": "Manuell wach halten",
        "awake.duration": "Dauer",
        "awake.until": "Bis",
        "awake.indefinite": "Bis ich es ausschalte",
        "awake.start": "Starten",
        "awake.stop": "Stoppen",
        "awake.activeUntil": "Der Mac bleibt bis %@ wach",
        "awake.untilOff": "Der Mac bleibt wach, bis du stoppst",
        "awake.lid": "Bei geschlossenem Deckel weiterarbeiten",
        "awake.lidWarning": "Nur am Ladegerät. Fragt einmal nach dem Admin-Passwort, um genau einen Befehl (pmset disablesleep) zu erlauben, und schaltet sich ab, wenn die Arbeit fertig ist. Einen laufenden, zugeklappten Mac nicht in die Tasche stecken.",
        "awake.lidNeedsPower": "Gerade im Akkubetrieb – schaltet sich ein, sobald das Ladegerät angeschlossen ist.",

        "risk.safe": "Sieht sicher aus",
        "risk.caution": "Kurz prüfen",
        "risk.danger": "Gefährlich",
        "risk.critical": "Sehr gefährlich",
        "risk.reason.pipeToShell": "Lädt Code aus dem Internet und führt ihn sofort aus.",
        "risk.reason.wipeRoot": "Löscht alles in /, im Benutzerordner oder im aktuellen Ordner.",
        "risk.reason.rawDisk": "Schreibt direkt auf eine Festplatte – kann sie löschen.",
        "risk.reason.format": "Formatiert oder löscht eine Festplatte.",
        "risk.reason.forkBomb": "Eine Fork-Bombe: der Mac friert ein.",
        "risk.reason.dropData": "Löscht Datenbanktabellen oder Daten.",
        "risk.reason.deleteRecursive": "Löscht den Ordner %@ samt Inhalt, ohne Papierkorb.",
        "risk.reason.forcePush": "Überschreibt die Branch-Historie auf dem Server.",
        "risk.reason.resetHard": "Verwirft alle nicht committeten Änderungen.",
        "risk.reason.cleanUntracked": "Löscht Dateien, die git nicht verfolgt.",
        "risk.reason.sudo": "Läuft als Administrator (sudo).",
        "risk.reason.permissions": "Gibt Dateien für alle frei oder ändert den Besitzer.",
        "risk.reason.killProcess": "Beendet laufende Programme zwangsweise.",
        "risk.reason.reboot": "Fährt den Computer herunter oder startet ihn neu.",
        "risk.reason.dockerPrune": "Löscht Docker-Container, Volumes oder Daten.",
        "risk.reason.publish": "Veröffentlicht ein Paket oder Release für alle.",
        "risk.reason.secrets": "Berührt Schlüssel, Passwörter oder .env-Geheimnisse.",
        "risk.reason.push": "Schickt Commits an den Server.",
        "risk.reason.deleteFile": "Löscht %@.",
        "risk.reason.install": "Installiert Pakete aus dem Internet.",
        "risk.reason.network": "Greift aufs Netzwerk zu.",
        "risk.reason.gitHistory": "Schreibt die git-Historie um oder verwirft Dateiänderungen.",
        "risk.reason.sensitiveFile": "Ändert eine heikle Datei: %@.",
        "risk.reason.externalTool": "Nutzt ein externes Werkzeug (MCP-Server).",

        "load.thisMac": "Dieser Mac",
        "load.cpu": "CPU",
        "load.cpuLoad": "Last (%ld Kerne)",
        "load.memory": "Speicher",
        "load.pressureNormal": "Speicherdruck: normal",
        "load.pressureWarning": "Speicherdruck: hoch",
        "load.pressureCritical": "Speicherdruck: kritisch",
        "load.swap": "Swap %@",
        "load.uptime": "Läuft seit %@",
        "load.memoryLow": "Speicher fast voll – ein schwerer Build könnte abgebrochen werden.",
        "load.noServer": "Die Serverlast kommt mit dem nächsten Bericht eines verbundenen Servers.",
        "settings.section.load": "Last",

        "relay.title": "%@ hat sein Limit erreicht",
        "relay.titleUntil": "%1$@ hat sein Limit bis %2$@ erreicht",
        "relay.body": "Die Aufgabe an %@ übergeben? Ich schreibe eine Notiz mit Auftrag und Stand.",
        "relay.copy": "Notiz für %@ kopieren",
        "relay.later": "Nicht jetzt",
        "relay.copied": "Notiz kopiert – füge sie in %@ ein (⌘V)",
        "relay.handoff": "Aufgabe an %@ übergeben",
        "relay.note.intro": "Setze eine Aufgabe fort, die %1$@ begonnen hat (%2$@).",
        "relay.note.reasonLimit": "es hat sein Tariflimit erreicht",
        "relay.note.reasonManual": "ich übergebe sie dir",
        "relay.note.folder": "Ordner: %@",
        "relay.note.server": "Server: %@",
        "relay.note.task": "Die Aufgabe:",
        "relay.note.done": "Bereits erledigt:",
        "relay.note.edited": "bearbeitet: %@",
        "relay.note.ran": "ausgeführt: %@",
        "relay.note.last": "Letzte Nachricht von %@:",
        "relay.note.next": "Sieh dir zuerst die aktuellen Änderungen an (git status, git diff) und mach dann dort weiter, wo aufgehört wurde.",

        "stuck.title": "%@ dreht sich offenbar im Kreis",
        "stuck.repeatCommand": "Führt „%2$@“ zum %1$ld. Mal aus",
        "stuck.repeatEdit": "Bearbeitet %2$@ zum %1$ld. Mal",
        "stuck.noProgress": "%ld Min. Arbeit ohne eine einzige Änderung",
        "stuck.setting": "Warnen, wenn ein Agent sich im Kreis dreht"
    ]
}
