extension Translations {
    static let german: [String: String] = [
        "step.runs": "Führt %@ aus",
        "step.runsCommand": "Führt einen Befehl aus",
        "step.reads": "Liest %@",
        "step.aFile": "eine Datei",
        "step.edits": "Bearbeitet %@",
        "step.editsFiles": "Bearbeitet Dateien",
        "step.searches": "Sucht „%@“",
        "step.searchesCode": "Durchsucht den Code",
        "step.searchesWeb": "Sucht im Web",
        "step.opens": "Öffnet %@",
        "step.startsHelper": "Startet einen Hilfsagenten",
        "step.updatesPlan": "Aktualisiert den Plan",
        "step.uses": "Nutzt %@",
        "step.working": "Arbeitet…",
        "step.thinking": "Denkt nach…",
        "step.waitingForYou": "Wartet auf dich",
        "step.done": "Fertig",

        "title.idle": "Alles ruhig",
        "title.working": "Agenten arbeiten",
        "title.needsYou": "Braucht dich",
        "title.limitUsedUp": "%@-Limit aufgebraucht",
        "title.limitAlmost": "%@-Limit fast aufgebraucht",
        "subtitle.noSessions": "Starte Claude Code oder Codex – ich behalte es im Blick.",
        "subtitle.noHooks": "Verbinde Claude Code und Codex in der Menüleiste.",
        "subtitle.serverDown": "Konnte nicht auf Agenten lauschen.",
        "limit.detailResets": "%1$@, Reset in %2$@",

        "approval.allow": "Erlauben",
        "approval.deny": "Ablehnen",
        "approval.askThere": "Dort fragen",
        "approval.wantsTo": "möchte",
        "approval.more": "+%ld weitere warten",

        "stats.spending": "Kosten",
        "stats.apiValue": "API-Wert",
        "stats.now": "Jetzt",
        "stats.workingNow": "arbeitet",
        "stats.limitsLater": "Limits erscheinen nach der nächsten Antwort",
        "stats.updated": "Aktualisiert %@",
        "stats.tokens": "%@ Tokens",
        "stats.tokensWord": "Tokens",
        "stats.fromCache": "%ld%% aus dem Cache",
        "stats.todayTotal": "Heute %@",
        "stats.noPrice": "Kein öffentlicher Preis für Codex-Modelle",
        "period.today": "Heute",
        "period.week": "7 Tage",
        "period.month": "30 Tage",
        "window.session": "Sitzung",
        "window.week": "Woche",
        "window.limit": "Limit",
        "stats.activity": "Aktivität",
        "stats.streak": "%ld Tage in Folge",
        "stats.activeDays": "Aktive Tage",
        "stats.busiestDay": "Aktivster Tag",

        "time.daysHours": "%1$ld T %2$ld Std",
        "time.hoursMinutes": "%1$ld Std %2$ld Min",
        "time.minutes": "%ld Min",
        "time.hours": "%ld Std",
        "time.days": "%ld T",
        "time.months": "%ld Mon.",
        "time.justNow": "gerade eben",
        "time.ago": "vor %@",

        "resets.line": "Resets: %ld",
        "resets.expiresIn": "nächster verfällt in %@",
        "resets.use": "Reset nutzen",
        "resets.resetting": "Setze zurück…",
        "resets.confirmTitle": "Codex-Limits jetzt zurücksetzen?",
        "resets.confirmBody": "Verbraucht einen gesparten Reset: Sitzungs- und Wochenlimit erneuern sich sofort. Verbleibende Resets: %ld.",
        "resets.outcome.reset": "Codex-Limits wurden zurückgesetzt",
        "resets.outcome.nothing": "Noch nichts zurückzusetzen",
        "resets.outcome.noCredit": "Keine Resets mehr übrig",
        "resets.outcome.already": "Dieser Reset wurde bereits genutzt",
        "resets.outcome.failed": "Reset fehlgeschlagen – ist Codex auf diesem Mac angemeldet?",

        "drop.here": "Loslassen – ich kopiere den Pfad für deinen Agenten",
        "drop.copiedOne": "Pfad zu %@ kopiert – füge ihn bei deinem Agenten ein (⌘V)",
        "drop.copiedMany": "%ld Pfade kopiert – füge sie bei deinem Agenten ein (⌘V)",
        "drop.remoteCantSee": "Der Agent auf %@ sieht keine Dateien auf diesem Mac.",
        "drop.willSendOne": "Serverpfad kopiert – die Datei geht mit deiner nächsten Nachricht an %@ (⌘V)",
        "drop.willSendMany": "Serverpfade kopiert – %1$ld Dateien gehen mit deiner nächsten Nachricht an %2$@ (⌘V)",
        "drop.delivered": "An %1$@ geliefert: %2$ld",
        "drop.skippedFolders": "Ordner werden noch nicht gesendet.",
        "drop.tooBig": "Bis zu 20 MB pro Ablage.",
        "drop.shelfInFullDenny": "Dateiablage und Musiksteuerung – im vollen Denny →",
        "fullDenny": "Aufgaben, Notizen & Offline-KI – der volle Denny →",

        "alerts.menu": "Mitteilungen",
        "alerts.finish": "Aufgabe fertig",
        "alerts.limit": "Tariflimit",
        "alerts.budget": "Tagesbudget (API-Preise)",
        "alerts.off": "Aus",
        "alerts.anyLength": "Jede Dauer",
        "alerts.longerThan": "Länger als %ld Min",
        "alerts.atPercent": "Bei %ld%%",
        "alerts.finishedTitle": "%@ ist fertig",
        "alerts.finishedBody": "%1$@ · hat %2$@ gearbeitet",
        "alerts.limitTitle": "%1$@-Limit bei %2$ld%%",
        "alerts.budgetTitle": "Tagesbudget erreicht: %@",
        "alerts.budgetBody": "Zu API-Listenpreisen, über diesen Mac und deine Server.",

        "menu.claude": "Claude Code beobachten",
        "menu.codex": "Codex beobachten",
        "menu.remote": "Entfernter Server (SSH)…",
        "menu.fullDenny": "Den vollen Denny holen…",
        "menu.quit": "Denny for Agents beenden",
        "remote.title": "Agenten auf einem SSH-Server beobachten",
        "remote.body": "1. Leite den Port während der Verbindung weiter: in Termius eine Remote-Port-Weiterleitung anlegen (Server 127.0.0.1:{port} → dieser Mac 127.0.0.1:{port}) oder so verbinden: ssh -R {port}:127.0.0.1:{port} user@server\n2. Lege remote/denny-hook.py aus dem Repo auf dem Server in ~/.denny-for-agents/ ab.\n3. Führe auf dem Server den kopierten Befehl aus, dann: python3 ~/.denny-for-agents/denny-hook.py --ping",
        "remote.copy": "Installationsbefehl kopieren",
        "remote.unavailable": "Remote-Modus konnte nicht starten: Port belegt.",
        "common.close": "Schließen",
        "common.cancel": "Abbrechen",
        "connect.title": "Denny mit deinen Agenten verbinden?",
        "connect.body": "Denny fügt Hooks zu ~/.claude/settings.json und ~/.codex/hooks.json hinzu (daneben wird eine Sicherung abgelegt). Läuft Denny nicht, tun die Hooks nichts und blockieren deine Agenten nie.",
        "connect.connect": "Verbinden",
        "connect.later": "Später",
        "connect.failed": "Einstellungsdatei konnte nicht geändert werden"
    ]
}
