extension Translations {
    static let japanese: [String: String] = [
        "step.runs": "%@ を実行中",
        "step.runsCommand": "コマンドを実行中",
        "step.reads": "%@ を読み込み中",
        "step.aFile": "ファイル",
        "step.edits": "%@ を編集中",
        "step.editsFiles": "ファイルを編集中",
        "step.searches": "「%@」を検索中",
        "step.searchesCode": "コードを検索中",
        "step.searchesWeb": "Web を検索中",
        "step.opens": "%@ を開いています",
        "step.startsHelper": "ヘルパーエージェントを起動",
        "step.updatesPlan": "計画を更新中",
        "step.uses": "%@ を使用中",
        "step.working": "作業中…",
        "step.thinking": "考え中…",
        "step.waitingForYou": "あなたの返事待ち",
        "step.done": "完了",

        "title.idle": "異常なし",
        "title.working": "エージェントが作業中",
        "title.needsYou": "あなたの出番です",
        "title.limitUsedUp": "%@ の上限に達しました",
        "title.limitAlmost": "%@ の上限が近づいています",
        "subtitle.noSessions": "Claude Code か Codex を起動してください — 見守っています。",
        "subtitle.noHooks": "メニューバーから Claude Code と Codex を接続してください。",
        "subtitle.serverDown": "エージェントの待ち受けを開始できませんでした。",
        "limit.detailResets": "%1$@、%2$@ 後にリセット",

        "approval.allow": "許可",
        "approval.deny": "拒否",
        "approval.askThere": "向こうで確認",
        "approval.wantsTo": "の実行許可を求めています",
        "approval.more": "ほかに %ld 件待機中",

        "stats.spending": "利用額",
        "stats.apiValue": "API 換算",
        "stats.now": "いま",
        "stats.workingNow": "作業中",
        "stats.limitsLater": "上限は次の応答のあとに表示されます",
        "stats.updated": "%@ に更新",
        "stats.tokens": "%@ トークン",
        "stats.tokensWord": "トークン",
        "stats.fromCache": "%ld%% がキャッシュから",
        "stats.todayTotal": "今日 %@",
        "stats.noPrice": "Codex モデルの公開価格はありません",
        "period.today": "今日",
        "period.week": "7 日間",
        "period.month": "30 日間",
        "window.session": "セッション",
        "window.week": "週",
        "window.limit": "上限",
        "stats.activity": "アクティビティ",
        "stats.streak": "%ld 日連続",
        "stats.activeDays": "稼働日数",
        "stats.busiestDay": "最も忙しかった日",

        "time.daysHours": "%1$ld日 %2$ld時間",
        "time.hoursMinutes": "%1$ld時間 %2$ld分",
        "time.minutes": "%ld分",
        "time.hours": "%ld時間",
        "time.days": "%ld日",
        "time.months": "%ldか月",
        "time.justNow": "たった今",
        "time.ago": "%@前",

        "resets.line": "リセット: %ld 回",
        "resets.expiresIn": "次の失効まで %@",
        "resets.use": "リセットを使う",
        "resets.resetting": "リセット中…",
        "resets.confirmTitle": "Codex の上限をいまリセットしますか？",
        "resets.confirmBody": "保有しているリセットを 1 回使います。セッションと週の上限がすぐに回復します。残り: %ld 回。",
        "resets.outcome.reset": "Codex の上限をリセットしました",
        "resets.outcome.nothing": "まだリセットするものはありません",
        "resets.outcome.noCredit": "リセットが残っていません",
        "resets.outcome.already": "このリセットはすでに使用済みです",
        "resets.outcome.failed": "リセットできませんでした — この Mac の Codex はサインイン済みですか？",

        "drop.here": "ドロップするとエージェント用にパスをコピーします",
        "drop.copiedOne": "%@ のパスをコピーしました — エージェントに貼り付けてください (⌘V)",
        "drop.copiedMany": "%ld 件のパスをコピーしました — エージェントに貼り付けてください (⌘V)",
        "drop.remoteCantSee": "%@ のエージェントはこの Mac のファイルを見られません。",
        "drop.willSendOne": "サーバー上のパスをコピーしました — ファイルは次のメッセージと一緒に %@ へ送られます (⌘V)",
        "drop.willSendMany": "サーバー上のパスをコピーしました — %1$ld 件のファイルが次のメッセージと一緒に %2$@ へ送られます (⌘V)",
        "drop.delivered": "%1$@ に届けました: %2$ld 件",
        "drop.skippedFolders": "フォルダーはまだ送れません。",
        "drop.tooBig": "1 回あたり 20 MB まで。",
        "drop.shelfInFullDenny": "ファイル置き場と音楽操作は完全版 Denny で →",
        "fullDenny": "タスク、メモ、オフライン AI — 完全版 Denny →",

        "alerts.menu": "通知",
        "alerts.finish": "タスク完了",
        "alerts.limit": "プランの上限",
        "alerts.budget": "1 日の予算（API 価格）",
        "alerts.off": "オフ",
        "alerts.anyLength": "すべて",
        "alerts.longerThan": "%ld 分以上",
        "alerts.atPercent": "%ld%% で通知",
        "alerts.finishedTitle": "%@ が完了しました",
        "alerts.finishedBody": "%1$@ · %2$@ 作業",
        "alerts.limitTitle": "%1$@ の上限 %2$ld%%",
        "alerts.budgetTitle": "1 日の予算に達しました: %@",
        "alerts.budgetBody": "API の定価換算、この Mac とサーバーの合計です。",

        "menu.claude": "Claude Code を見守る",
        "menu.codex": "Codex を見守る",
        "menu.remote": "リモートサーバー (SSH)…",
        "menu.fullDenny": "完全版 Denny を入手…",
        "menu.quit": "Denny for Agents を終了",
        "remote.title": "SSH サーバー上のエージェントを見守る",
        "remote.body": "1. 接続中はポートを転送します: Termius で Remote ポート転送ルールを追加（サーバー 127.0.0.1:{port} → この Mac 127.0.0.1:{port}）、または ssh -R {port}:127.0.0.1:{port} user@server で接続\n2. リポジトリの remote/denny-hook.py をサーバーの ~/.denny-for-agents/ に置きます。\n3. サーバーでコピーしたコマンドを実行し、次に: python3 ~/.denny-for-agents/denny-hook.py --ping",
        "remote.copy": "インストールコマンドをコピー",
        "remote.unavailable": "リモートモードを開始できません: ポートが使用中です。",
        "common.close": "閉じる",
        "common.cancel": "キャンセル",
        "connect.title": "Denny をエージェントに接続しますか？",
        "connect.body": "Denny は ~/.claude/settings.json と ~/.codex/hooks.json にフックを追加します（それぞれの横にバックアップを保存）。Denny が起動していなければフックは何もせず、エージェントを妨げることはありません。",
        "connect.connect": "接続",
        "connect.later": "あとで",
        "connect.failed": "設定ファイルを変更できませんでした"
    ]
}
