extension Translations {
    static let japanese: [String: String] = [
        "step.runs": "%@ を実行中",
        "step.runsCommand": "コマンドを実行中",
        "step.reads": "%@ を読み込み中",
        "step.aFile": "ファイル",
        "step.edits": "%@ を編集中",
        "step.editsFiles": "ファイルを編集中",
        "step.searches": "「%@」を検索中",
        "step.searchesCode": "コードを検索中",
        "step.searchesWeb": "Web を検索中",
        "step.opens": "%@ を開いています",
        "step.startsHelper": "ヘルパーエージェントを起動",
        "step.updatesPlan": "計画を更新中",
        "step.uses": "%@ を使用中",
        "step.working": "作業中…",
        "step.thinking": "考え中…",
        "step.waitingForYou": "あなたの返事待ち",
        "step.done": "完了",

        "title.idle": "異常なし",
        "title.working": "エージェントが作業中",
        "title.needsYou": "あなたの出番です",
        "title.limitUsedUp": "%@ の上限に達しました",
        "title.limitAlmost": "%@ の上限が近づいています",
        "subtitle.noSessions": "Claude Code か Codex を起動してください — 見守っています。",
        "subtitle.noHooks": "メニューバーから Claude Code と Codex を接続してください。",
        "subtitle.serverDown": "エージェントの待ち受けを開始できませんでした。",
        "limit.detailResets": "%1$@、%2$@ 後にリセット",

        "approval.allow": "許可",
        "approval.deny": "拒否",
        "approval.askThere": "向こうで確認",
        "approval.wantsTo": "の実行許可を求めています",
        "approval.more": "ほかに %ld 件待機中",

        "stats.spending": "利用額",
        "stats.apiValue": "API 換算",
        "stats.now": "いま",
        "stats.workingNow": "作業中",
        "stats.limitsLater": "上限は次の応答のあとに表示されます",
        "stats.updated": "%@ に更新",
        "stats.tokens": "%@ トークン",
        "stats.tokensWord": "トークン",
        "stats.fromCache": "%ld%% がキャッシュから",
        "stats.todayTotal": "今日 %@",
        "stats.noPrice": "Codex モデルの公開価格はありません",
        "period.today": "今日",
        "period.week": "7 日間",
        "period.month": "30 日間",
        "window.session": "セッション",
        "window.week": "週",
        "window.limit": "上限",
        "stats.activity": "アクティビティ",
        "stats.streak": "%ld 日連続",
        "stats.activeDays": "稼働日数",
        "stats.busiestDay": "最も忙しかった日",

        "time.daysHours": "%1$ld日 %2$ld時間",
        "time.hoursMinutes": "%1$ld時間 %2$ld分",
        "time.minutes": "%ld分",
        "time.hours": "%ld時間",
        "time.days": "%ld日",
        "time.months": "%ldか月",
        "time.justNow": "たった今",
        "time.ago": "%@前",

        "resets.line": "リセット: %ld 回",
        "resets.expiresIn": "次の失効まで %@",
        "resets.use": "リセットを使う",
        "resets.resetting": "リセット中…",
        "resets.confirmTitle": "Codex の上限をいまリセットしますか？",
        "resets.confirmBody": "保有しているリセットを 1 回使います。セッションと週の上限がすぐに回復します。残り: %ld 回。",
        "resets.outcome.reset": "Codex の上限をリセットしました",
        "resets.outcome.nothing": "まだリセットするものはありません",
        "resets.outcome.noCredit": "リセットが残っていません",
        "resets.outcome.already": "このリセットはすでに使用済みです",
        "resets.outcome.failed": "リセットできませんでした — この Mac の Codex はサインイン済みですか？",

        "drop.here": "ドロップするとエージェント用にパスをコピーします",
        "drop.copiedOne": "%@ のパスをコピーしました — エージェントに貼り付けてください (⌘V)",
        "drop.copiedMany": "%ld 件のパスをコピーしました — エージェントに貼り付けてください (⌘V)",
        "drop.remoteCantSee": "%@ のエージェントはこの Mac のファイルを見られません。",
        "drop.willSendOne": "サーバー上のパスをコピーしました — ファイルは次のメッセージと一緒に %@ へ送られます (⌘V)",
        "drop.willSendMany": "サーバー上のパスをコピーしました — %1$ld 件のファイルが次のメッセージと一緒に %2$@ へ送られます (⌘V)",
        "drop.delivered": "%1$@ に届けました: %2$ld 件",
        "drop.skippedFolders": "フォルダーはまだ送れません。",
        "drop.tooBig": "1 回あたり 20 MB まで。",
        "drop.shelfInFullDenny": "ファイル置き場と音楽操作は完全版 Denny で →",
        "fullDenny": "タスク、メモ、オフライン AI — 完全版 Denny →",

        "alerts.menu": "通知",
        "alerts.finish": "タスク完了",
        "alerts.limit": "プランの上限",
        "alerts.budget": "1 日の予算（API 価格）",
        "alerts.off": "オフ",
        "alerts.anyLength": "すべて",
        "alerts.longerThan": "%ld 分以上",
        "alerts.atPercent": "%ld%% で通知",
        "alerts.finishedTitle": "%@ が完了しました",
        "alerts.finishedBody": "%1$@ · %2$@ 作業",
        "alerts.limitTitle": "%1$@ の上限 %2$ld%%",
        "alerts.budgetTitle": "1 日の予算に達しました: %@",
        "alerts.budgetBody": "API の定価換算、この Mac とサーバーの合計です。",

        "menu.claude": "Claude Code を見守る",
        "menu.codex": "Codex を見守る",
        "menu.remote": "リモートサーバー (SSH)…",
        "menu.fullDenny": "完全版 Denny を入手…",
        "menu.quit": "Denny for Agents を終了",
        "remote.title": "SSH サーバー上のエージェントを見守る",
        "remote.body": "1. 接続中はポートを転送します: Termius で Remote ポート転送ルールを追加（サーバー 127.0.0.1:{port} → この Mac 127.0.0.1:{port}）、または ssh -R {port}:127.0.0.1:{port} user@server で接続\n2. リポジトリの remote/denny-hook.py をサーバーの ~/.denny-for-agents/ に置きます。\n3. サーバーでコピーしたコマンドを実行し、次に: python3 ~/.denny-for-agents/denny-hook.py --ping",
        "remote.copy": "インストールコマンドをコピー",
        "remote.unavailable": "リモートモードを開始できません: ポートが使用中です。",
        "common.close": "閉じる",
        "common.cancel": "キャンセル",
        "connect.title": "Denny をエージェントに接続しますか？",
        "connect.body": "Denny は ~/.claude/settings.json と ~/.codex/hooks.json にフックを追加します（それぞれの横にバックアップを保存）。Denny が起動していなければフックは何もせず、エージェントを妨げることはありません。",
        "connect.connect": "接続",
        "connect.later": "あとで",
        "connect.failed": "設定ファイルを変更できませんでした",

        "value.title": "プランのお得度",
        "value.line": "30 日間の API 換算 %@",
        "value.planMonthly": "%1$@ · %2$@/月",
        "stats.trend": "推移",
        "stats.models": "モデル",
        "stats.projects": "プロジェクト",
        "stats.peak": "ピーク %@",
        "card.limits": "上限",
        "alerts.renewedTitle": "%@ の上限が回復しました",
        "menu.cards": "カード",
        "menu.readout": "カメラの横",
        "readout.timer": "タスクのタイマー",
        "readout.limit": "いちばん厳しい上限",
        "page.overview": "概要",
        "page.stats": "統計",
        "stats.noFresh": "最新データがありません",

        "settings.title": "設定",
        "settings.menu": "設定…",
        "settings.section.agents": "エージェント",
        "settings.section.servers": "サーバー",
        "settings.section.notch": "ノッチ",
        "settings.section.cards": "カード",
        "settings.section.alerts": "通知",
        "settings.section.language": "言語",
        "settings.section.privacy": "プライバシー",
        "settings.section.about": "情報",
        "settings.connected": "接続済み",
        "settings.notConnected": "未接続",
        "settings.disconnect": "接続解除",
        "settings.agentsFooter": "Denny は各エージェントの設定ファイルにフックを追加し、隣にバックアップを保存します。Denny が起動していなければフックは何もしません。",
        "settings.keepAwake": "エージェント作業中は Mac をスリープさせない",
        "settings.keepAwakeFooter": "この Mac でエージェントが作業中のときだけです。画面は消えることがあります。",
        "settings.serversConnected": "接続中のサーバー",
        "settings.noServers": "まだサーバーはありません。下で設定してください。",
        "settings.lastSeen": "最終確認 %@",
        "settings.peeks": "ひょっこり表示",
        "settings.peekOnStart": "タスクを送ったとき",
        "settings.peekOnWriting": "エージェントがコードを書き始めたとき",
        "settings.peekOnFinish": "エージェントが完了したとき",
        "settings.display": "ディスプレイ",
        "settings.displayAuto": "ノッチのあるディスプレイ",
        "settings.fullScreen": "フルスクリーンアプリの上にも表示",
        "settings.cardsFooter": "オフにしたカードはノッチから消えます。概要には上限・利用額・いまが、統計にはそれ以外が入ります。",
        "settings.languageSystem": "システムと同じ",
        "settings.languageRestart": "新しい言語は再起動後に反映されます。",
        "settings.restart": "今すぐ再起動",
        "settings.privacyReads": "Denny が読むもの",
        "settings.privacyReadsBody": "Claude Code と Codex のログにあるトークン数、モデル名、時刻、プロジェクトフォルダ名。~/.claude.json、Claude アプリ、Codex からのプラン上限。エージェントがフックに送るイベント。",
        "settings.privacyNever": "Denny が決して読まない・送らないもの",
        "settings.privacyNeverBody": "あなたのプロンプト、回答、ファイルの中身。公開価格表の毎日のダウンロード以外、何もマシンの外へ出ません。ノッチにドロップしたファイルはあなたのサーバーにだけ送られます。",
        "settings.removeAll": "エージェントを切断して Denny のデータを消去",
        "settings.removeAllFooter": "Claude Code と Codex からフックを外し、履歴と設定を含む ~/.denny-for-agents を削除して終了します。",
        "settings.removeAllConfirm": "Denny for Agents が保存したものをすべて消去しますか？",
        "settings.version": "バージョン %@",
        "settings.about": "ノッチに住んで Claude Code と Codex を見守る小さなロボット。Denny の無料のオープン部分です。",
        "settings.section.nightShift": "夜勤",
        "night.newJob": "あとで実行するタスク",
        "night.agent": "エージェント",
        "night.noFolder": "フォルダ未選択",
        "night.chooseFolder": "選択…",
        "night.when": "開始",
        "night.whenRenews": "制限がリセットされたら",
        "night.whenAt": "指定した時刻に",
        "night.queue": "キューに追加",
        "night.queueTitle": "キュー",
        "night.waitsUntil": "%@ まで待機",
        "night.waitsForLimit": "制限のリセット待ち",
        "night.running": "実行中 %@",
        "night.doneAt": "%@ に完了",
        "night.failedShort": "失敗：%@",
        "night.footer": "この Mac がオンの間に実行します（Denny がスリープを防ぎます）。夜は誰も許可できないので Denny は慎重です：ファイルの編集と安全なコマンドは進め、ガードが危険と判断したものは拒否します。セーフティネットはいつも通りスナップショットを取り、朝にはレシートが待っています。完了は Telegram でお知らせします。",
        "night.interrupted": "再起動で中断されました",
        "night.started": "%1$@ が %2$@ で夜勤タスクを開始しました",
        "night.done": "%1$@ が %2$@ で夜勤タスクを終えました — レシートがノッチで待っています",
        "night.failed": "%1$@ は %2$@ の夜勤タスクを終えられませんでした：%3$@",
        "settings.section.phone": "スマホ",
        "phone.title": "スマホで許可",
        "phone.steps": "1. Telegram で @BotFather を開き /newbot を送信します。\n2. 名前を決めると BotFather がトークンを送ってきます。\n3. トークンをここに貼り付けます。",
        "phone.tokenPlaceholder": "ボットのトークン",
        "phone.check": "確認",
        "phone.badToken": "このトークンは使えません — @BotFather からもう一度コピーしてください。",
        "phone.sendCode": "このコードを @%@ に送ってください：",
        "phone.openBot": "ボットを開く",
        "phone.topicHint": "特定のトピックやグループで受け取りたい場合は、そこにコードを送ってください — Denny はそのトピックにだけ書き込み、ボタンを押せるのはあなただけです。",
        "phone.waiting": "コードを待っています…",
        "phone.connected": "@%2$@ 経由で %1$@ に接続済み",
        "phone.whenAway": "Mac から離れているとき",
        "phone.always": "常に",
        "phone.finished": "タスクが終わったときも知らせる",
        "phone.test": "テストを送る",
        "phone.testText": "Denny です 👋 エージェントからのリクエストはこのチャットに届きます。",
        "phone.disconnect": "接続を解除",
        "phone.footer": "リクエストはコマンドの文面も含め Telegram のサーバーを経由します。ボットはコードを送ったチャットにだけ従います。離席 = 2 分間マウスもキーボードも操作なし。",
        "phone.paired": "Denny が接続しました 🎉 エージェントが許可を求め、あなたが Mac から離れているとき、リクエストがここに届きます。",
        "phone.request": "%1$@ · %2$@ がやりたいこと：",
        "phone.allow": "✅ 許可",
        "phone.deny": "❌ 拒否",
        "phone.allowed": "✅ 許可しました",
        "phone.denied": "❌ 拒否しました",
        "phone.expired": "⌛ ここでは応答なし — エージェントは自分のターミナルで確認します。",
        "review.button": "%@ にチェックしてもらう",
        "review.running": "%1$@ がレビュー中… %2$@",
        "review.clean": "✅ %@ は問題を見つけませんでした",
        "review.findings": "%1$@ が問題を見つけました：%2$ld",
        "review.send": "%@ に送る",
        "review.copied": "コピーしました — %@ に貼り付けてください（⌘V）",
        "review.failed": "%1$@ はレビューできませんでした：%2$@",
        "review.noChanges": "レビューする変更がありません",
        "review.notFound": "この Mac に見つかりません",
        "review.agentMessage": "%1$@ があなたの変更をレビューして見つけた点です：\n\n%2$@\n\n確認して、妥当なものを修正してください。",
        "tests.run": "テストを実行",
        "tests.running": "テスト実行中… %@",
        "tests.passed": "✅ テスト成功 · %@",
        "tests.failed": "❌ テスト失敗 · %@",
        "tests.sendToAgent": "エージェントに送る",
        "tests.copied": "コピーしました — エージェントに貼り付けてください（⌘V）",
        "tests.agentMessage": "変更後にテストが失敗しています（`%1$@`）。出力の最後です — 修正してください：\n\n%2$@",
        "tests.autoSetting": "各タスクの後にプロジェクトのテストを実行",
        "tests.autoFooter": "この Mac のプロジェクトのみ。Denny がコマンドを自動で見つけます（swift test、npm test、cargo test、pytest…）。独自のコマンドはプロジェクト直下の .denny-test ファイルに書いてください。",
        "tests.timedOut": "10 分で停止しました。",
        "receipt.title": "タスクのレシート",
        "receipt.files": "ファイル：%ld",
        "receipt.lines": "+%1$ld −%2$ld",
        "receipt.commands": "コマンド：%ld",
        "receipt.tokens": "トークン：%@",
        "receipt.cost": "API 価格で %@",
        "receipt.copy": "コピー",
        "receipt.copied": "レシートをコピーしました",
        "receipt.hide": "隠す",
        "receipt.signature": "Denny for Agents より",
        "settings.section.safetyNet": "セーフティネット",
        "safety.peekTitle": "危険なコマンドの前にファイルを保存しました",
        "safety.cardTitle": "セーフティネット",
        "safety.cardBody": "このコマンドの直前にファイルを保存しました。「元に戻す」で復元できます。",
        "safety.onServer": "%@ に保存 — 復元はそちらで実行します",
        "safety.undo": "元に戻す…",
        "safety.copyCommand": "サーバー用コマンドをコピー",
        "safety.hide": "隠す",
        "safety.confirmTitle": "「%@」の前の状態にファイルを戻しますか？",
        "safety.confirmBody": "%ld 個のファイルが戻ります。スナップショット後の変更は失われます。新しいファイルは残ります。",
        "safety.confirmRestore": "戻す",
        "safety.nothing": "戻すものはありません — ファイルはスナップショットと同じです。",
        "safety.restored": "ファイルを戻しました",
        "safety.failed": "ファイルを戻せませんでした",
        "safety.commandCopied": "コマンドをコピーしました — サーバーで実行してください",
        "safety.empty": "まだスナップショットはありません。エージェントが rm や git reset --hard などを実行する直前に、Denny がここにファイルを保存します。",
        "safety.footer": "最大 50 件。git プロジェクトでは隠し ref に保存され、ブランチ・インデックス・stash には一切触れません。",
        "safety.storage": "保存",
        "safety.keepFor": "スナップショットの保存期間",
        "safety.keep.1": "1 日",
        "safety.keep.7": "7 日",
        "safety.keep.30": "30 日",
        "safety.limit": "コピー用の容量",
        "safety.gb": "%ld GB",
        "safety.used": "この Mac のコピー：%@",
        "safety.clear": "すべてのスナップショットを削除…",
        "safety.clearConfirm": "この Mac のすべてのスナップショットを削除しますか？",
        "safety.clearBody": "削除後はファイルを戻せなくなります。",
        "safety.delete": "削除",
        "safety.limitFooter": "git 外のファイルのコピーだけが対象です — git のスナップショットはプロジェクト内にあり、ほとんど容量を使いません。容量が足りなくなると古いものから削除します。サーバーには、エージェントへの次のメッセージと一緒に設定が届きます。",
        "update.check": "アップデートを確認",
        "update.checking": "確認中…",
        "update.upToDate": "最新バージョンです",
        "update.available": "バージョン %@ が利用可能です",
        "update.install": "アップデート",
        "update.installing": "アップデートをダウンロード中… Denny が再起動します",
        "update.failed": "アップデートできませんでした：%@",
        "update.reason.offline": "GitHub に接続できません",
        "update.reason.checksum": "ファイルがチェックサムと一致しません",
        "update.reason.folder": "アプリを置き換える権限がありません — アプリケーションフォルダに置いてください",
        "update.reason.download": "ダウンロードに失敗しました",
        "update.homebrew": "Homebrew でインストール済み — 実行：brew upgrade denny-for-agents",
        "update.notifyBody": "Denny の設定 → 情報 からアップデートしてください。",

        "quiet.on": "1 時間おやすみモード",
        "quiet.active": "%@ までおやすみ中 — タップで解除",
        "quick.refresh": "今すぐ更新",
        "awake.manual": "手動でスリープさせない",
        "awake.duration": "時間で",
        "awake.until": "時刻まで",
        "awake.indefinite": "オフにするまで",
        "awake.start": "開始",
        "awake.stop": "停止",
        "awake.activeUntil": "Mac は %@ までスリープしません",
        "awake.untilOff": "止めるまで Mac はスリープしません",
        "awake.lid": "ふたを閉じても作業を続ける",
        "awake.lidWarning": "充電中のみ有効です。管理者パスワードを一度だけ求め、1 つのコマンド（pmset disablesleep）だけを許可し、作業が終わると自動でオフになります。動作中の閉じた Mac をバッグに入れないでください。",
        "awake.lidNeedsPower": "いまはバッテリー駆動です — 充電器をつなぐとオンになります。",

        "risk.safe": "安全そうです",
        "risk.caution": "念のため確認を",
        "risk.danger": "危険",
        "risk.critical": "非常に危険",
        "risk.reason.pipeToShell": "インターネットからコードをダウンロードしてすぐ実行します。",
        "risk.reason.wipeRoot": "/、ホームフォルダ、または現在のフォルダの中身をすべて削除します。",
        "risk.reason.rawDisk": "ディスクに直接書き込みます — 消える恐れがあります。",
        "risk.reason.format": "ディスクをフォーマットまたは消去します。",
        "risk.reason.forkBomb": "フォーク爆弾です。Mac が固まります。",
        "risk.reason.dropData": "データベースのテーブルやデータを削除します。",
        "risk.reason.deleteRecursive": "フォルダ %@ を中身ごと削除します（ゴミ箱を経由しません）。",
        "risk.reason.forcePush": "サーバー上のブランチ履歴を上書きします。",
        "risk.reason.resetHard": "コミットしていない変更をすべて捨てます。",
        "risk.reason.cleanUntracked": "git が追跡していないファイルを削除します。",
        "risk.reason.sudo": "管理者として実行します（sudo）。",
        "risk.reason.permissions": "ファイルを全員に開放するか、所有者を変更します。",
        "risk.reason.killProcess": "実行中のプログラムを強制終了します。",
        "risk.reason.reboot": "コンピュータをシャットダウンまたは再起動します。",
        "risk.reason.dockerPrune": "Docker のコンテナ、ボリューム、データを削除します。",
        "risk.reason.publish": "パッケージやリリースを全員に公開します。",
        "risk.reason.secrets": "鍵、パスワード、.env の秘密情報に触れます。",
        "risk.reason.push": "コミットをサーバーに送ります。",
        "risk.reason.deleteFile": "%@ を削除します。",
        "risk.reason.install": "インターネットからパッケージをインストールします。",
        "risk.reason.network": "ネットワークにアクセスします。",
        "risk.reason.gitHistory": "git の履歴を書き換えるか、ファイルの変更を取り消します。",
        "risk.reason.sensitiveFile": "重要なファイルを変更します: %@。",
        "risk.reason.externalTool": "外部ツール（MCP サーバー）を使います。",

        "load.thisMac": "この Mac",
        "load.cpu": "CPU",
        "load.cpuLoad": "負荷（%ld コア）",
        "load.memory": "メモリ",
        "load.pressureNormal": "メモリプレッシャー: 正常",
        "load.pressureWarning": "メモリプレッシャー: 高い",
        "load.pressureCritical": "メモリプレッシャー: 危険",
        "load.swap": "スワップ %@",
        "load.uptime": "稼働時間 %@",
        "load.memoryLow": "メモリがほぼいっぱいです — 重いビルドが強制終了されるかもしれません。",
        "load.noServer": "サーバーの負荷は、接続中のサーバーの次のレポートで届きます。",
        "settings.section.load": "負荷",

        "relay.title": "%@ が上限に達しました",
        "relay.titleUntil": "%1$@ は %2$@ まで上限です",
        "relay.body": "%@ にタスクを引き継ぎますか？依頼内容と進捗をメモにまとめます。",
        "relay.copy": "%@ 用のメモをコピー",
        "relay.later": "あとで",
        "relay.copied": "メモをコピーしました — %@ に貼り付けてください (⌘V)",
        "relay.handoff": "%@ に引き継ぐ",
        "relay.note.intro": "%1$@ が始めたタスクを続けてください（%2$@）。",
        "relay.note.reasonLimit": "プランの上限に達しました",
        "relay.note.reasonManual": "あなたに引き継ぎます",
        "relay.note.folder": "フォルダ: %@",
        "relay.note.server": "サーバー: %@",
        "relay.note.task": "タスク:",
        "relay.note.done": "済んでいること:",
        "relay.note.edited": "編集: %@",
        "relay.note.ran": "実行: %@",
        "relay.note.last": "%@ の最後のメッセージ:",
        "relay.note.next": "まず現在の変更を確認し（git status、git diff）、止まったところから続けてください。",

        "stuck.title": "%@ が堂々巡りしているようです",
        "stuck.repeatCommand": "「%2$@」を %1$ld 回目の実行中",
        "stuck.repeatEdit": "%2$@ を %1$ld 回目の編集中",
        "stuck.noProgress": "%ld 分作業して変更が一つもありません",
        "stuck.setting": "エージェントが堂々巡りしたら知らせる"
    ]
}
