extension Translations {
    static let korean: [String: String] = [
        "step.runs": "%@ 실행 중",
        "step.runsCommand": "명령 실행 중",
        "step.reads": "%@ 읽는 중",
        "step.aFile": "파일",
        "step.edits": "%@ 수정 중",
        "step.editsFiles": "파일 수정 중",
        "step.searches": "“%@” 검색 중",
        "step.searchesCode": "코드 검색 중",
        "step.searchesWeb": "웹 검색 중",
        "step.opens": "%@ 여는 중",
        "step.startsHelper": "도우미 에이전트 시작",
        "step.updatesPlan": "계획 업데이트 중",
        "step.uses": "%@ 사용 중",
        "step.working": "작업 중…",
        "step.thinking": "생각 중…",
        "step.waitingForYou": "당신을 기다리는 중",
        "step.done": "완료",

        "title.idle": "모두 조용해요",
        "title.working": "에이전트 작업 중",
        "title.needsYou": "확인이 필요해요",
        "title.limitUsedUp": "%@ 한도 소진",
        "title.limitAlmost": "%@ 한도가 거의 다 찼어요",
        "subtitle.noSessions": "Claude Code나 Codex를 실행하세요 — 제가 지켜볼게요.",
        "subtitle.noHooks": "메뉴 막대에서 Claude Code와 Codex를 연결하세요.",
        "subtitle.serverDown": "에이전트 수신을 시작하지 못했어요.",
        "limit.detailResets": "%1$@, %2$@ 후 초기화",

        "approval.allow": "허용",
        "approval.deny": "거부",
        "approval.askThere": "거기서 묻기",
        "approval.wantsTo": "요청",
        "approval.more": "%ld개 더 대기 중",

        "stats.spending": "지출",
        "stats.apiValue": "API 가격 기준",
        "stats.now": "지금",
        "stats.workingNow": "작업 중",
        "stats.limitsLater": "다음 응답 후에 한도가 표시돼요",
        "stats.updated": "%@ 업데이트",
        "stats.tokens": "%@ 토큰",
        "stats.tokensWord": "토큰",
        "stats.fromCache": "%ld%% 캐시 사용",
        "stats.todayTotal": "오늘 %@",
        "stats.noPrice": "Codex 모델은 공개 가격이 없어요",
        "period.today": "오늘",
        "period.week": "7일",
        "period.month": "30일",
        "window.session": "세션",
        "window.week": "주간",
        "window.limit": "한도",
        "stats.activity": "활동",
        "stats.streak": "%ld일 연속",
        "stats.activeDays": "활동한 날",
        "stats.busiestDay": "가장 바빴던 날",

        "time.daysHours": "%1$ld일 %2$ld시간",
        "time.hoursMinutes": "%1$ld시간 %2$ld분",
        "time.minutes": "%ld분",
        "time.hours": "%ld시간",
        "time.days": "%ld일",
        "time.months": "%ld개월",
        "time.justNow": "방금",
        "time.ago": "%@ 전",

        "resets.line": "초기화: %ld회",
        "resets.expiresIn": "다음 만료까지 %@",
        "resets.use": "초기화 사용",
        "resets.resetting": "초기화 중…",
        "resets.confirmTitle": "지금 Codex 한도를 초기화할까요?",
        "resets.confirmBody": "보유한 초기화 1회를 사용합니다. 세션 및 주간 한도가 즉시 갱신돼요. 남은 횟수: %ld.",
        "resets.outcome.reset": "Codex 한도를 초기화했어요",
        "resets.outcome.nothing": "아직 초기화할 것이 없어요",
        "resets.outcome.noCredit": "남은 초기화가 없어요",
        "resets.outcome.already": "이미 사용한 초기화예요",
        "resets.outcome.failed": "초기화하지 못했어요 — 이 Mac의 Codex에 로그인되어 있나요?",

        "drop.here": "놓으면 에이전트용 경로를 복사해요",
        "drop.copiedOne": "%@ 경로를 복사했어요 — 에이전트에 붙여넣으세요 (⌘V)",
        "drop.copiedMany": "경로 %ld개를 복사했어요 — 에이전트에 붙여넣으세요 (⌘V)",
        "drop.remoteCantSee": "%@의 에이전트는 이 Mac의 파일을 볼 수 없어요.",
        "drop.willSendOne": "서버 경로를 복사했어요 — 다음 메시지와 함께 파일이 %@(으)로 전송돼요 (⌘V)",
        "drop.willSendMany": "서버 경로를 복사했어요 — 파일 %1$ld개가 다음 메시지와 함께 %2$@(으)로 전송돼요 (⌘V)",
        "drop.delivered": "%1$@에 전달됨: %2$ld개",
        "drop.skippedFolders": "폴더는 아직 보낼 수 없어요.",
        "drop.tooBig": "한 번에 최대 20MB까지.",
        "drop.shelfInFullDenny": "파일 선반과 음악 제어는 정식 Denny에서 →",
        "fullDenny": "할 일, 메모, 오프라인 AI — 정식 Denny →",

        "alerts.menu": "알림",
        "alerts.finish": "작업 완료",
        "alerts.limit": "요금제 한도",
        "alerts.budget": "일일 예산 (API 가격)",
        "alerts.off": "끔",
        "alerts.anyLength": "길이 상관없이",
        "alerts.longerThan": "%ld분 이상",
        "alerts.atPercent": "%ld%%에서",
        "alerts.finishedTitle": "%@ 작업 완료",
        "alerts.finishedBody": "%1$@ · %2$@ 작업",
        "alerts.limitTitle": "%1$@ 한도 %2$ld%%",
        "alerts.budgetTitle": "일일 예산 도달: %@",
        "alerts.budgetBody": "API 정가 기준, 이 Mac과 서버를 합산했어요.",

        "menu.claude": "Claude Code 지켜보기",
        "menu.codex": "Codex 지켜보기",
        "menu.remote": "원격 서버 (SSH)…",
        "menu.fullDenny": "정식 Denny 받기…",
        "menu.quit": "Denny for Agents 종료",
        "remote.title": "SSH 서버의 에이전트 지켜보기",
        "remote.body": "1. 연결된 동안 포트를 전달하세요: Termius에서 Remote 포트 전달 규칙 추가(서버 127.0.0.1:{port} → 이 Mac 127.0.0.1:{port}) 또는 ssh -R {port}:127.0.0.1:{port} user@server 로 연결\n2. 저장소의 remote/denny-hook.py를 서버의 ~/.denny-for-agents/에 넣으세요.\n3. 서버에서 복사한 명령을 실행한 뒤: python3 ~/.denny-for-agents/denny-hook.py --ping",
        "remote.copy": "설치 명령 복사",
        "remote.unavailable": "원격 모드를 시작하지 못했어요: 포트 사용 중.",
        "common.close": "닫기",
        "common.cancel": "취소",
        "connect.title": "Denny를 에이전트에 연결할까요?",
        "connect.body": "Denny가 ~/.claude/settings.json과 ~/.codex/hooks.json에 훅을 추가해요(각 파일 옆에 백업 저장). Denny가 실행 중이 아니면 훅은 아무것도 하지 않으며 에이전트를 막지 않아요.",
        "connect.connect": "연결",
        "connect.later": "나중에",
        "connect.failed": "설정 파일을 변경하지 못했어요"
    ]
}
