extension Translations {
    static let korean: [String: String] = [
        "step.runs": "%@ 실행 중",
        "step.runsCommand": "명령 실행 중",
        "step.reads": "%@ 읽는 중",
        "step.aFile": "파일",
        "step.edits": "%@ 수정 중",
        "step.editsFiles": "파일 수정 중",
        "step.searches": "“%@” 검색 중",
        "step.searchesCode": "코드 검색 중",
        "step.searchesWeb": "웹 검색 중",
        "step.opens": "%@ 여는 중",
        "step.startsHelper": "도우미 에이전트 시작",
        "step.updatesPlan": "계획 업데이트 중",
        "step.uses": "%@ 사용 중",
        "step.working": "작업 중…",
        "step.thinking": "생각 중…",
        "step.waitingForYou": "당신을 기다리는 중",
        "step.done": "완료",

        "title.idle": "모두 조용해요",
        "title.working": "에이전트 작업 중",
        "title.needsYou": "확인이 필요해요",
        "title.limitUsedUp": "%@ 한도 소진",
        "title.limitAlmost": "%@ 한도가 거의 다 찼어요",
        "subtitle.noSessions": "Claude Code나 Codex를 실행하세요 — 제가 지켜볼게요.",
        "subtitle.noHooks": "메뉴 막대에서 Claude Code와 Codex를 연결하세요.",
        "subtitle.serverDown": "에이전트 수신을 시작하지 못했어요.",
        "limit.detailResets": "%1$@, %2$@ 후 초기화",

        "approval.allow": "허용",
        "approval.deny": "거부",
        "approval.askThere": "거기서 묻기",
        "approval.wantsTo": "요청",
        "approval.more": "%ld개 더 대기 중",

        "stats.spending": "지출",
        "stats.apiValue": "API 가격 기준",
        "stats.now": "지금",
        "stats.workingNow": "작업 중",
        "stats.limitsLater": "다음 응답 후에 한도가 표시돼요",
        "stats.updated": "%@ 업데이트",
        "stats.tokens": "%@ 토큰",
        "stats.tokensWord": "토큰",
        "stats.fromCache": "%ld%% 캐시 사용",
        "stats.todayTotal": "오늘 %@",
        "stats.noPrice": "Codex 모델은 공개 가격이 없어요",
        "period.today": "오늘",
        "period.week": "7일",
        "period.month": "30일",
        "window.session": "세션",
        "window.week": "주간",
        "window.limit": "한도",
        "stats.activity": "활동",
        "stats.streak": "%ld일 연속",
        "stats.activeDays": "활동한 날",
        "stats.busiestDay": "가장 바빴던 날",

        "time.daysHours": "%1$ld일 %2$ld시간",
        "time.hoursMinutes": "%1$ld시간 %2$ld분",
        "time.minutes": "%ld분",
        "time.hours": "%ld시간",
        "time.days": "%ld일",
        "time.months": "%ld개월",
        "time.justNow": "방금",
        "time.ago": "%@ 전",

        "resets.line": "초기화: %ld회",
        "resets.expiresIn": "다음 만료까지 %@",
        "resets.use": "초기화 사용",
        "resets.resetting": "초기화 중…",
        "resets.confirmTitle": "지금 Codex 한도를 초기화할까요?",
        "resets.confirmBody": "보유한 초기화 1회를 사용합니다. 세션 및 주간 한도가 즉시 갱신돼요. 남은 횟수: %ld.",
        "resets.outcome.reset": "Codex 한도를 초기화했어요",
        "resets.outcome.nothing": "아직 초기화할 것이 없어요",
        "resets.outcome.noCredit": "남은 초기화가 없어요",
        "resets.outcome.already": "이미 사용한 초기화예요",
        "resets.outcome.failed": "초기화하지 못했어요 — 이 Mac의 Codex에 로그인되어 있나요?",

        "drop.here": "놓으면 에이전트용 경로를 복사해요",
        "drop.copiedOne": "%@ 경로를 복사했어요 — 에이전트에 붙여넣으세요 (⌘V)",
        "drop.copiedMany": "경로 %ld개를 복사했어요 — 에이전트에 붙여넣으세요 (⌘V)",
        "drop.remoteCantSee": "%@의 에이전트는 이 Mac의 파일을 볼 수 없어요.",
        "drop.willSendOne": "서버 경로를 복사했어요 — 다음 메시지와 함께 파일이 %@(으)로 전송돼요 (⌘V)",
        "drop.willSendMany": "서버 경로를 복사했어요 — 파일 %1$ld개가 다음 메시지와 함께 %2$@(으)로 전송돼요 (⌘V)",
        "drop.delivered": "%1$@에 전달됨: %2$ld개",
        "drop.skippedFolders": "폴더는 아직 보낼 수 없어요.",
        "drop.tooBig": "한 번에 최대 20MB까지.",
        "drop.shelfInFullDenny": "파일 선반과 음악 제어는 정식 Denny에서 →",
        "fullDenny": "할 일, 메모, 오프라인 AI — 정식 Denny →",

        "alerts.menu": "알림",
        "alerts.finish": "작업 완료",
        "alerts.limit": "요금제 한도",
        "alerts.budget": "일일 예산 (API 가격)",
        "alerts.off": "끔",
        "alerts.anyLength": "길이 상관없이",
        "alerts.longerThan": "%ld분 이상",
        "alerts.atPercent": "%ld%%에서",
        "alerts.finishedTitle": "%@ 작업 완료",
        "alerts.finishedBody": "%1$@ · %2$@ 작업",
        "alerts.limitTitle": "%1$@ 한도 %2$ld%%",
        "alerts.budgetTitle": "일일 예산 도달: %@",
        "alerts.budgetBody": "API 정가 기준, 이 Mac과 서버를 합산했어요.",

        "menu.claude": "Claude Code 지켜보기",
        "menu.codex": "Codex 지켜보기",
        "menu.remote": "원격 서버 (SSH)…",
        "menu.fullDenny": "정식 Denny 받기…",
        "menu.quit": "Denny for Agents 종료",
        "remote.title": "SSH 서버의 에이전트 지켜보기",
        "remote.body": "1. 연결된 동안 포트를 전달하세요: Termius에서 Remote 포트 전달 규칙 추가(서버 127.0.0.1:{port} → 이 Mac 127.0.0.1:{port}) 또는 ssh -R {port}:127.0.0.1:{port} user@server 로 연결\n2. 저장소의 remote/denny-hook.py를 서버의 ~/.denny-for-agents/에 넣으세요.\n3. 서버에서 복사한 명령을 실행한 뒤: python3 ~/.denny-for-agents/denny-hook.py --ping",
        "remote.copy": "설치 명령 복사",
        "remote.unavailable": "원격 모드를 시작하지 못했어요: 포트 사용 중.",
        "common.close": "닫기",
        "common.cancel": "취소",
        "connect.title": "Denny를 에이전트에 연결할까요?",
        "connect.body": "Denny가 ~/.claude/settings.json과 ~/.codex/hooks.json에 훅을 추가해요(각 파일 옆에 백업 저장). Denny가 실행 중이 아니면 훅은 아무것도 하지 않으며 에이전트를 막지 않아요.",
        "connect.connect": "연결",
        "connect.later": "나중에",
        "connect.failed": "설정 파일을 변경하지 못했어요",

        "value.title": "요금제 가치",
        "value.line": "30일간 API 가격 기준 %@",
        "value.planMonthly": "%1$@ · %2$@/월",
        "stats.trend": "추이",
        "stats.models": "모델",
        "stats.projects": "프로젝트",
        "stats.peak": "최고 %@",
        "card.limits": "한도",
        "alerts.renewedTitle": "%@ 한도가 갱신됐어요",
        "menu.cards": "카드",
        "menu.readout": "카메라 옆",
        "readout.timer": "작업 타이머",
        "readout.limit": "가장 빡빡한 한도",
        "page.overview": "개요",
        "page.stats": "통계",
        "stats.noFresh": "최신 데이터 없음",

        "settings.title": "설정",
        "settings.menu": "설정…",
        "settings.section.agents": "에이전트",
        "settings.section.servers": "서버",
        "settings.section.notch": "노치",
        "settings.section.cards": "카드",
        "settings.section.alerts": "알림",
        "settings.section.language": "언어",
        "settings.section.privacy": "개인정보 보호",
        "settings.section.about": "정보",
        "settings.connected": "연결됨",
        "settings.notConnected": "연결 안 됨",
        "settings.disconnect": "연결 해제",
        "settings.agentsFooter": "Denny는 각 에이전트의 설정 파일에 훅을 추가하고 옆에 백업을 저장해요. Denny가 실행 중이 아니면 훅은 아무것도 하지 않아요.",
        "settings.keepAwake": "에이전트 작업 중에는 Mac 잠자기 막기",
        "settings.keepAwakeFooter": "이 Mac에서 에이전트가 작업할 때만요. 화면은 꺼질 수 있어요.",
        "settings.serversConnected": "연결된 서버",
        "settings.noServers": "아직 서버가 없어요. 아래에서 설정하세요.",
        "settings.lastSeen": "마지막 연결 %@",
        "settings.peeks": "살짝 보이기",
        "settings.peekOnStart": "작업을 보낼 때",
        "settings.peekOnWriting": "에이전트가 코드를 쓰기 시작할 때",
        "settings.peekOnFinish": "에이전트가 끝났을 때",
        "settings.display": "디스플레이",
        "settings.displayAuto": "노치가 있는 디스플레이",
        "settings.fullScreen": "전체 화면 앱 위에도 표시",
        "settings.cardsFooter": "끈 카드는 노치에서 사라져요. 개요에는 한도·지출·지금이, 통계에는 나머지가 있어요.",
        "settings.languageSystem": "시스템과 같게",
        "settings.languageRestart": "새 언어는 다시 시작한 뒤 적용돼요.",
        "settings.restart": "지금 다시 시작",
        "settings.privacyReads": "Denny가 읽는 것",
        "settings.privacyReadsBody": "Claude Code와 Codex 로그의 토큰 수, 모델 이름, 시간, 프로젝트 폴더 이름. ~/.claude.json, Claude 앱, Codex의 요금제 한도. 에이전트가 훅으로 보내는 이벤트.",
        "settings.privacyNever": "Denny가 절대 읽거나 보내지 않는 것",
        "settings.privacyNeverBody": "프롬프트, 답변, 파일 내용. 공개 가격표를 매일 내려받는 것 말고는 아무것도 기기를 떠나지 않아요. 노치에 놓은 파일은 내 서버로만 가요.",
        "settings.removeAll": "에이전트 연결 해제 및 Denny 데이터 지우기",
        "settings.removeAllFooter": "Claude Code와 Codex에서 훅을 제거하고, 기록과 설정이 담긴 ~/.denny-for-agents를 삭제한 뒤 종료해요.",
        "settings.removeAllConfirm": "Denny for Agents가 저장한 모든 것을 지울까요?",
        "settings.version": "버전 %@",
        "settings.about": "노치에 살면서 Claude Code와 Codex를 지켜보는 작은 로봇. Denny의 무료 오픈 부분이에요.",
        "update.check": "업데이트 확인",
        "update.checking": "확인 중…",
        "update.upToDate": "최신 버전입니다",
        "update.available": "%@ 버전을 사용할 수 있습니다",
        "update.install": "업데이트",
        "update.installing": "업데이트 다운로드 중… Denny가 다시 시작됩니다",
        "update.failed": "업데이트하지 못했습니다: %@",
        "update.reason.offline": "GitHub에 연결할 수 없습니다",
        "update.reason.checksum": "파일이 체크섬과 일치하지 않습니다",
        "update.reason.folder": "앱을 교체할 권한이 없습니다 — 응용 프로그램 폴더에 두세요",
        "update.reason.download": "다운로드에 실패했습니다",
        "update.homebrew": "Homebrew로 설치됨 — 실행: brew upgrade denny-for-agents",
        "update.notifyBody": "Denny 설정 → 정보에서 업데이트하세요.",

        "quiet.on": "1시간 조용히",
        "quiet.active": "%@까지 조용히 — 눌러서 해제",
        "quick.refresh": "지금 새로 고침",
        "awake.manual": "수동으로 깨어 있기",
        "awake.duration": "시간 동안",
        "awake.until": "시각까지",
        "awake.indefinite": "끌 때까지",
        "awake.start": "시작",
        "awake.stop": "중지",
        "awake.activeUntil": "%@까지 Mac이 잠들지 않아요",
        "awake.untilOff": "멈출 때까지 Mac이 잠들지 않아요",
        "awake.lid": "덮개를 닫아도 계속 작업",
        "awake.lidWarning": "충전기 연결 시에만 동작해요. 관리자 암호를 한 번 물어 단 하나의 명령(pmset disablesleep)만 허용하고, 작업이 끝나면 스스로 꺼져요. 작동 중인 닫힌 Mac을 가방에 넣지 마세요.",
        "awake.lidNeedsPower": "지금은 배터리 사용 중 — 충전기를 연결하면 켜져요.",

        "risk.safe": "안전해 보여요",
        "risk.caution": "한번 확인해 보세요",
        "risk.danger": "위험",
        "risk.critical": "매우 위험",
        "risk.reason.pipeToShell": "인터넷에서 코드를 내려받아 바로 실행해요.",
        "risk.reason.wipeRoot": "/, 홈 폴더 또는 현재 폴더의 모든 것을 삭제해요.",
        "risk.reason.rawDisk": "디스크에 직접 써요 — 지워질 수 있어요.",
        "risk.reason.format": "디스크를 포맷하거나 지워요.",
        "risk.reason.forkBomb": "포크 폭탄이에요: Mac이 멈춰요.",
        "risk.reason.dropData": "데이터베이스 테이블이나 데이터를 삭제해요.",
        "risk.reason.deleteRecursive": "%@ 폴더를 내용째 삭제해요(휴지통 없이).",
        "risk.reason.forcePush": "서버의 브랜치 기록을 덮어써요.",
        "risk.reason.resetHard": "커밋하지 않은 변경 사항을 모두 버려요.",
        "risk.reason.cleanUntracked": "git이 추적하지 않는 파일을 삭제해요.",
        "risk.reason.sudo": "관리자 권한으로 실행해요(sudo).",
        "risk.reason.permissions": "파일을 모두에게 열거나 소유자를 바꿔요.",
        "risk.reason.killProcess": "실행 중인 프로그램을 강제로 종료해요.",
        "risk.reason.reboot": "컴퓨터를 끄거나 다시 시작해요.",
        "risk.reason.dockerPrune": "Docker 컨테이너, 볼륨 또는 데이터를 삭제해요.",
        "risk.reason.publish": "패키지나 릴리스를 모두에게 공개해요.",
        "risk.reason.secrets": "키, 암호 또는 .env 비밀 정보를 건드려요.",
        "risk.reason.push": "커밋을 서버로 보내요.",
        "risk.reason.deleteFile": "%@을(를) 삭제해요.",
        "risk.reason.install": "인터넷에서 패키지를 설치해요.",
        "risk.reason.network": "네트워크에 접근해요.",
        "risk.reason.gitHistory": "git 기록을 다시 쓰거나 파일 변경을 되돌려요.",
        "risk.reason.sensitiveFile": "민감한 파일을 바꿔요: %@.",
        "risk.reason.externalTool": "외부 도구(MCP 서버)를 사용해요.",

        "load.thisMac": "이 Mac",
        "load.cpu": "CPU",
        "load.cpuLoad": "부하(코어 %ld개)",
        "load.memory": "메모리",
        "load.pressureNormal": "메모리 압력: 정상",
        "load.pressureWarning": "메모리 압력: 높음",
        "load.pressureCritical": "메모리 압력: 위험",
        "load.swap": "스왑 %@",
        "load.uptime": "가동 시간 %@",
        "load.memoryLow": "메모리가 거의 찼어요 — 무거운 빌드가 강제 종료될 수 있어요.",
        "load.noServer": "서버 부하는 연결된 서버의 다음 보고서와 함께 와요.",
        "settings.section.load": "부하",

        "relay.title": "%@ 한도 도달",
        "relay.titleUntil": "%1$@ 한도 도달, %2$@에 갱신",
        "relay.body": "%@에 작업을 넘길까요? 요청 내용과 진행 상황을 메모로 정리할게요.",
        "relay.copy": "%@용 메모 복사",
        "relay.later": "나중에",
        "relay.copied": "메모를 복사했어요 — %@에 붙여넣으세요 (⌘V)",
        "relay.handoff": "%@에 작업 넘기기",
        "relay.note.intro": "%1$@이(가) 시작한 작업을 이어서 해 주세요(%2$@).",
        "relay.note.reasonLimit": "요금제 한도에 도달했어요",
        "relay.note.reasonManual": "당신에게 넘겨요",
        "relay.note.folder": "폴더: %@",
        "relay.note.server": "서버: %@",
        "relay.note.task": "작업:",
        "relay.note.done": "이미 한 일:",
        "relay.note.edited": "수정함: %@",
        "relay.note.ran": "실행함: %@",
        "relay.note.last": "%@의 마지막 메시지:",
        "relay.note.next": "먼저 현재 변경 사항을 확인하고(git status, git diff) 멈춘 곳부터 이어서 해 주세요.",

        "stuck.title": "%@이(가) 제자리를 맴도는 것 같아요",
        "stuck.repeatCommand": "“%2$@”을(를) %1$ld번째 실행 중",
        "stuck.repeatEdit": "%2$@을(를) %1$ld번째 수정 중",
        "stuck.noProgress": "%ld분 동안 작업했지만 바뀐 게 없어요",
        "stuck.setting": "에이전트가 제자리를 맴돌면 알려 주기"
    ]
}
