extension Translations {
    static let portuguese: [String: String] = [
        "step.runs": "Executa %@",
        "step.runsCommand": "Executa um comando",
        "step.reads": "Lê %@",
        "step.aFile": "um arquivo",
        "step.edits": "Edita %@",
        "step.editsFiles": "Edita arquivos",
        "step.searches": "Busca “%@”",
        "step.searchesCode": "Busca no código",
        "step.searchesWeb": "Busca na web",
        "step.opens": "Abre %@",
        "step.startsHelper": "Inicia um agente auxiliar",
        "step.updatesPlan": "Atualiza o plano",
        "step.uses": "Usa %@",
        "step.working": "Trabalhando…",
        "step.thinking": "Pensando…",
        "step.waitingForYou": "Esperando você",
        "step.done": "Pronto",

        "title.idle": "Tudo tranquilo",
        "title.working": "Agentes trabalhando",
        "title.needsYou": "Precisa de você",
        "title.limitUsedUp": "Limite do %@ esgotado",
        "title.limitAlmost": "Limite do %@ quase esgotado",
        "subtitle.noSessions": "Abra o Claude Code ou o Codex — eu fico de olho.",
        "subtitle.noHooks": "Conecte o Claude Code e o Codex pela barra de menus.",
        "subtitle.serverDown": "Não foi possível começar a ouvir os agentes.",
        "limit.detailResets": "%1$@, renova em %2$@",

        "approval.allow": "Permitir",
        "approval.deny": "Negar",
        "approval.askThere": "Perguntar lá",
        "approval.wantsTo": "quer",
        "approval.more": "+%ld aguardando",

        "stats.spending": "Gastos",
        "stats.apiValue": "valor de API",
        "stats.now": "Agora",
        "stats.workingNow": "trabalhando",
        "stats.limitsLater": "Os limites aparecem após a próxima resposta",
        "stats.updated": "Atualizado %@",
        "stats.tokens": "%@ tokens",
        "stats.tokensWord": "tokens",
        "stats.fromCache": "%ld%% do cache",
        "stats.todayTotal": "Hoje %@",
        "stats.noPrice": "Sem preço público para os modelos do Codex",
        "period.today": "Hoje",
        "period.week": "7 dias",
        "period.month": "30 dias",
        "window.session": "Sessão",
        "window.week": "Semana",
        "window.limit": "Limite",
        "stats.activity": "Atividade",
        "stats.streak": "%ld dias seguidos",
        "stats.activeDays": "Dias ativos",
        "stats.busiestDay": "Dia mais ativo",

        "time.daysHours": "%1$ld d %2$ld h",
        "time.hoursMinutes": "%1$ld h %2$ld min",
        "time.minutes": "%ld min",
        "time.hours": "%ld h",
        "time.days": "%ld d",
        "time.months": "%ld meses",
        "time.justNow": "agora mesmo",
        "time.ago": "há %@",

        "resets.line": "Renovações: %ld",
        "resets.expiresIn": "a próxima expira em %@",
        "resets.use": "Usar uma renovação",
        "resets.resetting": "Renovando…",
        "resets.confirmTitle": "Renovar os limites do Codex agora?",
        "resets.confirmBody": "Usa uma renovação guardada: os limites da sessão e da semana se renovam na hora. Restantes: %ld.",
        "resets.outcome.reset": "Limites do Codex renovados",
        "resets.outcome.nothing": "Nada para renovar ainda",
        "resets.outcome.noCredit": "Nenhuma renovação disponível",
        "resets.outcome.already": "Essa renovação já foi usada",
        "resets.outcome.failed": "Não deu certo — o Codex está conectado neste Mac?",

        "drop.here": "Solte — copio o caminho para o seu agente",
        "drop.copiedOne": "Caminho de %@ copiado — cole no seu agente (⌘V)",
        "drop.copiedMany": "%ld caminhos copiados — cole no seu agente (⌘V)",
        "drop.remoteCantSee": "O agente em %@ não vê arquivos deste Mac.",
        "drop.willSendOne": "Caminho do servidor copiado — o arquivo vai para %@ com sua próxima mensagem (⌘V)",
        "drop.willSendMany": "Caminhos do servidor copiados — %1$ld arquivos vão para %2$@ com sua próxima mensagem (⌘V)",
        "drop.delivered": "Entregue em %1$@: %2$ld",
        "drop.skippedFolders": "Pastas ainda não são enviadas.",
        "drop.tooBig": "Até 20 MB por envio.",
        "drop.shelfInFullDenny": "Prateleira de arquivos e controle de música — no Denny completo →",
        "fullDenny": "Tarefas, notas e IA offline — Denny completo →",

        "alerts.menu": "Notificações",
        "alerts.finish": "Tarefa concluída",
        "alerts.limit": "Limite do plano",
        "alerts.budget": "Orçamento diário (preços de API)",
        "alerts.off": "Desligado",
        "alerts.anyLength": "Qualquer duração",
        "alerts.longerThan": "Mais de %ld min",
        "alerts.atPercent": "Em %ld%%",
        "alerts.finishedTitle": "%@ terminou",
        "alerts.finishedBody": "%1$@ · trabalhou %2$@",
        "alerts.limitTitle": "Limite do %1$@ em %2$ld%%",
        "alerts.budgetTitle": "Orçamento diário atingido: %@",
        "alerts.budgetBody": "Pelos preços de tabela da API, neste Mac e nos seus servidores.",

        "menu.claude": "Acompanhar o Claude Code",
        "menu.codex": "Acompanhar o Codex",
        "menu.remote": "Servidor remoto (SSH)…",
        "menu.fullDenny": "Obter o Denny completo…",
        "menu.quit": "Sair do Denny for Agents",
        "remote.title": "Acompanhar agentes em um servidor SSH",
        "remote.body": "1. Redirecione a porta enquanto estiver conectado: no Termius, adicione uma regra de encaminhamento Remote (servidor 127.0.0.1:{port} → este Mac 127.0.0.1:{port}), ou conecte com ssh -R {port}:127.0.0.1:{port} user@server\n2. Coloque remote/denny-hook.py do repositório em ~/.denny-for-agents/ no servidor.\n3. No servidor, rode o comando copiado e depois: python3 ~/.denny-for-agents/denny-hook.py --ping",
        "remote.copy": "Copiar comando de instalação",
        "remote.unavailable": "O modo remoto não iniciou: porta ocupada.",
        "common.close": "Fechar",
        "common.cancel": "Cancelar",
        "connect.title": "Conectar o Denny aos seus agentes?",
        "connect.body": "O Denny vai adicionar hooks em ~/.claude/settings.json e ~/.codex/hooks.json (um backup fica salvo ao lado). Se o Denny não estiver aberto, os hooks não fazem nada e nunca bloqueiam seus agentes.",
        "connect.connect": "Conectar",
        "connect.later": "Depois",
        "connect.failed": "Não foi possível alterar o arquivo de configurações"
    ]
}
