extension Translations {
    static let portuguese: [String: String] = [
        "step.runs": "Executa %@",
        "step.runsCommand": "Executa um comando",
        "step.reads": "Lê %@",
        "step.aFile": "um arquivo",
        "step.edits": "Edita %@",
        "step.editsFiles": "Edita arquivos",
        "step.searches": "Busca “%@”",
        "step.searchesCode": "Busca no código",
        "step.searchesWeb": "Busca na web",
        "step.opens": "Abre %@",
        "step.startsHelper": "Inicia um agente auxiliar",
        "step.updatesPlan": "Atualiza o plano",
        "step.uses": "Usa %@",
        "step.working": "Trabalhando…",
        "step.thinking": "Pensando…",
        "step.waitingForYou": "Esperando você",
        "step.done": "Pronto",

        "title.idle": "Tudo tranquilo",
        "title.working": "Agentes trabalhando",
        "title.needsYou": "Precisa de você",
        "title.limitUsedUp": "Limite do %@ esgotado",
        "title.limitAlmost": "Limite do %@ quase esgotado",
        "subtitle.noSessions": "Abra o Claude Code ou o Codex — eu fico de olho.",
        "subtitle.noHooks": "Conecte o Claude Code e o Codex pela barra de menus.",
        "subtitle.serverDown": "Não foi possível começar a ouvir os agentes.",
        "limit.detailResets": "%1$@, renova em %2$@",

        "approval.allow": "Permitir",
        "approval.deny": "Negar",
        "approval.askThere": "Perguntar lá",
        "approval.wantsTo": "quer",
        "approval.more": "+%ld aguardando",

        "stats.spending": "Gastos",
        "stats.apiValue": "valor de API",
        "stats.now": "Agora",
        "stats.workingNow": "trabalhando",
        "stats.limitsLater": "Os limites aparecem após a próxima resposta",
        "stats.updated": "Atualizado %@",
        "stats.tokens": "%@ tokens",
        "stats.tokensWord": "tokens",
        "stats.fromCache": "%ld%% do cache",
        "stats.todayTotal": "Hoje %@",
        "stats.noPrice": "Sem preço público para os modelos do Codex",
        "period.today": "Hoje",
        "period.week": "7 dias",
        "period.month": "30 dias",
        "window.session": "Sessão",
        "window.week": "Semana",
        "window.limit": "Limite",
        "stats.activity": "Atividade",
        "stats.streak": "%ld dias seguidos",
        "stats.activeDays": "Dias ativos",
        "stats.busiestDay": "Dia mais ativo",

        "time.daysHours": "%1$ld d %2$ld h",
        "time.hoursMinutes": "%1$ld h %2$ld min",
        "time.minutes": "%ld min",
        "time.hours": "%ld h",
        "time.days": "%ld d",
        "time.months": "%ld meses",
        "time.justNow": "agora mesmo",
        "time.ago": "há %@",

        "resets.line": "Renovações: %ld",
        "resets.expiresIn": "a próxima expira em %@",
        "resets.use": "Usar uma renovação",
        "resets.resetting": "Renovando…",
        "resets.confirmTitle": "Renovar os limites do Codex agora?",
        "resets.confirmBody": "Usa uma renovação guardada: os limites da sessão e da semana se renovam na hora. Restantes: %ld.",
        "resets.outcome.reset": "Limites do Codex renovados",
        "resets.outcome.nothing": "Nada para renovar ainda",
        "resets.outcome.noCredit": "Nenhuma renovação disponível",
        "resets.outcome.already": "Essa renovação já foi usada",
        "resets.outcome.failed": "Não deu certo — o Codex está conectado neste Mac?",

        "drop.here": "Solte — copio o caminho para o seu agente",
        "drop.copiedOne": "Caminho de %@ copiado — cole no seu agente (⌘V)",
        "drop.copiedMany": "%ld caminhos copiados — cole no seu agente (⌘V)",
        "drop.remoteCantSee": "O agente em %@ não vê arquivos deste Mac.",
        "drop.willSendOne": "Caminho do servidor copiado — o arquivo vai para %@ com sua próxima mensagem (⌘V)",
        "drop.willSendMany": "Caminhos do servidor copiados — %1$ld arquivos vão para %2$@ com sua próxima mensagem (⌘V)",
        "drop.delivered": "Entregue em %1$@: %2$ld",
        "drop.skippedFolders": "Pastas ainda não são enviadas.",
        "drop.tooBig": "Até 20 MB por envio.",
        "drop.shelfInFullDenny": "Prateleira de arquivos e controle de música — no Denny completo →",
        "fullDenny": "Tarefas, notas e IA offline — Denny completo →",

        "alerts.menu": "Notificações",
        "alerts.finish": "Tarefa concluída",
        "alerts.limit": "Limite do plano",
        "alerts.budget": "Orçamento diário (preços de API)",
        "alerts.off": "Desligado",
        "alerts.anyLength": "Qualquer duração",
        "alerts.longerThan": "Mais de %ld min",
        "alerts.atPercent": "Em %ld%%",
        "alerts.finishedTitle": "%@ terminou",
        "alerts.finishedBody": "%1$@ · trabalhou %2$@",
        "alerts.limitTitle": "Limite do %1$@ em %2$ld%%",
        "alerts.budgetTitle": "Orçamento diário atingido: %@",
        "alerts.budgetBody": "Pelos preços de tabela da API, neste Mac e nos seus servidores.",

        "menu.claude": "Acompanhar o Claude Code",
        "menu.codex": "Acompanhar o Codex",
        "menu.remote": "Servidor remoto (SSH)…",
        "menu.fullDenny": "Obter o Denny completo…",
        "menu.quit": "Sair do Denny for Agents",
        "remote.title": "Acompanhar agentes em um servidor SSH",
        "remote.body": "1. Redirecione a porta enquanto estiver conectado: no Termius, adicione uma regra de encaminhamento Remote (servidor 127.0.0.1:{port} → este Mac 127.0.0.1:{port}), ou conecte com ssh -R {port}:127.0.0.1:{port} user@server\n2. Coloque remote/denny-hook.py do repositório em ~/.denny-for-agents/ no servidor.\n3. No servidor, rode o comando copiado e depois: python3 ~/.denny-for-agents/denny-hook.py --ping",
        "remote.copy": "Copiar comando de instalação",
        "remote.unavailable": "O modo remoto não iniciou: porta ocupada.",
        "common.close": "Fechar",
        "common.cancel": "Cancelar",
        "connect.title": "Conectar o Denny aos seus agentes?",
        "connect.body": "O Denny vai adicionar hooks em ~/.claude/settings.json e ~/.codex/hooks.json (um backup fica salvo ao lado). Se o Denny não estiver aberto, os hooks não fazem nada e nunca bloqueiam seus agentes.",
        "connect.connect": "Conectar",
        "connect.later": "Depois",
        "connect.failed": "Não foi possível alterar o arquivo de configurações",

        "value.title": "Valor do plano",
        "value.line": "%@ em preços de API em 30 dias",
        "value.planMonthly": "%1$@ · %2$@/mês",
        "stats.trend": "Tendência",
        "stats.models": "Modelos",
        "stats.projects": "Projetos",
        "stats.peak": "pico %@",
        "card.limits": "Limites",
        "alerts.renewedTitle": "Limite do %@ renovado",
        "menu.cards": "Cartões",
        "menu.readout": "Ao lado da câmera",
        "readout.timer": "Cronômetro da tarefa",
        "readout.limit": "Limite mais apertado",
        "page.overview": "Visão geral",
        "page.stats": "Estatísticas",
        "stats.noFresh": "Sem dados recentes",

        "settings.title": "Ajustes",
        "settings.menu": "Ajustes…",
        "settings.section.agents": "Agentes",
        "settings.section.servers": "Servidores",
        "settings.section.notch": "Notch",
        "settings.section.cards": "Cartões",
        "settings.section.alerts": "Notificações",
        "settings.section.language": "Idioma",
        "settings.section.privacy": "Privacidade",
        "settings.section.about": "Sobre",
        "settings.connected": "Conectado",
        "settings.notConnected": "Não conectado",
        "settings.disconnect": "Desconectar",
        "settings.agentsFooter": "O Denny adiciona seus hooks ao arquivo de configurações de cada agente e salva um backup ao lado. Se o Denny não estiver aberto, os hooks não fazem nada.",
        "settings.keepAwake": "Manter o Mac acordado enquanto os agentes trabalham",
        "settings.keepAwakeFooter": "Só enquanto um agente trabalha neste Mac. A tela ainda pode apagar.",
        "settings.serversConnected": "Servidores conectados",
        "settings.noServers": "Nenhum servidor ainda. Configure um abaixo.",
        "settings.lastSeen": "visto %@",
        "settings.noContact": "sem contato %@",
        "ssh.title": "Conexões do Denny",
        "ssh.body": "O Denny se conecta por SSH sozinho e mantém o link: depois do repouso, de uma troca de rede ou de reconectar a VPN, ele reconecta sozinho. Usa as chaves SSH e o ~/.ssh/config deste Mac — sem precisar do Termius.",
        "ssh.placeholder": "root@servidor ou um nome do ~/.ssh/config",
        "ssh.add": "Adicionar",
        "ssh.invalid": "Use user@host ou um nome do ~/.ssh/config (para outra porta, adicione no ~/.ssh/config).",
        "ssh.connecting": "Conectando…",
        "ssh.connected": "conectado %@",
        "ssh.retry": "nova tentativa em %@",
        "ssh.connectAgents": "Conectar agentes",
        "ssh.connectAgentsHelp": "Colocar o hook do Denny no servidor e conectar lá o Claude Code e o Codex",
        "ssh.installing": "Conectando…",
        "ssh.agentsConnected": "Agentes conectados. Reinicie o Claude Code / Codex no servidor.",
        "ssh.installFailed": "Não foi possível conectar os agentes: %@",
        "ssh.needsKey": "Sem chave SSH para este servidor",
        "ssh.keyHint": "Este Mac precisa de uma chave SSH que o servidor aceite. Execute no Terminal do Mac (o segundo comando pede a senha do servidor uma vez):",
        "ssh.copyCommands": "Copiar comandos",
        "ssh.hostKeyChanged": "A chave do servidor mudou — confira e corrija o ~/.ssh/known_hosts",
        "ssh.unreachable": "Servidor inacessível",
        "ssh.portBusy": "Porta ainda ocupada no servidor, tentando a próxima",
        "ssh.noPython": "python3 não está instalado no servidor",
        "ssh.dropped": "Conexão caiu",
        "ssh.remove": "Remover",
        "ssh.removeAndUnhook": "Remover e desconectar os agentes do servidor",
        "ssh.removeQuestion": "Remover este servidor?",
        "settings.peeks": "Aparições",
        "settings.peekOnStart": "Quando você envia uma tarefa",
        "settings.peekOnWriting": "Quando o agente começa a escrever código",
        "settings.peekOnFinish": "Quando o agente termina",
        "settings.display": "Tela",
        "settings.displayAuto": "A que tem notch",
        "settings.fullScreen": "Mostrar sobre apps em tela cheia",
        "settings.cardsFooter": "Cartões desativados somem do notch. Visão geral tem limites, gastos e Agora; Estatísticas tem o resto.",
        "settings.languageSystem": "Igual ao sistema",
        "settings.languageRestart": "O novo idioma vale após reiniciar.",
        "settings.restart": "Reiniciar agora",
        "settings.privacyReads": "O que o Denny lê",
        "settings.privacyReadsBody": "Contagem de tokens, nomes de modelos, horários e nomes de pastas de projeto dos logs do Claude Code e do Codex; limites do plano de ~/.claude.json, do app Claude e do Codex; os eventos que seus agentes enviam aos hooks.",
        "settings.privacyNever": "O que o Denny nunca lê nem envia",
        "settings.privacyNeverBody": "Seus prompts, respostas e conteúdo de arquivos. Nada sai das suas máquinas, exceto o download diário da lista pública de preços. Arquivos soltos no notch vão só para o seu servidor.",
        "settings.removeAll": "Desconectar agentes e apagar os dados do Denny",
        "settings.removeAllFooter": "Remove os hooks do Claude Code e do Codex, apaga ~/.denny-for-agents com histórico e configurações e fecha o app.",
        "settings.removeAllConfirm": "Apagar tudo o que o Denny for Agents salvou?",
        "settings.version": "Versão %@",
        "settings.about": "Um pequeno robô no seu notch que fica de olho no Claude Code e no Codex. A parte gratuita e aberta do Denny.",
        "tests.onServer": "Roda em %@",
        "tests.noneOnServer": "Nenhum teste encontrado no servidor",
        "server.jobWaits": "%@: a tarefa espera o servidor — começa assim que um agente fizer algo lá (ou em segundos se houver um rodando)",
        "night.where": "Onde",
        "night.thisMac": "Este Mac",
        "night.serverFolder": "Pasta no servidor, ex. ~/projects/shop",
        "settings.section.nightShift": "Turno da noite",
        "night.newJob": "Nova tarefa para depois",
        "night.agent": "Agente",
        "night.noFolder": "Nenhuma pasta escolhida",
        "night.chooseFolder": "Escolher…",
        "night.when": "Iniciar",
        "night.whenRenews": "Quando o limite renovar",
        "night.whenAt": "Num horário definido",
        "night.queue": "Colocar na fila",
        "night.queueTitle": "Fila",
        "night.waitsUntil": "espera até %@",
        "night.waitsForLimit": "espera o limite",
        "night.running": "rodando %@",
        "night.doneAt": "pronto às %@",
        "night.failedShort": "falhou: %@",
        "night.footer": "Neste Mac (o Denny não deixa dormir) ou num servidor (lá a tarefa continua mesmo se a sessão SSH cair; o resultado chega quando você reconectar). À noite ninguém aprova nada, então o Denny é cuidadoso: edições de arquivos e comandos seguros seguem; o que o guarda considera perigoso é negado. A rede de segurança continua salvando, e o Telegram avisa quando terminar. Para uma tarefa no servidor, a mensagem do Telegram chega quando o Mac voltar a se conectar a esse servidor.",
        "night.interrupted": "interrompido por uma reinicialização",
        "night.started": "%1$@ começou a tarefa da noite em %2$@",
        "night.done": "%1$@ terminou a tarefa da noite em %2$@ — o recibo espera no notch",
        "night.failed": "%1$@ não conseguiu terminar a tarefa da noite em %2$@: %3$@",
        "settings.section.phone": "Telefone",
        "phone.title": "Permissões no celular",
        "phone.steps": "1. No Telegram abra o @BotFather e envie /newbot.\n2. Escolha um nome — o BotFather manda um token.\n3. Cole o token aqui.",
        "phone.tokenPlaceholder": "Token do bot",
        "phone.check": "Verificar",
        "phone.badToken": "Este token não funciona — copie de novo do @BotFather.",
        "phone.sendCode": "Envie este código para @%@:",
        "phone.openBot": "Abrir o bot",
        "phone.topicHint": "Quer os pedidos num tópico ou grupo específico? Envie o código lá mesmo — o Denny vai escrever só nesse tópico, e só você poderá apertar os botões.",
        "phone.waiting": "Esperando o código…",
        "phone.connected": "Conectado a %1$@ via @%2$@",
        "phone.whenAway": "Quando eu não estiver no Mac",
        "phone.always": "Sempre",
        "phone.finished": "Avisar também quando uma tarefa terminar",
        "phone.test": "Enviar teste",
        "phone.testText": "Aqui é o Denny 👋 Os pedidos dos seus agentes chegarão neste chat.",
        "phone.disconnect": "Desconectar",
        "phone.footer": "Os pedidos passam pelos servidores do Telegram, incluindo o texto do comando. O bot só obedece ao chat que mandou o código. Ausente = 2 minutos sem mouse nem teclado.",
        "phone.paired": "O Denny está conectado 🎉 Quando um agente pedir permissão e você não estiver no Mac, o pedido chega aqui.",
        "phone.request": "%1$@ · %2$@ quer:",
        "phone.allow": "✅ Permitir",
        "phone.deny": "❌ Negar",
        "phone.allowed": "✅ Permitido",
        "phone.denied": "❌ Negado",
        "phone.expired": "⌛ Sem resposta aqui — o agente pergunta no terminal dele.",
        "review.button": "Revisar com %@",
        "review.running": "%1$@ está revisando… %2$@",
        "review.clean": "✅ %@ não encontrou problemas",
        "review.findings": "%1$@ encontrou problemas: %2$ld",
        "review.send": "Enviar ao %@",
        "review.copied": "Copiado — cole para o %@ (⌘V)",
        "review.failed": "%1$@ não conseguiu revisar: %2$@",
        "review.noChanges": "sem mudanças para revisar",
        "review.notFound": "não encontrado neste Mac",
        "review.agentMessage": "%1$@ revisou suas mudanças e encontrou:\n\n%2$@\n\nConfira esses pontos e corrija o que fizer sentido.",
        "tests.run": "Rodar testes",
        "tests.running": "Testes rodando… %@",
        "tests.passed": "✅ Testes passaram · %@",
        "tests.failed": "❌ Testes falharam · %@",
        "tests.sendToAgent": "Enviar ao agente",
        "tests.copied": "Copiado — cole para o agente (⌘V)",
        "tests.agentMessage": "Os testes falham depois das suas mudanças (`%1$@`). Aqui está o fim da saída — corrija, por favor:\n\n%2$@",
        "tests.autoSetting": "Rodar os testes do projeto após cada tarefa",
        "tests.autoFooter": "Neste Mac e nos servidores. O Denny acha o comando sozinho (swift test, npm test, cargo test, pytest…); coloque o seu num arquivo .denny-test na raiz do projeto.",
        "tests.timedOut": "Parado após 10 minutos.",
        "receipt.title": "Recibo da tarefa",
        "receipt.files": "Arquivos: %ld",
        "receipt.lines": "+%1$ld −%2$ld",
        "receipt.commands": "Comandos: %ld",
        "receipt.tokens": "Tokens: %@",
        "receipt.cost": "%@ a preços da API",
        "receipt.copy": "Copiar",
        "receipt.copied": "Recibo copiado",
        "receipt.hide": "Ocultar",
        "receipt.signature": "via Denny for Agents",
        "settings.section.safetyNet": "Rede de segurança",
        "safety.peekTitle": "Arquivos salvos antes de um comando arriscado",
        "safety.cardTitle": "Rede de segurança",
        "safety.cardBody": "Os arquivos foram salvos logo antes deste comando. Desfazer os traz de volta.",
        "safety.onServer": "Salvo em %@ — a restauração roda lá",
        "safety.undo": "Desfazer…",
        "safety.copyCommand": "Copiar comando para o servidor",
        "safety.hide": "Ocultar",
        "safety.confirmTitle": "Devolver os arquivos como estavam antes de “%@”?",
        "safety.confirmBody": "%ld arquivo(s) vão voltar. Alterações feitas depois do backup serão perdidas; arquivos novos ficam.",
        "safety.confirmRestore": "Devolver",
        "safety.nothing": "Nada a devolver — os arquivos batem com o backup.",
        "safety.restored": "Os arquivos voltaram",
        "safety.failed": "Não foi possível devolver os arquivos",
        "safety.commandCopied": "Comando copiado — rode no servidor",
        "safety.empty": "Ainda não há backups. Logo antes de um agente rodar rm, git reset --hard ou parecido, o Denny salva seus arquivos aqui.",
        "safety.footer": "Até 50 backups. Num projeto git ficam numa ref oculta e nunca mexem na sua branch, índice ou stash.",
        "safety.storage": "Armazenamento",
        "safety.keepFor": "Guardar backups",
        "safety.keep.1": "1 dia",
        "safety.keep.7": "7 dias",
        "safety.keep.30": "30 dias",
        "safety.limit": "Espaço para cópias",
        "safety.gb": "%ld GB",
        "safety.used": "Cópias neste Mac: %@",
        "safety.clear": "Apagar todos os backups…",
        "safety.clearConfirm": "Apagar todos os backups deste Mac?",
        "safety.clearBody": "Os arquivos deles não poderão ser devolvidos depois.",
        "safety.delete": "Apagar",
        "safety.limitFooter": "Só contam cópias de arquivos fora do git — os backups do git ficam dentro do projeto e quase não ocupam espaço. Quando o espaço acaba, os mais antigos saem primeiro. Os servidores recebem estes ajustes com sua próxima mensagem ao agente.",
        "update.check": "Procurar atualizações",
        "update.checking": "Procurando…",
        "update.upToDate": "Você tem a versão mais recente",
        "update.available": "A versão %@ está disponível",
        "update.install": "Atualizar",
        "update.installing": "Baixando a atualização… Denny vai reiniciar",
        "update.failed": "Não foi possível atualizar: %@",
        "update.reason.offline": "não dá para acessar o GitHub",
        "update.reason.checksum": "o arquivo não confere com o checksum",
        "update.reason.folder": "sem permissão para substituir o app — mantenha-o em Aplicativos",
        "update.reason.download": "o download falhou",
        "update.homebrew": "Instalado com Homebrew — rode: brew upgrade denny-for-agents",
        "update.notifyBody": "Abra os ajustes do Denny → Sobre para atualizar.",

        "quiet.on": "Silêncio por uma hora",
        "quiet.active": "Silêncio até %@ — toque para encerrar",
        "quick.refresh": "Atualizar agora",
        "awake.manual": "Manter acordado manualmente",
        "awake.duration": "Por",
        "awake.until": "Até",
        "awake.indefinite": "Até eu desligar",
        "awake.start": "Iniciar",
        "awake.stop": "Parar",
        "awake.activeUntil": "O Mac fica acordado até %@",
        "awake.untilOff": "O Mac fica acordado até você parar",
        "awake.lid": "Continuar com a tampa fechada",
        "awake.lidWarning": "Só no carregador. Pede a senha de administrador uma vez para permitir um único comando (pmset disablesleep) e desliga sozinho quando o trabalho termina. Não guarde na mochila um Mac fechado e ligado.",
        "awake.lidNeedsPower": "Na bateria agora — liga quando você conectar o carregador.",

        "risk.safe": "Parece seguro",
        "risk.caution": "Vale uma olhada",
        "risk.danger": "Perigoso",
        "risk.critical": "Muito perigoso",
        "risk.reason.pipeToShell": "Baixa código da internet e executa na hora.",
        "risk.reason.wipeRoot": "Apaga tudo em /, na sua pasta pessoal ou na pasta atual.",
        "risk.reason.rawDisk": "Escreve direto em um disco — pode apagá-lo.",
        "risk.reason.format": "Formata ou apaga um disco.",
        "risk.reason.forkBomb": "Uma fork bomb: o Mac vai travar.",
        "risk.reason.dropData": "Apaga tabelas ou dados do banco.",
        "risk.reason.deleteRecursive": "Apaga a pasta %@ com tudo dentro, sem Lixeira.",
        "risk.reason.forcePush": "Sobrescreve o histórico do branch no servidor.",
        "risk.reason.resetHard": "Descarta todas as mudanças sem commit.",
        "risk.reason.cleanUntracked": "Apaga arquivos que o git não acompanha.",
        "risk.reason.sudo": "Roda como administrador (sudo).",
        "risk.reason.permissions": "Abre arquivos para todos ou muda o dono.",
        "risk.reason.killProcess": "Força o encerramento de programas.",
        "risk.reason.reboot": "Desliga ou reinicia o computador.",
        "risk.reason.dockerPrune": "Apaga contêineres, volumes ou dados do Docker.",
        "risk.reason.publish": "Publica um pacote ou release para todos.",
        "risk.reason.secrets": "Mexe em chaves, senhas ou segredos .env.",
        "risk.reason.push": "Envia commits para o servidor.",
        "risk.reason.deleteFile": "Apaga %@.",
        "risk.reason.install": "Instala pacotes da internet.",
        "risk.reason.network": "Acessa a rede.",
        "risk.reason.gitHistory": "Reescreve o histórico do git ou descarta mudanças.",
        "risk.reason.sensitiveFile": "Altera um arquivo sensível: %@.",
        "risk.reason.externalTool": "Usa uma ferramenta externa (servidor MCP).",

        "load.thisMac": "Este Mac",
        "load.cpu": "CPU",
        "load.cpuLoad": "Carga (%ld núcleos)",
        "load.memory": "Memória",
        "load.pressureNormal": "Pressão de memória: normal",
        "load.pressureWarning": "Pressão de memória: alta",
        "load.pressureCritical": "Pressão de memória: crítica",
        "load.swap": "Swap %@",
        "load.uptime": "Ligado há %@",
        "load.memoryLow": "Memória quase cheia — um build pesado pode ser encerrado.",
        "load.noServer": "A carga do servidor chega com o próximo relatório de um servidor conectado.",
        "settings.section.load": "Carga",

        "relay.title": "%@ chegou ao limite",
        "relay.titleUntil": "%1$@ chegou ao limite até %2$@",
        "relay.body": "Passar a tarefa para o %@? Eu escrevo uma nota com o pedido e o que já foi feito.",
        "relay.copy": "Copiar nota para o %@",
        "relay.later": "Agora não",
        "relay.copied": "Nota copiada — cole no %@ (⌘V)",
        "relay.handoff": "Passar a tarefa para o %@",
        "relay.note.intro": "Continue uma tarefa que o %1$@ começou (%2$@).",
        "relay.note.reasonLimit": "ele chegou ao limite do plano",
        "relay.note.reasonManual": "estou passando para você",
        "relay.note.folder": "Pasta: %@",
        "relay.note.server": "Servidor: %@",
        "relay.note.task": "A tarefa:",
        "relay.note.done": "Já feito:",
        "relay.note.edited": "editou: %@",
        "relay.note.ran": "rodou: %@",
        "relay.note.last": "Última mensagem do %@:",
        "relay.note.next": "Primeiro veja as mudanças atuais (git status, git diff) e depois continue de onde parou.",

        "stuck.title": "O %@ parece estar andando em círculos",
        "stuck.repeatCommand": "Rodando “%2$@” pela %1$ldª vez",
        "stuck.repeatEdit": "Editando %2$@ pela %1$ldª vez",
        "stuck.noProgress": "%ld min de trabalho sem nenhuma mudança",
        "stuck.setting": "Avisar quando um agente anda em círculos"
    ]
}
