extension Translations {
    static let portuguese: [String: String] = [
        "step.runs": "Executa %@",
        "step.runsCommand": "Executa um comando",
        "step.reads": "Lê %@",
        "step.aFile": "um arquivo",
        "step.edits": "Edita %@",
        "step.editsFiles": "Edita arquivos",
        "step.searches": "Busca “%@”",
        "step.searchesCode": "Busca no código",
        "step.searchesWeb": "Busca na web",
        "step.opens": "Abre %@",
        "step.startsHelper": "Inicia um agente auxiliar",
        "step.updatesPlan": "Atualiza o plano",
        "step.uses": "Usa %@",
        "step.working": "Trabalhando…",
        "step.thinking": "Pensando…",
        "step.waitingForYou": "Esperando você",
        "step.done": "Pronto",

        "title.idle": "Tudo tranquilo",
        "title.working": "Agentes trabalhando",
        "title.needsYou": "Precisa de você",
        "title.limitUsedUp": "Limite do %@ esgotado",
        "title.limitAlmost": "Limite do %@ quase esgotado",
        "subtitle.noSessions": "Abra o Claude Code ou o Codex — eu fico de olho.",
        "subtitle.noHooks": "Conecte o Claude Code e o Codex pela barra de menus.",
        "subtitle.serverDown": "Não foi possível começar a ouvir os agentes.",
        "limit.detailResets": "%1$@, renova em %2$@",

        "approval.allow": "Permitir",
        "approval.deny": "Negar",
        "approval.askThere": "Perguntar lá",
        "approval.wantsTo": "quer",
        "approval.more": "+%ld aguardando",

        "stats.spending": "Gastos",
        "stats.apiValue": "valor de API",
        "stats.now": "Agora",
        "stats.workingNow": "trabalhando",
        "stats.limitsLater": "Os limites aparecem após a próxima resposta",
        "stats.updated": "Atualizado %@",
        "stats.tokens": "%@ tokens",
        "stats.tokensWord": "tokens",
        "stats.fromCache": "%ld%% do cache",
        "stats.todayTotal": "Hoje %@",
        "stats.noPrice": "Sem preço público para os modelos do Codex",
        "period.today": "Hoje",
        "period.week": "7 dias",
        "period.month": "30 dias",
        "window.session": "Sessão",
        "window.week": "Semana",
        "window.limit": "Limite",
        "stats.activity": "Atividade",
        "stats.streak": "%ld dias seguidos",
        "stats.activeDays": "Dias ativos",
        "stats.busiestDay": "Dia mais ativo",

        "time.daysHours": "%1$ld d %2$ld h",
        "time.hoursMinutes": "%1$ld h %2$ld min",
        "time.minutes": "%ld min",
        "time.hours": "%ld h",
        "time.days": "%ld d",
        "time.months": "%ld meses",
        "time.justNow": "agora mesmo",
        "time.ago": "há %@",

        "resets.line": "Renovações: %ld",
        "resets.expiresIn": "a próxima expira em %@",
        "resets.use": "Usar uma renovação",
        "resets.resetting": "Renovando…",
        "resets.confirmTitle": "Renovar os limites do Codex agora?",
        "resets.confirmBody": "Usa uma renovação guardada: os limites da sessão e da semana se renovam na hora. Restantes: %ld.",
        "resets.outcome.reset": "Limites do Codex renovados",
        "resets.outcome.nothing": "Nada para renovar ainda",
        "resets.outcome.noCredit": "Nenhuma renovação disponível",
        "resets.outcome.already": "Essa renovação já foi usada",
        "resets.outcome.failed": "Não deu certo — o Codex está conectado neste Mac?",

        "drop.here": "Solte — copio o caminho para o seu agente",
        "drop.copiedOne": "Caminho de %@ copiado — cole no seu agente (⌘V)",
        "drop.copiedMany": "%ld caminhos copiados — cole no seu agente (⌘V)",
        "drop.remoteCantSee": "O agente em %@ não vê arquivos deste Mac.",
        "drop.willSendOne": "Caminho do servidor copiado — o arquivo vai para %@ com sua próxima mensagem (⌘V)",
        "drop.willSendMany": "Caminhos do servidor copiados — %1$ld arquivos vão para %2$@ com sua próxima mensagem (⌘V)",
        "drop.delivered": "Entregue em %1$@: %2$ld",
        "drop.skippedFolders": "Pastas ainda não são enviadas.",
        "drop.tooBig": "Até 20 MB por envio.",
        "drop.shelfInFullDenny": "Prateleira de arquivos e controle de música — no Denny completo →",
        "fullDenny": "Tarefas, notas e IA offline — Denny completo →",

        "alerts.menu": "Notificações",
        "alerts.finish": "Tarefa concluída",
        "alerts.limit": "Limite do plano",
        "alerts.budget": "Orçamento diário (preços de API)",
        "alerts.off": "Desligado",
        "alerts.anyLength": "Qualquer duração",
        "alerts.longerThan": "Mais de %ld min",
        "alerts.atPercent": "Em %ld%%",
        "alerts.finishedTitle": "%@ terminou",
        "alerts.finishedBody": "%1$@ · trabalhou %2$@",
        "alerts.limitTitle": "Limite do %1$@ em %2$ld%%",
        "alerts.budgetTitle": "Orçamento diário atingido: %@",
        "alerts.budgetBody": "Pelos preços de tabela da API, neste Mac e nos seus servidores.",

        "menu.claude": "Acompanhar o Claude Code",
        "menu.codex": "Acompanhar o Codex",
        "menu.remote": "Servidor remoto (SSH)…",
        "menu.fullDenny": "Obter o Denny completo…",
        "menu.quit": "Sair do Denny for Agents",
        "remote.title": "Acompanhar agentes em um servidor SSH",
        "remote.body": "1. Redirecione a porta enquanto estiver conectado: no Termius, adicione uma regra de encaminhamento Remote (servidor 127.0.0.1:{port} → este Mac 127.0.0.1:{port}), ou conecte com ssh -R {port}:127.0.0.1:{port} user@server\n2. Coloque remote/denny-hook.py do repositório em ~/.denny-for-agents/ no servidor.\n3. No servidor, rode o comando copiado e depois: python3 ~/.denny-for-agents/denny-hook.py --ping",
        "remote.copy": "Copiar comando de instalação",
        "remote.unavailable": "O modo remoto não iniciou: porta ocupada.",
        "common.close": "Fechar",
        "common.cancel": "Cancelar",
        "connect.title": "Conectar o Denny aos seus agentes?",
        "connect.body": "O Denny vai adicionar hooks em ~/.claude/settings.json e ~/.codex/hooks.json (um backup fica salvo ao lado). Se o Denny não estiver aberto, os hooks não fazem nada e nunca bloqueiam seus agentes.",
        "connect.connect": "Conectar",
        "connect.later": "Depois",
        "connect.failed": "Não foi possível alterar o arquivo de configurações",

        "value.title": "Valor do plano",
        "value.line": "%@ em preços de API em 30 dias",
        "value.planMonthly": "%1$@ · %2$@/mês",
        "stats.trend": "Tendência",
        "stats.models": "Modelos",
        "stats.projects": "Projetos",
        "stats.peak": "pico %@",
        "card.limits": "Limites",
        "alerts.renewedTitle": "Limite do %@ renovado",
        "menu.cards": "Cartões",
        "menu.readout": "Ao lado da câmera",
        "readout.timer": "Cronômetro da tarefa",
        "readout.limit": "Limite mais apertado",
        "page.overview": "Visão geral",
        "page.stats": "Estatísticas",
        "stats.noFresh": "Sem dados recentes",

        "settings.title": "Ajustes",
        "settings.menu": "Ajustes…",
        "settings.section.agents": "Agentes",
        "settings.section.servers": "Servidores",
        "settings.section.notch": "Notch",
        "settings.section.cards": "Cartões",
        "settings.section.alerts": "Notificações",
        "settings.section.language": "Idioma",
        "settings.section.privacy": "Privacidade",
        "settings.section.about": "Sobre",
        "settings.connected": "Conectado",
        "settings.notConnected": "Não conectado",
        "settings.disconnect": "Desconectar",
        "settings.agentsFooter": "O Denny adiciona seus hooks ao arquivo de configurações de cada agente e salva um backup ao lado. Se o Denny não estiver aberto, os hooks não fazem nada.",
        "settings.keepAwake": "Manter o Mac acordado enquanto os agentes trabalham",
        "settings.keepAwakeFooter": "Só enquanto um agente trabalha neste Mac. A tela ainda pode apagar.",
        "settings.serversConnected": "Servidores conectados",
        "settings.noServers": "Nenhum servidor ainda. Configure um abaixo.",
        "settings.lastSeen": "visto %@",
        "settings.peeks": "Aparições",
        "settings.peekOnStart": "Quando você envia uma tarefa",
        "settings.peekOnWriting": "Quando o agente começa a escrever código",
        "settings.peekOnFinish": "Quando o agente termina",
        "settings.display": "Tela",
        "settings.displayAuto": "A que tem notch",
        "settings.fullScreen": "Mostrar sobre apps em tela cheia",
        "settings.cardsFooter": "Cartões desativados somem do notch. Visão geral tem limites, gastos e Agora; Estatísticas tem o resto.",
        "settings.languageSystem": "Igual ao sistema",
        "settings.languageRestart": "O novo idioma vale após reiniciar.",
        "settings.restart": "Reiniciar agora",
        "settings.privacyReads": "O que o Denny lê",
        "settings.privacyReadsBody": "Contagem de tokens, nomes de modelos, horários e nomes de pastas de projeto dos logs do Claude Code e do Codex; limites do plano de ~/.claude.json, do app Claude e do Codex; os eventos que seus agentes enviam aos hooks.",
        "settings.privacyNever": "O que o Denny nunca lê nem envia",
        "settings.privacyNeverBody": "Seus prompts, respostas e conteúdo de arquivos. Nada sai das suas máquinas, exceto o download diário da lista pública de preços. Arquivos soltos no notch vão só para o seu servidor.",
        "settings.removeAll": "Desconectar agentes e apagar os dados do Denny",
        "settings.removeAllFooter": "Remove os hooks do Claude Code e do Codex, apaga ~/.denny-for-agents com histórico e configurações e fecha o app.",
        "settings.removeAllConfirm": "Apagar tudo o que o Denny for Agents salvou?",
        "settings.version": "Versão %@",
        "settings.about": "Um pequeno robô no seu notch que fica de olho no Claude Code e no Codex. A parte gratuita e aberta do Denny.",

        "quiet.on": "Silêncio por uma hora",
        "quiet.active": "Silêncio até %@ — toque para encerrar",
        "quick.refresh": "Atualizar agora",
        "awake.manual": "Manter acordado manualmente",
        "awake.duration": "Por",
        "awake.until": "Até",
        "awake.indefinite": "Até eu desligar",
        "awake.start": "Iniciar",
        "awake.stop": "Parar",
        "awake.activeUntil": "O Mac fica acordado até %@",
        "awake.untilOff": "O Mac fica acordado até você parar",
        "awake.lid": "Continuar com a tampa fechada",
        "awake.lidWarning": "Só no carregador. Pede a senha de administrador uma vez para permitir um único comando (pmset disablesleep) e desliga sozinho quando o trabalho termina. Não guarde na mochila um Mac fechado e ligado.",
        "awake.lidNeedsPower": "Na bateria agora — liga quando você conectar o carregador.",

        "risk.safe": "Parece seguro",
        "risk.caution": "Vale uma olhada",
        "risk.danger": "Perigoso",
        "risk.critical": "Muito perigoso",
        "risk.reason.pipeToShell": "Baixa código da internet e executa na hora.",
        "risk.reason.wipeRoot": "Apaga tudo em /, na sua pasta pessoal ou na pasta atual.",
        "risk.reason.rawDisk": "Escreve direto em um disco — pode apagá-lo.",
        "risk.reason.format": "Formata ou apaga um disco.",
        "risk.reason.forkBomb": "Uma fork bomb: o Mac vai travar.",
        "risk.reason.dropData": "Apaga tabelas ou dados do banco.",
        "risk.reason.deleteRecursive": "Apaga a pasta %@ com tudo dentro, sem Lixeira.",
        "risk.reason.forcePush": "Sobrescreve o histórico do branch no servidor.",
        "risk.reason.resetHard": "Descarta todas as mudanças sem commit.",
        "risk.reason.cleanUntracked": "Apaga arquivos que o git não acompanha.",
        "risk.reason.sudo": "Roda como administrador (sudo).",
        "risk.reason.permissions": "Abre arquivos para todos ou muda o dono.",
        "risk.reason.killProcess": "Força o encerramento de programas.",
        "risk.reason.reboot": "Desliga ou reinicia o computador.",
        "risk.reason.dockerPrune": "Apaga contêineres, volumes ou dados do Docker.",
        "risk.reason.publish": "Publica um pacote ou release para todos.",
        "risk.reason.secrets": "Mexe em chaves, senhas ou segredos .env.",
        "risk.reason.push": "Envia commits para o servidor.",
        "risk.reason.deleteFile": "Apaga %@.",
        "risk.reason.install": "Instala pacotes da internet.",
        "risk.reason.network": "Acessa a rede.",
        "risk.reason.gitHistory": "Reescreve o histórico do git ou descarta mudanças.",
        "risk.reason.sensitiveFile": "Altera um arquivo sensível: %@.",
        "risk.reason.externalTool": "Usa uma ferramenta externa (servidor MCP).",

        "load.thisMac": "Este Mac",
        "load.cpu": "CPU",
        "load.cpuLoad": "Carga (%ld núcleos)",
        "load.memory": "Memória",
        "load.pressureNormal": "Pressão de memória: normal",
        "load.pressureWarning": "Pressão de memória: alta",
        "load.pressureCritical": "Pressão de memória: crítica",
        "load.swap": "Swap %@",
        "load.uptime": "Ligado há %@",
        "load.memoryLow": "Memória quase cheia — um build pesado pode ser encerrado.",
        "load.noServer": "A carga do servidor chega com o próximo relatório de um servidor conectado.",
        "settings.section.load": "Carga",

        "relay.title": "%@ chegou ao limite",
        "relay.titleUntil": "%1$@ chegou ao limite até %2$@",
        "relay.body": "Passar a tarefa para o %@? Eu escrevo uma nota com o pedido e o que já foi feito.",
        "relay.copy": "Copiar nota para o %@",
        "relay.later": "Agora não",
        "relay.copied": "Nota copiada — cole no %@ (⌘V)",
        "relay.handoff": "Passar a tarefa para o %@",
        "relay.note.intro": "Continue uma tarefa que o %1$@ começou (%2$@).",
        "relay.note.reasonLimit": "ele chegou ao limite do plano",
        "relay.note.reasonManual": "estou passando para você",
        "relay.note.folder": "Pasta: %@",
        "relay.note.server": "Servidor: %@",
        "relay.note.task": "A tarefa:",
        "relay.note.done": "Já feito:",
        "relay.note.edited": "editou: %@",
        "relay.note.ran": "rodou: %@",
        "relay.note.last": "Última mensagem do %@:",
        "relay.note.next": "Primeiro veja as mudanças atuais (git status, git diff) e depois continue de onde parou.",

        "stuck.title": "O %@ parece estar andando em círculos",
        "stuck.repeatCommand": "Rodando “%2$@” pela %1$ldª vez",
        "stuck.repeatEdit": "Editando %2$@ pela %1$ldª vez",
        "stuck.noProgress": "%ld min de trabalho sem nenhuma mudança",
        "stuck.setting": "Avisar quando um agente anda em círculos"
    ]
}
