extension Translations {
    static let russian: [String: String] = [
        "step.runs": "Запускает %@",
        "step.runsCommand": "Запускает команду",
        "step.reads": "Читает %@",
        "step.aFile": "файл",
        "step.edits": "Правит %@",
        "step.editsFiles": "Правит файлы",
        "step.searches": "Ищет «%@»",
        "step.searchesCode": "Ищет в коде",
        "step.searchesWeb": "Ищет в интернете",
        "step.opens": "Открывает %@",
        "step.startsHelper": "Запускает помощника",
        "step.updatesPlan": "Обновляет план",
        "step.uses": "Использует %@",
        "step.working": "Работает…",
        "step.thinking": "Думает…",
        "step.waitingForYou": "Ждёт тебя",
        "step.done": "Готово",

        "title.idle": "Всё спокойно",
        "title.working": "Агенты работают",
        "title.needsYou": "Нужен ты",
        "title.limitUsedUp": "Лимит %@ исчерпан",
        "title.limitAlmost": "Лимит %@ почти закончился",
        "subtitle.noSessions": "Запусти Claude Code или Codex — я присмотрю.",
        "subtitle.noHooks": "Подключи Claude Code и Codex в строке меню.",
        "subtitle.serverDown": "Не получилось начать слушать агентов.",
        "limit.detailResets": "%1$@, сброс через %2$@",

        "approval.allow": "Разрешить",
        "approval.deny": "Запретить",
        "approval.askThere": "Спросить там",
        "approval.wantsTo": "хочет",
        "approval.more": "Ещё ждут: %ld",

        "stats.spending": "Расходы",
        "stats.apiValue": "по ценам API",
        "stats.now": "Сейчас",
        "stats.workingNow": "работает",
        "stats.limitsLater": "Лимиты появятся после следующего ответа",
        "stats.updated": "Обновлено: %@",
        "stats.tokens": "%@ токенов",
        "stats.tokensWord": "токенов",
        "stats.fromCache": "%ld%% из кэша",
        "stats.todayTotal": "Сегодня %@",
        "stats.noPrice": "Цены Codex неизвестны",
        "period.today": "Сегодня",
        "period.week": "7 дней",
        "period.month": "30 дней",
        "window.session": "Сессия",
        "window.week": "Неделя",
        "window.limit": "Лимит",
        "stats.activity": "Активность",
        "stats.streak": "%ld дн. подряд",
        "stats.activeDays": "Активных дней",
        "stats.busiestDay": "Самый активный день",

        "time.daysHours": "%1$ld д %2$ld ч",
        "time.hoursMinutes": "%1$ld ч %2$ld мин",
        "time.minutes": "%ld мин",
        "time.hours": "%ld ч",
        "time.days": "%ld д",
        "time.months": "%ld мес.",
        "time.justNow": "только что",
        "time.ago": "%@ назад",

        "resets.line": "Сбросы: %ld",
        "resets.expiresIn": "ближайший сгорит через %@",
        "resets.use": "Использовать сброс",
        "resets.resetting": "Сбрасываю…",
        "resets.confirmTitle": "Сбросить лимиты Codex сейчас?",
        "resets.confirmBody": "Потратится один запасной сброс: лимиты сессии и недели обновятся сразу. Сбросов осталось: %ld.",
        "resets.outcome.reset": "Лимиты Codex сброшены",
        "resets.outcome.nothing": "Сбрасывать пока нечего",
        "resets.outcome.noCredit": "Запасных сбросов нет",
        "resets.outcome.already": "Этот сброс уже использован",
        "resets.outcome.failed": "Не получилось — Codex на этом Mac вошёл в аккаунт?",

        "drop.here": "Отпусти — скопирую путь для агента",
        "drop.copiedOne": "Путь к %@ скопирован — вставь агенту (⌘V)",
        "drop.copiedMany": "Скопировано путей: %ld — вставь агенту (⌘V)",
        "drop.remoteCantSee": "Агент на %@ не увидит файл с этого Mac.",
        "drop.willSendOne": "Путь на сервере скопирован — файл уйдёт на %@ с твоим следующим сообщением (⌘V)",
        "drop.willSendMany": "Пути на сервере скопированы — файлов: %1$ld, уйдут на %2$@ с твоим следующим сообщением (⌘V)",
        "drop.delivered": "Доставлено на %1$@: %2$ld",
        "drop.skippedFolders": "Папки пока не пересылаются.",
        "drop.tooBig": "За раз можно до 20 МБ.",
        "drop.shelfInFullDenny": "Полка для файлов и музыка — в полном Денни →",
        "fullDenny": "Задачи, заметки и офлайн-ИИ — полный Денни →",

        "alerts.menu": "Уведомления",
        "alerts.finish": "Задача готова",
        "alerts.limit": "Лимит тарифа",
        "alerts.budget": "Дневной бюджет по ценам API",
        "alerts.off": "Выкл.",
        "alerts.anyLength": "Любой длины",
        "alerts.longerThan": "Дольше %ld мин",
        "alerts.atPercent": "При %ld%%",
        "alerts.finishedTitle": "%@ закончил",
        "alerts.finishedBody": "%1$@ · работал %2$@",
        "alerts.limitTitle": "Лимит %1$@: %2$ld%%",
        "alerts.budgetTitle": "Дневной бюджет превышен: %@",
        "alerts.budgetBody": "По ценам API, вместе с серверами.",

        "menu.claude": "Следить за Claude Code",
        "menu.codex": "Следить за Codex",
        "menu.remote": "Удалённый сервер (SSH)…",
        "menu.fullDenny": "Полный Денни…",
        "menu.quit": "Выйти из Denny for Agents",
        "remote.title": "Следить за агентами на сервере (SSH)",
        "remote.body": "1. Перешли порт на время подключения: в Termius добавь правило Remote (сервер 127.0.0.1:{port} → этот Mac 127.0.0.1:{port}) или подключайся так: ssh -R {port}:127.0.0.1:{port} user@server\n2. Положи remote/denny-hook.py из репозитория на сервер в ~/.denny-for-agents/.\n3. На сервере выполни скопированную команду, затем: python3 ~/.denny-for-agents/denny-hook.py --ping",
        "remote.copy": "Скопировать команду",
        "remote.unavailable": "Удалённый режим не запустился: порт занят.",
        "common.close": "Закрыть",
        "common.cancel": "Отмена",
        "connect.title": "Подключить Денни к агентам?",
        "connect.body": "Денни добавит хуки в ~/.claude/settings.json и ~/.codex/hooks.json (рядом сохранится резервная копия). Если Денни не запущен, хуки ничего не делают и никогда не мешают агентам.",
        "connect.connect": "Подключить",
        "connect.later": "Позже",
        "connect.failed": "Не получилось изменить файл настроек",

        "value.title": "Выгода тарифа",
        "value.line": "%@ по ценам API за 30 дней",
        "value.planMonthly": "%1$@ · %2$@/мес",
        "stats.trend": "Динамика",
        "stats.models": "Модели",
        "stats.projects": "Проекты",
        "stats.peak": "пик %@",
        "card.limits": "Лимиты",
        "alerts.renewedTitle": "Лимит %@ обновился",
        "menu.cards": "Карточки",
        "menu.readout": "У камеры",
        "readout.timer": "Таймер задачи",
        "readout.limit": "Самый полный лимит",
        "page.overview": "Обзор",
        "page.stats": "Статистика",
        "stats.noFresh": "Нет свежих данных",

        "settings.title": "Настройки",
        "settings.menu": "Настройки…",
        "settings.section.agents": "Агенты",
        "settings.section.servers": "Серверы",
        "settings.section.notch": "Вырез",
        "settings.section.cards": "Карточки",
        "settings.section.alerts": "Уведомления",
        "settings.section.language": "Язык",
        "settings.section.privacy": "Конфиденциальность",
        "settings.section.about": "О программе",
        "settings.connected": "Подключён",
        "settings.notConnected": "Не подключён",
        "settings.disconnect": "Отключить",
        "settings.agentsFooter": "Денни добавляет свои хуки в файл настроек каждого агента и сохраняет рядом резервную копию. Если Денни не запущен, хуки ничего не делают.",
        "settings.keepAwake": "Не давать Mac засыпать, пока агенты работают",
        "settings.keepAwakeFooter": "Только пока работает агент на этом Mac. Экран при этом может гаснуть.",
        "settings.serversConnected": "Подключённые серверы",
        "settings.noServers": "Серверов пока нет. Подключи сервер ниже.",
        "settings.lastSeen": "на связи %@",
        "settings.noContact": "нет связи %@",
        "ssh.title": "Подключения Денни",
        "ssh.body": "Денни сам подключается по SSH и держит связь: после сна, смены сети или переподключения VPN переподключается сам. Использует SSH-ключи и ~/.ssh/config этого Mac — Termius не нужен.",
        "ssh.placeholder": "root@сервер или имя из ~/.ssh/config",
        "ssh.add": "Добавить",
        "ssh.invalid": "Нужно user@host или имя из ~/.ssh/config (другой порт укажи в ~/.ssh/config).",
        "ssh.connecting": "Подключаюсь…",
        "ssh.connected": "на связи %@",
        "ssh.retry": "повтор через %@",
        "ssh.connectAgents": "Подключить агентов",
        "ssh.connectAgentsHelp": "Поставить хук Денни на сервер и подключить там Claude Code и Codex",
        "ssh.installing": "Подключаю…",
        "ssh.agentsConnected": "Агенты подключены. Перезапусти Claude Code / Codex на сервере.",
        "ssh.installFailed": "Не удалось подключить агентов: %@",
        "ssh.needsKey": "Нет SSH-ключа к этому серверу",
        "ssh.keyHint": "Этому Mac нужен SSH-ключ, который примет сервер. Выполни в Терминале на Mac (вторая команда один раз спросит пароль сервера):",
        "ssh.copyCommands": "Скопировать команды",
        "ssh.hostKeyChanged": "Ключ сервера изменился — проверь его и поправь ~/.ssh/known_hosts",
        "ssh.unreachable": "Сервер недоступен",
        "ssh.portBusy": "Порт на сервере ещё занят, пробую следующий",
        "ssh.noPython": "На сервере не установлен python3",
        "ssh.dropped": "Связь оборвалась",
        "ssh.remove": "Убрать",
        "ssh.removeAndUnhook": "Убрать и отключить агентов на сервере",
        "ssh.removeQuestion": "Убрать этот сервер?",
        "settings.peeks": "Выглядывание",
        "settings.peekOnStart": "Когда отправляешь задачу",
        "settings.peekOnWriting": "Когда агент начинает писать код",
        "settings.peekOnFinish": "Когда агент закончил",
        "settings.display": "Монитор",
        "settings.displayAuto": "Тот, где есть вырез",
        "settings.fullScreen": "Показывать поверх полноэкранных приложений",
        "settings.cardsFooter": "Выключенные карточки пропадают из выреза. В «Обзоре» — лимиты, расходы и «Сейчас», в «Статистике» — остальное.",
        "settings.languageSystem": "Как в системе",
        "settings.languageRestart": "Новый язык применится после перезапуска.",
        "settings.restart": "Перезапустить",
        "settings.privacyReads": "Что читает Денни",
        "settings.privacyReadsBody": "Число токенов, названия моделей, время и названия папок проектов из журналов Claude Code и Codex; лимиты тарифа из ~/.claude.json, приложения Claude и Codex; события, которые агенты передают хукам.",
        "settings.privacyNever": "Что Денни никогда не читает и не отправляет",
        "settings.privacyNeverBody": "Твои запросы, ответы и содержимое файлов. С твоих машин ничего не уходит, кроме ежедневной загрузки публичного списка цен. Файлы, брошенные на вырез, уходят только на твой сервер.",
        "settings.removeAll": "Отключить агентов и стереть данные Денни",
        "settings.removeAllFooter": "Уберёт хуки из Claude Code и Codex, удалит ~/.denny-for-agents с историей и настройками и закроет приложение.",
        "settings.removeAllConfirm": "Стереть всё, что сохранил Denny for Agents?",
        "settings.version": "Версия %@",
        "settings.about": "Маленький робот в вырезе, который присматривает за Claude Code и Codex. Бесплатная открытая часть Денни.",
        "tests.onServer": "Запустится на %@",
        "tests.noneOnServer": "На сервере тесты не найдены",
        "server.jobWaits": "%@: задача ждёт сервер — начнётся, как только агент там что-нибудь сделает (или через пару секунд, если он работает)",
        "night.where": "Где",
        "night.thisMac": "Этот Mac",
        "night.serverFolder": "Папка на сервере, например ~/projects/shop",
        "settings.section.nightShift": "Ночная смена",
        "night.newJob": "Новая задача на потом",
        "night.agent": "Агент",
        "night.noFolder": "Папка не выбрана",
        "night.chooseFolder": "Выбрать…",
        "night.when": "Запустить",
        "night.whenRenews": "Когда обновится лимит",
        "night.whenAt": "В заданное время",
        "night.queue": "Поставить в очередь",
        "night.queueTitle": "Очередь",
        "night.waitsUntil": "ждёт до %@",
        "night.waitsForLimit": "ждёт обновления лимита",
        "night.running": "идёт %@",
        "night.doneAt": "готово в %@",
        "night.failedShort": "не вышло: %@",
        "night.footer": "На этом Mac (Денни не даст ему уснуть) или на сервере (там задача идёт, даже если SSH-сессия оборвётся; результат придёт, когда снова подключишься). Ночью некому нажимать «Разрешить», поэтому Денни осторожен: правка файлов и безопасные команды идут сами, всё, что охранник считает опасным, запрещается. Страховочная сетка делает снимки, а Telegram сообщит, когда готово. О задаче на сервере Telegram сообщит, когда Mac снова будет на связи с этим сервером.",
        "night.interrupted": "прервано перезапуском",
        "night.started": "%1$@ начал ночную задачу в %2$@",
        "night.done": "%1$@ закончил ночную задачу в %2$@ — чек ждёт в вырезе",
        "night.failed": "%1$@ не смог закончить ночную задачу в %2$@: %3$@",
        "settings.section.phone": "Телефон",
        "phone.title": "Разрешения с телефона",
        "phone.steps": "1. В Telegram открой @BotFather и отправь /newbot.\n2. Придумай имя — BotFather пришлёт токен.\n3. Вставь токен сюда.",
        "phone.tokenPlaceholder": "Токен бота",
        "phone.check": "Проверить",
        "phone.badToken": "Этот токен не подходит — скопируй его ещё раз у @BotFather.",
        "phone.sendCode": "Отправь этот код боту @%@:",
        "phone.openBot": "Открыть бота",
        "phone.topicHint": "Хочешь получать запросы в определённой теме или группе? Отправь код прямо туда — Денни будет писать только в эту тему, а нажимать кнопки сможешь только ты.",
        "phone.waiting": "Жду код…",
        "phone.connected": "Подключено к %1$@ через @%2$@",
        "phone.whenAway": "Когда я не за Mac",
        "phone.always": "Всегда",
        "phone.finished": "Ещё сообщать, когда задача готова",
        "phone.test": "Отправить тест",
        "phone.testText": "Это Денни 👋 Сюда будут приходить запросы твоих агентов.",
        "phone.disconnect": "Отключить",
        "phone.footer": "Запросы идут через серверы Telegram, включая текст команды. Бот слушается только чат, который прислал код. «Не за Mac» — 2 минуты без мыши и клавиатуры.",
        "phone.paired": "Денни подключён 🎉 Когда агент попросит разрешения, а тебя не будет за Mac, запрос придёт сюда.",
        "phone.request": "%1$@ · %2$@ хочет:",
        "phone.allow": "✅ Разрешить",
        "phone.deny": "❌ Запретить",
        "phone.allowed": "✅ Разрешено",
        "phone.denied": "❌ Запрещено",
        "phone.expired": "⌛ Здесь не ответили — агент спрашивает у себя в терминале.",
        "review.button": "Проверить у %@",
        "review.running": "%1$@ проверяет… %2$@",
        "review.clean": "✅ %@ не нашёл проблем",
        "review.findings": "%1$@ нашёл замечаний: %2$ld",
        "review.send": "Отправить %@",
        "review.copied": "Скопировано — вставь %@ (⌘V)",
        "review.failed": "%1$@ не смог проверить: %2$@",
        "review.noChanges": "нет изменений для проверки",
        "review.notFound": "не найден на этом Mac",
        "review.agentMessage": "%1$@ проверил твои изменения и нашёл:\n\n%2$@\n\nПроверь эти замечания и исправь то, что по делу.",
        "tests.run": "Запустить тесты",
        "tests.running": "Тесты идут… %@",
        "tests.passed": "✅ Тесты прошли · %@",
        "tests.failed": "❌ Тесты упали · %@",
        "tests.sendToAgent": "Отправить агенту",
        "tests.copied": "Скопировано — вставь агенту (⌘V)",
        "tests.agentMessage": "После твоих изменений падают тесты (`%1$@`). Вот конец вывода — почини, пожалуйста:\n\n%2$@",
        "tests.autoSetting": "Запускать тесты проекта после каждой задачи",
        "tests.autoFooter": "На этом Mac и на серверах. Команду Денни находит сам (swift test, npm test, cargo test, pytest…); свою можно записать в файл .denny-test в корне проекта.",
        "tests.timedOut": "Остановлено через 10 минут.",
        "receipt.title": "Чек задачи",
        "receipt.files": "Файлов: %ld",
        "receipt.lines": "+%1$ld −%2$ld",
        "receipt.commands": "Команд: %ld",
        "receipt.tokens": "Токенов: %@",
        "receipt.cost": "%@ по ценам API",
        "receipt.copy": "Скопировать",
        "receipt.copied": "Чек скопирован",
        "receipt.hide": "Скрыть",
        "receipt.signature": "через Denny for Agents",
        "settings.section.safetyNet": "Страховка",
        "safety.peekTitle": "Сохранил файлы перед опасной командой",
        "safety.cardTitle": "Страховочная сетка",
        "safety.cardBody": "Перед этой командой я сохранил файлы. «Отменить» вернёт их как было.",
        "safety.onServer": "Снимок на %@ — откат запускается там",
        "safety.undo": "Отменить…",
        "safety.copyCommand": "Скопировать команду для сервера",
        "safety.hide": "Скрыть",
        "safety.confirmTitle": "Вернуть файлы как было перед «%@»?",
        "safety.confirmBody": "Вернётся файлов: %ld. Изменения в них после снимка пропадут, новые файлы останутся.",
        "safety.confirmRestore": "Вернуть",
        "safety.nothing": "Возвращать нечего — файлы такие же, как в снимке.",
        "safety.restored": "Файлы вернулись",
        "safety.failed": "Не удалось вернуть файлы",
        "safety.commandCopied": "Команда скопирована — выполни её на сервере",
        "safety.empty": "Снимков пока нет. Прямо перед тем, как агент запустит rm, git reset --hard и подобное, Денни сохранит здесь твои файлы.",
        "safety.footer": "До 50 снимков. В git-проекте лежат в скрытой ссылке и не трогают твою ветку, индекс и stash.",
        "safety.storage": "Хранение",
        "safety.keepFor": "Хранить снимки",
        "safety.keep.1": "1 день",
        "safety.keep.7": "7 дней",
        "safety.keep.30": "30 дней",
        "safety.limit": "Место для копий",
        "safety.gb": "%ld ГБ",
        "safety.used": "Копии на этом Mac: %@",
        "safety.clear": "Удалить все снимки…",
        "safety.clearConfirm": "Удалить все снимки на этом Mac?",
        "safety.clearBody": "Файлы из них потом не вернуть.",
        "safety.delete": "Удалить",
        "safety.limitFooter": "Считаются только копии файлов вне git — снимки git лежат внутри проекта и почти не занимают места. Когда место кончается, первыми удаляются самые старые снимки. Серверы получат эти настройки с твоим следующим сообщением агенту.",
        "update.check": "Проверить обновления",
        "update.checking": "Проверяю…",
        "update.upToDate": "У тебя последняя версия",
        "update.available": "Доступна версия %@",
        "update.install": "Обновить",
        "update.installing": "Скачиваю обновление… Денни перезапустится",
        "update.failed": "Не удалось обновить: %@",
        "update.reason.offline": "не получается связаться с GitHub",
        "update.reason.checksum": "файл не совпадает с контрольной суммой",
        "update.reason.folder": "нет прав заменить приложение — держи его в «Программах»",
        "update.reason.download": "не удалось скачать",
        "update.homebrew": "Установлено через Homebrew — выполни: brew upgrade denny-for-agents",
        "update.notifyBody": "Открой настройки Денни → «О программе», чтобы обновить.",

        "quiet.on": "Тишина на час",
        "quiet.active": "Тишина до %@ — нажми, чтобы снять",
        "quick.refresh": "Обновить данные",
        "awake.manual": "Не спать вручную",
        "awake.duration": "На время",
        "awake.until": "До времени",
        "awake.indefinite": "Пока не выключу",
        "awake.start": "Начать",
        "awake.stop": "Остановить",
        "awake.activeUntil": "Mac не уснёт до %@",
        "awake.untilOff": "Mac не уснёт, пока не остановишь",
        "awake.lid": "Работать с закрытой крышкой",
        "awake.lidWarning": "Только на зарядке. Один раз спросит пароль администратора, чтобы разрешить ровно одну команду (pmset disablesleep), и сам выключится, когда работа закончена. Не убирай работающий закрытый Mac в сумку.",
        "awake.lidNeedsPower": "Сейчас от батареи — включится, когда подключишь зарядку.",

        "risk.safe": "Выглядит безопасно",
        "risk.caution": "Стоит взглянуть",
        "risk.danger": "Опасно",
        "risk.critical": "Очень опасно",
        "risk.reason.pipeToShell": "Скачает код из интернета и сразу его запустит.",
        "risk.reason.wipeRoot": "Удалит всё в /, в домашней папке или в текущей папке.",
        "risk.reason.rawDisk": "Пишет прямо на диск — может его стереть.",
        "risk.reason.format": "Форматирует или стирает диск.",
        "risk.reason.forkBomb": "Форк-бомба: Mac зависнет.",
        "risk.reason.dropData": "Удалит таблицы или данные в базе.",
        "risk.reason.deleteRecursive": "Удалит папку %@ со всем содержимым, без Корзины.",
        "risk.reason.forcePush": "Перезапишет историю ветки на сервере.",
        "risk.reason.resetHard": "Выбросит все незакоммиченные изменения.",
        "risk.reason.cleanUntracked": "Удалит файлы, которые не отслеживает git.",
        "risk.reason.sudo": "Запуск от имени администратора (sudo).",
        "risk.reason.permissions": "Откроет файлы для всех или сменит их владельца.",
        "risk.reason.killProcess": "Принудительно остановит программы.",
        "risk.reason.reboot": "Выключит или перезагрузит компьютер.",
        "risk.reason.dockerPrune": "Удалит контейнеры, тома или данные Docker.",
        "risk.reason.publish": "Опубликует пакет или релиз для всех.",
        "risk.reason.secrets": "Трогает ключи, пароли или секреты .env.",
        "risk.reason.push": "Отправит коммиты на сервер.",
        "risk.reason.deleteFile": "Удалит %@.",
        "risk.reason.install": "Установит пакеты из интернета.",
        "risk.reason.network": "Обращается к сети.",
        "risk.reason.gitHistory": "Перепишет историю git или откатит изменения файлов.",
        "risk.reason.sensitiveFile": "Меняет важный файл: %@.",
        "risk.reason.externalTool": "Использует внешний инструмент (MCP-сервер).",

        "load.thisMac": "Этот Mac",
        "load.cpu": "Процессор",
        "load.cpuLoad": "Нагрузка (ядер: %ld)",
        "load.memory": "Память",
        "load.pressureNormal": "Давление памяти: в норме",
        "load.pressureWarning": "Давление памяти: высокое",
        "load.pressureCritical": "Давление памяти: критическое",
        "load.swap": "Swap %@",
        "load.uptime": "Работает без перезагрузки %@",
        "load.memoryLow": "Память почти кончилась — тяжёлую сборку может убить.",
        "load.noServer": "Нагрузка сервера придёт со следующим отчётом подключённого сервера.",
        "settings.section.load": "Нагрузка",

        "relay.title": "%@ упёрся в лимит",
        "relay.titleUntil": "%1$@ упёрся в лимит до %2$@",
        "relay.body": "Передать задачу %@? Я напишу записку: что просили и что уже сделано.",
        "relay.copy": "Скопировать записку для %@",
        "relay.later": "Не сейчас",
        "relay.copied": "Записка скопирована — вставь её в %@ (⌘V)",
        "relay.handoff": "Передать задачу %@",
        "relay.note.intro": "Продолжи задачу, которую начал %1$@ (%2$@).",
        "relay.note.reasonLimit": "он упёрся в лимит тарифа",
        "relay.note.reasonManual": "передаю её тебе",
        "relay.note.folder": "Папка: %@",
        "relay.note.server": "Сервер: %@",
        "relay.note.task": "Задача:",
        "relay.note.done": "Что уже сделано:",
        "relay.note.edited": "правил: %@",
        "relay.note.ran": "запускал: %@",
        "relay.note.last": "Последнее сообщение %@:",
        "relay.note.next": "Сначала посмотри текущие изменения (git status, git diff), потом продолжай с того места, где остановились.",

        "stuck.title": "%@, кажется, ходит по кругу",
        "stuck.repeatCommand": "В %1$ld-й раз запускает «%2$@»",
        "stuck.repeatEdit": "Правит %2$@ уже %1$ld-й раз",
        "stuck.noProgress": "%ld мин работает и ничего не меняет",
        "stuck.setting": "Предупреждать, когда агент ходит по кругу"
    ]
}
