extension Translations {
    static let russian: [String: String] = [
        "step.runs": "Запускает %@",
        "step.runsCommand": "Запускает команду",
        "step.reads": "Читает %@",
        "step.aFile": "файл",
        "step.edits": "Правит %@",
        "step.editsFiles": "Правит файлы",
        "step.searches": "Ищет «%@»",
        "step.searchesCode": "Ищет в коде",
        "step.searchesWeb": "Ищет в интернете",
        "step.opens": "Открывает %@",
        "step.startsHelper": "Запускает помощника",
        "step.updatesPlan": "Обновляет план",
        "step.uses": "Использует %@",
        "step.working": "Работает…",
        "step.thinking": "Думает…",
        "step.waitingForYou": "Ждёт тебя",
        "step.done": "Готово",

        "title.idle": "Всё спокойно",
        "title.working": "Агенты работают",
        "title.needsYou": "Нужен ты",
        "title.limitUsedUp": "Лимит %@ исчерпан",
        "title.limitAlmost": "Лимит %@ почти закончился",
        "subtitle.noSessions": "Запусти Claude Code или Codex — я присмотрю.",
        "subtitle.noHooks": "Подключи Claude Code и Codex в строке меню.",
        "subtitle.serverDown": "Не получилось начать слушать агентов.",
        "limit.detailResets": "%1$@, сброс через %2$@",

        "approval.allow": "Разрешить",
        "approval.deny": "Запретить",
        "approval.askThere": "Спросить там",
        "approval.wantsTo": "хочет",
        "approval.more": "Ещё ждут: %ld",

        "stats.spending": "Расходы",
        "stats.apiValue": "по ценам API",
        "stats.now": "Сейчас",
        "stats.workingNow": "работает",
        "stats.limitsLater": "Лимиты появятся после следующего ответа",
        "stats.updated": "Обновлено: %@",
        "stats.tokens": "%@ токенов",
        "stats.tokensWord": "токенов",
        "stats.fromCache": "%ld%% из кэша",
        "stats.todayTotal": "Сегодня %@",
        "stats.noPrice": "Цены Codex неизвестны",
        "period.today": "Сегодня",
        "period.week": "7 дней",
        "period.month": "30 дней",
        "window.session": "Сессия",
        "window.week": "Неделя",
        "window.limit": "Лимит",
        "stats.activity": "Активность",
        "stats.streak": "%ld дн. подряд",
        "stats.activeDays": "Активных дней",
        "stats.busiestDay": "Самый активный день",

        "time.daysHours": "%1$ld д %2$ld ч",
        "time.hoursMinutes": "%1$ld ч %2$ld мин",
        "time.minutes": "%ld мин",
        "time.hours": "%ld ч",
        "time.days": "%ld д",
        "time.months": "%ld мес.",
        "time.justNow": "только что",
        "time.ago": "%@ назад",

        "resets.line": "Сбросы: %ld",
        "resets.expiresIn": "ближайший сгорит через %@",
        "resets.use": "Использовать сброс",
        "resets.resetting": "Сбрасываю…",
        "resets.confirmTitle": "Сбросить лимиты Codex сейчас?",
        "resets.confirmBody": "Потратится один запасной сброс: лимиты сессии и недели обновятся сразу. Сбросов осталось: %ld.",
        "resets.outcome.reset": "Лимиты Codex сброшены",
        "resets.outcome.nothing": "Сбрасывать пока нечего",
        "resets.outcome.noCredit": "Запасных сбросов нет",
        "resets.outcome.already": "Этот сброс уже использован",
        "resets.outcome.failed": "Не получилось — Codex на этом Mac вошёл в аккаунт?",

        "drop.here": "Отпусти — скопирую путь для агента",
        "drop.copiedOne": "Путь к %@ скопирован — вставь агенту (⌘V)",
        "drop.copiedMany": "Скопировано путей: %ld — вставь агенту (⌘V)",
        "drop.remoteCantSee": "Агент на %@ не увидит файл с этого Mac.",
        "drop.willSendOne": "Путь на сервере скопирован — файл уйдёт на %@ с твоим следующим сообщением (⌘V)",
        "drop.willSendMany": "Пути на сервере скопированы — файлов: %1$ld, уйдут на %2$@ с твоим следующим сообщением (⌘V)",
        "drop.delivered": "Доставлено на %1$@: %2$ld",
        "drop.skippedFolders": "Папки пока не пересылаются.",
        "drop.tooBig": "За раз можно до 20 МБ.",
        "drop.shelfInFullDenny": "Полка для файлов и музыка — в полном Денни →",
        "fullDenny": "Задачи, заметки и офлайн-ИИ — полный Денни →",

        "alerts.menu": "Уведомления",
        "alerts.finish": "Задача готова",
        "alerts.limit": "Лимит тарифа",
        "alerts.budget": "Дневной бюджет по ценам API",
        "alerts.off": "Выкл.",
        "alerts.anyLength": "Любой длины",
        "alerts.longerThan": "Дольше %ld мин",
        "alerts.atPercent": "При %ld%%",
        "alerts.finishedTitle": "%@ закончил",
        "alerts.finishedBody": "%1$@ · работал %2$@",
        "alerts.limitTitle": "Лимит %1$@: %2$ld%%",
        "alerts.budgetTitle": "Дневной бюджет превышен: %@",
        "alerts.budgetBody": "По ценам API, вместе с серверами.",

        "menu.claude": "Следить за Claude Code",
        "menu.codex": "Следить за Codex",
        "menu.remote": "Удалённый сервер (SSH)…",
        "menu.fullDenny": "Полный Денни…",
        "menu.quit": "Выйти из Denny for Agents",
        "remote.title": "Следить за агентами на сервере (SSH)",
        "remote.body": "1. Перешли порт на время подключения: в Termius добавь правило Remote (сервер 127.0.0.1:{port} → этот Mac 127.0.0.1:{port}) или подключайся так: ssh -R {port}:127.0.0.1:{port} user@server\n2. Положи remote/denny-hook.py из репозитория на сервер в ~/.denny-for-agents/.\n3. На сервере выполни скопированную команду, затем: python3 ~/.denny-for-agents/denny-hook.py --ping",
        "remote.copy": "Скопировать команду",
        "remote.unavailable": "Удалённый режим не запустился: порт занят.",
        "common.close": "Закрыть",
        "common.cancel": "Отмена",
        "connect.title": "Подключить Денни к агентам?",
        "connect.body": "Денни добавит хуки в ~/.claude/settings.json и ~/.codex/hooks.json (рядом сохранится резервная копия). Если Денни не запущен, хуки ничего не делают и никогда не мешают агентам.",
        "connect.connect": "Подключить",
        "connect.later": "Позже",
        "connect.failed": "Не получилось изменить файл настроек",

        "value.title": "Выгода тарифа",
        "value.line": "%@ по ценам API за 30 дней",
        "value.planMonthly": "%1$@ · %2$@/мес",
        "stats.trend": "Динамика",
        "stats.models": "Модели",
        "stats.projects": "Проекты",
        "stats.peak": "пик %@",
        "card.limits": "Лимиты",
        "alerts.renewedTitle": "Лимит %@ обновился",
        "menu.cards": "Карточки",
        "menu.readout": "У камеры",
        "readout.timer": "Таймер задачи",
        "readout.limit": "Самый полный лимит",
        "page.overview": "Обзор",
        "page.stats": "Статистика",
        "stats.noFresh": "Нет свежих данных",

        "settings.title": "Настройки",
        "settings.menu": "Настройки…",
        "settings.section.agents": "Агенты",
        "settings.section.servers": "Серверы",
        "settings.section.notch": "Вырез",
        "settings.section.cards": "Карточки",
        "settings.section.alerts": "Уведомления",
        "settings.section.language": "Язык",
        "settings.section.privacy": "Конфиденциальность",
        "settings.section.about": "О программе",
        "settings.connected": "Подключён",
        "settings.notConnected": "Не подключён",
        "settings.disconnect": "Отключить",
        "settings.agentsFooter": "Денни добавляет свои хуки в файл настроек каждого агента и сохраняет рядом резервную копию. Если Денни не запущен, хуки ничего не делают.",
        "settings.keepAwake": "Не давать Mac засыпать, пока агенты работают",
        "settings.keepAwakeFooter": "Только пока работает агент на этом Mac. Экран при этом может гаснуть.",
        "settings.serversConnected": "Подключённые серверы",
        "settings.noServers": "Серверов пока нет. Подключи сервер ниже.",
        "settings.lastSeen": "на связи %@",
        "settings.peeks": "Выглядывание",
        "settings.peekOnStart": "Когда отправляешь задачу",
        "settings.peekOnWriting": "Когда агент начинает писать код",
        "settings.peekOnFinish": "Когда агент закончил",
        "settings.display": "Монитор",
        "settings.displayAuto": "Тот, где есть вырез",
        "settings.fullScreen": "Показывать поверх полноэкранных приложений",
        "settings.cardsFooter": "Выключенные карточки пропадают из выреза. В «Обзоре» — лимиты, расходы и «Сейчас», в «Статистике» — остальное.",
        "settings.languageSystem": "Как в системе",
        "settings.languageRestart": "Новый язык применится после перезапуска.",
        "settings.restart": "Перезапустить",
        "settings.privacyReads": "Что читает Денни",
        "settings.privacyReadsBody": "Число токенов, названия моделей, время и названия папок проектов из журналов Claude Code и Codex; лимиты тарифа из ~/.claude.json, приложения Claude и Codex; события, которые агенты передают хукам.",
        "settings.privacyNever": "Что Денни никогда не читает и не отправляет",
        "settings.privacyNeverBody": "Твои запросы, ответы и содержимое файлов. С твоих машин ничего не уходит, кроме ежедневной загрузки публичного списка цен. Файлы, брошенные на вырез, уходят только на твой сервер.",
        "settings.removeAll": "Отключить агентов и стереть данные Денни",
        "settings.removeAllFooter": "Уберёт хуки из Claude Code и Codex, удалит ~/.denny-for-agents с историей и настройками и закроет приложение.",
        "settings.removeAllConfirm": "Стереть всё, что сохранил Denny for Agents?",
        "settings.version": "Версия %@",
        "settings.about": "Маленький робот в вырезе, который присматривает за Claude Code и Codex. Бесплатная открытая часть Денни.",

        "quiet.on": "Тишина на час",
        "quiet.active": "Тишина до %@ — нажми, чтобы снять",
        "quick.refresh": "Обновить данные",
        "awake.manual": "Не спать вручную",
        "awake.duration": "На время",
        "awake.until": "До времени",
        "awake.indefinite": "Пока не выключу",
        "awake.start": "Начать",
        "awake.stop": "Остановить",
        "awake.activeUntil": "Mac не уснёт до %@",
        "awake.untilOff": "Mac не уснёт, пока не остановишь",
        "awake.lid": "Работать с закрытой крышкой",
        "awake.lidWarning": "Только на зарядке. Один раз спросит пароль администратора, чтобы разрешить ровно одну команду (pmset disablesleep), и сам выключится, когда работа закончена. Не убирай работающий закрытый Mac в сумку.",
        "awake.lidNeedsPower": "Сейчас от батареи — включится, когда подключишь зарядку.",

        "risk.safe": "Выглядит безопасно",
        "risk.caution": "Стоит взглянуть",
        "risk.danger": "Опасно",
        "risk.critical": "Очень опасно",
        "risk.reason.pipeToShell": "Скачает код из интернета и сразу его запустит.",
        "risk.reason.wipeRoot": "Удалит всё в /, в домашней папке или в текущей папке.",
        "risk.reason.rawDisk": "Пишет прямо на диск — может его стереть.",
        "risk.reason.format": "Форматирует или стирает диск.",
        "risk.reason.forkBomb": "Форк-бомба: Mac зависнет.",
        "risk.reason.dropData": "Удалит таблицы или данные в базе.",
        "risk.reason.deleteRecursive": "Удалит папку %@ со всем содержимым, без Корзины.",
        "risk.reason.forcePush": "Перезапишет историю ветки на сервере.",
        "risk.reason.resetHard": "Выбросит все незакоммиченные изменения.",
        "risk.reason.cleanUntracked": "Удалит файлы, которые не отслеживает git.",
        "risk.reason.sudo": "Запуск от имени администратора (sudo).",
        "risk.reason.permissions": "Откроет файлы для всех или сменит их владельца.",
        "risk.reason.killProcess": "Принудительно остановит программы.",
        "risk.reason.reboot": "Выключит или перезагрузит компьютер.",
        "risk.reason.dockerPrune": "Удалит контейнеры, тома или данные Docker.",
        "risk.reason.publish": "Опубликует пакет или релиз для всех.",
        "risk.reason.secrets": "Трогает ключи, пароли или секреты .env.",
        "risk.reason.push": "Отправит коммиты на сервер.",
        "risk.reason.deleteFile": "Удалит %@.",
        "risk.reason.install": "Установит пакеты из интернета.",
        "risk.reason.network": "Обращается к сети.",
        "risk.reason.gitHistory": "Перепишет историю git или откатит изменения файлов.",
        "risk.reason.sensitiveFile": "Меняет важный файл: %@.",
        "risk.reason.externalTool": "Использует внешний инструмент (MCP-сервер).",

        "load.thisMac": "Этот Mac",
        "load.cpu": "Процессор",
        "load.cpuLoad": "Нагрузка (ядер: %ld)",
        "load.memory": "Память",
        "load.pressureNormal": "Давление памяти: в норме",
        "load.pressureWarning": "Давление памяти: высокое",
        "load.pressureCritical": "Давление памяти: критическое",
        "load.swap": "Swap %@",
        "load.uptime": "Работает без перезагрузки %@",
        "load.memoryLow": "Память почти кончилась — тяжёлую сборку может убить.",
        "load.noServer": "Нагрузка сервера придёт со следующим отчётом подключённого сервера.",
        "settings.section.load": "Нагрузка",

        "relay.title": "%@ упёрся в лимит",
        "relay.titleUntil": "%1$@ упёрся в лимит до %2$@",
        "relay.body": "Передать задачу %@? Я напишу записку: что просили и что уже сделано.",
        "relay.copy": "Скопировать записку для %@",
        "relay.later": "Не сейчас",
        "relay.copied": "Записка скопирована — вставь её в %@ (⌘V)",
        "relay.handoff": "Передать задачу %@",
        "relay.note.intro": "Продолжи задачу, которую начал %1$@ (%2$@).",
        "relay.note.reasonLimit": "он упёрся в лимит тарифа",
        "relay.note.reasonManual": "передаю её тебе",
        "relay.note.folder": "Папка: %@",
        "relay.note.server": "Сервер: %@",
        "relay.note.task": "Задача:",
        "relay.note.done": "Что уже сделано:",
        "relay.note.edited": "правил: %@",
        "relay.note.ran": "запускал: %@",
        "relay.note.last": "Последнее сообщение %@:",
        "relay.note.next": "Сначала посмотри текущие изменения (git status, git diff), потом продолжай с того места, где остановились."
    ]
}
