extension Translations {
    static let russian: [String: String] = [
        "step.runs": "Запускает %@",
        "step.runsCommand": "Запускает команду",
        "step.reads": "Читает %@",
        "step.aFile": "файл",
        "step.edits": "Правит %@",
        "step.editsFiles": "Правит файлы",
        "step.searches": "Ищет «%@»",
        "step.searchesCode": "Ищет в коде",
        "step.searchesWeb": "Ищет в интернете",
        "step.opens": "Открывает %@",
        "step.startsHelper": "Запускает помощника",
        "step.updatesPlan": "Обновляет план",
        "step.uses": "Использует %@",
        "step.working": "Работает…",
        "step.thinking": "Думает…",
        "step.waitingForYou": "Ждёт тебя",
        "step.done": "Готово",

        "title.idle": "Всё спокойно",
        "title.working": "Агенты работают",
        "title.needsYou": "Нужен ты",
        "title.limitUsedUp": "Лимит %@ исчерпан",
        "title.limitAlmost": "Лимит %@ почти закончился",
        "subtitle.noSessions": "Запусти Claude Code или Codex — я присмотрю.",
        "subtitle.noHooks": "Подключи Claude Code и Codex в строке меню.",
        "subtitle.serverDown": "Не получилось начать слушать агентов.",
        "limit.detailResets": "%1$@, сброс через %2$@",

        "approval.allow": "Разрешить",
        "approval.deny": "Запретить",
        "approval.askThere": "Спросить там",
        "approval.wantsTo": "хочет",
        "approval.more": "Ещё ждут: %ld",

        "stats.spending": "Расходы",
        "stats.apiValue": "по ценам API",
        "stats.now": "Сейчас",
        "stats.workingNow": "работает",
        "stats.limitsLater": "Лимиты появятся после следующего ответа",
        "stats.updated": "Обновлено: %@",
        "stats.tokens": "%@ токенов",
        "stats.tokensWord": "токенов",
        "stats.fromCache": "%ld%% из кэша",
        "stats.todayTotal": "Сегодня %@",
        "stats.noPrice": "Цены Codex неизвестны",
        "period.today": "Сегодня",
        "period.week": "7 дней",
        "period.month": "30 дней",
        "window.session": "Сессия",
        "window.week": "Неделя",
        "window.limit": "Лимит",
        "stats.activity": "Активность",
        "stats.streak": "%ld дн. подряд",
        "stats.activeDays": "Активных дней",
        "stats.busiestDay": "Самый активный день",

        "time.daysHours": "%1$ld д %2$ld ч",
        "time.hoursMinutes": "%1$ld ч %2$ld мин",
        "time.minutes": "%ld мин",
        "time.hours": "%ld ч",
        "time.days": "%ld д",
        "time.months": "%ld мес.",
        "time.justNow": "только что",
        "time.ago": "%@ назад",

        "resets.line": "Сбросы: %ld",
        "resets.expiresIn": "ближайший сгорит через %@",
        "resets.use": "Использовать сброс",
        "resets.resetting": "Сбрасываю…",
        "resets.confirmTitle": "Сбросить лимиты Codex сейчас?",
        "resets.confirmBody": "Потратится один запасной сброс: лимиты сессии и недели обновятся сразу. Сбросов осталось: %ld.",
        "resets.outcome.reset": "Лимиты Codex сброшены",
        "resets.outcome.nothing": "Сбрасывать пока нечего",
        "resets.outcome.noCredit": "Запасных сбросов нет",
        "resets.outcome.already": "Этот сброс уже использован",
        "resets.outcome.failed": "Не получилось — Codex на этом Mac вошёл в аккаунт?",

        "drop.here": "Отпусти — скопирую путь для агента",
        "drop.copiedOne": "Путь к %@ скопирован — вставь агенту (⌘V)",
        "drop.copiedMany": "Скопировано путей: %ld — вставь агенту (⌘V)",
        "drop.remoteCantSee": "Агент на %@ не увидит файл с этого Mac.",
        "drop.willSendOne": "Путь на сервере скопирован — файл уйдёт на %@ с твоим следующим сообщением (⌘V)",
        "drop.willSendMany": "Пути на сервере скопированы — файлов: %1$ld, уйдут на %2$@ с твоим следующим сообщением (⌘V)",
        "drop.delivered": "Доставлено на %1$@: %2$ld",
        "drop.skippedFolders": "Папки пока не пересылаются.",
        "drop.tooBig": "За раз можно до 20 МБ.",
        "drop.shelfInFullDenny": "Полка для файлов и музыка — в полном Денни →",
        "fullDenny": "Задачи, заметки и офлайн-ИИ — полный Денни →",

        "alerts.menu": "Уведомления",
        "alerts.finish": "Задача готова",
        "alerts.limit": "Лимит тарифа",
        "alerts.budget": "Дневной бюджет по ценам API",
        "alerts.off": "Выкл.",
        "alerts.anyLength": "Любой длины",
        "alerts.longerThan": "Дольше %ld мин",
        "alerts.atPercent": "При %ld%%",
        "alerts.finishedTitle": "%@ закончил",
        "alerts.finishedBody": "%1$@ · работал %2$@",
        "alerts.limitTitle": "Лимит %1$@: %2$ld%%",
        "alerts.budgetTitle": "Дневной бюджет превышен: %@",
        "alerts.budgetBody": "По ценам API, вместе с серверами.",

        "menu.claude": "Следить за Claude Code",
        "menu.codex": "Следить за Codex",
        "menu.remote": "Удалённый сервер (SSH)…",
        "menu.fullDenny": "Полный Денни…",
        "menu.quit": "Выйти из Denny for Agents",
        "remote.title": "Следить за агентами на сервере (SSH)",
        "remote.body": "1. Перешли порт на время подключения: в Termius добавь правило Remote (сервер 127.0.0.1:{port} → этот Mac 127.0.0.1:{port}) или подключайся так: ssh -R {port}:127.0.0.1:{port} user@server\n2. Положи remote/denny-hook.py из репозитория на сервер в ~/.denny-for-agents/.\n3. На сервере выполни скопированную команду, затем: python3 ~/.denny-for-agents/denny-hook.py --ping",
        "remote.copy": "Скопировать команду",
        "remote.unavailable": "Удалённый режим не запустился: порт занят.",
        "common.close": "Закрыть",
        "common.cancel": "Отмена",
        "connect.title": "Подключить Денни к агентам?",
        "connect.body": "Денни добавит хуки в ~/.claude/settings.json и ~/.codex/hooks.json (рядом сохранится резервная копия). Если Денни не запущен, хуки ничего не делают и никогда не мешают агентам.",
        "connect.connect": "Подключить",
        "connect.later": "Позже",
        "connect.failed": "Не получилось изменить файл настроек"
    ]
}
