extension Translations {
    static let spanish: [String: String] = [
        "step.runs": "Ejecuta %@",
        "step.runsCommand": "Ejecuta un comando",
        "step.reads": "Lee %@",
        "step.aFile": "un archivo",
        "step.edits": "Edita %@",
        "step.editsFiles": "Edita archivos",
        "step.searches": "Busca «%@»",
        "step.searchesCode": "Busca en el código",
        "step.searchesWeb": "Busca en la web",
        "step.opens": "Abre %@",
        "step.startsHelper": "Inicia un agente ayudante",
        "step.updatesPlan": "Actualiza el plan",
        "step.uses": "Usa %@",
        "step.working": "Trabajando…",
        "step.thinking": "Pensando…",
        "step.waitingForYou": "Te espera",
        "step.done": "Listo",

        "title.idle": "Todo tranquilo",
        "title.working": "Los agentes trabajan",
        "title.needsYou": "Te necesita",
        "title.limitUsedUp": "Límite de %@ agotado",
        "title.limitAlmost": "Límite de %@ casi agotado",
        "subtitle.noSessions": "Inicia Claude Code o Codex — yo lo vigilo.",
        "subtitle.noHooks": "Conecta Claude Code y Codex desde la barra de menús.",
        "subtitle.serverDown": "No se pudo empezar a escuchar a los agentes.",
        "limit.detailResets": "%1$@, se reinicia en %2$@",

        "approval.allow": "Permitir",
        "approval.deny": "Denegar",
        "approval.askThere": "Preguntar allí",
        "approval.wantsTo": "quiere",
        "approval.more": "+%ld más en espera",

        "stats.spending": "Gasto",
        "stats.apiValue": "valor API",
        "stats.now": "Ahora",
        "stats.workingNow": "trabajando",
        "stats.limitsLater": "Los límites aparecerán tras la próxima respuesta",
        "stats.updated": "Actualizado %@",
        "stats.tokens": "%@ tokens",
        "stats.tokensWord": "tokens",
        "stats.fromCache": "%ld%% desde caché",
        "stats.todayTotal": "Hoy %@",
        "stats.noPrice": "Sin precio público para los modelos de Codex",
        "period.today": "Hoy",
        "period.week": "7 días",
        "period.month": "30 días",
        "window.session": "Sesión",
        "window.week": "Semana",
        "window.limit": "Límite",
        "stats.activity": "Actividad",
        "stats.streak": "%ld días seguidos",
        "stats.activeDays": "Días activos",
        "stats.busiestDay": "Día más activo",

        "time.daysHours": "%1$ld d %2$ld h",
        "time.hoursMinutes": "%1$ld h %2$ld min",
        "time.minutes": "%ld min",
        "time.hours": "%ld h",
        "time.days": "%ld d",
        "time.months": "%ld meses",
        "time.justNow": "justo ahora",
        "time.ago": "hace %@",

        "resets.line": "Reinicios: %ld",
        "resets.expiresIn": "el próximo caduca en %@",
        "resets.use": "Usar un reinicio",
        "resets.resetting": "Reiniciando…",
        "resets.confirmTitle": "¿Reiniciar ahora los límites de Codex?",
        "resets.confirmBody": "Gasta un reinicio guardado: los límites de sesión y de semana se renuevan al instante. Quedan: %ld.",
        "resets.outcome.reset": "Se reiniciaron los límites de Codex",
        "resets.outcome.nothing": "Aún no hay nada que reiniciar",
        "resets.outcome.noCredit": "No quedan reinicios",
        "resets.outcome.already": "Ese reinicio ya se usó",
        "resets.outcome.failed": "No se pudo — ¿Codex tiene la sesión iniciada en este Mac?",

        "drop.here": "Suelta — copio la ruta para tu agente",
        "drop.copiedOne": "Ruta de %@ copiada — pégala a tu agente (⌘V)",
        "drop.copiedMany": "%ld rutas copiadas — pégalas a tu agente (⌘V)",
        "drop.remoteCantSee": "El agente en %@ no ve los archivos de este Mac.",
        "drop.willSendOne": "Ruta del servidor copiada — el archivo irá a %@ con tu próximo mensaje (⌘V)",
        "drop.willSendMany": "Rutas del servidor copiadas — %1$ld archivos irán a %2$@ con tu próximo mensaje (⌘V)",
        "drop.delivered": "Entregado en %1$@: %2$ld",
        "drop.skippedFolders": "Las carpetas aún no se envían.",
        "drop.tooBig": "Hasta 20 MB por envío.",
        "drop.shelfInFullDenny": "Estante de archivos y control de música — en Denny completo →",
        "fullDenny": "Tareas, notas e IA sin conexión — Denny completo →",

        "alerts.menu": "Notificaciones",
        "alerts.finish": "Tarea terminada",
        "alerts.limit": "Límite del plan",
        "alerts.budget": "Presupuesto diario (precios API)",
        "alerts.off": "Desactivado",
        "alerts.anyLength": "Cualquier duración",
        "alerts.longerThan": "Más de %ld min",
        "alerts.atPercent": "Al %ld%%",
        "alerts.finishedTitle": "%@ terminó",
        "alerts.finishedBody": "%1$@ · trabajó %2$@",
        "alerts.limitTitle": "Límite de %1$@ al %2$ld%%",
        "alerts.budgetTitle": "Presupuesto diario alcanzado: %@",
        "alerts.budgetBody": "A precios de lista de la API, en este Mac y tus servidores.",

        "menu.claude": "Vigilar Claude Code",
        "menu.codex": "Vigilar Codex",
        "menu.remote": "Servidor remoto (SSH)…",
        "menu.fullDenny": "Obtener Denny completo…",
        "menu.quit": "Salir de Denny for Agents",
        "remote.title": "Vigilar agentes en un servidor SSH",
        "remote.body": "1. Redirige el puerto mientras estés conectado: en Termius añade una regla de reenvío Remote (servidor 127.0.0.1:{port} → este Mac 127.0.0.1:{port}), o conéctate con ssh -R {port}:127.0.0.1:{port} user@server\n2. Copia remote/denny-hook.py del repositorio a ~/.denny-for-agents/ en el servidor.\n3. En el servidor ejecuta el comando copiado y luego: python3 ~/.denny-for-agents/denny-hook.py --ping",
        "remote.copy": "Copiar comando de instalación",
        "remote.unavailable": "El modo remoto no pudo iniciar: puerto ocupado.",
        "common.close": "Cerrar",
        "common.cancel": "Cancelar",
        "connect.title": "¿Conectar a Denny con tus agentes?",
        "connect.body": "Denny añadirá hooks a ~/.claude/settings.json y ~/.codex/hooks.json (se guarda una copia de seguridad al lado). Si Denny no está abierto, los hooks no hacen nada y nunca bloquean a tus agentes.",
        "connect.connect": "Conectar",
        "connect.later": "Más tarde",
        "connect.failed": "No se pudo modificar el archivo de ajustes"
    ]
}
