extension Translations {
    static let spanish: [String: String] = [
        "step.runs": "Ejecuta %@",
        "step.runsCommand": "Ejecuta un comando",
        "step.reads": "Lee %@",
        "step.aFile": "un archivo",
        "step.edits": "Edita %@",
        "step.editsFiles": "Edita archivos",
        "step.searches": "Busca «%@»",
        "step.searchesCode": "Busca en el código",
        "step.searchesWeb": "Busca en la web",
        "step.opens": "Abre %@",
        "step.startsHelper": "Inicia un agente ayudante",
        "step.updatesPlan": "Actualiza el plan",
        "step.uses": "Usa %@",
        "step.working": "Trabajando…",
        "step.thinking": "Pensando…",
        "step.waitingForYou": "Te espera",
        "step.done": "Listo",

        "title.idle": "Todo tranquilo",
        "title.working": "Los agentes trabajan",
        "title.needsYou": "Te necesita",
        "title.limitUsedUp": "Límite de %@ agotado",
        "title.limitAlmost": "Límite de %@ casi agotado",
        "subtitle.noSessions": "Inicia Claude Code o Codex — yo lo vigilo.",
        "subtitle.noHooks": "Conecta Claude Code y Codex desde la barra de menús.",
        "subtitle.serverDown": "No se pudo empezar a escuchar a los agentes.",
        "limit.detailResets": "%1$@, se reinicia en %2$@",

        "approval.allow": "Permitir",
        "approval.deny": "Denegar",
        "approval.askThere": "Preguntar allí",
        "approval.wantsTo": "quiere",
        "approval.more": "+%ld más en espera",

        "stats.spending": "Gasto",
        "stats.apiValue": "valor API",
        "stats.now": "Ahora",
        "stats.workingNow": "trabajando",
        "stats.limitsLater": "Los límites aparecerán tras la próxima respuesta",
        "stats.updated": "Actualizado %@",
        "stats.tokens": "%@ tokens",
        "stats.tokensWord": "tokens",
        "stats.fromCache": "%ld%% desde caché",
        "stats.todayTotal": "Hoy %@",
        "stats.noPrice": "Sin precio público para los modelos de Codex",
        "period.today": "Hoy",
        "period.week": "7 días",
        "period.month": "30 días",
        "window.session": "Sesión",
        "window.week": "Semana",
        "window.limit": "Límite",
        "stats.activity": "Actividad",
        "stats.streak": "%ld días seguidos",
        "stats.activeDays": "Días activos",
        "stats.busiestDay": "Día más activo",

        "time.daysHours": "%1$ld d %2$ld h",
        "time.hoursMinutes": "%1$ld h %2$ld min",
        "time.minutes": "%ld min",
        "time.hours": "%ld h",
        "time.days": "%ld d",
        "time.months": "%ld meses",
        "time.justNow": "justo ahora",
        "time.ago": "hace %@",

        "resets.line": "Reinicios: %ld",
        "resets.expiresIn": "el próximo caduca en %@",
        "resets.use": "Usar un reinicio",
        "resets.resetting": "Reiniciando…",
        "resets.confirmTitle": "¿Reiniciar ahora los límites de Codex?",
        "resets.confirmBody": "Gasta un reinicio guardado: los límites de sesión y de semana se renuevan al instante. Quedan: %ld.",
        "resets.outcome.reset": "Se reiniciaron los límites de Codex",
        "resets.outcome.nothing": "Aún no hay nada que reiniciar",
        "resets.outcome.noCredit": "No quedan reinicios",
        "resets.outcome.already": "Ese reinicio ya se usó",
        "resets.outcome.failed": "No se pudo — ¿Codex tiene la sesión iniciada en este Mac?",

        "drop.here": "Suelta — copio la ruta para tu agente",
        "drop.copiedOne": "Ruta de %@ copiada — pégala a tu agente (⌘V)",
        "drop.copiedMany": "%ld rutas copiadas — pégalas a tu agente (⌘V)",
        "drop.remoteCantSee": "El agente en %@ no ve los archivos de este Mac.",
        "drop.willSendOne": "Ruta del servidor copiada — el archivo irá a %@ con tu próximo mensaje (⌘V)",
        "drop.willSendMany": "Rutas del servidor copiadas — %1$ld archivos irán a %2$@ con tu próximo mensaje (⌘V)",
        "drop.delivered": "Entregado en %1$@: %2$ld",
        "drop.skippedFolders": "Las carpetas aún no se envían.",
        "drop.tooBig": "Hasta 20 MB por envío.",
        "drop.shelfInFullDenny": "Estante de archivos y control de música — en Denny completo →",
        "fullDenny": "Tareas, notas e IA sin conexión — Denny completo →",

        "alerts.menu": "Notificaciones",
        "alerts.finish": "Tarea terminada",
        "alerts.limit": "Límite del plan",
        "alerts.budget": "Presupuesto diario (precios API)",
        "alerts.off": "Desactivado",
        "alerts.anyLength": "Cualquier duración",
        "alerts.longerThan": "Más de %ld min",
        "alerts.atPercent": "Al %ld%%",
        "alerts.finishedTitle": "%@ terminó",
        "alerts.finishedBody": "%1$@ · trabajó %2$@",
        "alerts.limitTitle": "Límite de %1$@ al %2$ld%%",
        "alerts.budgetTitle": "Presupuesto diario alcanzado: %@",
        "alerts.budgetBody": "A precios de lista de la API, en este Mac y tus servidores.",

        "menu.claude": "Vigilar Claude Code",
        "menu.codex": "Vigilar Codex",
        "menu.remote": "Servidor remoto (SSH)…",
        "menu.fullDenny": "Obtener Denny completo…",
        "menu.quit": "Salir de Denny for Agents",
        "remote.title": "Vigilar agentes en un servidor SSH",
        "remote.body": "1. Redirige el puerto mientras estés conectado: en Termius añade una regla de reenvío Remote (servidor 127.0.0.1:{port} → este Mac 127.0.0.1:{port}), o conéctate con ssh -R {port}:127.0.0.1:{port} user@server\n2. Copia remote/denny-hook.py del repositorio a ~/.denny-for-agents/ en el servidor.\n3. En el servidor ejecuta el comando copiado y luego: python3 ~/.denny-for-agents/denny-hook.py --ping",
        "remote.copy": "Copiar comando de instalación",
        "remote.unavailable": "El modo remoto no pudo iniciar: puerto ocupado.",
        "common.close": "Cerrar",
        "common.cancel": "Cancelar",
        "connect.title": "¿Conectar a Denny con tus agentes?",
        "connect.body": "Denny añadirá hooks a ~/.claude/settings.json y ~/.codex/hooks.json (se guarda una copia de seguridad al lado). Si Denny no está abierto, los hooks no hacen nada y nunca bloquean a tus agentes.",
        "connect.connect": "Conectar",
        "connect.later": "Más tarde",
        "connect.failed": "No se pudo modificar el archivo de ajustes",

        "value.title": "Valor del plan",
        "value.line": "%@ a precios de API en 30 días",
        "value.planMonthly": "%1$@ · %2$@/mes",
        "stats.trend": "Tendencia",
        "stats.models": "Modelos",
        "stats.projects": "Proyectos",
        "stats.peak": "pico %@",
        "card.limits": "Límites",
        "alerts.renewedTitle": "Límite de %@ renovado",
        "menu.cards": "Tarjetas",
        "menu.readout": "Junto a la cámara",
        "readout.timer": "Temporizador de tarea",
        "readout.limit": "Límite más ajustado",
        "page.overview": "Resumen",
        "page.stats": "Estadísticas",
        "stats.noFresh": "Sin datos recientes",

        "settings.title": "Ajustes",
        "settings.menu": "Ajustes…",
        "settings.section.agents": "Agentes",
        "settings.section.servers": "Servidores",
        "settings.section.notch": "Muesca",
        "settings.section.cards": "Tarjetas",
        "settings.section.alerts": "Notificaciones",
        "settings.section.language": "Idioma",
        "settings.section.privacy": "Privacidad",
        "settings.section.about": "Acerca de",
        "settings.connected": "Conectado",
        "settings.notConnected": "No conectado",
        "settings.disconnect": "Desconectar",
        "settings.agentsFooter": "Denny añade sus hooks al archivo de ajustes de cada agente y guarda una copia de seguridad al lado. Si Denny no está abierto, los hooks no hacen nada.",
        "settings.keepAwake": "Mantener el Mac despierto mientras trabajan los agentes",
        "settings.keepAwakeFooter": "Solo mientras un agente trabaja en este Mac. La pantalla puede apagarse igualmente.",
        "settings.serversConnected": "Servidores conectados",
        "settings.noServers": "Aún no hay servidores. Configura uno abajo.",
        "settings.lastSeen": "visto %@",
        "settings.noContact": "sin contacto %@",
        "ssh.title": "Conexiones de Denny",
        "ssh.body": "Denny se conecta por SSH él mismo y mantiene el enlace: tras el reposo, un cambio de red o una reconexión de VPN, se reconecta solo. Usa las claves SSH y ~/.ssh/config de este Mac — no hace falta Termius.",
        "ssh.placeholder": "root@servidor o un nombre de ~/.ssh/config",
        "ssh.add": "Añadir",
        "ssh.invalid": "Usa user@host o un nombre de ~/.ssh/config (para otro puerto, añádelo en ~/.ssh/config).",
        "ssh.connecting": "Conectando…",
        "ssh.connected": "conectado %@",
        "ssh.retry": "reintento en %@",
        "ssh.connectAgents": "Conectar agentes",
        "ssh.connectAgentsHelp": "Instalar el hook de Denny en el servidor y conectar allí Claude Code y Codex",
        "ssh.installing": "Conectando…",
        "ssh.agentsConnected": "Agentes conectados. Reinicia Claude Code / Codex en el servidor.",
        "ssh.installFailed": "No se pudieron conectar los agentes: %@",
        "ssh.needsKey": "No hay clave SSH para este servidor",
        "ssh.keyHint": "Este Mac necesita una clave SSH que el servidor acepte. Ejecuta en el Terminal del Mac (el segundo comando pide una vez la contraseña del servidor):",
        "ssh.copyCommands": "Copiar comandos",
        "ssh.hostKeyChanged": "La clave del servidor ha cambiado — revísala y corrige ~/.ssh/known_hosts",
        "ssh.unreachable": "Servidor inaccesible",
        "ssh.portBusy": "El puerto sigue ocupado en el servidor, probando el siguiente",
        "ssh.noPython": "python3 no está instalado en el servidor",
        "ssh.dropped": "Conexión perdida",
        "ssh.remove": "Quitar",
        "ssh.removeAndUnhook": "Quitar y desconectar los agentes del servidor",
        "ssh.removeQuestion": "¿Quitar este servidor?",
        "settings.peeks": "Apariciones",
        "settings.peekOnStart": "Cuando envías una tarea",
        "settings.peekOnWriting": "Cuando el agente empieza a escribir código",
        "settings.peekOnFinish": "Cuando el agente termina",
        "settings.display": "Pantalla",
        "settings.displayAuto": "La que tiene muesca",
        "settings.fullScreen": "Mostrar sobre apps a pantalla completa",
        "settings.cardsFooter": "Las tarjetas desactivadas desaparecen de la muesca. Resumen tiene límites, gasto y Ahora; Estadísticas, el resto.",
        "settings.languageSystem": "Como el sistema",
        "settings.languageRestart": "El nuevo idioma se aplica tras reiniciar.",
        "settings.restart": "Reiniciar ahora",
        "settings.privacyReads": "Qué lee Denny",
        "settings.privacyReadsBody": "Recuento de tokens, nombres de modelos, horas y nombres de carpetas de proyecto de los registros de Claude Code y Codex; límites del plan de ~/.claude.json, la app de Claude y Codex; los eventos que tus agentes envían a los hooks.",
        "settings.privacyNever": "Qué nunca lee ni envía Denny",
        "settings.privacyNeverBody": "Tus prompts, respuestas y el contenido de tus archivos. Nada sale de tus equipos salvo la descarga diaria de la lista pública de precios. Los archivos que sueltas en la muesca van solo a tu servidor.",
        "settings.removeAll": "Desconectar agentes y borrar los datos de Denny",
        "settings.removeAllFooter": "Quita los hooks de Claude Code y Codex, borra ~/.denny-for-agents con su historial y ajustes, y cierra la app.",
        "settings.removeAllConfirm": "¿Borrar todo lo que guardó Denny for Agents?",
        "settings.version": "Versión %@",
        "settings.about": "Un pequeño robot en tu muesca que vigila Claude Code y Codex. La parte gratuita y abierta de Denny.",
        "tests.onServer": "Se ejecuta en %@",
        "tests.noneOnServer": "No se encontraron pruebas en el servidor",
        "server.jobWaits": "%@: la tarea espera al servidor — empieza en cuanto un agente haga algo allí (o en segundos si hay uno trabajando)",
        "night.where": "Dónde",
        "night.thisMac": "Este Mac",
        "night.serverFolder": "Carpeta en el servidor, p. ej. ~/projects/shop",
        "settings.section.nightShift": "Turno de noche",
        "night.newJob": "Nueva tarea para más tarde",
        "night.agent": "Agente",
        "night.noFolder": "Ninguna carpeta elegida",
        "night.chooseFolder": "Elegir…",
        "night.when": "Empezar",
        "night.whenRenews": "Cuando se renueve el límite",
        "night.whenAt": "A una hora fija",
        "night.queue": "Poner en cola",
        "night.queueTitle": "Cola",
        "night.waitsUntil": "espera hasta %@",
        "night.waitsForLimit": "espera al límite",
        "night.running": "en curso %@",
        "night.doneAt": "hecho a las %@",
        "night.failedShort": "falló: %@",
        "night.footer": "En este Mac (Denny no le deja dormir) o en un servidor (allí sigue aunque se corte la sesión SSH; el resultado llega cuando vuelvas a conectarte). De noche nadie aprueba nada, así que Denny es prudente: los cambios en archivos y los comandos seguros siguen; lo que el guardián considera peligroso se rechaza. La red de seguridad sigue guardando copias y Telegram avisa cuando termina. Para una tarea en un servidor, el mensaje de Telegram llega cuando el Mac vuelve a estar conectado a ese servidor.",
        "night.interrupted": "interrumpido por un reinicio",
        "night.started": "%1$@ empezó la tarea de noche en %2$@",
        "night.done": "%1$@ terminó la tarea de noche en %2$@ — el recibo espera en el notch",
        "night.failed": "%1$@ no pudo terminar la tarea de noche en %2$@: %3$@",
        "settings.section.phone": "Teléfono",
        "phone.title": "Permisos desde el teléfono",
        "phone.steps": "1. En Telegram abre @BotFather y envía /newbot.\n2. Elige un nombre — BotFather te enviará un token.\n3. Pega el token aquí.",
        "phone.tokenPlaceholder": "Token del bot",
        "phone.check": "Comprobar",
        "phone.badToken": "Este token no funciona — cópialo de nuevo de @BotFather.",
        "phone.sendCode": "Envía este código a @%@:",
        "phone.openBot": "Abrir el bot",
        "phone.topicHint": "¿Quieres las peticiones en un tema o grupo concreto? Envía el código justo ahí: Denny escribirá solo en ese tema y solo tú podrás pulsar los botones.",
        "phone.waiting": "Esperando el código…",
        "phone.connected": "Conectado a %1$@ mediante @%2$@",
        "phone.whenAway": "Cuando no estoy en el Mac",
        "phone.always": "Siempre",
        "phone.finished": "Avisarme también cuando termine una tarea",
        "phone.test": "Enviar prueba",
        "phone.testText": "Aquí Denny 👋 Las peticiones de tus agentes llegarán a este chat.",
        "phone.disconnect": "Desconectar",
        "phone.footer": "Las peticiones pasan por los servidores de Telegram, incluido el texto del comando. El bot solo obedece al chat que envió el código. Ausente = 2 minutos sin ratón ni teclado.",
        "phone.paired": "Denny está conectado 🎉 Cuando un agente pida permiso y no estés en el Mac, la petición llegará aquí.",
        "phone.request": "%1$@ · %2$@ quiere:",
        "phone.allow": "✅ Permitir",
        "phone.deny": "❌ Denegar",
        "phone.allowed": "✅ Permitido",
        "phone.denied": "❌ Denegado",
        "phone.expired": "⌛ Sin respuesta aquí — el agente pregunta en su terminal.",
        "review.button": "Revisar con %@",
        "review.running": "%1$@ está revisando… %2$@",
        "review.clean": "✅ %@ no encontró problemas",
        "review.findings": "%1$@ encontró problemas: %2$ld",
        "review.send": "Enviar a %@",
        "review.copied": "Copiado — pégalo a %@ (⌘V)",
        "review.failed": "%1$@ no pudo revisar: %2$@",
        "review.noChanges": "no hay cambios que revisar",
        "review.notFound": "no se encontró en este Mac",
        "review.agentMessage": "%1$@ revisó tus cambios y encontró:\n\n%2$@\n\nRevisa estos puntos y corrige lo que proceda.",
        "tests.run": "Ejecutar pruebas",
        "tests.running": "Pruebas en curso… %@",
        "tests.passed": "✅ Pruebas superadas · %@",
        "tests.failed": "❌ Pruebas fallidas · %@",
        "tests.sendToAgent": "Enviar al agente",
        "tests.copied": "Copiado — pégalo al agente (⌘V)",
        "tests.agentMessage": "Las pruebas fallan tras tus cambios (`%1$@`). Aquí está el final de la salida — arréglalo, por favor:\n\n%2$@",
        "tests.autoSetting": "Ejecutar las pruebas del proyecto tras cada tarea",
        "tests.autoFooter": "En este Mac y en los servidores. Denny encuentra el comando solo (swift test, npm test, cargo test, pytest…); pon el tuyo en un archivo .denny-test en la raíz del proyecto.",
        "tests.timedOut": "Detenido tras 10 minutos.",
        "receipt.title": "Recibo de la tarea",
        "receipt.files": "Archivos: %ld",
        "receipt.lines": "+%1$ld −%2$ld",
        "receipt.commands": "Comandos: %ld",
        "receipt.tokens": "Tokens: %@",
        "receipt.cost": "%@ a precios de la API",
        "receipt.copy": "Copiar",
        "receipt.copied": "Recibo copiado",
        "receipt.hide": "Ocultar",
        "receipt.signature": "vía Denny for Agents",
        "settings.section.safetyNet": "Red de seguridad",
        "safety.peekTitle": "Archivos guardados antes de un comando arriesgado",
        "safety.cardTitle": "Red de seguridad",
        "safety.cardBody": "Los archivos se guardaron justo antes de este comando. Deshacer los devuelve.",
        "safety.onServer": "Guardado en %@ — la restauración se ejecuta allí",
        "safety.undo": "Deshacer…",
        "safety.copyCommand": "Copiar comando para el servidor",
        "safety.hide": "Ocultar",
        "safety.confirmTitle": "¿Devolver los archivos a como estaban antes de «%@»?",
        "safety.confirmBody": "Volverán %ld archivo(s). Los cambios hechos después de la copia se perderán; los archivos nuevos se quedan.",
        "safety.confirmRestore": "Devolver",
        "safety.nothing": "Nada que devolver: los archivos coinciden con la copia.",
        "safety.restored": "Los archivos han vuelto",
        "safety.failed": "No se pudieron devolver los archivos",
        "safety.commandCopied": "Comando copiado — ejecútalo en el servidor",
        "safety.empty": "Aún no hay copias. Justo antes de que un agente ejecute rm, git reset --hard o similar, Denny guarda aquí tus archivos.",
        "safety.footer": "Hasta 50 copias. En un proyecto git viven en una ref oculta y nunca tocan tu rama, índice ni stash.",
        "safety.storage": "Almacenamiento",
        "safety.keepFor": "Guardar copias",
        "safety.keep.1": "1 día",
        "safety.keep.7": "7 días",
        "safety.keep.30": "30 días",
        "safety.limit": "Espacio para copias",
        "safety.gb": "%ld GB",
        "safety.used": "Copias en este Mac: %@",
        "safety.clear": "Borrar todas las copias…",
        "safety.clearConfirm": "¿Borrar todas las copias de este Mac?",
        "safety.clearBody": "Sus archivos ya no se podrán devolver.",
        "safety.delete": "Borrar",
        "safety.limitFooter": "Solo cuentan las copias de archivos fuera de git: las de git viven dentro del proyecto y casi no ocupan. Cuando se acaba el espacio, se borran primero las más antiguas. Los servidores reciben estos ajustes con tu próximo mensaje al agente.",
        "update.check": "Buscar actualizaciones",
        "update.checking": "Buscando…",
        "update.upToDate": "Tienes la última versión",
        "update.available": "La versión %@ está disponible",
        "update.install": "Actualizar",
        "update.installing": "Descargando la actualización… Denny se reiniciará",
        "update.failed": "No se pudo actualizar: %@",
        "update.reason.offline": "no se puede conectar con GitHub",
        "update.reason.checksum": "el archivo no coincide con su suma de verificación",
        "update.reason.folder": "sin permiso para reemplazar la app — déjala en Aplicaciones",
        "update.reason.download": "la descarga falló",
        "update.homebrew": "Instalado con Homebrew — ejecuta: brew upgrade denny-for-agents",
        "update.notifyBody": "Abre los ajustes de Denny → Acerca de para actualizar.",

        "quiet.on": "Silencio una hora",
        "quiet.active": "Silencio hasta %@ — toca para quitar",
        "quick.refresh": "Actualizar ahora",
        "awake.manual": "Mantener despierto a mano",
        "awake.duration": "Durante",
        "awake.until": "Hasta",
        "awake.indefinite": "Hasta que lo apague",
        "awake.start": "Iniciar",
        "awake.stop": "Detener",
        "awake.activeUntil": "El Mac seguirá despierto hasta %@",
        "awake.untilOff": "El Mac seguirá despierto hasta que lo detengas",
        "awake.lid": "Seguir trabajando con la tapa cerrada",
        "awake.lidWarning": "Solo con el cargador. Pide una vez la contraseña de administrador para permitir un único comando (pmset disablesleep) y se apaga solo al terminar el trabajo. No guardes en la mochila un Mac cerrado y encendido.",
        "awake.lidNeedsPower": "Ahora con batería — se activará al conectar el cargador.",

        "risk.safe": "Parece seguro",
        "risk.caution": "Échale un vistazo",
        "risk.danger": "Peligroso",
        "risk.critical": "Muy peligroso",
        "risk.reason.pipeToShell": "Descarga código de internet y lo ejecuta en el acto.",
        "risk.reason.wipeRoot": "Borra todo en /, en tu carpeta personal o en la carpeta actual.",
        "risk.reason.rawDisk": "Escribe directamente en un disco: puede borrarlo.",
        "risk.reason.format": "Formatea o borra un disco.",
        "risk.reason.forkBomb": "Una fork bomb: el Mac se colgará.",
        "risk.reason.dropData": "Borra tablas o datos de la base.",
        "risk.reason.deleteRecursive": "Borra la carpeta %@ con todo su contenido, sin papelera.",
        "risk.reason.forcePush": "Sobrescribe el historial de la rama en el servidor.",
        "risk.reason.resetHard": "Descarta todos los cambios sin commit.",
        "risk.reason.cleanUntracked": "Borra los archivos que git no sigue.",
        "risk.reason.sudo": "Se ejecuta como administrador (sudo).",
        "risk.reason.permissions": "Abre archivos a todos o cambia su propietario.",
        "risk.reason.killProcess": "Detiene programas a la fuerza.",
        "risk.reason.reboot": "Apaga o reinicia el ordenador.",
        "risk.reason.dockerPrune": "Borra contenedores, volúmenes o datos de Docker.",
        "risk.reason.publish": "Publica un paquete o versión para todos.",
        "risk.reason.secrets": "Toca claves, contraseñas o secretos .env.",
        "risk.reason.push": "Envía commits al servidor.",
        "risk.reason.deleteFile": "Borra %@.",
        "risk.reason.install": "Instala paquetes de internet.",
        "risk.reason.network": "Accede a la red.",
        "risk.reason.gitHistory": "Reescribe el historial de git o descarta cambios.",
        "risk.reason.sensitiveFile": "Modifica un archivo delicado: %@.",
        "risk.reason.externalTool": "Usa una herramienta externa (servidor MCP).",

        "load.thisMac": "Este Mac",
        "load.cpu": "CPU",
        "load.cpuLoad": "Carga (%ld núcleos)",
        "load.memory": "Memoria",
        "load.pressureNormal": "Presión de memoria: normal",
        "load.pressureWarning": "Presión de memoria: alta",
        "load.pressureCritical": "Presión de memoria: crítica",
        "load.swap": "Swap %@",
        "load.uptime": "Encendido desde hace %@",
        "load.memoryLow": "Memoria casi llena: una compilación pesada podría morir.",
        "load.noServer": "La carga del servidor llegará con el próximo informe de un servidor conectado.",
        "settings.section.load": "Carga",

        "relay.title": "%@ llegó a su límite",
        "relay.titleUntil": "%1$@ llegó a su límite hasta las %2$@",
        "relay.body": "¿Pasar la tarea a %@? Escribo una nota con lo pedido y lo ya hecho.",
        "relay.copy": "Copiar nota para %@",
        "relay.later": "Ahora no",
        "relay.copied": "Nota copiada: pégala en %@ (⌘V)",
        "relay.handoff": "Pasar la tarea a %@",
        "relay.note.intro": "Continúa una tarea que empezó %1$@ (%2$@).",
        "relay.note.reasonLimit": "llegó al límite de su plan",
        "relay.note.reasonManual": "te la paso",
        "relay.note.folder": "Carpeta: %@",
        "relay.note.server": "Servidor: %@",
        "relay.note.task": "La tarea:",
        "relay.note.done": "Ya hecho:",
        "relay.note.edited": "editó: %@",
        "relay.note.ran": "ejecutó: %@",
        "relay.note.last": "Último mensaje de %@:",
        "relay.note.next": "Primero revisa los cambios actuales (git status, git diff) y luego sigue desde donde se quedó.",

        "stuck.title": "%@ parece estar dando vueltas",
        "stuck.repeatCommand": "Ejecuta «%2$@» por %1$ldª vez",
        "stuck.repeatEdit": "Edita %2$@ por %1$ldª vez",
        "stuck.noProgress": "%ld min de trabajo sin un solo cambio",
        "stuck.setting": "Avisar cuando un agente da vueltas en círculo"
    ]
}
