extension Translations {
    static let spanish: [String: String] = [
        "step.runs": "Ejecuta %@",
        "step.runsCommand": "Ejecuta un comando",
        "step.reads": "Lee %@",
        "step.aFile": "un archivo",
        "step.edits": "Edita %@",
        "step.editsFiles": "Edita archivos",
        "step.searches": "Busca «%@»",
        "step.searchesCode": "Busca en el código",
        "step.searchesWeb": "Busca en la web",
        "step.opens": "Abre %@",
        "step.startsHelper": "Inicia un agente ayudante",
        "step.updatesPlan": "Actualiza el plan",
        "step.uses": "Usa %@",
        "step.working": "Trabajando…",
        "step.thinking": "Pensando…",
        "step.waitingForYou": "Te espera",
        "step.done": "Listo",

        "title.idle": "Todo tranquilo",
        "title.working": "Los agentes trabajan",
        "title.needsYou": "Te necesita",
        "title.limitUsedUp": "Límite de %@ agotado",
        "title.limitAlmost": "Límite de %@ casi agotado",
        "subtitle.noSessions": "Inicia Claude Code o Codex — yo lo vigilo.",
        "subtitle.noHooks": "Conecta Claude Code y Codex desde la barra de menús.",
        "subtitle.serverDown": "No se pudo empezar a escuchar a los agentes.",
        "limit.detailResets": "%1$@, se reinicia en %2$@",

        "approval.allow": "Permitir",
        "approval.deny": "Denegar",
        "approval.askThere": "Preguntar allí",
        "approval.wantsTo": "quiere",
        "approval.more": "+%ld más en espera",

        "stats.spending": "Gasto",
        "stats.apiValue": "valor API",
        "stats.now": "Ahora",
        "stats.workingNow": "trabajando",
        "stats.limitsLater": "Los límites aparecerán tras la próxima respuesta",
        "stats.updated": "Actualizado %@",
        "stats.tokens": "%@ tokens",
        "stats.tokensWord": "tokens",
        "stats.fromCache": "%ld%% desde caché",
        "stats.todayTotal": "Hoy %@",
        "stats.noPrice": "Sin precio público para los modelos de Codex",
        "period.today": "Hoy",
        "period.week": "7 días",
        "period.month": "30 días",
        "window.session": "Sesión",
        "window.week": "Semana",
        "window.limit": "Límite",
        "stats.activity": "Actividad",
        "stats.streak": "%ld días seguidos",
        "stats.activeDays": "Días activos",
        "stats.busiestDay": "Día más activo",

        "time.daysHours": "%1$ld d %2$ld h",
        "time.hoursMinutes": "%1$ld h %2$ld min",
        "time.minutes": "%ld min",
        "time.hours": "%ld h",
        "time.days": "%ld d",
        "time.months": "%ld meses",
        "time.justNow": "justo ahora",
        "time.ago": "hace %@",

        "resets.line": "Reinicios: %ld",
        "resets.expiresIn": "el próximo caduca en %@",
        "resets.use": "Usar un reinicio",
        "resets.resetting": "Reiniciando…",
        "resets.confirmTitle": "¿Reiniciar ahora los límites de Codex?",
        "resets.confirmBody": "Gasta un reinicio guardado: los límites de sesión y de semana se renuevan al instante. Quedan: %ld.",
        "resets.outcome.reset": "Se reiniciaron los límites de Codex",
        "resets.outcome.nothing": "Aún no hay nada que reiniciar",
        "resets.outcome.noCredit": "No quedan reinicios",
        "resets.outcome.already": "Ese reinicio ya se usó",
        "resets.outcome.failed": "No se pudo — ¿Codex tiene la sesión iniciada en este Mac?",

        "drop.here": "Suelta — copio la ruta para tu agente",
        "drop.copiedOne": "Ruta de %@ copiada — pégala a tu agente (⌘V)",
        "drop.copiedMany": "%ld rutas copiadas — pégalas a tu agente (⌘V)",
        "drop.remoteCantSee": "El agente en %@ no ve los archivos de este Mac.",
        "drop.willSendOne": "Ruta del servidor copiada — el archivo irá a %@ con tu próximo mensaje (⌘V)",
        "drop.willSendMany": "Rutas del servidor copiadas — %1$ld archivos irán a %2$@ con tu próximo mensaje (⌘V)",
        "drop.delivered": "Entregado en %1$@: %2$ld",
        "drop.skippedFolders": "Las carpetas aún no se envían.",
        "drop.tooBig": "Hasta 20 MB por envío.",
        "drop.shelfInFullDenny": "Estante de archivos y control de música — en Denny completo →",
        "fullDenny": "Tareas, notas e IA sin conexión — Denny completo →",

        "alerts.menu": "Notificaciones",
        "alerts.finish": "Tarea terminada",
        "alerts.limit": "Límite del plan",
        "alerts.budget": "Presupuesto diario (precios API)",
        "alerts.off": "Desactivado",
        "alerts.anyLength": "Cualquier duración",
        "alerts.longerThan": "Más de %ld min",
        "alerts.atPercent": "Al %ld%%",
        "alerts.finishedTitle": "%@ terminó",
        "alerts.finishedBody": "%1$@ · trabajó %2$@",
        "alerts.limitTitle": "Límite de %1$@ al %2$ld%%",
        "alerts.budgetTitle": "Presupuesto diario alcanzado: %@",
        "alerts.budgetBody": "A precios de lista de la API, en este Mac y tus servidores.",

        "menu.claude": "Vigilar Claude Code",
        "menu.codex": "Vigilar Codex",
        "menu.remote": "Servidor remoto (SSH)…",
        "menu.fullDenny": "Obtener Denny completo…",
        "menu.quit": "Salir de Denny for Agents",
        "remote.title": "Vigilar agentes en un servidor SSH",
        "remote.body": "1. Redirige el puerto mientras estés conectado: en Termius añade una regla de reenvío Remote (servidor 127.0.0.1:{port} → este Mac 127.0.0.1:{port}), o conéctate con ssh -R {port}:127.0.0.1:{port} user@server\n2. Copia remote/denny-hook.py del repositorio a ~/.denny-for-agents/ en el servidor.\n3. En el servidor ejecuta el comando copiado y luego: python3 ~/.denny-for-agents/denny-hook.py --ping",
        "remote.copy": "Copiar comando de instalación",
        "remote.unavailable": "El modo remoto no pudo iniciar: puerto ocupado.",
        "common.close": "Cerrar",
        "common.cancel": "Cancelar",
        "connect.title": "¿Conectar a Denny con tus agentes?",
        "connect.body": "Denny añadirá hooks a ~/.claude/settings.json y ~/.codex/hooks.json (se guarda una copia de seguridad al lado). Si Denny no está abierto, los hooks no hacen nada y nunca bloquean a tus agentes.",
        "connect.connect": "Conectar",
        "connect.later": "Más tarde",
        "connect.failed": "No se pudo modificar el archivo de ajustes",

        "value.title": "Valor del plan",
        "value.line": "%@ a precios de API en 30 días",
        "value.planMonthly": "%1$@ · %2$@/mes",
        "stats.trend": "Tendencia",
        "stats.models": "Modelos",
        "stats.projects": "Proyectos",
        "stats.peak": "pico %@",
        "card.limits": "Límites",
        "alerts.renewedTitle": "Límite de %@ renovado",
        "menu.cards": "Tarjetas",
        "menu.readout": "Junto a la cámara",
        "readout.timer": "Temporizador de tarea",
        "readout.limit": "Límite más ajustado",
        "page.overview": "Resumen",
        "page.stats": "Estadísticas",
        "stats.noFresh": "Sin datos recientes",

        "settings.title": "Ajustes",
        "settings.menu": "Ajustes…",
        "settings.section.agents": "Agentes",
        "settings.section.servers": "Servidores",
        "settings.section.notch": "Muesca",
        "settings.section.cards": "Tarjetas",
        "settings.section.alerts": "Notificaciones",
        "settings.section.language": "Idioma",
        "settings.section.privacy": "Privacidad",
        "settings.section.about": "Acerca de",
        "settings.connected": "Conectado",
        "settings.notConnected": "No conectado",
        "settings.disconnect": "Desconectar",
        "settings.agentsFooter": "Denny añade sus hooks al archivo de ajustes de cada agente y guarda una copia de seguridad al lado. Si Denny no está abierto, los hooks no hacen nada.",
        "settings.keepAwake": "Mantener el Mac despierto mientras trabajan los agentes",
        "settings.keepAwakeFooter": "Solo mientras un agente trabaja en este Mac. La pantalla puede apagarse igualmente.",
        "settings.serversConnected": "Servidores conectados",
        "settings.noServers": "Aún no hay servidores. Configura uno abajo.",
        "settings.lastSeen": "visto %@",
        "settings.peeks": "Apariciones",
        "settings.peekOnStart": "Cuando envías una tarea",
        "settings.peekOnWriting": "Cuando el agente empieza a escribir código",
        "settings.peekOnFinish": "Cuando el agente termina",
        "settings.display": "Pantalla",
        "settings.displayAuto": "La que tiene muesca",
        "settings.fullScreen": "Mostrar sobre apps a pantalla completa",
        "settings.cardsFooter": "Las tarjetas desactivadas desaparecen de la muesca. Resumen tiene límites, gasto y Ahora; Estadísticas, el resto.",
        "settings.languageSystem": "Como el sistema",
        "settings.languageRestart": "El nuevo idioma se aplica tras reiniciar.",
        "settings.restart": "Reiniciar ahora",
        "settings.privacyReads": "Qué lee Denny",
        "settings.privacyReadsBody": "Recuento de tokens, nombres de modelos, horas y nombres de carpetas de proyecto de los registros de Claude Code y Codex; límites del plan de ~/.claude.json, la app de Claude y Codex; los eventos que tus agentes envían a los hooks.",
        "settings.privacyNever": "Qué nunca lee ni envía Denny",
        "settings.privacyNeverBody": "Tus prompts, respuestas y el contenido de tus archivos. Nada sale de tus equipos salvo la descarga diaria de la lista pública de precios. Los archivos que sueltas en la muesca van solo a tu servidor.",
        "settings.removeAll": "Desconectar agentes y borrar los datos de Denny",
        "settings.removeAllFooter": "Quita los hooks de Claude Code y Codex, borra ~/.denny-for-agents con su historial y ajustes, y cierra la app.",
        "settings.removeAllConfirm": "¿Borrar todo lo que guardó Denny for Agents?",
        "settings.version": "Versión %@",
        "settings.about": "Un pequeño robot en tu muesca que vigila Claude Code y Codex. La parte gratuita y abierta de Denny.",
        "update.check": "Buscar actualizaciones",
        "update.checking": "Buscando…",
        "update.upToDate": "Tienes la última versión",
        "update.available": "La versión %@ está disponible",
        "update.install": "Actualizar",
        "update.installing": "Descargando la actualización… Denny se reiniciará",
        "update.failed": "No se pudo actualizar: %@",
        "update.reason.offline": "no se puede conectar con GitHub",
        "update.reason.checksum": "el archivo no coincide con su suma de verificación",
        "update.reason.folder": "sin permiso para reemplazar la app — déjala en Aplicaciones",
        "update.reason.download": "la descarga falló",
        "update.homebrew": "Instalado con Homebrew — ejecuta: brew upgrade denny-for-agents",
        "update.notifyBody": "Abre los ajustes de Denny → Acerca de para actualizar.",

        "quiet.on": "Silencio una hora",
        "quiet.active": "Silencio hasta %@ — toca para quitar",
        "quick.refresh": "Actualizar ahora",
        "awake.manual": "Mantener despierto a mano",
        "awake.duration": "Durante",
        "awake.until": "Hasta",
        "awake.indefinite": "Hasta que lo apague",
        "awake.start": "Iniciar",
        "awake.stop": "Detener",
        "awake.activeUntil": "El Mac seguirá despierto hasta %@",
        "awake.untilOff": "El Mac seguirá despierto hasta que lo detengas",
        "awake.lid": "Seguir trabajando con la tapa cerrada",
        "awake.lidWarning": "Solo con el cargador. Pide una vez la contraseña de administrador para permitir un único comando (pmset disablesleep) y se apaga solo al terminar el trabajo. No guardes en la mochila un Mac cerrado y encendido.",
        "awake.lidNeedsPower": "Ahora con batería — se activará al conectar el cargador.",

        "risk.safe": "Parece seguro",
        "risk.caution": "Échale un vistazo",
        "risk.danger": "Peligroso",
        "risk.critical": "Muy peligroso",
        "risk.reason.pipeToShell": "Descarga código de internet y lo ejecuta en el acto.",
        "risk.reason.wipeRoot": "Borra todo en /, en tu carpeta personal o en la carpeta actual.",
        "risk.reason.rawDisk": "Escribe directamente en un disco: puede borrarlo.",
        "risk.reason.format": "Formatea o borra un disco.",
        "risk.reason.forkBomb": "Una fork bomb: el Mac se colgará.",
        "risk.reason.dropData": "Borra tablas o datos de la base.",
        "risk.reason.deleteRecursive": "Borra la carpeta %@ con todo su contenido, sin papelera.",
        "risk.reason.forcePush": "Sobrescribe el historial de la rama en el servidor.",
        "risk.reason.resetHard": "Descarta todos los cambios sin commit.",
        "risk.reason.cleanUntracked": "Borra los archivos que git no sigue.",
        "risk.reason.sudo": "Se ejecuta como administrador (sudo).",
        "risk.reason.permissions": "Abre archivos a todos o cambia su propietario.",
        "risk.reason.killProcess": "Detiene programas a la fuerza.",
        "risk.reason.reboot": "Apaga o reinicia el ordenador.",
        "risk.reason.dockerPrune": "Borra contenedores, volúmenes o datos de Docker.",
        "risk.reason.publish": "Publica un paquete o versión para todos.",
        "risk.reason.secrets": "Toca claves, contraseñas o secretos .env.",
        "risk.reason.push": "Envía commits al servidor.",
        "risk.reason.deleteFile": "Borra %@.",
        "risk.reason.install": "Instala paquetes de internet.",
        "risk.reason.network": "Accede a la red.",
        "risk.reason.gitHistory": "Reescribe el historial de git o descarta cambios.",
        "risk.reason.sensitiveFile": "Modifica un archivo delicado: %@.",
        "risk.reason.externalTool": "Usa una herramienta externa (servidor MCP).",

        "load.thisMac": "Este Mac",
        "load.cpu": "CPU",
        "load.cpuLoad": "Carga (%ld núcleos)",
        "load.memory": "Memoria",
        "load.pressureNormal": "Presión de memoria: normal",
        "load.pressureWarning": "Presión de memoria: alta",
        "load.pressureCritical": "Presión de memoria: crítica",
        "load.swap": "Swap %@",
        "load.uptime": "Encendido desde hace %@",
        "load.memoryLow": "Memoria casi llena: una compilación pesada podría morir.",
        "load.noServer": "La carga del servidor llegará con el próximo informe de un servidor conectado.",
        "settings.section.load": "Carga",

        "relay.title": "%@ llegó a su límite",
        "relay.titleUntil": "%1$@ llegó a su límite hasta las %2$@",
        "relay.body": "¿Pasar la tarea a %@? Escribo una nota con lo pedido y lo ya hecho.",
        "relay.copy": "Copiar nota para %@",
        "relay.later": "Ahora no",
        "relay.copied": "Nota copiada: pégala en %@ (⌘V)",
        "relay.handoff": "Pasar la tarea a %@",
        "relay.note.intro": "Continúa una tarea que empezó %1$@ (%2$@).",
        "relay.note.reasonLimit": "llegó al límite de su plan",
        "relay.note.reasonManual": "te la paso",
        "relay.note.folder": "Carpeta: %@",
        "relay.note.server": "Servidor: %@",
        "relay.note.task": "La tarea:",
        "relay.note.done": "Ya hecho:",
        "relay.note.edited": "editó: %@",
        "relay.note.ran": "ejecutó: %@",
        "relay.note.last": "Último mensaje de %@:",
        "relay.note.next": "Primero revisa los cambios actuales (git status, git diff) y luego sigue desde donde se quedó.",

        "stuck.title": "%@ parece estar dando vueltas",
        "stuck.repeatCommand": "Ejecuta «%2$@» por %1$ldª vez",
        "stuck.repeatEdit": "Edita %2$@ por %1$ldª vez",
        "stuck.noProgress": "%ld min de trabajo sin un solo cambio",
        "stuck.setting": "Avisar cuando un agente da vueltas en círculo"
    ]
}
