extension Translations {
    static let ukrainian: [String: String] = [
        "step.runs": "Запускає %@",
        "step.runsCommand": "Запускає команду",
        "step.reads": "Читає %@",
        "step.aFile": "файл",
        "step.edits": "Редагує %@",
        "step.editsFiles": "Редагує файли",
        "step.searches": "Шукає «%@»",
        "step.searchesCode": "Шукає в коді",
        "step.searchesWeb": "Шукає в інтернеті",
        "step.opens": "Відкриває %@",
        "step.startsHelper": "Запускає помічника",
        "step.updatesPlan": "Оновлює план",
        "step.uses": "Використовує %@",
        "step.working": "Працює…",
        "step.thinking": "Думає…",
        "step.waitingForYou": "Чекає на тебе",
        "step.done": "Готово",

        "title.idle": "Усе спокійно",
        "title.working": "Агенти працюють",
        "title.needsYou": "Потрібен ти",
        "title.limitUsedUp": "Ліміт %@ вичерпано",
        "title.limitAlmost": "Ліміт %@ майже вичерпано",
        "subtitle.noSessions": "Запусти Claude Code або Codex — я наглядатиму.",
        "subtitle.noHooks": "Підключи Claude Code і Codex у рядку меню.",
        "subtitle.serverDown": "Не вдалося почати слухати агентів.",
        "limit.detailResets": "%1$@, скидання через %2$@",

        "approval.allow": "Дозволити",
        "approval.deny": "Заборонити",
        "approval.askThere": "Запитати там",
        "approval.wantsTo": "хоче",
        "approval.more": "Ще чекають: %ld",

        "stats.spending": "Витрати",
        "stats.apiValue": "за цінами API",
        "stats.now": "Зараз",
        "stats.workingNow": "працює",
        "stats.limitsLater": "Ліміти з'являться після наступної відповіді",
        "stats.updated": "Оновлено: %@",
        "stats.tokens": "%@ токенів",
        "stats.tokensWord": "токенів",
        "stats.fromCache": "%ld%% з кешу",
        "stats.todayTotal": "Сьогодні %@",
        "stats.noPrice": "Ціни Codex невідомі",
        "period.today": "Сьогодні",
        "period.week": "7 днів",
        "period.month": "30 днів",
        "window.session": "Сесія",
        "window.week": "Тиждень",
        "window.limit": "Ліміт",
        "stats.activity": "Активність",
        "stats.streak": "%ld дн. поспіль",
        "stats.activeDays": "Активних днів",
        "stats.busiestDay": "Найактивніший день",

        "time.daysHours": "%1$ld д %2$ld год",
        "time.hoursMinutes": "%1$ld год %2$ld хв",
        "time.minutes": "%ld хв",
        "time.hours": "%ld год",
        "time.days": "%ld д",
        "time.months": "%ld міс.",
        "time.justNow": "щойно",
        "time.ago": "%@ тому",

        "resets.line": "Скидання: %ld",
        "resets.expiresIn": "найближче згорить через %@",
        "resets.use": "Використати скидання",
        "resets.resetting": "Скидаю…",
        "resets.confirmTitle": "Скинути ліміти Codex зараз?",
        "resets.confirmBody": "Буде витрачено одне запасне скидання: ліміти сесії й тижня оновляться одразу. Залишилось скидань: %ld.",
        "resets.outcome.reset": "Ліміти Codex скинуто",
        "resets.outcome.nothing": "Поки нічого скидати",
        "resets.outcome.noCredit": "Запасних скидань немає",
        "resets.outcome.already": "Це скидання вже використано",
        "resets.outcome.failed": "Не вдалося — Codex на цьому Mac увійшов в акаунт?",

        "drop.here": "Відпусти — скопіюю шлях для агента",
        "drop.copiedOne": "Шлях до %@ скопійовано — встав агенту (⌘V)",
        "drop.copiedMany": "Скопійовано шляхів: %ld — встав агенту (⌘V)",
        "drop.remoteCantSee": "Агент на %@ не побачить файл із цього Mac.",
        "drop.willSendOne": "Шлях на сервері скопійовано — файл піде на %@ з твоїм наступним повідомленням (⌘V)",
        "drop.willSendMany": "Шляхи на сервері скопійовано — файлів: %1$ld, підуть на %2$@ з твоїм наступним повідомленням (⌘V)",
        "drop.delivered": "Доставлено на %1$@: %2$ld",
        "drop.skippedFolders": "Теки поки не пересилаються.",
        "drop.tooBig": "За раз можна до 20 МБ.",
        "drop.shelfInFullDenny": "Полиця для файлів і музика — у повному Денні →",
        "fullDenny": "Завдання, нотатки й офлайн-ШІ — повний Денні →",

        "alerts.menu": "Сповіщення",
        "alerts.finish": "Завдання готове",
        "alerts.limit": "Ліміт тарифу",
        "alerts.budget": "Денний бюджет за цінами API",
        "alerts.off": "Вимк.",
        "alerts.anyLength": "Будь-якої тривалості",
        "alerts.longerThan": "Довше %ld хв",
        "alerts.atPercent": "При %ld%%",
        "alerts.finishedTitle": "%@ завершив",
        "alerts.finishedBody": "%1$@ · працював %2$@",
        "alerts.limitTitle": "Ліміт %1$@: %2$ld%%",
        "alerts.budgetTitle": "Денний бюджет перевищено: %@",
        "alerts.budgetBody": "За цінами API, разом із серверами.",

        "menu.claude": "Стежити за Claude Code",
        "menu.codex": "Стежити за Codex",
        "menu.remote": "Віддалений сервер (SSH)…",
        "menu.fullDenny": "Повний Денні…",
        "menu.quit": "Вийти з Denny for Agents",
        "remote.title": "Стежити за агентами на сервері (SSH)",
        "remote.body": "1. Перешли порт на час підключення: у Termius додай правило Remote (сервер 127.0.0.1:{port} → цей Mac 127.0.0.1:{port}) або підключайся так: ssh -R {port}:127.0.0.1:{port} user@server\n2. Поклади remote/denny-hook.py з репозиторію на сервер у ~/.denny-for-agents/.\n3. На сервері виконай скопійовану команду, потім: python3 ~/.denny-for-agents/denny-hook.py --ping",
        "remote.copy": "Скопіювати команду",
        "remote.unavailable": "Віддалений режим не запустився: порт зайнятий.",
        "common.close": "Закрити",
        "common.cancel": "Скасувати",
        "connect.title": "Підключити Денні до агентів?",
        "connect.body": "Денні додасть хуки в ~/.claude/settings.json і ~/.codex/hooks.json (поруч збережеться резервна копія). Якщо Денні не запущений, хуки нічого не роблять і ніколи не заважають агентам.",
        "connect.connect": "Підключити",
        "connect.later": "Пізніше",
        "connect.failed": "Не вдалося змінити файл налаштувань"
    ]
}
