extension Translations {
    static let ukrainian: [String: String] = [
        "step.runs": "Запускає %@",
        "step.runsCommand": "Запускає команду",
        "step.reads": "Читає %@",
        "step.aFile": "файл",
        "step.edits": "Редагує %@",
        "step.editsFiles": "Редагує файли",
        "step.searches": "Шукає «%@»",
        "step.searchesCode": "Шукає в коді",
        "step.searchesWeb": "Шукає в інтернеті",
        "step.opens": "Відкриває %@",
        "step.startsHelper": "Запускає помічника",
        "step.updatesPlan": "Оновлює план",
        "step.uses": "Використовує %@",
        "step.working": "Працює…",
        "step.thinking": "Думає…",
        "step.waitingForYou": "Чекає на тебе",
        "step.done": "Готово",

        "title.idle": "Усе спокійно",
        "title.working": "Агенти працюють",
        "title.needsYou": "Потрібен ти",
        "title.limitUsedUp": "Ліміт %@ вичерпано",
        "title.limitAlmost": "Ліміт %@ майже вичерпано",
        "subtitle.noSessions": "Запусти Claude Code або Codex — я наглядатиму.",
        "subtitle.noHooks": "Підключи Claude Code і Codex у рядку меню.",
        "subtitle.serverDown": "Не вдалося почати слухати агентів.",
        "limit.detailResets": "%1$@, скидання через %2$@",

        "approval.allow": "Дозволити",
        "approval.deny": "Заборонити",
        "approval.askThere": "Запитати там",
        "approval.wantsTo": "хоче",
        "approval.more": "Ще чекають: %ld",

        "stats.spending": "Витрати",
        "stats.apiValue": "за цінами API",
        "stats.now": "Зараз",
        "stats.workingNow": "працює",
        "stats.limitsLater": "Ліміти з'являться після наступної відповіді",
        "stats.updated": "Оновлено: %@",
        "stats.tokens": "%@ токенів",
        "stats.tokensWord": "токенів",
        "stats.fromCache": "%ld%% з кешу",
        "stats.todayTotal": "Сьогодні %@",
        "stats.noPrice": "Ціни Codex невідомі",
        "period.today": "Сьогодні",
        "period.week": "7 днів",
        "period.month": "30 днів",
        "window.session": "Сесія",
        "window.week": "Тиждень",
        "window.limit": "Ліміт",
        "stats.activity": "Активність",
        "stats.streak": "%ld дн. поспіль",
        "stats.activeDays": "Активних днів",
        "stats.busiestDay": "Найактивніший день",

        "time.daysHours": "%1$ld д %2$ld год",
        "time.hoursMinutes": "%1$ld год %2$ld хв",
        "time.minutes": "%ld хв",
        "time.hours": "%ld год",
        "time.days": "%ld д",
        "time.months": "%ld міс.",
        "time.justNow": "щойно",
        "time.ago": "%@ тому",

        "resets.line": "Скидання: %ld",
        "resets.expiresIn": "найближче згорить через %@",
        "resets.use": "Використати скидання",
        "resets.resetting": "Скидаю…",
        "resets.confirmTitle": "Скинути ліміти Codex зараз?",
        "resets.confirmBody": "Буде витрачено одне запасне скидання: ліміти сесії й тижня оновляться одразу. Залишилось скидань: %ld.",
        "resets.outcome.reset": "Ліміти Codex скинуто",
        "resets.outcome.nothing": "Поки нічого скидати",
        "resets.outcome.noCredit": "Запасних скидань немає",
        "resets.outcome.already": "Це скидання вже використано",
        "resets.outcome.failed": "Не вдалося — Codex на цьому Mac увійшов в акаунт?",

        "drop.here": "Відпусти — скопіюю шлях для агента",
        "drop.copiedOne": "Шлях до %@ скопійовано — встав агенту (⌘V)",
        "drop.copiedMany": "Скопійовано шляхів: %ld — встав агенту (⌘V)",
        "drop.remoteCantSee": "Агент на %@ не побачить файл із цього Mac.",
        "drop.willSendOne": "Шлях на сервері скопійовано — файл піде на %@ з твоїм наступним повідомленням (⌘V)",
        "drop.willSendMany": "Шляхи на сервері скопійовано — файлів: %1$ld, підуть на %2$@ з твоїм наступним повідомленням (⌘V)",
        "drop.delivered": "Доставлено на %1$@: %2$ld",
        "drop.skippedFolders": "Теки поки не пересилаються.",
        "drop.tooBig": "За раз можна до 20 МБ.",
        "drop.shelfInFullDenny": "Полиця для файлів і музика — у повному Денні →",
        "fullDenny": "Завдання, нотатки й офлайн-ШІ — повний Денні →",

        "alerts.menu": "Сповіщення",
        "alerts.finish": "Завдання готове",
        "alerts.limit": "Ліміт тарифу",
        "alerts.budget": "Денний бюджет за цінами API",
        "alerts.off": "Вимк.",
        "alerts.anyLength": "Будь-якої тривалості",
        "alerts.longerThan": "Довше %ld хв",
        "alerts.atPercent": "При %ld%%",
        "alerts.finishedTitle": "%@ завершив",
        "alerts.finishedBody": "%1$@ · працював %2$@",
        "alerts.limitTitle": "Ліміт %1$@: %2$ld%%",
        "alerts.budgetTitle": "Денний бюджет перевищено: %@",
        "alerts.budgetBody": "За цінами API, разом із серверами.",

        "menu.claude": "Стежити за Claude Code",
        "menu.codex": "Стежити за Codex",
        "menu.remote": "Віддалений сервер (SSH)…",
        "menu.fullDenny": "Повний Денні…",
        "menu.quit": "Вийти з Denny for Agents",
        "remote.title": "Стежити за агентами на сервері (SSH)",
        "remote.body": "1. Перешли порт на час підключення: у Termius додай правило Remote (сервер 127.0.0.1:{port} → цей Mac 127.0.0.1:{port}) або підключайся так: ssh -R {port}:127.0.0.1:{port} user@server\n2. Поклади remote/denny-hook.py з репозиторію на сервер у ~/.denny-for-agents/.\n3. На сервері виконай скопійовану команду, потім: python3 ~/.denny-for-agents/denny-hook.py --ping",
        "remote.copy": "Скопіювати команду",
        "remote.unavailable": "Віддалений режим не запустився: порт зайнятий.",
        "common.close": "Закрити",
        "common.cancel": "Скасувати",
        "connect.title": "Підключити Денні до агентів?",
        "connect.body": "Денні додасть хуки в ~/.claude/settings.json і ~/.codex/hooks.json (поруч збережеться резервна копія). Якщо Денні не запущений, хуки нічого не роблять і ніколи не заважають агентам.",
        "connect.connect": "Підключити",
        "connect.later": "Пізніше",
        "connect.failed": "Не вдалося змінити файл налаштувань",

        "value.title": "Вигода тарифу",
        "value.line": "%@ за цінами API за 30 днів",
        "value.planMonthly": "%1$@ · %2$@/міс",
        "stats.trend": "Динаміка",
        "stats.models": "Моделі",
        "stats.projects": "Проєкти",
        "stats.peak": "пік %@",
        "card.limits": "Ліміти",
        "alerts.renewedTitle": "Ліміт %@ оновився",
        "menu.cards": "Картки",
        "menu.readout": "Біля камери",
        "readout.timer": "Таймер завдання",
        "readout.limit": "Найповніший ліміт",
        "page.overview": "Огляд",
        "page.stats": "Статистика",
        "stats.noFresh": "Немає свіжих даних",

        "settings.title": "Налаштування",
        "settings.menu": "Налаштування…",
        "settings.section.agents": "Агенти",
        "settings.section.servers": "Сервери",
        "settings.section.notch": "Виріз",
        "settings.section.cards": "Картки",
        "settings.section.alerts": "Сповіщення",
        "settings.section.language": "Мова",
        "settings.section.privacy": "Конфіденційність",
        "settings.section.about": "Про програму",
        "settings.connected": "Підключено",
        "settings.notConnected": "Не підключено",
        "settings.disconnect": "Відключити",
        "settings.agentsFooter": "Денні додає свої хуки у файл налаштувань кожного агента й зберігає поруч резервну копію. Якщо Денні не запущений, хуки нічого не роблять.",
        "settings.keepAwake": "Не давати Mac засинати, поки агенти працюють",
        "settings.keepAwakeFooter": "Лише поки працює агент на цьому Mac. Екран при цьому може гаснути.",
        "settings.serversConnected": "Підключені сервери",
        "settings.noServers": "Серверів поки немає. Підключи сервер нижче.",
        "settings.lastSeen": "на зв'язку %@",
        "settings.peeks": "Визирання",
        "settings.peekOnStart": "Коли надсилаєш завдання",
        "settings.peekOnWriting": "Коли агент починає писати код",
        "settings.peekOnFinish": "Коли агент завершив",
        "settings.display": "Монітор",
        "settings.displayAuto": "Той, де є виріз",
        "settings.fullScreen": "Показувати поверх повноекранних застосунків",
        "settings.cardsFooter": "Вимкнені картки зникають із вирізу. В «Огляді» — ліміти, витрати й «Зараз», у «Статистиці» — решта.",
        "settings.languageSystem": "Як у системі",
        "settings.languageRestart": "Нова мова застосується після перезапуску.",
        "settings.restart": "Перезапустити",
        "settings.privacyReads": "Що читає Денні",
        "settings.privacyReadsBody": "Кількість токенів, назви моделей, час і назви тек проєктів із журналів Claude Code і Codex; ліміти тарифу з ~/.claude.json, застосунку Claude і Codex; події, які агенти передають хукам.",
        "settings.privacyNever": "Що Денні ніколи не читає й не надсилає",
        "settings.privacyNeverBody": "Твої запити, відповіді та вміст файлів. З твоїх машин нічого не йде, крім щоденного завантаження публічного списку цін. Файли, кинуті на виріз, ідуть лише на твій сервер.",
        "settings.removeAll": "Відключити агентів і стерти дані Денні",
        "settings.removeAllFooter": "Прибере хуки з Claude Code і Codex, видалить ~/.denny-for-agents з історією та налаштуваннями й закриє застосунок.",
        "settings.removeAllConfirm": "Стерти все, що зберіг Denny for Agents?",
        "settings.version": "Версія %@",
        "settings.about": "Маленький робот у вирізі, який наглядає за Claude Code і Codex. Безкоштовна відкрита частина Денні.",

        "quiet.on": "Тиша на годину",
        "quiet.active": "Тиша до %@ — натисни, щоб зняти",
        "quick.refresh": "Оновити дані",
        "awake.manual": "Не спати вручну",
        "awake.duration": "На час",
        "awake.until": "До часу",
        "awake.indefinite": "Поки не вимкну",
        "awake.start": "Почати",
        "awake.stop": "Зупинити",
        "awake.activeUntil": "Mac не засне до %@",
        "awake.untilOff": "Mac не засне, поки не зупиниш",
        "awake.lid": "Працювати із закритою кришкою",
        "awake.lidWarning": "Лише на зарядці. Один раз попросить пароль адміністратора, щоб дозволити рівно одну команду (pmset disablesleep), і сам вимкнеться, коли робота закінчена. Не клади працюючий закритий Mac у сумку.",
        "awake.lidNeedsPower": "Зараз від батареї — увімкнеться, коли підключиш зарядку.",

        "risk.safe": "Виглядає безпечно",
        "risk.caution": "Варто глянути",
        "risk.danger": "Небезпечно",
        "risk.critical": "Дуже небезпечно",
        "risk.reason.pipeToShell": "Завантажить код з інтернету й одразу його запустить.",
        "risk.reason.wipeRoot": "Видалить усе в /, у домашній теці або в поточній теці.",
        "risk.reason.rawDisk": "Пише прямо на диск — може його стерти.",
        "risk.reason.format": "Форматує або стирає диск.",
        "risk.reason.forkBomb": "Форк-бомба: Mac зависне.",
        "risk.reason.dropData": "Видалить таблиці або дані в базі.",
        "risk.reason.deleteRecursive": "Видалить теку %@ з усім вмістом, без Кошика.",
        "risk.reason.forcePush": "Перезапише історію гілки на сервері.",
        "risk.reason.resetHard": "Викине всі незакомічені зміни.",
        "risk.reason.cleanUntracked": "Видалить файли, які не відстежує git.",
        "risk.reason.sudo": "Запуск від імені адміністратора (sudo).",
        "risk.reason.permissions": "Відкриє файли для всіх або змінить їхнього власника.",
        "risk.reason.killProcess": "Примусово зупинить програми.",
        "risk.reason.reboot": "Вимкне або перезавантажить комп'ютер.",
        "risk.reason.dockerPrune": "Видалить контейнери, томи або дані Docker.",
        "risk.reason.publish": "Опублікує пакет або реліз для всіх.",
        "risk.reason.secrets": "Чіпає ключі, паролі або секрети .env.",
        "risk.reason.push": "Надішле коміти на сервер.",
        "risk.reason.deleteFile": "Видалить %@.",
        "risk.reason.install": "Встановить пакети з інтернету.",
        "risk.reason.network": "Звертається до мережі.",
        "risk.reason.gitHistory": "Перепише історію git або відкотить зміни файлів.",
        "risk.reason.sensitiveFile": "Змінює важливий файл: %@.",
        "risk.reason.externalTool": "Використовує зовнішній інструмент (MCP-сервер).",

        "load.thisMac": "Цей Mac",
        "load.cpu": "Процесор",
        "load.cpuLoad": "Навантаження (ядер: %ld)",
        "load.memory": "Пам'ять",
        "load.pressureNormal": "Тиск пам'яті: у нормі",
        "load.pressureWarning": "Тиск пам'яті: високий",
        "load.pressureCritical": "Тиск пам'яті: критичний",
        "load.swap": "Swap %@",
        "load.uptime": "Працює без перезавантаження %@",
        "load.memoryLow": "Пам'ять майже скінчилась — важку збірку може вбити.",
        "load.noServer": "Навантаження сервера прийде з наступним звітом підключеного сервера.",
        "settings.section.load": "Навантаження",

        "relay.title": "%@ уперся в ліміт",
        "relay.titleUntil": "%1$@ уперся в ліміт до %2$@",
        "relay.body": "Передати завдання %@? Я напишу записку: що просили і що вже зроблено.",
        "relay.copy": "Скопіювати записку для %@",
        "relay.later": "Не зараз",
        "relay.copied": "Записку скопійовано — встав її в %@ (⌘V)",
        "relay.handoff": "Передати завдання %@",
        "relay.note.intro": "Продовж завдання, яке почав %1$@ (%2$@).",
        "relay.note.reasonLimit": "він уперся в ліміт тарифу",
        "relay.note.reasonManual": "передаю його тобі",
        "relay.note.folder": "Тека: %@",
        "relay.note.server": "Сервер: %@",
        "relay.note.task": "Завдання:",
        "relay.note.done": "Що вже зроблено:",
        "relay.note.edited": "редагував: %@",
        "relay.note.ran": "запускав: %@",
        "relay.note.last": "Останнє повідомлення %@:",
        "relay.note.next": "Спершу переглянь поточні зміни (git status, git diff), потім продовжуй з того місця, де зупинилися.",

        "stuck.title": "%@, здається, ходить по колу",
        "stuck.repeatCommand": "Уже %1$ld-й раз запускає «%2$@»",
        "stuck.repeatEdit": "Редагує %2$@ уже %1$ld-й раз",
        "stuck.noProgress": "%ld хв працює й нічого не змінює",
        "stuck.setting": "Попереджати, коли агент ходить по колу"
    ]
}
