extension Translations {
    static let ukrainian: [String: String] = [
        "step.runs": "Запускає %@",
        "step.runsCommand": "Запускає команду",
        "step.reads": "Читає %@",
        "step.aFile": "файл",
        "step.edits": "Редагує %@",
        "step.editsFiles": "Редагує файли",
        "step.searches": "Шукає «%@»",
        "step.searchesCode": "Шукає в коді",
        "step.searchesWeb": "Шукає в інтернеті",
        "step.opens": "Відкриває %@",
        "step.startsHelper": "Запускає помічника",
        "step.updatesPlan": "Оновлює план",
        "step.uses": "Використовує %@",
        "step.working": "Працює…",
        "step.thinking": "Думає…",
        "step.waitingForYou": "Чекає на тебе",
        "step.done": "Готово",

        "title.idle": "Усе спокійно",
        "title.working": "Агенти працюють",
        "title.needsYou": "Потрібен ти",
        "title.limitUsedUp": "Ліміт %@ вичерпано",
        "title.limitAlmost": "Ліміт %@ майже вичерпано",
        "subtitle.noSessions": "Запусти Claude Code або Codex — я наглядатиму.",
        "subtitle.noHooks": "Підключи Claude Code і Codex у рядку меню.",
        "subtitle.serverDown": "Не вдалося почати слухати агентів.",
        "limit.detailResets": "%1$@, скидання через %2$@",

        "approval.allow": "Дозволити",
        "approval.deny": "Заборонити",
        "approval.askThere": "Запитати там",
        "approval.wantsTo": "хоче",
        "approval.more": "Ще чекають: %ld",

        "stats.spending": "Витрати",
        "stats.apiValue": "за цінами API",
        "stats.now": "Зараз",
        "stats.workingNow": "працює",
        "stats.limitsLater": "Ліміти з'являться після наступної відповіді",
        "stats.updated": "Оновлено: %@",
        "stats.tokens": "%@ токенів",
        "stats.tokensWord": "токенів",
        "stats.fromCache": "%ld%% з кешу",
        "stats.todayTotal": "Сьогодні %@",
        "stats.noPrice": "Ціни Codex невідомі",
        "period.today": "Сьогодні",
        "period.week": "7 днів",
        "period.month": "30 днів",
        "window.session": "Сесія",
        "window.week": "Тиждень",
        "window.limit": "Ліміт",
        "stats.activity": "Активність",
        "stats.streak": "%ld дн. поспіль",
        "stats.activeDays": "Активних днів",
        "stats.busiestDay": "Найактивніший день",

        "time.daysHours": "%1$ld д %2$ld год",
        "time.hoursMinutes": "%1$ld год %2$ld хв",
        "time.minutes": "%ld хв",
        "time.hours": "%ld год",
        "time.days": "%ld д",
        "time.months": "%ld міс.",
        "time.justNow": "щойно",
        "time.ago": "%@ тому",

        "resets.line": "Скидання: %ld",
        "resets.expiresIn": "найближче згорить через %@",
        "resets.use": "Використати скидання",
        "resets.resetting": "Скидаю…",
        "resets.confirmTitle": "Скинути ліміти Codex зараз?",
        "resets.confirmBody": "Буде витрачено одне запасне скидання: ліміти сесії й тижня оновляться одразу. Залишилось скидань: %ld.",
        "resets.outcome.reset": "Ліміти Codex скинуто",
        "resets.outcome.nothing": "Поки нічого скидати",
        "resets.outcome.noCredit": "Запасних скидань немає",
        "resets.outcome.already": "Це скидання вже використано",
        "resets.outcome.failed": "Не вдалося — Codex на цьому Mac увійшов в акаунт?",

        "drop.here": "Відпусти — скопіюю шлях для агента",
        "drop.copiedOne": "Шлях до %@ скопійовано — встав агенту (⌘V)",
        "drop.copiedMany": "Скопійовано шляхів: %ld — встав агенту (⌘V)",
        "drop.remoteCantSee": "Агент на %@ не побачить файл із цього Mac.",
        "drop.willSendOne": "Шлях на сервері скопійовано — файл піде на %@ з твоїм наступним повідомленням (⌘V)",
        "drop.willSendMany": "Шляхи на сервері скопійовано — файлів: %1$ld, підуть на %2$@ з твоїм наступним повідомленням (⌘V)",
        "drop.delivered": "Доставлено на %1$@: %2$ld",
        "drop.skippedFolders": "Теки поки не пересилаються.",
        "drop.tooBig": "За раз можна до 20 МБ.",
        "drop.shelfInFullDenny": "Полиця для файлів і музика — у повному Денні →",
        "fullDenny": "Завдання, нотатки й офлайн-ШІ — повний Денні →",

        "alerts.menu": "Сповіщення",
        "alerts.finish": "Завдання готове",
        "alerts.limit": "Ліміт тарифу",
        "alerts.budget": "Денний бюджет за цінами API",
        "alerts.off": "Вимк.",
        "alerts.anyLength": "Будь-якої тривалості",
        "alerts.longerThan": "Довше %ld хв",
        "alerts.atPercent": "При %ld%%",
        "alerts.finishedTitle": "%@ завершив",
        "alerts.finishedBody": "%1$@ · працював %2$@",
        "alerts.limitTitle": "Ліміт %1$@: %2$ld%%",
        "alerts.budgetTitle": "Денний бюджет перевищено: %@",
        "alerts.budgetBody": "За цінами API, разом із серверами.",

        "menu.claude": "Стежити за Claude Code",
        "menu.codex": "Стежити за Codex",
        "menu.remote": "Віддалений сервер (SSH)…",
        "menu.fullDenny": "Повний Денні…",
        "menu.quit": "Вийти з Denny for Agents",
        "remote.title": "Стежити за агентами на сервері (SSH)",
        "remote.body": "1. Перешли порт на час підключення: у Termius додай правило Remote (сервер 127.0.0.1:{port} → цей Mac 127.0.0.1:{port}) або підключайся так: ssh -R {port}:127.0.0.1:{port} user@server\n2. Поклади remote/denny-hook.py з репозиторію на сервер у ~/.denny-for-agents/.\n3. На сервері виконай скопійовану команду, потім: python3 ~/.denny-for-agents/denny-hook.py --ping",
        "remote.copy": "Скопіювати команду",
        "remote.unavailable": "Віддалений режим не запустився: порт зайнятий.",
        "common.close": "Закрити",
        "common.cancel": "Скасувати",
        "connect.title": "Підключити Денні до агентів?",
        "connect.body": "Денні додасть хуки в ~/.claude/settings.json і ~/.codex/hooks.json (поруч збережеться резервна копія). Якщо Денні не запущений, хуки нічого не роблять і ніколи не заважають агентам.",
        "connect.connect": "Підключити",
        "connect.later": "Пізніше",
        "connect.failed": "Не вдалося змінити файл налаштувань",

        "value.title": "Вигода тарифу",
        "value.line": "%@ за цінами API за 30 днів",
        "value.planMonthly": "%1$@ · %2$@/міс",
        "stats.trend": "Динаміка",
        "stats.models": "Моделі",
        "stats.projects": "Проєкти",
        "stats.peak": "пік %@",
        "card.limits": "Ліміти",
        "alerts.renewedTitle": "Ліміт %@ оновився",
        "menu.cards": "Картки",
        "menu.readout": "Біля камери",
        "readout.timer": "Таймер завдання",
        "readout.limit": "Найповніший ліміт",
        "page.overview": "Огляд",
        "page.stats": "Статистика",
        "stats.noFresh": "Немає свіжих даних",

        "settings.title": "Налаштування",
        "settings.menu": "Налаштування…",
        "settings.section.agents": "Агенти",
        "settings.section.servers": "Сервери",
        "settings.section.notch": "Виріз",
        "settings.section.cards": "Картки",
        "settings.section.alerts": "Сповіщення",
        "settings.section.language": "Мова",
        "settings.section.privacy": "Конфіденційність",
        "settings.section.about": "Про програму",
        "settings.connected": "Підключено",
        "settings.notConnected": "Не підключено",
        "settings.disconnect": "Відключити",
        "settings.agentsFooter": "Денні додає свої хуки у файл налаштувань кожного агента й зберігає поруч резервну копію. Якщо Денні не запущений, хуки нічого не роблять.",
        "settings.keepAwake": "Не давати Mac засинати, поки агенти працюють",
        "settings.keepAwakeFooter": "Лише поки працює агент на цьому Mac. Екран при цьому може гаснути.",
        "settings.serversConnected": "Підключені сервери",
        "settings.noServers": "Серверів поки немає. Підключи сервер нижче.",
        "settings.lastSeen": "на зв'язку %@",
        "settings.noContact": "немає зв'язку %@",
        "ssh.title": "Підключення Денні",
        "ssh.body": "Денні сам підключається по SSH і тримає зв'язок: після сну, зміни мережі чи перепідключення VPN перепідключається сам. Використовує SSH-ключі та ~/.ssh/config цього Mac — Termius не потрібен.",
        "ssh.placeholder": "root@сервер або ім'я з ~/.ssh/config",
        "ssh.add": "Додати",
        "ssh.invalid": "Потрібно user@host або ім'я з ~/.ssh/config (інший порт вкажи в ~/.ssh/config).",
        "ssh.connecting": "Підключаюся…",
        "ssh.connected": "на зв'язку %@",
        "ssh.retry": "повтор через %@",
        "ssh.connectAgents": "Підключити агентів",
        "ssh.connectAgentsHelp": "Поставити хук Денні на сервер і підключити там Claude Code і Codex",
        "ssh.installing": "Підключаю…",
        "ssh.agentsConnected": "Агентів підключено. Перезапусти Claude Code / Codex на сервері.",
        "ssh.installFailed": "Не вдалося підключити агентів: %@",
        "ssh.needsKey": "Немає SSH-ключа до цього сервера",
        "ssh.keyHint": "Цьому Mac потрібен SSH-ключ, який прийме сервер. Виконай у Терміналі на Mac (друга команда один раз запитає пароль сервера):",
        "ssh.copyCommands": "Скопіювати команди",
        "ssh.hostKeyChanged": "Ключ сервера змінився — перевір його та виправ ~/.ssh/known_hosts",
        "ssh.unreachable": "Сервер недоступний",
        "ssh.portBusy": "Порт на сервері ще зайнятий, пробую наступний",
        "ssh.noPython": "На сервері не встановлено python3",
        "ssh.dropped": "Зв'язок обірвався",
        "ssh.remove": "Прибрати",
        "ssh.removeAndUnhook": "Прибрати й відключити агентів на сервері",
        "ssh.removeQuestion": "Прибрати цей сервер?",
        "settings.peeks": "Визирання",
        "settings.peekOnStart": "Коли надсилаєш завдання",
        "settings.peekOnWriting": "Коли агент починає писати код",
        "settings.peekOnFinish": "Коли агент завершив",
        "settings.display": "Монітор",
        "settings.displayAuto": "Той, де є виріз",
        "settings.fullScreen": "Показувати поверх повноекранних застосунків",
        "settings.cardsFooter": "Вимкнені картки зникають із вирізу. В «Огляді» — ліміти, витрати й «Зараз», у «Статистиці» — решта.",
        "settings.languageSystem": "Як у системі",
        "settings.languageRestart": "Нова мова застосується після перезапуску.",
        "settings.restart": "Перезапустити",
        "settings.privacyReads": "Що читає Денні",
        "settings.privacyReadsBody": "Кількість токенів, назви моделей, час і назви тек проєктів із журналів Claude Code і Codex; ліміти тарифу з ~/.claude.json, застосунку Claude і Codex; події, які агенти передають хукам.",
        "settings.privacyNever": "Що Денні ніколи не читає й не надсилає",
        "settings.privacyNeverBody": "Твої запити, відповіді та вміст файлів. З твоїх машин нічого не йде, крім щоденного завантаження публічного списку цін. Файли, кинуті на виріз, ідуть лише на твій сервер.",
        "settings.removeAll": "Відключити агентів і стерти дані Денні",
        "settings.removeAllFooter": "Прибере хуки з Claude Code і Codex, видалить ~/.denny-for-agents з історією та налаштуваннями й закриє застосунок.",
        "settings.removeAllConfirm": "Стерти все, що зберіг Denny for Agents?",
        "settings.version": "Версія %@",
        "settings.about": "Маленький робот у вирізі, який наглядає за Claude Code і Codex. Безкоштовна відкрита частина Денні.",
        "tests.onServer": "Запуститься на %@",
        "tests.noneOnServer": "На сервері тести не знайдено",
        "server.jobWaits": "%@: завдання чекає на сервер — почнеться, щойно агент там щось зробить (або за кілька секунд, якщо він працює)",
        "night.where": "Де",
        "night.thisMac": "Цей Mac",
        "night.serverFolder": "Папка на сервері, наприклад ~/projects/shop",
        "settings.section.office": "Офіс",
        "settings.section.nightShift": "Нічна зміна",
        "night.newJob": "Нове завдання на потім",
        "night.agent": "Агент",
        "night.noFolder": "Папку не вибрано",
        "night.chooseFolder": "Вибрати…",
        "night.when": "Запустити",
        "night.whenRenews": "Коли оновиться ліміт",
        "night.whenAt": "У заданий час",
        "night.queue": "Поставити в чергу",
        "night.queueTitle": "Черга",
        "night.waitsUntil": "чекає до %@",
        "night.waitsForLimit": "чекає оновлення ліміту",
        "night.running": "йде %@",
        "night.doneAt": "готово о %@",
        "night.failedShort": "не вийшло: %@",
        "night.footer": "На цьому Mac (Денні не дасть йому заснути) або на сервері (там завдання йде, навіть якщо SSH-сесія обірветься; результат прийде, коли знову підключишся). Уночі нікому натискати «Дозволити», тож Денні обережний: правка файлів і безпечні команди йдуть самі, усе, що охоронець вважає небезпечним, забороняється. Страхувальна сітка робить знімки, а Telegram повідомить, коли готово. Про завдання на сервері Telegram повідомить, коли Mac знову буде на зв'язку з цим сервером.",
        "night.interrupted": "перервано перезапуском",
        "night.started": "%1$@ почав нічне завдання в %2$@",
        "night.done": "%1$@ закінчив нічне завдання в %2$@ — чек чекає у вирізі",
        "night.failed": "%1$@ не зміг закінчити нічне завдання в %2$@: %3$@",
        "settings.section.phone": "Телефон",
        "phone.title": "Дозволи з телефона",
        "phone.steps": "1. У Telegram відкрий @BotFather і надішли /newbot.\n2. Придумай ім'я — BotFather надішле токен.\n3. Встав токен сюди.",
        "phone.tokenPlaceholder": "Токен бота",
        "phone.check": "Перевірити",
        "phone.badToken": "Цей токен не підходить — скопіюй його ще раз у @BotFather.",
        "phone.sendCode": "Надішли цей код боту @%@:",
        "phone.openBot": "Відкрити бота",
        "phone.topicHint": "Хочеш отримувати запити в певній темі чи групі? Надішли код саме туди — Денні писатиме лише в цю тему, а натискати кнопки зможеш тільки ти.",
        "phone.waiting": "Чекаю код…",
        "phone.connected": "Підключено до %1$@ через @%2$@",
        "phone.whenAway": "Коли я не за Mac",
        "phone.always": "Завжди",
        "phone.finished": "Ще повідомляти, коли завдання готове",
        "phone.test": "Надіслати тест",
        "phone.testText": "Це Денні 👋 Сюди надходитимуть запити твоїх агентів.",
        "phone.disconnect": "Відключити",
        "phone.footer": "Запити йдуть через сервери Telegram, разом із текстом команди. Бот слухається лише чат, який надіслав код. «Не за Mac» — 2 хвилини без миші й клавіатури.",
        "phone.paired": "Денні підключено 🎉 Коли агент попросить дозволу, а тебе не буде за Mac, запит прийде сюди.",
        "phone.request": "%1$@ · %2$@ хоче:",
        "phone.allow": "✅ Дозволити",
        "phone.deny": "❌ Заборонити",
        "phone.allowed": "✅ Дозволено",
        "phone.denied": "❌ Заборонено",
        "phone.expired": "⌛ Тут не відповіли — агент питає у своєму терміналі.",
        "phone.replyHint": "↩️ Відповідай на це повідомлення, щоб сказати агенту, що робити далі.",
        "phone.replyUnknown": "Відповідай на повідомлення ✅ про готове завдання, щоб сказати цьому агенту, що робити далі.",
        "phone.replyLive": "%@ отримав відповідь і продовжує у своєму терміналі.",
        "phone.replyBackground": "%1$@ продовжує у фоні в %2$@ (обережний режим: нічого небезпечного без тебе). Telegram повідомить, коли буде готово.",
        "phone.replyFailed": "Не можу продовжити це завдання: невідома папка або сесія.",
        "office.interrupted": "Перервано: застосунок перезапускався",
        "office.stopped": "Зупинено",
        "office.newTask": "Нове завдання",
        "office.give": "Дати завдання",
        "office.column.inbox": "Вхідні",
        "office.column.working": "В роботі",
        "office.column.review": "На перевірці",
        "office.column.done": "Готово",
        "office.remove": "Прибрати",
        "office.stop": "Зупинити",
        "office.accept": "Прийняти",
        "office.discard": "Викинути",
        "office.waiting": "чекає черги",
        "office.readyAt": "готово о %@",
        "office.accepted": "прийнято",
        "office.discarded": "викинуто",
        "office.acceptFailed": "Не вдалося влити: %@",
        "office.noGit": "Папка не в git: агент працював просто в ній, вливати нічого.",
        "office.empty": "Поки завдань немає.",
        "office.footer": "Кожне завдання йде у своїй гілці git і своїй копії проєкту: твій проєкт не змінюється, доки не натиснеш «Прийняти» (гілка вливається в поточну), а «Викинути» видаляє гілку. Поки агент працює, дозволяти нікому, тож діє обережний режим нічної зміни: правки й безпечні команди йдуть самі, небезпечне забороняється. В одній папці — одне завдання за раз, усього два одночасно.",
        "office.auto": "Денні вирішить",
        "office.repeat": "Повторювати регулярно",
        "office.everyDay": "Щодня",
        "office.atHour": "о %ld:00",
        "office.addRecurring": "Додати доручення",
        "office.recurringTitle": "Регулярні доручення",
        "office.rework": "Доопрацювати",
        "office.sendRework": "Надіслати",
        "office.cancel": "Скасувати",
        "office.howTitle": "Як працює офіс",
        "office.reviewToggle": "Другий агент перевіряє кожне завдання",
        "office.claudeBudget": "Бюджет Claude на завдання, $",
        "office.codexBudget": "Бюджет Codex на завдання, тис. токенів",
        "office.standupToggle": "Ранкова планірка в Telegram",
        "office.howFooter": "Порожній бюджет — без обмеження. Claude зупиняється сам за своїм лімітом витрат; у Codex немає публічних цін, тож Денні зупиняє його за токенами. Планірка: що зроблено, що чекає на тебе і скільки коштувало.",
        "office.overBudget": "Зупинено: перевищено бюджет",
        "office.reviewClean": "%@ перевірив: зауважень немає",
        "office.reviewFindings": "%1$@ перевірив: зауважень — %2$ld",
        "office.changes": "файлів: %1$ld · +%2$ld −%3$ld",
        "office.testsPassed": "тести ✅",
        "office.testsFailed": "тести ❌",
        "office.tg.expired": "Це вже неактуально: завдання пішло далі.",
        "office.tg.accepted": "✅ Влито в %@",
        "office.tg.discarded": "🗑 Викинуто",
        "office.tg.given": "📥 Передав %1$@ у %2$@. Звіт прийде сюди.",
        "office.tg.reworking": "🔁 %@ доопрацьовує.",
        "office.tg.how": "Напиши так: /task що зробити. Відповідай на звіт, щоб доопрацювати, /board — дошка офісу.",
        "office.tg.noFolders": "Проєктів поки немає: дай перше завдання на Mac (Налаштування → Офіс).",
        "office.tg.pick": "Кому і де?",
        "office.tg.boardEmpty": "В офісі порожньо: відкритих завдань немає.",
        "office.tg.replyHint": "↩️ Відповідай на це повідомлення, щоб попросити доопрацювати.",
        "office.tg.taskCommand": "Дати завдання Claude або Codex",
        "office.tg.boardCommand": "Дошка офісу",
        "office.standup.title": "☀️ Планірка офісу",
        "office.standup.done": "Закрито: %ld",
        "office.standup.waiting": "Чекають твого рішення: %ld",
        "office.standup.working": "В роботі: %ld",
        "office.standup.queued": "У черзі: %ld",
        "office.standup.spent": "Витрачено: %@",
        "review.button": "Перевірити в %@",
        "review.running": "%1$@ перевіряє… %2$@",
        "review.clean": "✅ %@ не знайшов проблем",
        "review.findings": "%1$@ знайшов зауважень: %2$ld",
        "review.send": "Надіслати %@",
        "review.copied": "Скопійовано — встав %@ (⌘V)",
        "review.failed": "%1$@ не зміг перевірити: %2$@",
        "review.noChanges": "немає змін для перевірки",
        "review.notFound": "не знайдено на цьому Mac",
        "review.agentMessage": "%1$@ перевірив твої зміни й знайшов:\n\n%2$@\n\nПеревір ці зауваження й виправ те, що слушне.",
        "tests.run": "Запустити тести",
        "tests.running": "Тести йдуть… %@",
        "tests.passed": "✅ Тести пройшли · %@",
        "tests.failed": "❌ Тести впали · %@",
        "tests.sendToAgent": "Надіслати агенту",
        "tests.copied": "Скопійовано — встав агенту (⌘V)",
        "tests.agentMessage": "Після твоїх змін падають тести (`%1$@`). Ось кінець виводу — виправ, будь ласка:\n\n%2$@",
        "tests.autoSetting": "Запускати тести проєкту після кожного завдання",
        "tests.autoFooter": "На цьому Mac і на серверах. Команду Денні знаходить сам (swift test, npm test, cargo test, pytest…); свою можна записати у файл .denny-test у корені проєкту.",
        "tests.timedOut": "Зупинено через 10 хвилин.",
        "receipt.title": "Чек завдання",
        "receipt.files": "Файлів: %ld",
        "receipt.lines": "+%1$ld −%2$ld",
        "receipt.commands": "Команд: %ld",
        "receipt.tokens": "Токенів: %@",
        "receipt.cost": "%@ за цінами API",
        "receipt.copy": "Скопіювати",
        "receipt.copied": "Чек скопійовано",
        "receipt.hide": "Сховати",
        "receipt.signature": "через Denny for Agents",
        "settings.section.safetyNet": "Страховка",
        "safety.peekTitle": "Зберіг файли перед небезпечною командою",
        "safety.cardTitle": "Страхувальна сітка",
        "safety.cardBody": "Перед цією командою я зберіг файли. «Скасувати» поверне їх як було.",
        "safety.onServer": "Знімок на %@ — відкат запускається там",
        "safety.undo": "Скасувати…",
        "safety.copyCommand": "Скопіювати команду для сервера",
        "safety.hide": "Сховати",
        "safety.confirmTitle": "Повернути файли як було перед «%@»?",
        "safety.confirmBody": "Повернеться файлів: %ld. Зміни в них після знімка зникнуть, нові файли залишаться.",
        "safety.confirmRestore": "Повернути",
        "safety.nothing": "Нічого повертати — файли такі ж, як у знімку.",
        "safety.restored": "Файли повернулися",
        "safety.failed": "Не вдалося повернути файли",
        "safety.commandCopied": "Команду скопійовано — виконай її на сервері",
        "safety.empty": "Знімків поки немає. Просто перед тим, як агент запустить rm, git reset --hard і подібне, Денні збереже тут твої файли.",
        "safety.footer": "До 50 знімків. У git-проєкті лежать у прихованому посиланні й не чіпають твою гілку, індекс і stash.",
        "safety.storage": "Зберігання",
        "safety.keepFor": "Зберігати знімки",
        "safety.keep.1": "1 день",
        "safety.keep.7": "7 днів",
        "safety.keep.30": "30 днів",
        "safety.limit": "Місце для копій",
        "safety.gb": "%ld ГБ",
        "safety.used": "Копії на цьому Mac: %@",
        "safety.clear": "Видалити всі знімки…",
        "safety.clearConfirm": "Видалити всі знімки на цьому Mac?",
        "safety.clearBody": "Файли з них потім не повернути.",
        "safety.delete": "Видалити",
        "safety.limitFooter": "Рахуються лише копії файлів поза git — знімки git лежать усередині проєкту й майже не займають місця. Коли місце закінчується, першими видаляються найстаріші знімки. Сервери отримають ці налаштування з твоїм наступним повідомленням агенту.",
        "update.check": "Перевірити оновлення",
        "update.checking": "Перевіряю…",
        "update.upToDate": "У тебе остання версія",
        "update.available": "Доступна версія %@",
        "update.install": "Оновити",
        "update.installing": "Завантажую оновлення… Денні перезапуститься",
        "update.failed": "Не вдалося оновити: %@",
        "update.reason.offline": "не вдається зв'язатися з GitHub",
        "update.reason.checksum": "файл не збігається з контрольною сумою",
        "update.reason.folder": "немає прав замінити застосунок — тримай його в «Програмах»",
        "update.reason.download": "не вдалося завантажити",
        "update.homebrew": "Встановлено через Homebrew — виконай: brew upgrade denny-for-agents",
        "update.notifyBody": "Відкрий налаштування Денні → «Про програму», щоб оновити.",

        "quiet.on": "Тиша на годину",
        "quiet.active": "Тиша до %@ — натисни, щоб зняти",
        "quick.refresh": "Оновити дані",
        "awake.manual": "Не спати вручну",
        "awake.duration": "На час",
        "awake.until": "До часу",
        "awake.indefinite": "Поки не вимкну",
        "awake.start": "Почати",
        "awake.stop": "Зупинити",
        "awake.activeUntil": "Mac не засне до %@",
        "awake.untilOff": "Mac не засне, поки не зупиниш",
        "awake.lid": "Працювати із закритою кришкою",
        "awake.lidWarning": "Лише на зарядці. Один раз попросить пароль адміністратора, щоб дозволити рівно одну команду (pmset disablesleep), і сам вимкнеться, коли робота закінчена. Не клади працюючий закритий Mac у сумку.",
        "awake.lidNeedsPower": "Зараз від батареї — увімкнеться, коли підключиш зарядку.",

        "risk.safe": "Виглядає безпечно",
        "risk.caution": "Варто глянути",
        "risk.danger": "Небезпечно",
        "risk.critical": "Дуже небезпечно",
        "risk.reason.pipeToShell": "Завантажить код з інтернету й одразу його запустить.",
        "risk.reason.wipeRoot": "Видалить усе в /, у домашній теці або в поточній теці.",
        "risk.reason.rawDisk": "Пише прямо на диск — може його стерти.",
        "risk.reason.format": "Форматує або стирає диск.",
        "risk.reason.forkBomb": "Форк-бомба: Mac зависне.",
        "risk.reason.dropData": "Видалить таблиці або дані в базі.",
        "risk.reason.deleteRecursive": "Видалить теку %@ з усім вмістом, без Кошика.",
        "risk.reason.forcePush": "Перезапише історію гілки на сервері.",
        "risk.reason.resetHard": "Викине всі незакомічені зміни.",
        "risk.reason.cleanUntracked": "Видалить файли, які не відстежує git.",
        "risk.reason.sudo": "Запуск від імені адміністратора (sudo).",
        "risk.reason.permissions": "Відкриє файли для всіх або змінить їхнього власника.",
        "risk.reason.killProcess": "Примусово зупинить програми.",
        "risk.reason.reboot": "Вимкне або перезавантажить комп'ютер.",
        "risk.reason.dockerPrune": "Видалить контейнери, томи або дані Docker.",
        "risk.reason.publish": "Опублікує пакет або реліз для всіх.",
        "risk.reason.secrets": "Чіпає ключі, паролі або секрети .env.",
        "risk.reason.push": "Надішле коміти на сервер.",
        "risk.reason.deleteFile": "Видалить %@.",
        "risk.reason.install": "Встановить пакети з інтернету.",
        "risk.reason.network": "Звертається до мережі.",
        "risk.reason.gitHistory": "Перепише історію git або відкотить зміни файлів.",
        "risk.reason.sensitiveFile": "Змінює важливий файл: %@.",
        "risk.reason.externalTool": "Використовує зовнішній інструмент (MCP-сервер).",

        "load.thisMac": "Цей Mac",
        "load.cpu": "Процесор",
        "load.cpuLoad": "Навантаження (ядер: %ld)",
        "load.memory": "Пам'ять",
        "load.pressureNormal": "Тиск пам'яті: у нормі",
        "load.pressureWarning": "Тиск пам'яті: високий",
        "load.pressureCritical": "Тиск пам'яті: критичний",
        "load.swap": "Swap %@",
        "load.uptime": "Працює без перезавантаження %@",
        "load.memoryLow": "Пам'ять майже скінчилась — важку збірку може вбити.",
        "load.noServer": "Навантаження сервера прийде з наступним звітом підключеного сервера.",
        "settings.section.load": "Навантаження",

        "relay.title": "%@ уперся в ліміт",
        "relay.titleUntil": "%1$@ уперся в ліміт до %2$@",
        "relay.body": "Передати завдання %@? Я напишу записку: що просили і що вже зроблено.",
        "relay.copy": "Скопіювати записку для %@",
        "relay.later": "Не зараз",
        "relay.copied": "Записку скопійовано — встав її в %@ (⌘V)",
        "relay.handoff": "Передати завдання %@",
        "relay.note.intro": "Продовж завдання, яке почав %1$@ (%2$@).",
        "relay.note.reasonLimit": "він уперся в ліміт тарифу",
        "relay.note.reasonManual": "передаю його тобі",
        "relay.note.folder": "Тека: %@",
        "relay.note.server": "Сервер: %@",
        "relay.note.task": "Завдання:",
        "relay.note.done": "Що вже зроблено:",
        "relay.note.edited": "редагував: %@",
        "relay.note.ran": "запускав: %@",
        "relay.note.last": "Останнє повідомлення %@:",
        "relay.note.next": "Спершу переглянь поточні зміни (git status, git diff), потім продовжуй з того місця, де зупинилися.",

        "stuck.title": "%@, здається, ходить по колу",
        "stuck.repeatCommand": "Уже %1$ld-й раз запускає «%2$@»",
        "stuck.repeatEdit": "Редагує %2$@ уже %1$ld-й раз",
        "stuck.noProgress": "%ld хв працює й нічого не змінює",
        "stuck.setting": "Попереджати, коли агент ходить по колу"
    ]
}
